### PR TITLE
[TRANSLATION] Big Romanian (ro-RO) translation update - part 2

### PR DESCRIPTION
**Pull request by AndreiMiloiu**

### CODE REVIEW

**Comment by reactos-contributor** [comment]
I notice no update in more than a week. Is it because it is ready for review?

**Comment by AndreiMiloiu** [comment]
No, not yet. I will make some translation updates in the future. I didn't have time to translate anymore.

**Comment by AndreiMiloiu** [comment]
I tried to solve conflicts with base/shell/explorer/lang/ro-RO.rc and dll/cpl/desk/lang/ro-RO.rc but I don't know why I can't do it. I deleted the files and created them back while trying to solve these conflicts, but it doesn't work.

**Comment by AndreiMiloiu** [comment]
Please help me in solving the conficts. I don't know how to do it. I just wanted to translate the newly added strings in these two files.

**Comment by reactos-contributor** [comment]
> Please help me in solving the conficts. I don't know how to do it. I just wanted to translate the newly added strings in these two files.

No conflicts are visible to me. I just presume that you wanted to merge the latest changes in the master with your branch and got conflicts? (I hope you did something like "git pull origin master" instead of something else for your branch update.) There are a number of ways to work on resolving conflicts, one of them being with "git mergetool". If you'll still encounter issues then maybe drop your changes in these files for now and just focus on the rest?

**Comment by binarymaster** [comment]
@AndreiMiloiu is this button visible/accessible to you?

image

**Comment by AndreiMiloiu** [comment]
Yes, @binarymaster the button is visible to me, but I didn't know how to use it. Now I was able to solve the conflicts. Also, I want to add that you are right [reactos-contributor](https://github.com/reactos-contributor). I know that a contributor added new options and I wanted to translate them immeditely after his PR was merged and I didn't wait to see the changes to language files (especially, to the Romanian file), too. So, I immediately noticed these new options and started to translate them. This was the cause of the conflicts. But now, everything was solved.

Thank you both for the help!

**Review by ericsomto — CHANGES_REQUESTED** [review]
Still need changes before merging

**Review by AndreiMiloiu — COMMENTED** [review]
I hope it's good now.

**Comment by AndreiMiloiu** [comment]
> Still need changes before merging

Please let me know if it's good now and if not, please tell me what's wrong.

**Comment by reactos-contributor** [comment]
> > Still need changes before merging
> 
> Please let me know if it's good now and if not, please tell me what's wrong. Don't forget that it's a draft.

Please let me know when it is not a draft any more, but a candidate ready for review.

**Comment by AndreiMiloiu** [comment]
Ok, I'll tell you. I still have to translate.

**Review by ericsomto — APPROVED** [review]

**Review by ericsomto — APPROVED** [review]

**Review by ericsomto — APPROVED** [review]

**Review by ericsomto — APPROVED** [review]

**Review by s0mt0chukwu — APPROVED** [review]

**Review by s0mt0chukwu — APPROVED** [review]

**Comment by GeoB99** [comment]
To be brutally honest, I would like if you could commit the translations as per components (like "[WORDPAD] Update Romanian translation" for example) and include a list of the said components that you are translating so that things are a bit more organized because right now it's a big pain in the brain to review all of this stuff myself when I see "Update ro-Ro.rc" all over the place....

**Comment by AndreiMiloiu** [comment]
Ok, I will try to do it depending on my free time.

**Comment by reactos-contributor** [comment]
I subscribe to what George said above about separating a bit the translations (at least big parts, like the "getuname", from the rest) into distinct PRs. This way, what you have (finished) so far could be passed to review.

**Comment by AndreiMiloiu** [comment]
Yes, I know. I already start doing this. I just want to keep this PR just as a draft in order to do some tests on my translations. When I'm going to finish translating the last file from this PR (named ro-RO.rc), I'm going to open a new PR just for it and I'm going to close this. So, this PR will be just a draft that I'm going to close it soon.

**Comment by AndreiMiloiu** [comment]
I'm going to close this PR as I made more distinct PRs named according to the files I translated.

**Pull request closed without merging**
