### PR TITLE
[WIN32SS][MENU] Fix menu text Y positioning

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
This PR will fix the vertical position of menu text.
JIRA issue: [CORE-15094](https://jira.reactos.org/browse/CORE-15094)

### CODE REVIEW

**Comment by katahiromz** [comment]
BEFORE:
winmine-before
AFTER:
winmine-after
COMPARE:
winmine-compare

**Comment by katahiromz** [comment]
The lower contents of the window was a bit raised.

**Comment by katahiromz** [comment]
COMPARE PART 2:
winmine-compare-2

MenuTextY COMPARE PART 2:
menutexty-compare-2

OK, fixed.

**Comment by HBelusca** [comment]
In your winemine's "compare part 2" , you can notice that the underline of the 'I' of "Info" is not correctly aligned.

**Comment by katahiromz** [comment]
COMPARISON 3:
comparison-3

**Pull request merged**
