### PR TITLE
[FONTS] Add Wine's 'MS Sans Serif' font

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
This PR will add Wine's MS Sans Serif font for font rendering compatibilities.
JIRA issue: [CORE-15130](https://jira.reactos.org/browse/CORE-15130)

The font file is 37.6 KB. Its license is LGPL. Designer is Huw D M Davies. Its family name and display name is "MS Sans Serif".

### CODE REVIEW

**Comment by gigaherz** [comment]
If it's going to make it more compatible with windows apps, I would say yes. Just don't change it for no gain.

**Comment by learn-more** [comment]
Can you please add a comment in the cmakelists.txt indicating the original filename?

**Comment by gonzoMD** [comment]
Is an entry in readme.wine or somewhere else for syncing purposes needed?

**Comment by gigaherz** [comment]
Does the font actually work? I'm trying to view the .ttf file in my windows 10, and I don't see anything in the preview, and opening it in Birdfont shows only one glyph present in the file: 
image

**Comment by gigaherz** [comment]
On further inspection, this IS a bitmap font, with the bitmaps embedded into the .ttf file. That's why birdfont didn't find any glyph -- there are no glyphs, only bitmaps. 
image

I'm not sure of the value of importing this .ttf file as-is.

**Comment by Zero3K** [comment]
Does it even work properly when used as a font in a word processing program?

**Comment by katahiromz** [comment]
Closed.

**Comment by roytam1** [comment]
@katahiromz please don't mix-up Vector Font "Microsoft Sans Serif" (micross.ttf) and Bitmap-only font "MS Sans Serif" (sserif*.fon)

**Comment by katahiromz** [comment]
Thank you @roytam1. My thinking unit had a fatal logical error last night but now it was resolved.

**Comment by roytam1** [comment]
for more details: https://wiki.archlinux.org/index.php/Metric-compatible_fonts

**Pull request closed without merging**
