### PR TITLE
[WIN32SS][NTUSER] fix window snap madness

### PR DESCRIPTION
**Pull request by Getequ**
Desktop window was treated as possible to resize.
fix for 7e396787ed00a3939031447725f79697a41878e1

CORE-15624

### CODE REVIEW

**Comment by Getequ** [comment]
wait a minute...

**Comment by HBelusca** [comment]
That's very simple: Windows snapping works **ONLY** for windows that can usually be resized, which excludes: - desktop, - invisible windows, - non-resizable popups, - menus ... and possibly disabled windows (those with WS_DISABLED style).
Should have one of these styles (I let you test on actual windows which ones we need to look at; you can also check in our win32k source how we detect windows that can be resized): WS_VISIBLE | WS_MAXIMIZEBOX | WS_SIZEBOX . When WS_MAXIMIZEBOX is specified, the WS_SYSMENU must also be present by the way.

**Comment by Getequ** [comment]
In this fix:
for mouse dragging there is check that window have ws_sizebox/ws_thickframe and not minimized so it can be sized.
for win-arrows - dialogs and consoles are skipped (GetForegroundWindow don't get them) and desktop skipped by checking wm_sizebox/wm_thickframe

on Windows have one difference:
snapping by win+arrows required only ws_thickframe style; 
for snapping by mouse required ws_thickframe and ws_maximizebox.
Do we need to copy this behaviour or checking ws_thickframe is enough?

**Comment by MailYouLater** [comment]
Just so GitHub shows the connection between the two:
This is related to #1226.

**Comment by Getequ** [comment]
@katahiromz i added check for WS_EX_MDICHILD so now MDI child windows not affected by mouse dragging or dbl-click on top/botom edge. Win-arrows can't control it bcz GetForegroundWindow does not get them.

**Comment by HBelusca** [comment]
@Getequ / @katahiromz : I don't understand, what's the matter with the WS_EX_MDICHILD aka. why do you need to check it too?
Otherwise @katahiromz was drawing your attention to that `QuerySizeFix()` function that is called in the MDI code, that queries what the min or max window size a window can have. In win32k there is for example `co_WinPosGetMinMaxInfo()`...

**Comment by yagoulas** [comment]
> 
> In this fix:
> for mouse dragging there is check that window have ws_sizebox/ws_thickframe and not minimized so it can be sized.
> for win-arrows - dialogs, consoles and hidden are skipped (GetForegroundWindow don't get them) and desktop skipped by checking wm_sizebox/wm_thickframe
> 
> on Windows have one difference:
> snapping by win+arrows required only ws_thickframe style;
> for snapping by mouse required ws_thickframe and ws_maximizebox (without ws_sysmenu max.button unseen but style is checked by OS).
> Do we need to copy this behaviour or checking ws_thickframe is enough?

At first I found Herme's concern reasonable. After thinking of it however I thought that if we just snap to the left we don't really maximize the window so it doesn't make much sense to check for WS_MAXIMIZEBOX . It would however make sense to check it when we try to maxize it by snapping to the top. @Getequ are you sure that snapping to the left or top doesn't work unless a window has WS_MAXIMIZEBOX?

**Comment by Getequ** [comment]
@HBelusca i tested sample MDI application on Win7 - MDI child windows does not react on any snap action, so i decided to add this style-check to exclude them.

@yagoulas yes, without WS_MAXIMIZEBOX mouse snapping does not work, but win-arrows works fine. Of couse win+up does not work w/o WS_MAXIMIZEBOX. Weird but fact :)

**Comment by feel-the-dz3n** [comment]
This PR will fix this?
image

**Comment by Getequ** [comment]
yes

**Pull request merged**
