### PR TITLE
[FONTS] Fix underline/underscore position of Tahoma

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Because of FontForge's bug, the underline position value of Tahoma and Tahoma Bold was wrongly set (#789, #809). This PR will fix those values.
JIRA issue: [CORE-15079](https://jira.reactos.org/browse/CORE-15079)

### CODE REVIEW

**Comment by JoachimHenze** [comment]
Looks excellent from pure testers pov and fixes 100% the regression I wanted to see fixed. see CORE-15079 for my latest retetests. Still have no clue why tahomabd.ttf decreases in size here. HexEdit shows much more changes in Tahomabd.ttf compared to Tahoma.ttf. Just wanted to mention that. Since file size is shrinking and not enlarging I have no problem with that (second) FontForge anomalie. Hope for that being effectless.

**Comment by HBelusca** [comment]
@katahiromz : can you check about this font file size decrease and tell us whether it's OK or whether there are missing things?

**Comment by katahiromz** [comment]
I just modified the underline position value. No change in bitmaps and glyphs.

**Comment by HBelusca** [comment]
As long as the font is fine and doesn't miss bitmaps or other info, it's fine then.

**Pull request merged**
