### PR TITLE
[CHARMAP] Improve Romanian (ro-RO) translation

### PR DESCRIPTION
**Pull request by AndreiMiloiu**
Attendum to https://github.com/reactos/reactos/pull/6517

### CODE REVIEW

**Comment by AndreiMiloiu** [comment]
Cc @reactos/lang-romanian

**Comment by AndreiMiloiu** [comment]
I don't understand what is wrong with line 33. In Spanish and in other languages changing the text label size works, but in Romanian language it doesn't.

**Comment by AndreiMiloiu** [comment]
Any news?

**Comment by binarymaster** [comment]
Better ping Romanians in the chat.

**Comment by AndreiMiloiu** [comment]
> Better ping Romanians in the chat.

OK, I will.

**Pull request merged**
