### PR TITLE
[REACTOS] C99 'inline' needs 'static'

### PR DESCRIPTION
**Pull request by SergeGautherie**
Fix GCC 'MinSizeRel' build.

### CODE REVIEW

**Comment by Extravert-ir** [comment]
If you want to fix errors in some special build, please make all changes required for that in a single pull request

**Comment by SergeGautherie** [comment]
> all changes

Added workaround for `RelWithDebInfo` and `MinSizeRel` builds.
With this PR, all 4 GCC builds succeed.

**Comment by Extravert-ir** [comment]
This is too easy :) Would be nice to have this bug fixed as well https://jira.reactos.org/browse/CORE-16793

**Comment by SergeGautherie** [comment]
> This is too easy :)

That is the workaround already used for 'Release'.

--

> Would be nice to have this bug fixed as well

Not this PR, though I did already start/try to work on these warnings.

> CORE-16793

Please, answer my questions on #2982...

**Review by Extravert-ir — CHANGES_REQUESTED** [review]
I will accept the change with `static inline` thing, but only if you fix all occurrences of that in the codebase

**Comment by SergeGautherie** [comment]
> fix all occurrences of that in the codebase

Which other occurrences?

**Comment by Extravert-ir** [comment]
Better just override the `__inline` definition with `static inline`

**Pull request closed without merging**
