### PR TITLE
[CPL][DESK] Update monitor resource

### PR DESCRIPTION
**Pull request by A-Rafael**
Related to JIRA issues: [CORE-11578](https://jira.reactos.org/browse/CORE-11578), [CORE-11614](https://jira.reactos.org/browse/CORE-11614) and [CORE-10606](https://jira.reactos.org/browse/CORE-10606).

New monitor resource for desk.cpl.
monitor-resource
Commit with name and email.

### CODE REVIEW

**Comment by binarymaster** [comment]
Maybe add some shadows to the image? It looks too flat :)

**Comment by JoachimHenze** [comment]
I like the new picture compared to our old from aesthetics standpoint.
Still a suggestion:
Old resource filesize was 31.722byte. New size is 89.478bytes.
The x and y dimensions are rather similar, but bit depth is 8bit old and 24bit new.
Since the picture is so simple, I wonder whether we could not save some disk-space here by adding that ressource as optimized 8bit instead? I bet it would still look excellent with optimized palette.

**Comment by A-Rafael** [comment]
@JoachimHenze, fixed - 30.2 KB.

@binarymaster, I have no idea how to add a good shadow.

**Comment by gigaherz** [comment]
I think he meant shading (highlights/shadows). something more like 
image

(changed the screenshot, not the original image -- just to give you an idea)

**Comment by gigaherz** [comment]
By the way, I noticed that the image drawn on the dialog, doesn't match the size drawn in the dialog (it's slightly scaled down). Is your BMP the right size?

**Comment by gigaherz** [comment]
Okay good to know. Since the scaling "issue" doesn't seem to be your fault, I will continue investigating what causes it without polluting this PR's comments any further.

**Comment by A-Rafael** [comment]
Added one more shadow

**Comment by JoachimHenze** [comment]
Double-checked: after commit #4 33723bf I verify the image to have 8bit, is 31.722byte (same as the original one). Dimensions are now 185x163Pixels which is the same as the original one.

Just a thought: dpi setting is 72dpi for old one, but 96dpi for new one (gigaherz, does that play a role in the scaling?)
It could be that this setting is meaningless for resources, really have no clue.

Personally I am happy already and think it's good to go.

**Comment by gigaherz** [comment]
No it has nothing to do with the image size, as I was just mentioning on IRC. We just downscale the image to fit the resource dialog, and the resource dialog's preview control is smaller than the size of the bitmap. Since the size of the bitmap can't change without fixing the code that uses it, I think that shouldn't affect this PR at all. We'll just have to decide eventually, if we prefer to keep the current downscaling, fix the dialog to use a bigger image area for the preview, or fix the code to expect a smaller bitmap. But this isn't the place for such decision.

**Comment by A-Rafael** [comment]
It seems even with scaling looks good and better than now.

**Comment by A-Rafael** [comment]
I [removed](https://github.com/reactos/reactos/pull/876) the scaling.

**Pull request merged**
