### PR TITLE
[WINHTTP_WINETEST] winhttp: Skip tests on ReactOS only. ROSTESTS-350

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Let tests run on Windows.
Addendum to 0685e02d9ee69ba5ff4d024d41ec40801d701161.

JIRA issue: [ROSTESTS-350](https://jira.reactos.org/browse/ROSTESTS-350)

### CODE REVIEW

**Comment by SergeGautherie** [comment]
ReactOS:
unchanged.
WXP, before:
'winhttp: 956 tests executed (0 marked as todo, 0 failures), 3 skipped'.
WXP, after:
'winhttp: 1092 tests executed (0 marked as todo, 0 failures), 2 skipped'.

**Comment by Extravert-ir** [comment]
That will introduce confusion while comparing Windows results with ReactOS ones. It's better to just fix them :)

**Comment by SergeGautherie** [comment]
Hum, from my point of view, confusion is the current state: can't tell at first glance which tests need fixing on ReactOS, Windows or both. As in: test itself (first) or ReactOS core (only).

**Comment by Extravert-ir** [comment]
[This](https://jira.reactos.org/browse/ROSTESTS-125) ticket is for tracking tests which needs fixing on ReactOS. Thus most of the tests are winetests, we don't bother fixing them on Windows

**Comment by SergeGautherie** [comment]
Not bothering (about [WHS testbot](https://jira.reactos.org/browse/ROSTESTS-260)) then.

**Pull request closed without merging**
