### PR TITLE
[OSK] Rearrange window elements for ru-RU and en-US locales

### PR DESCRIPTION
**Pull request by petr-akhlamov**
## Purpose

Now osk.exe very large and occupies many space on low-resolution screens. I changed rc-files (en and ru) for reduce size and make program more compact. English rc-file _maybe_ needed to correct.

was
**before**

osk-ros
**after**

http://jira.reactos.org/browse/CORE-14428

## Proposed changes

In this PR - rc-files with changed keyboard size.

## TODO

If this changes are acceptable then need make other lang-files with that size.

### CODE REVIEW

**Comment by sanchaez** [comment]
You should probably update all the other layouts to avoid inconsistency.

**Comment by HBelusca** [comment]
I like how it looks now, and yes, it would be nice if you actually could fix the other languages :)

**Comment by Fraizeraust** [comment]
I can help with Romanian & Italian languages, however it will take a considerable time as I must prepare a Boot CD with the latest changes on OSK to see the actual results.

**Comment by petr-akhlamov** [comment]
By request by start from JIRA i made osk more compact + in rc-file are comments now how to make osk full and compact. (JIRA/more compact.zip) In WinXP osk works not  bad.
compact
oskxp

**Comment by sanchaez** [comment]
I think TKL layout is too much, but I would make a toggle for it.

4 мар. 2018 г. 14:33 пользователь "Petr Akhlamov" <notifications@github.com<mailto:notifications@github.com>> написал:

By request by start from JIRA i made osk more compact + in rc-file are comments now how to make osk full and compact. (JIRA/more compact.zip) In WinXP osk works not bad.
[compact]<https://user-images.githubusercontent.com/16255202/36945505-2953fef6-1fc0-11e8-9ee5-ae40b3ddc175.png>
[oskxp]<https://user-images.githubusercontent.com/16255202/36945546-1a392ef4-1fc1-11e8-9050-af8338002852.png>

**Comment by petr-akhlamov** [comment]
Will not bad make next menu:
menu
├── file
│   └── exit
├── keyboard
│   ├── standard
│   ├── extension
│   └── next layout [virtual keyboard can't switched with alt+shift]
└── parameters ── on top of other windows

**Comment by sstopkin** [comment]
To add application menu required to rewrite osk from dialog to window.

**Comment by HBelusca** [comment]
Wrong, you can have a menu inside a dialog box.
https://msdn.microsoft.com/en-us/library/windows/desktop/aa381002(v=vs.85).aspx
Check for "MENU".

**Comment by sstopkin** [comment]
@petr-akhlamov I started implementation of your request
virtualbox_windows 10_20_03_2018_23_25_30

**Comment by sanchaez** [comment]
What's with that unrelated changes?

**Comment by learn-more** [comment]
In general, dont make pull requests from your master branch, but create a dedicated branch per PR.

**Comment by learn-more** [comment]
So this resizes the OSK for EN and RU ?
What is the status on this?

**Pull request merged**
