### PR TITLE
[SETUPAPI] Sync setupapi/queue.c to Wine 4.8

### PR DESCRIPTION
**Pull request by Doug-Lyons**
## Purpose

_Sync setupapi/queue.c to Wine 4.8 to improve cab extraction._
_This fixes 'fixme:(dll/win32/setupapi/queue.c:418) awful hack: extracting cabinet'_

JIRA issue: [CORE-15471](https://jira.reactos.org/browse/CORE-15471)

## Proposed changes

_This is not specific to CORE-15471, but is an aside and related to it._
_Partial Wine Sync to Version 4.8 for Setupapi queue function._

### CODE REVIEW

**Review by JoachimHenze — APPROVED** [review]

**Comment by HBelusca** [comment]
Thank you very much, as this is part of what's needed for the 1st-stage ReactOS GUI setup.

**Review by HBelusca — APPROVED** [review]
Have you tested other installers that also use cab extraction, to see whether this new wine code works better?

**Comment by Doug-Lyons** [comment]
> Have you tested other installers that also use cab extraction, to see whether this new wine code works better?

Yes, In https://jira.reactos.org/browse/CORE-18678 DirectX 9.0 seems to install without errors now.

**Comment by Doug-Lyons** [comment]
Thanks for the commit, @HBelusca.

**Pull request merged**
