### PR TITLE
Use KeClearEvent instead of KeResetEvent where the previous state is not needed

### PR DESCRIPTION
**Pull request by ThFabba**
This avoids having to acquire the dispatcher lock, thus improving performance.

### CODE REVIEW

**Comment by yagoulas** [comment]
I think that after this was merged both testbots take more time to complete. Can you give it a look? (or I got it wrong and it was caused by another commit?)

**Comment by ThFabba** [comment]
Yeah that does look odd, I'll look into it. Thanks.

**Comment by ThFabba** [comment]
The slowed down tests were all network-related:

```
272.46 htmldoc
266.43 url
187.04 http
178.23 winhttp
140.25 protocol
```

... and now things are back to normal even with newer revisions. So it looks like it was environmental, e.g. Wine's servers being slow.

**Comment by yagoulas** [comment]
Ok, sorry for the false alarm. Perhaps we should consider hosting that stuff in our servers ...

**Pull request merged**
