### PR TITLE
[FONT] Improve Marlett font file

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

This PR will improve the Marlett font. Marlett is a Windows/ReactOS font that is used to render GUI components.
JIRA issue: [CORE-14872](https://jira.reactos.org/browse/CORE-14872)

## Proposed change

- Improve the vector glyphs of the Marlett font file.
- Append the bitmap glyphs.
- Update the copyright ane version texts.

### CODE REVIEW

**Comment by katahiromz** [comment]
BEFORE:
marlett-before

AFTER:
marlett-after

**Comment by katahiromz** [comment]
2K3:
marlett-2k3

**Comment by cernodile** [comment]
The "x" close button looks very odd at the left side. The radio button could be made a bit smaller (kinda like server 2003). The slider on "after" picture seems to overlap, or is that normal in your test program?

**Comment by katahiromz** [comment]
Another test program:
https://jira.reactos.org/secure/attachment/47901/MarlettTest2.zip

2K3:
marlett2-2k3

**Comment by katahiromz** [comment]
AFTER (RADIO):
marlett2-ros-radio

AFTER (CHECK):
marlett2-ros-check

**Comment by cernodile** [comment]
Radio buttons seem much better now. Don't think anything was wrong with checkbox before?

The "x" buttons should go up/down like stairs and end with final pixel pointing horizontally.
image

**Comment by katahiromz** [comment]
I will add bitmap glyphs to improve rendering.

**Comment by gedmurphy** [comment]
Is it just me, or do the before shots look better?

**Comment by katahiromz** [comment]
IMPROVED MORE:
improved-more

**Comment by dsp2003** [comment]
@katahiromz It appears you have dropped the glyphs I've created into trashbin (especially the question mark, which is now clearly copypasted from Wine Marlett), yet left my copyright string intact.

If that's the case, I would humbly request you to remove any mentions of me and replace it with Wine's copyrights, as the font's contents no longer have anything to do with my old work.

**Comment by HBelusca** [comment]
Why do the RADIO buttons look anything but circular?

**Comment by cernodile** [comment]
Close button looks way much better, same for radio button. Don't see any difference in checkbox. Also wondering why radio button looks anything but circular on your Marlett test.

**Comment by katahiromz** [comment]
@dsp2003: I'll fix.
@HBelusca @cernodile: The 2k3 radiobutton also looks circular. What's the problem?

**Comment by katahiromz** [comment]
Sorry, I cannot understand.

**Comment by vicmarcal** [comment]
Hi! @katahiromz  Please look at the screenshot I took, basically I created several red line circles as references of what a "perfect circle" is. As you can see in Windows, the red circles matches perfectly the circle shapes. However in ReactOS, you can see by comparing against these red lines the circles drawn have big distortions.
I've also highlighted red areas which are "unfilled" gaps. Since circles, in ReactOS, are not perfect circles, there are gaps within them (I represented a couple of them with the red areas). 
I think the previous comments about the "not perfect circles", "ellipses", etc means these artifacts in the drawing.

comparison

**Comment by HBelusca** [comment]
Very simple:

2k3: OK (but not antialiased):
original_2k3

ROS (antialiased):
ros_1_radio

ros_2_radio

EDIT: While writing this comment, @vicmarcal wrote a nice comment.

I don't know whether these are actually just artifacts due to the antialiasing functionality of FreeType.

**Comment by cernodile** [comment]
The border of radiobutton isn't a perfect circle on the darker side.

**Comment by HBelusca** [comment]
For the check-box, is it possible to make the V-sign a little bit larger than it currently is? (but maybe a bit smaller than windows' one to avoid any infringement).
Finally, I find the "minimize-window" symbol (horizontal bar) too short.

**Comment by katahiromz** [comment]
testtest3
It's enough!

**Comment by katahiromz** [comment]
FIXED.
test2

**Comment by katahiromz** [comment]
@HBelusca Impossible.

**Comment by katahiromz** [comment]
Copyright (C) 2018 Red A.N.T.
License: CC0 BY
https://creativecommons.org/publicdomain/zero/1.0/deed

**Comment by katahiromz** [comment]
Done.

**Comment by katahiromz** [comment]
@HBelusca MarlettTest2 draws radio/check buttons by user32!DrawFrameControl. To disable the anti-aliasing there, set LOGFONT.lfQuality = NONANTIALIASED_QUALITY.

**Comment by katahiromz** [comment]
I thought mathematical construction. Combination builds a circle. To locate a circle mathematically, it needs the radius and the center position. Tracing didn't give the precise answer but constructive ideas can get the accurate values.

**Comment by HBelusca** [comment]
Comparing our new marlett font vs. Windows' marlett font on Windows Server 2003:

Our Marlett font:
win2k3_our_marlett

Windows' Marlett font:
win2k3_windows_marlett

**Comment by katahiromz** [comment]
Thanks and interesting but you're using our old font for these screenshots?

**Comment by HBelusca** [comment]
No, it's our new font in the "ReactOS" screenshot o_O

Also I tried to replace our marlett font by Windows' one on ReactOS, and I get only tofu-blocks instead of the correct symbols; no idea why...

**Comment by katahiromz** [comment]
ReactOS font engine doesn't support the symbol encoding yet, thus tofu glyphs are observed.

**Comment by katahiromz** [comment]
@HBelusca How can I replace Marlett.ttf in Win2003?

**Comment by HBelusca** [comment]
To replace the marlett:
- either you run Win2k3 in a VM and you have direct access to its VHD (without snapshot) that you can mount: in this case you just save the original marlett.ttf file and replace it with another one;
- or, you need to replace the font on a live Win2k3 system: save the original marlett.ttf to some other directory than the C:\WINDOWS\Fonts , then install the new marlett font as you would do for any other font and try to uninstall the old one (using the commands in the Fonts directory).
You may need to control what happens in the `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts` registry key, and maybe adjust the Marlett font entry by hand.

**Comment by katahiromz** [comment]
Confirmed.

SHOT1:
shot1

SHOT2:
shot2

**Comment by katahiromz** [comment]
Tired. Feel free to use this file.

**Pull request closed without merging**
