### PR TITLE
[SYSDM] Fix label height in IDD_SYSSETTINGS dialog

### PR DESCRIPTION
**Pull request by binarymaster**
## Purpose

This fixes checkbox rendering issue.

JIRA issue: [CORE-13792](https://jira.reactos.org/browse/CORE-13792)

## Proposed changes

- Fix label height in russian translation. Other translations are ok.
- Fix controls order in IDD_SYSSETTINGS dialog

### CODE REVIEW

**Comment by HBelusca** [comment]
Isn't it due also to the description static text zone being too large?

**Comment by binarymaster** [comment]
@HBelusca you're right:

image

Fixed that. Btw. other translations are not affected by this problem.

**Comment by HBelusca** [comment]
Correctly reordering the elements in the dialog can be done too ;)

**Comment by Doug-Lyons** [comment]
@binarymaster, what is the tool you are using in the screenshot?

**Comment by binarymaster** [comment]
@Doug-Lyons it's Restorator 2007.

**Pull request merged**
