### PR TITLE
[CALC] Use pragma once for calc.h

### PR DESCRIPTION
**Pull request by sarthakroy2002**

### CODE REVIEW

**Comment by GeoB99** [comment]
Hi, and thanks for contributing to the ReactOS project! Could you please describe what are the benefits or what does this PR fix, if any?

**Comment by sarthakroy2002** [comment]
> Hi, and thanks for contributing to the ReactOS project! Could you please describe what are the benefits or what does this PR fix, if any?

It is simpler and only need to include it once at the beginning of the header file. It generates a unique identifier for the file automatically and the developer wont need to choose unique names for the macros.

Well I added it because it will be helpful if any future refactor will take place. Was checking out the ReactOS project and encountered it so commited the change.

**Review by JoachimHenze — APPROVED** [review]

**Comment by whindsaks** [comment]
> It is simpler

While this is true, leaving working alone is also simpler than creating a PR.

pragma once is non-standard so technically you are breaking code even if most compilers support it.

> It generates a unique identifier for the file automatically and the developer wont need to choose unique names for the macros.

I think most of us know how it works but I could use a refresher, could you explain how pragma once interacts with symlinks and hardlinks in GCC and MSVC? On POSIX? On Windows?

**Comment by HBelusca** [comment]
> interacts with symlinks and hardlinks 

Does this even matter? And why would it?

**Comment by whindsaks** [comment]
> Does this even matter? And why would it?

I guess I should have added some extra emojis to my comment so we could all have a laugh.

It is extremely unlikely to cause issues but there could be a difference between a classic include guard and pragma once when you are asking the compiler and OS combination to deal with it instead of the developer.

**Comment by JoachimHenze** [comment]
> It is extremely unlikely to cause issues but there could be a difference between a classic include guard and pragma once when you are asking the compiler and OS combination to deal with it instead of the developer.

The same is true for every other commit we do.

**Review by binarymaster — APPROVED** [review]

**Pull request merged**
