### PR TITLE
Add Search Hidden Files and Folders Registry Entry for HKCU

### PR DESCRIPTION
**Pull request by Doug-Lyons**
## Add Missing Explorer - SearchHidden Registry Entry in HKCU

_Update default ReactOS HKCU file._

JIRA issue: [CORE-16882](https://jira.reactos.org/browse/CORE-16882)

### CODE REVIEW

**Comment by KyleKatarn31** [comment]
I finally have a doubt that Windows XP creates these keys at 0x0 prior to 1st use of the function. Have you checked ?
Not a big issue anyway...

**Comment by Doug-Lyons** [comment]
@yagoulas, Thank you for helping with the commit. Doug Lyons

**Comment by Doug-Lyons** [comment]
> I finally have a doubt that Windows XP creates these keys at 0x0 prior to 1st use of the function. Have you checked ?
> Not a big issue anyway...

@KyleKatarn31, Actually I did check and you are correct that on a clean Windows XP install, this registry entry does not appear until you have used the "Search" button the first time, but I think having it prior is actually better, like we have it now. Thanks.

**Comment by KyleKatarn31** [comment]
> 
> 
> > I finally have a doubt that Windows XP creates these keys at 0x0 prior to 1st use of the function. Have you checked ?
> > Not a big issue anyway...
> 
> @KyleKatarn31, Actually I did check and you are correct that on a clean Windows XP install, this registry entry does not appear until you have used the "Search" button the first time, but I think having it prior is actually better, like we have it now. Thanks.

I agree !

**Pull request merged**
