### PR TITLE
[BOOTDATA][FONTS] Add vgaoem.fon font

### PR DESCRIPTION
**Pull request by archeYR**
Converted from the XFree vga.bdf font.
This is needed for Vista+ x64 Winload. ReactOS x64 now boots with Vista x64 Winload out of the box (like Windows Server 2003 x64).
Tested with winload.exe from Vista x64 RTM (6.0.6000.16386) and winload.efi from Server 2008 x64 Beta 3 (6.0.6001.16497).

Before:
vmplayer_z7hqcKj5c8

After:
vmplayer_BbHcbrdSQo

### CODE REVIEW

**Review by HBelusca — APPROVED** [review]

**Comment by katahiromz** [comment]
`*.fon` font files can be editable by Fony application.
Looking with Fony, it looks like a valid font file.
fony-1
fony-2
fony-3
fony-4

**Review by katahiromz — APPROVED** [review]

**Review by binarymaster — APPROVED** [review]

**Comment by katahiromz** [comment]
Can you add a license text into `media/fonts/doc/vgaoem`?

**Comment by archeYR** [comment]
> 
> 
> Can you add a license text into `media/fonts/doc/vgaoem`?
> 
>     * Where did it come from?
> 
>     * What is its license?
> 
>     * Who is the author(s)?
> 
>     * The license terms.

I did not find much information about that font, apart from that it's also used in FreeLDR's [vgafont.c](https://github.com/reactos/reactos/blob/957d07436bd0e4e36743c63797b52237a8fec702/boot/freeldr/freeldr/arch/vgafont.c#L8) and that it comes from XFree 2.1 which is under MIT license. Would the MIT license in license.txt be fine?

**Comment by katahiromz** [comment]
> Would the MIT license in license.txt be fine?

Okay.

**Comment by katahiromz** [comment]
XFreeVGA
There are some glitches in displaying `XFreeVGA` font, but the system is working well.

**Pull request merged**
