### PR TITLE
[OSK] Refactor the keyboard layout switching mechanism

### PR DESCRIPTION
**Pull request by Fraizeraust**

### CODE REVIEW

**Comment by katahiromz** [comment]
https://github.com/katahiromz/KeybdSystem

**Comment by katahiromz** [comment]
The keyboard layouts should be plugins. Manually adding is loser's work.

**Comment by Fraizeraust** [comment]
I suspect XP's On-Screen Keyboard uses keyboard layouts as in separate DLLs (or one single DLL?) considering XP's OSK doesn't have the keyboard layout resources implement in the program itself (you can check that with Resource Hacker).

I am not sure when I am going to implement such stuff as I have to do lots of research. I cannot promise anything at this moment so don't get your hopes up. This PR will shall serve as a temporary solution.

**Comment by learn-more** [comment]
I doubt that Server 2003's keyboard layouts are generated using resources at all...

**Comment by Fraizeraust** [comment]
Right. I've to research how XP's OSK actually loads the keyboard layout DLLs (and how such DLLs should actually look).

**Pull request closed without merging**
