### PR TITLE
[WIN32K:NTUSER] Fix color indices for themes

### PR DESCRIPTION
**Pull request by binarymaster**
## Purpose

Correct the system color indices, that will fix CORE-14231 and all themes (including classic ones).

JIRA issue: [CORE-14231](https://jira.reactos.org/browse/CORE-14231)

Cc @yagoulas

### CODE REVIEW

**Comment by HBelusca** [comment]
Cc @yagoulas.

**Comment by yagoulas** [comment]
Can you check that these are the correct values for flat menus? Afail flat menus cause different colours to be used and I'm not sure if it should also affect the ones you change here.

**Comment by binarymaster** [comment]
Tested with all classic color schemes, and some themes from tickets in bug tracker, everything looks ok.

**Comment by binarymaster** [comment]
image

**Comment by binarymaster** [comment]
Flat (bottom) and non-flat (top) classic menus:

image

**Pull request merged**
