### PR TITLE
[TRANSLATION] Add language support for Hong Kong Cantonese (zh-HK) - Phase 1 (1st try)

### PR DESCRIPTION
**Pull request by eason329**
## Purpose
Add new language support for Cantonese (Hong Kong) using the name of zh-HK.

Quick Note: Cantonese has ISO 639-3 code only, but ReactOS seems only support ISO 639-1. I add this language under Chinese because it also uses Chinese characters like zh-CN and zh-TW.

## Proposed changes
This is phase 1, I added zh-HK translation for following files:
- [BASE/SETUP] (except USETUP which does not support MultiByte character)
- [BASE/SHELL/EXPLORER]
- [BASE/APPLICATIONS] (except CMD and network related applicatons)
- [DLL/COMCTL32]
- [DLL/SHELL32]
- [DLL/SYSSETUP]
- [DLL/USERENV]
- some of [DLL/CPL]
- some of [MEDIA/INF]

**Two seperated Chinese translation for COMCTL32 (which is came from Wine) will be combined into one file as ReactOS supports multiple sublanguages in a single language RC file.**

## TODO
This PR is a series of 4 seperate PRs, I will add translation according to following sequences:

1. Base (except CMD, network and Wine related applicatons), SYSSETUP, COMCTL32 <b><-THIS PR</b>
2. DLL, Wine related applicatons
3. Boot, Media, Modules
4. Command Prompt related applicatons, other extremely large files

Each phase will have its own PR so no need to wait until everything is done.

<s>**I strongly recommanded to merge my PR #3673 first.**</s> Doesn't matter now

## For debuggers
Some CJK character used in zh-HK translation does not included in DroidSansFallback.ttf provided in ReactOS SVN. So I uploaded the DroidSansFallback.ttf that will work [here](https://github.com/eason329/reactos/blob/zh-HK-font/modules/optional/DroidSansFallback.ttf). Please download this one instead of the one stored in SVN.

See JIRA issue: [CORE-17599](https://jira.reactos.org/browse/CORE-17599)

## One more (important) thing
As I said in (newly edited) `Chinese translation notes.txt`:
> 由於 Wine 不支援香港繁體中文，所有與 Wine 相關的翻譯 (即大部份以 "(filename_)Zh.rc" 方式命名的檔案內的翻譯) 均需沿用臺灣正體中文的翻譯。

Wine **DOES NOT** yet support zh-HK, so Traditional Chinese (zh-TW) will be used for ALL Wine related translation files at this moment.

Therefore, do not ask me any question about synchronization to Wine for zh-HK again.

## P.S.
Who can send me a video tutorial for how to submit patches to Wine.hq?

### CODE REVIEW

**Comment by binarymaster** [comment]
Nice! :+1: We are lacking this translation in most places (if not all).

Cc @reactos/lang-chinese

**Comment by JoachimHenze** [comment]
Is it really necessary to have a 3rd chinese translation next to zh-CN and zh-TW?
Each now localization slows down the general ros progress further...

**Comment by eason329** [comment]
My opinion is that zh-HK is not "yet another Chinese". It allows the use of Cantonese so translators in Hong Kong and Macau can translate using their mother tongue. Also, even though zh-HK uses Traditional Chinese character, some technical terms are different between Hong Kong and Taiwan. For example: the word "Network" is translated to 「網絡」 and 「網路」 in Hong Kong and Taiwan respectively.

btw, I don't think localization is the main course of slowing down the process while the OS is still in heavy development.

**Comment by JoachimHenze** [comment]
It is, because every RC change needs to be n times by the dev implementing some UI stuff initially. And n is the number of localizations. We have a lot of started, but finally left unfinished localizations already. Imho it would make sense to improve on those first, before adding yet another one. But this is just my 2 cents. Other devs may have a different view on this.

**Comment by binarymaster** [comment]
> because every RC change needs to be n times by the dev implementing some UI stuff initially

Not really. We ask to not create additional RC files for all translations. They need to be created separately by the translators.

**Comment by JoachimHenze** [comment]
yes but once they do exist and someone wants to add a new dialog, that means touching each of them.

**Comment by binarymaster** [comment]
We probably can solve this problem with some tool that will automatically duplicate introduced changes into other translation files.

**Comment by learn-more** [comment]
> We probably can solve this problem with some tool that will automatically duplicate introduced changes into other translation files.

However for some reason such tool has not appeared from thin air in the last 10 or so years.
The only thing coming close is: https://github.com/gigaherz/TransDiffer

**Review by binarymaster — CHANGES_REQUESTED** [review]
It looks like there are some conflicts, please fix them and let me know when they're fixed.

image

**Comment by eason329** [comment]
> It looks like there are some conflicts, please fix them and let me know when they're fixed.
> 
> image

I actually don't know where is the conflicts because it says no conflicts (The pict below) on my side. (blame github)

螢幕擷取畫面 (24)

I just fetched upstream for the branch again, please check if the conflicts still exists.

**Comment by binarymaster** [comment]
> I just fetched upstream for the branch again, please check if the problem still exists

Yes it does, please avoid any merge commits, this is the reason for the problem. Rebase all the commits on top of master and do a force push.

**Comment by eason329** [comment]
I think I need to create another PR for this because I merged commits in this PR twice and that is difficult for me to solve. Closing this PR and create another one later. Sorry for any inconvenience caused.

**Pull request closed without merging**
