### PR TITLE
Added pt-PT translations

### PR DESCRIPTION
**Pull request by SantosSi**
Added pt-PT translations

Because there are differences in the brazilian dialect to the continental portuguese, those changes were incorporated into a pt-PT file.
[0001-Added-pt-PT-translations.patch.txt](https://github.com/reactos/reactos/files/1884340/0001-Added-pt-PT-translations.patch.txt)

### CODE REVIEW

**Comment by binarymaster** [comment]
There is no way to change the "from" branch for PRs, so new one should be created.

**Comment by learn-more** [comment]
Please re-create it from the proper branch

**Comment by SantosSi** [comment]
When creating a PR a change comparison is forced, so I selected master against release/4.8. So what would be the best procedure to commit correctly?

**Comment by binarymaster** [comment]
@SantosSi didn't you read any GitHub tutorials about making Pull Requests?

Follow this one: https://reactos.org/wiki/Commiting_Changes

**Comment by SantosSi** [comment]
Of course I did, but they do not seem to contain the level of information I need to do it right. RTM is useless here.

**Pull request closed without merging**
