### PR TITLE
[HHPCOMP] Fix 2 MSVC C4101 warnings

### PR DESCRIPTION
**Pull request by SergeGautherie**
"...\chmc\chmc.c(671): warning C4101: 'code': unreferenced local variable"
"...\chmc\chmc.c(671): warning C4101: 'len': unreferenced local variable"

### CODE REVIEW

**Comment by SergeGautherie** [comment]
NB:
Could you upstream this on my behalf, or tell me how to do it (I am not familiar with that project/sourceforge)? Thanks.

**Comment by Extravert-ir** [comment]
Waste of developer's time. This pull request doesn't have any added value

**Comment by SergeGautherie** [comment]
> doesn't have any added value

I replied on similar #2391.

**Comment by ThFabba** [comment]
This is not a 3rd party project, we're the "upstream". So I'd say this is valid, and please remove the `__REACTOS__` ifdef.

**Comment by Extravert-ir** [comment]
As far as I understand, `chmc` part of it can be considered "3rd party"

**Comment by SergeGautherie** [comment]
For the record, `chmc` comes from upstream, which seems stalled since years ago...

**Pull request merged**
