### PR TITLE
[GITHUB] Add a GitHub Action for ChatGPT code review

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Make ChatGPT do code review for each newly-opened PR.
JIRA issue: N/A

## Proposed changes

- Add `.github/workflow/cr.yml` for GitHub Actions.

## TODO

- [x] Check the cost and the budget.
- [ ] Reach consensus.
- [ ] Add `OPENAI_API_KEY` repository secret.
- [ ] Confirm whether this PR will work.

## Knowledge base

- An ChatGPT API key from OpenAI is necessary.
- The trigger of the GitHub Action is to open or reopen a PR after commit of this PR.
- ChatGPT will read PR changes.
- ChatGPT doesn't reply a PR's comment (yet).
- ChatGPT won't read more than 5000 bytes.
- The `Ada` plan (fastest): $0.0004 / 1K tokens
- The `Davinci` plan (most powerful): $0.0200 / 1K tokens
- For text in English, 1 token is approximately 4 characters or 0.75 words.

### CODE REVIEW

**Comment by katahiromz** [comment]
This is an example:

**Comment by katahiromz** [comment]
https://openai.com/pricing

> Start for free
> Start experimenting with $5 in free credit that can be used during your first 3 months.

> Ada Fastest $0.0004 / 1K tokens
> Davinci Most powerful $0.0200 / 1K tokens
What is token?

https://www.version1.com/an-analysis-of-chatgpt-and-openai-gpt3-how-to-use-it-for-your-business/#:~:text=Tokens%20are%20pieces%20of%20words,250%2C000%20words%2C%20and%20185%2C000%20tokens.

> For text in English, 1 token is approximately 4 characters or 0.75 words.

**Comment by katahiromz** [comment]
If one PR contains 200 lines, and 1 line costs 4 tokens, then one PR contains 800 tokens.
In the Davinci plan, $0.0200 / 1K tokens. So one PR costs  `$0.02 * 800 / 1000 == $0.016`.

**Comment by katahiromz** [comment]
In the Ada plan, the price is $0.0004 / 1K tokens.
If one PR contains 4 file changes, and then 1 file contains 2000 lines, then `4 * 2000 * 8 == 64000` tokens.
The cost is, `$64000 * 0.0004 / 1000 == $0.00256`.

**Comment by katahiromz** [comment]
https://github.com/anc95/ChatGPT-CodeReview/issues/28#issuecomment-1439920146

> OPEN AI API has a limitation for word count. it's not more than about 5000 bytes. so for the bigger file changes, I omit it and don't review.

**Comment by Extravert-ir** [comment]
> This is an example:

Is there an example of a useful comment?

**Comment by HBelusca** [comment]
I wonder how it would look like on an actual ReactOS PR...

**Comment by katahiromz** [comment]
> Is there an example of a useful comment?

https://github.com/anc95/ChatGPT-CodeReview

image

**Comment by katahiromz** [comment]
https://github.com/ThFabba/reactos/pull/6#discussion_r1125528703

image

**Comment by katahiromz** [comment]
ThFabba says:

> there's a requirement to grant the app access to our repository, and it's developed by a random 3rd party

ChatGPT allows free code review of the after source code, outside of GitHub without using an API key.

For example:

```txt
Please review the following code:

... (actual source code) ...

... (ChatGPT will answer) ...
```

We can use free code review manually.

Closed.

**Pull request closed without merging**
