### PR TITLE
[STOBJECT] New AC Adapter Icon

### PR DESCRIPTION
**Pull request by JaredSmudde**
New AC adapter icon taken from the Tango Patcher 2600 program. According to every readme I found by the author of the program, we should be ok with using this icon but I'm not an expert on this. I have included a text file in the resource directory with the licensing information for the icons from the program.
comparison

### CODE REVIEW

**Comment by JaredSmudde** [comment]
Here's both Readmes from the program.
[readme.txt](https://github.com/reactos/reactos/files/3099662/readme.txt)
@EricKohl @HBelusca

**Comment by binarymaster** [comment]
Previous icon looks more sharp (better) for me :thinking:

**Comment by BenNottelling** [comment]
> Previous icon looks more sharp (better) for me 🤔

If you actually zoom into the original it looks like it was taken out of something else and then had part of it erased
https://raw.githubusercontent.com/reactos/reactos/453e5bc2afacf8c9595a50a61714febf21636135/dll/shellext/stobject/resources/battery/ac.ico

**Comment by JaredSmudde** [comment]
That's exactly what happened.

**Comment by blackcrack** [comment]
the smaller icon is more better, the other is oversized !

**Comment by JaredSmudde** [comment]
It's still a 16 pixel icon. As BenNotteling said above, the icon was taken out of something else and that's why it's smaller.

**Comment by BenNottelling** [comment]
I went ahead and made  my own icon, I'm no artist though. I'm uploading it here under no licence, anyone who's interested in ReactOS is welcome to use it if they wish, just providing an alternative to the current icon and the one in the PR. I've added my icon to the bottom of the comparison image that @JaredSmudde uploaded, so it's easier to see how it compares. 
56449934-0a850280-62e6-11e9-93a7-694d6f151dfd


[ac.zip](https://github.com/reactos/reactos/files/3101602/ac.zip)

**Comment by ghostslayer989** [comment]
ac
Ayy?

**Comment by blackcrack** [comment]
hmmm.. i can only say, let the icon like it is at moment.. so the original one,
the wheel new invent again is a bad idea, can only goes more bad.. 

so let the fingers away .. !

best regards
blacky

**Comment by learn-more** [comment]
@EricKohl any input on this?

**Comment by ColinFinck** [comment]
We've just had a look at the suggested icons at ReactOS Hackfest and basically agree to stay with the current AC icon. Thanks for the input of everyone involved :)

**Pull request closed without merging**
