### PR TITLE
[FONT][WIN32SS] Restructure logical fonts and realized fonts

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
JIRA issue: [CORE-14892](https://jira.reactos.org/browse/CORE-14892)

```txt
TEXTOBJ --> LFONT + RFONT
TextIntRealizeFont --> LFONT_Realize
FontGetObject --> LFONT_GetObject
IntGetOutlineTextMetrics --> ftGetOutlineTextMetrics
IntGetFontLocalizedName --> get_face_name
```

WIP.

### CODE REVIEW

**Comment by katahiromz** [comment]
```txt
*** Assertion failed: FontGDI->SharedFace
***   Source File: ../win32ss/gdi/ntgdi/freetype.c, line 5420
```

**Comment by katahiromz** [comment]
I added assertion for SharedFace NULL checks at FontGDI creation. But always SharedFace != NULL at FontGDI creation. I'm doubting that the destruction of FontGDI or SharedFace does.

**Comment by learn-more** [comment]
In `GreExtTextOutW` used to be a call to `RealizeFontInit`,
I suspect that this is what initialized the `SharedFace` before.

**Comment by katahiromz** [comment]
```txt
(e.c:5438) FontGDI->SharedFace is NULL: prfnt->FaceName: Tahoma
```
The target is "Tahoma".

**Comment by learn-more** [comment]
If substitution points to itself,
we first need to increment reference count, then decrement?

**Comment by katahiromz** [comment]
Memory management was broken at all. Ouch!

**Pull request closed without merging**
