### PR TITLE
[APITESTS] Improve ShellExecCmdLine testcase

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
JIRA issue: [CORE-15431](https://jira.reactos.org/browse/CORE-15431)
- Add tests for `"%WINDIR%"`.
- Add friendly comments.

### CODE REVIEW

**Comment by HBelusca** [comment]
So what do we learn with these new tests? Does ShellExecCmdLine() expand the command line or not?

**Comment by katahiromz** [comment]
This testcase successfully passed on Win10. Expansion is inconsistent. So it's better to explicitly expand before ShellExecCmdLine.

**Comment by HBelusca** [comment]
How is expansion isconsistent? It doesn't appear to be so from your test
(I by the way note that you get these E_ACCESSDENIED when you don't allow non-exes for notepad.exe. It seems to be the return code corresponding to https://git.reactos.org/?p=reactos.git;a=blob;f=dll/win32/shell32/shlexec.cpp;hb=aa04a0a6d31477dbf5b3a65cf79a690e44dcd4a7#l2458 in our code. I suspect that here your test is compiled in 32-bit but you run it on a x64 Windows 10, and somehow the test looks at the 32-bit version of notepad.exe (in syswow64) and the potential GetBinaryTypeW() made by shell32.dll fails...

**Comment by katahiromz** [comment]
I compiled as 32-bit executable, and I'm using 64-bit Win10.

**Comment by katahiromz** [comment]
I mean that expansion is not always successful.

**Comment by katahiromz** [comment]
I don't have x86 Win7+

**Comment by katahiromz** [comment]
Temporarily closed.

**Pull request closed without merging**
