### PR TITLE
[USER32][NTUSER] Fix menu arrow drawing (of DrawFrameControl)

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
JIRA issue: [CORE-13211](https://jira.reactos.org/browse/CORE-13211)
Fix `UITOOLS95_DrawFrameMenu` drawing menu arrows of `user32!DrawFrameControl`. `DrawFrameControl` draws invalid if the width is shorter than the height.

- Use the squared rectangle. 
- Draw it in the transparent background mode.
- Save the old background mode of `HDC`.

Also fix `UITOOLS95_DFC_ButtonCheckRadio`. This PR will fix UltraISO's bug.

BEFORE:
MenuArrow-ros
AFTER:
MenuArrow-ros-after

### CODE REVIEW

**Comment by katahiromz** [comment]
The codes of `win32ss/user/ntuser/draw.c` and `win32ss/user/user32/windows/draw.c` are probably getting old. We have to version up them.

**Comment by katahiromz** [comment]
gotcha
Gotcha! This PR also fix UltraISO's bug.

**Comment by katahiromz** [comment]
must-fill-bkgnd
We must fill the background.

**Comment by katahiromz** [comment]
On certain conditions (?), we have to fill the background.

**Comment by JoachimHenze** [comment]
This PR introduced the regression CORE-16470 but we already have PR2009 in the making, which seems to give good results for both bugs.

**Pull request merged**
