### PR TITLE
[AUDIO] Applied [AUDIO] PR and AUDIO-BRINGUP SVN Branch

### PR DESCRIPTION
**Pull request by Zero3K**
## Purpose

I applied the [AUDIO] PR (#1631) (fixed so it can be applied to the master code by Ben Nottelling) and the AUDIO-BRINGUP SVN Branch (https://svn.reactos.org/reactos/!svn/bc/50001/branches/audio-bringup/) (fixed to allow for compiling with v2.2.1 of RosBE by encoded) in order to make audio playback work more reliably.

JIRA issue: [CORE-13488](https://jira.reactos.org/browse/CORE-13488), [CORE-13202](https://jira.reactos.org/browse/CORE-13202)

## Proposed changes

Fixes portcls.sys hanging programs that play audio, fixes wdmaud.drv crashing programs, fixes the things mentioned in the linked PR, etc.

## TODO

- [ ] Fix Portcls.sys BSOD occurring on shutdown, etc. 
- [ ] Fix audio not playing in some cases
- [ ] Fix  [CORE-15100](https://jira.reactos.org/browse/CORE-15100)
- [ ] Get it to play audio from more than one program at a time

### CODE REVIEW

**Comment by BenNottelling** [comment]
Please note that in its current state the portcls in this PR will revert PR #2302 and reintroduce CORE-[16611](https://jira.reactos.org/browse/CORE-16611)

**Comment by BenNottelling** [comment]
You are creating TODO's of things you have no hope of fixing yourself.. are you expecting people to just come by and do the work for you?

**Comment by Zero3K** [comment]
> 
> 
> You are creating TODO's of things you have no hope of fixing yourself.. are you expecting people to just come by and do the work for you?

If they tell me what to change. I will change it.

**Comment by BenNottelling** [comment]
> If they tell me what to change. I will change it.

That is making them do the work

**Pull request closed without merging**
