### PR TITLE
[USER32][WIN32SS] Implement CascadeWindows function

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
This PR will implement CascadeWindows function in user32.
JIRA issue: [CORE-14807](https://jira.reactos.org/browse/CORE-14807)

### CODE REVIEW

**Comment by katahiromz** [comment]
cascade

**Comment by katahiromz** [comment]
cascade2

**Comment by katahiromz** [comment]
Done.

**Comment by Mouvedia** [comment]
If you continue stacking windows in your second screenshot the 11th will overflow on the right side of the screen?

**Comment by katahiromz** [comment]
If it's to be overflowed on the right side, that will be adjusted to the left side. See source.

**Comment by ThFabba** [comment]
Quick tip for future reference: every time you push to a branch that has a PR open against it, people get an email notification. So if you could wait to push multiple commits at once, or only put up the PR once you're satisfied with the code, that would help avoid some spam.
Thanks!

**Comment by katahiromz** [comment]
It works.
it-works

**Comment by HBelusca** [comment]
Cool :smiley:

**Pull request merged**
