### PR TITLE
[THEMES] New ReactOS theme - Aigul

### PR DESCRIPTION
**Pull request by ConLenov**
Aigul is a theme made specifically for ReactOS. The design style I came up with.
The design concept appeared a long time ago. I made the design myself. With this design theme, ReactOS will be at least a little prettier.

### CODE REVIEW

**Comment by peterooch** [comment]
Screenshots? Can we see how this theme looks like?

**Comment by HBelusca** [comment]
Hi! Maybe a README / LICENSE file that mentions under which (artistic) license you provide your work would be welcome :)

**Comment by Extravert-ir** [comment]
It's not a secret that none of the default themes in ReactOS are polished well-enough, and have a lot of small (and not so small) issues if you try to use them in real life (for example, on Windows XP).

So yes, I want to see some screenshots :)

**Comment by jeditobe** [comment]
The main problem is that the text on the taskbar is not visible...

**Comment by ConLenov** [comment]
The text on the taskbar is not visible, because it was a LiveCD, and in the installed OS, the text on the taskbar is normally visible.
VirtualBox_ReactOS_03_10_2019_08_05_40

**Comment by EnterWINE** [comment]
This theme will be added in ReactOS?

**Comment by BenNottelling** [comment]
> This theme will be added in ReactOS?

Not necessarily, it ultimately depends on the community reaction to it I suppose, but at the least it could likely end up in RAPPS

**Comment by EnterWINE** [comment]
Stylish Theme. Looks beautiful.

**Comment by oleg-dubinskiy** [comment]
> The text on the taskbar is not visible, because it was a LiveCD

I noticed that this bug happens randomly for me with all my third-party themes even in BootCD. So it does not depend on LiveCD.

**Comment by cuchma19** [comment]
Add this theme to ReactOS. Because it’s very beautiful. This is a bright theme. ReactOS now has only dark skin. Add to ReactOS please

**Comment by wjk** [comment]
@ConLenov, I just wanted to let you know that even if this theme can't go into the main tree, there is a dedicated category in RAPPS for visual themes. You could always add it there.

**Comment by HBelusca** [comment]
But the problem is that we don't host what's inside RAPPS, we just merely provide download links.

**Comment by cuchma19** [comment]
You can add a theme in 0.4.13 One theme in ReactOS won't hurt anyone

**Comment by binarymaster** [comment]
> But the problem is that we don't host what's inside RAPPS, we just merely provide download links.

@ConLenov can create his own separate repository on GitHub and host prebuilt themes in the releases section, which can be accessed from RAPPS via direct link.

**Comment by blackcrack** [comment]
maybe would be more better if exist a Reactos-Theme Repository , like in KDE, 
to have a possibility for selecting and downloading different themes from a Server..

i have a collection of themes downloaded and have put together for a more easy download the whole Themes, maybe can you are take this files for building up a Theme Reactos repository.

http://www.blackysgate.de/files/folder-root/ros/WinXP-Themes/

**Comment by EnterWINE** [comment]
Please add this skin to the ReactOS 0.4.13 repository

**Comment by cernodile** [comment]
Honest opinion: it lacks professionalism you'd expect from a base install, I'd opt this for rapps instead. There is no excuse for "can't host" as OP did build theme and can move it to own repo and host ready msstyle there. Also @cuchma19 did you seriously make an account just for this PR (or perhaps you are an alt of OP).

**Comment by learn-more** [comment]
@ConLenov making multiple accounts to praise your own contribution is not going to influence our decision making in merging a PR.

**Comment by feel-the-dz3n** [comment]
Omg so cooool

**Comment by blackcrack** [comment]
humm, jokes about multible accounts..
humm, from  where do we know it also... Reactos Forum ? Kicking out Members ?
not really honest ?

And then making Jokes about to make it not really important and make it funny ..

nice ... this about multible account and not really honest !

Hey "Mr. Xpert" , why do you not write here ?

Close this Tread, is my voting .. (but do not Delete to have evidence )  
Mr.Xpert have it not ! (because my Livetime Ban in the Forum) 
@HBelusca and to other @Reactos_Projectleaders

this is why i am so angry about these f.. Jokes about ..

best regards
Blacky

**Comment by katahiromz** [comment]
There's abuse in this PR. For fairness, I close this PR.
Coloring is not photogenic for normal people.

**Comment by cuchma19** [comment]
Why is it closed?

**Pull request closed without merging**
