### PR TITLE
[COMCTL32] Export LoadIconMetric and LoadIconWithScaleDown

### PR DESCRIPTION
**Pull request by andrew-boyarshin**
## Purpose

They are already implemented and there is little sense for them to be hidden.
Required for ProcessHacker 3.0+.

JIRA issue: None

## Origin of changes
I have a [collection of patches](https://github.com/andrew-boyarshin/reactos/tree/a11y) to ReactOS for quite some time (regularly rebased upon upstream). Finally I've decided to send PRs upstream. These PRs (a lot more to come) are generated automatically based on latest `a11y` branch in my repo.

## Wine

### CODE REVIEW

**Comment by andrew-boyarshin** [comment]
`version` for now just deletes the entry (skips it), without adding it to any kind of shim library, does it not? What's the point in export that is inactive? That also applies to some other places in my branch.

**Comment by learn-more** [comment]
The idea is that we will generate multiple versions of the same dll, each for a specific NT version.
Some initial work for this has been done: #896, but more remains to be done still.

**Comment by learn-more** [comment]
@andrew-boyarshin We are working on a system to use those versioned exports.

**Comment by learn-more** [comment]
Thanks for your contribution!

**Pull request merged**
