### PR TITLE
[WIP] Enable support for IFileOpenDialog and IFileSaveDialog

### PR DESCRIPTION
**Pull request by wjk**
## Purpose

Does mostly what the title says. The comments in the code disabling these features simply says "Win 7". As I understand it, while Vista+ APIs were formerly out of scope for ReactOS, this policy has since been relaxed, as evidenced by PRs such as #240, as well as the `*_vista` DLLs currently in the source tree. In addition, this change helps me port some of my “real” Windows applications to run on ReactOS.

## Proposed changes

- Re-enable support for Wine’s `IFileOpenDialog` and `IFileSaveDialog`.
- I have not modified the implementation of these interfaces at all. I have simply removed the code that disabled them from compiling, and added `comdlg32.dll` to `media/inf/syssetup.inf` so it will be registered at installation time.

## TODO

- [ ] Add a test application under `modules/rostests/win32` that can be used to exercise the API interactively.
- [ ] Finish importing required APIs from Wine into `shell32`.

### CODE REVIEW

**Comment by wjk** [comment]
And, as it turns out, this code uses APIs not currently in our version of shell32. Therefore, the code in this PR doesn't link. I'll try looking into porting the requisite APIs from Wine into our shell32, but no guarantees that I will be successful, because our shell32 implementations are so wildly different. Thanks for bearing with me!

**Comment by ROCKNROLLKID** [comment]
Might want to put WIP in the label as well.

Anyways, good job with this. You have been doing such great work for ReactOS so far. Keep it up!

**Comment by ThFabba** [comment]
So, we haven't really discussed in detail how we're dealing with higher version APIs yet. The right approach here might be to put this functionality in comdlg32_vista.dll, then have the shim engine make it visible to applications configured for NT6. I don't think we're at the point where it's fully accepted to just put Vista functions into everything.
Other people may have more specific or up-to-date input on this though.

**Comment by gigaherz** [comment]
We don't yet know how apps react to a hybrid system: there is a chance applications assume that if one thing is present, others will be. So yes, there is a risk in adding exports to the standard DLLs. But on the other hand, we won't know if we don't try... I'm divided.

**Comment by HBelusca** [comment]
I think the best would be the _vista.dll shim idea. When we enable it for a given app we can then immediately see whether it wants (many) more features, or not.

**Comment by yagoulas** [comment]
I understand that there are apps out there that require this class to exist. This patch set won't work as it is right now because it requires CLSID_ExplorerBrowser which is missing from shell32 (a vista+) feature as well. I don't really like the idea about adding more and more vista stuff in shell32. We could try a compromise where comdlg32 is kept in sync with wine with minimum changes from us and keep the vista+ features in a new dll called shell32_vista. This dll should export the functions you added in shell32 and also wine's implementation of CLSID_ExplorerBrowser. Can you do this?

**Comment by wjk** [comment]
Once #419 has been completed and merged, I will start work on migrating `shell32_vista` to be loaded automatically by the sxs subsystem in lieu of normal `shell32` (cf. the "Future work" section in https://github.com/reactos/reactos/pull/298#issue-163738248). This may require tweaks to the first-stage setup (such that `shell32_vista.dll` can be called as such in the cab file, to avoid conflicting with the version to be put in System32, yet be renamed to `shell32.dll` once installed within the winsxs directory), which I will submit in a separate PR. Thanks!

**Comment by learn-more** [comment]
Thanks for your work.

Sadly. at the moment ReactOS lacks versioning support in our system DLL's to support this.
We will revisit this when we have worked out a way to handle versioning.

**Pull request closed without merging**
