### PR TITLE
[MSGINA] Improve Japanese and Chinese status dialog

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Asian dialog resources are using different fonts from English ones. Because of it, the Asian dialog item layouts are collapsing. This PR will fix the dialog item layouts.
JIRA issue: [CORE-16697](https://jira.reactos.org/browse/CORE-16697)
BEFORE (Japanese):
before
AFTER (Japanese):
after
AFTER (English):
after-english

### CODE REVIEW

**Comment by katahiromz** [comment]
AFTER (Japanese with standard fonts):
after-with-fonts
AFTER (Chinese):
after-chinese

**Comment by binarymaster** [comment]
Note that Windows XP/2003 (and probably 2000 too) does the drawing of logo and bar differently. They don't have these bitmaps on dialogs, but they somehow add them dynamically in code.

Comparison screenshot of dialog window resources (Windows XP at the top, ReactOS at the bottom):

image

**Comment by katahiromz** [comment]
We can shift all the dialog items down and draw the logo and the bar upon `WM_PAINT` message...
with dialog resizing...

**Comment by Prince-Kassad** [comment]
Windows dynamically loads bitmaps so they can do differentiation based on ProductSuite (i. e. Professional/Home). Not sure ReactOS needs to mimic the Windows way since there aren't any different suites.

**Comment by katahiromz** [comment]
It seems not a best solution. Closed.

**Comment by HBelusca** [comment]
Just adding extra doc concerning windows:
- the dialogs are just the templates (as shown by @binarymaster );
- the images are separate (but they are language-independent);
- when the dialogs are created, extra space on top of them is reserved for inserting the images
so their height during creation is modified (original_height + branding_image_height + scroll_band_height) and all the children controls in the dialog are moved down accordingly;
- the branding image is then added on top and centered horizontally, and extra colouring is added on the left and on the right of the centered image by copying the left-most and right-most pixels.
- The scrolling band may just be redimensionned horizontally.

**Pull request closed without merging**
