### PR TITLE
[THEMES] Fix mizu start logo resource

### PR DESCRIPTION
**Pull request by A-Rafael**
Before:
before
After:
after

### CODE REVIEW

**Comment by binarymaster** [comment]
@foxlet said on development channel:
> I have different ideas for Mizu updates.
> I don’t think the start icon is bad in particular, but that’s a different glyph altogether.

Personally I like your change, but I think it would be better to leave decision to the original author.

**Comment by A-Rafael** [comment]
The original logo has defects due to small size. The new logo can be used as a temporary solution until the original logo is fixed.

**Comment by HBelusca** [comment]
The wallpaper looks nice, is it already in our wallpaper library? If not, and if its license is compatible, maybe you can consider making a PR for wallpaper inclusion.

**Comment by A-Rafael** [comment]
https://wallpaperplay.com/walls/full/9/3/f/29133.jpg
I could not find information about the license, it seems the primary source (dw4.me or desktopwallpaper4.me) has not been working for a long time.

**Comment by binarymaster** [comment]
> I could not find information about the license, it seems the primary source (dw4.me or desktopwallpaper4.me) has not been working for a long time.

https://web.archive.org/web/20180416015946/http://www.desktopwallpaper4.me/minimalistic/blue-dotted-pattern-231/

**Comment by foxlet** [comment]
#2408 has an updated start button glyph.
Screenshot_20200410_153700

**Comment by Extravert-ir** [comment]
Hm, is it different from the one on "Before" screenshot?

**Comment by foxlet** [comment]
Yes, the outer orb lines have new weights to fix some of the aliasing.

**Comment by A-Rafael** [comment]
I think is too little space for two lines

**Comment by foxlet** [comment]
Subjectively, I feel the center orb has enough contrast with double lines; the proposed alternative has much less contrast overall. I'm willing to do an A/B with a filled single-line for the center, and see how it works out.

**Comment by A-Rafael** [comment]
Since another pull request with fix was closed, perhaps this one would be useful?

**Pull request merged**
