### PR TITLE
[OLE32] Fix Wine's implementation of IMalloc.DidAlloc ahead of Wine 5.7 (CORE-15262)

### PR DESCRIPTION
**Pull request by KyleKatarn31**
## Purpose

_ Wine's implementation of IMalloc.DidAlloc.
_ Problem reported to WineHQ : https://bugs.winehq.org/show_bug.cgi?id=48941
_ Implementation done in Wine 5.7
_ Patch produced by @Doug-Lyons to get the fix ahead of WineSync with Wine 5.7

JIRA issue: [CORE-15262 ](https://jira.reactos.org/browse/CORE-15262 )

## Proposed changes

_ Integration of patch produced by Doug here : https://jira.reactos.org/browse/CORE-15262
_ Test done with SUMo 5.10.16 => No more exceptions raised when called "Scan folder" a second time and no functionnal impact (problem is solved)

### CODE REVIEW

**Comment by KyleKatarn31** [comment]
@Doug-Lyons @sdever : for Review following the discussion on Mattermost & Jira Issue.

**Comment by KyleKatarn31** [comment]
> 
> 
> LTGM

LTGM ?

**Comment by HBelusca** [comment]
I see that this patch contains slightly more changes than those committed in Wine
https://github.com/wine-mirror/wine/commit/08f4b6ee0a05fe27e56cb9777dce845dcf1072f8
Any reason why?

**Comment by KyleKatarn31** [comment]
> 
> 
> I see that this patch contains slightly more changes than those committed in Wine
> [wine-mirror/wine@08f4b6e](https://github.com/wine-mirror/wine/commit/08f4b6ee0a05fe27e56cb9777dce845dcf1072f8)
> Any reason why?

Of course, I let @Doug-Lyons provide his view on that.

**Comment by Doug-Lyons** [comment]
LGTM - US English abbreviation for Looks Good To Me

@HBelusca, In Wine there were a set of three patches that were submitted together by Nikolay Sivov from this page: https://source.winehq.org/patches/

Individually they are as follows:
https://source.winehq.org/patches/data/183617

https://source.winehq.org/patches/data/183619

https://source.winehq.org/patches/data/183618

My thoughts were to just keep all of these together because they were done in the same time frame and have less syncing required later.

**Comment by KyleKatarn31** [comment]
Would such a PR require #ifdef __REACTOS__ ?

**Comment by Doug-Lyons** [comment]
> Would such a PR require #ifdef **REACTOS** ?

@KyleKatarn31, Since there changes have already been committed in Wine, the "#ifdef..." should not be necessary.

**Comment by KyleKatarn31** [comment]
> 
> 
> > Would such a PR require #ifdef **REACTOS** ?
> 
> @KyleKatarn31, Since there changes have already been committed in Wine, the "#ifdef..." should not be necessary, but since our readme.wine indicates a sync version maybe they should be. I will let a developer chime in here with their opinion.

OK, perfect.

**Comment by KyleKatarn31** [comment]
If not to be mergedi will close this PR since i'm likely the only one interested by this fix.

**Comment by KyleKatarn31** [comment]
Thanks

**Pull request merged**
