### PR TITLE
[COMCTL32] fix image list reading/writing (version number and mixing algorithm)

### PR DESCRIPTION
**Pull request by Getequ**
Fix version number in reading/writing image list streams and counting pointers for mixing image & mask while reading. Works perfect on data from *.reg files exported from XP/2003.

This is a part of managing tray icons hiding behaviour.

### CODE REVIEW

**Comment by HBelusca** [comment]
Let's first wait until Wine agrees with your patch sent upstream.

**Comment by Getequ** [comment]
Yeah, i was sended to them.

**Comment by JoachimHenze** [comment]
some experiments with PR619 (after commit1) manually applied on top of 0.4.10-dev-435-gfb5d5ec:
-CORE-14433 persists
-CORE-12377 persists
-CORE-14671 symptoms change slightly, not sure whether progress or regress actually

**Comment by gonzoMD** [comment]
Resend to wine. Your patch is out of the list.

**Comment by GeoB99** [comment]
I'm going to close this since this PR as is been sitting here for quite a long time with not further input. Feel free however to poke me though in case you want to continue working on this.

**Pull request closed without merging**
