### PR TITLE
[ROSAPPS] Remove unmaintained / half-implemented imagesoft

### PR DESCRIPTION
**Pull request by learn-more**

### CODE REVIEW

**Comment by HBelusca** [comment]
oh no! 😢😢
Can we move it instead to a separate github/reactos sub-project?

**Comment by HBelusca** [comment]
By the way in case you've tested it on ReactOS or on Windows, imagesoft strangely regressed: Whether tested on Win10 or Win2003 or on ReactOS:

- master version looks like this:
image

- while previous releases (0.4.14 and before) look like that (and work):
image

**Comment by Extravert-ir** [comment]
> Can we move it instead to a separate github/reactos sub-project?

We may do that, but I _very very_ much doubt it would be interesting to anyone.

**Review by Extravert-ir — APPROVED** [review]

**Comment by learn-more** [comment]
> oh no! 😢😢
> Can we move it instead to a separate github/reactos sub-project?

For what purpose?

**Comment by HBelusca** [comment]
> > oh no! 😢😢
> > Can we move it instead to a separate github/reactos sub-project?
> 
> For what purpose?

For the same purposes/reasons as to why we have reactos/reactosdbg, reactos/RosTE, reactos/Qemu_GUI, reactos/Message_Translator or reactos/packmgr : so that people can continue working on it (as part of starter_project).
It also offers an example of a lightweight C win32 app that has draggable toolbars that can turn into toolwindows, flat comboboxes... without using MFC or other frameworks. (Examples for such functionalities not using such frameworks being extremely hard to find on the Internet nowadays...)

**Comment by learn-more** [comment]
> > > oh no! 😢😢
> > > Can we move it instead to a separate github/reactos sub-project?
> > 
> > 
> > For what purpose?
> 
> For the same purposes/reasons as to why we have reactos/reactosdbg, reactos/RosTE, reactos/Qemu_GUI, reactos/Message_Translator or reactos/packmgr : so that people can continue working on it (as part of starter_project).
> It also offers an example of a lightweight C win32 app that has draggable toolbars that can turn into toolwindows, flat comboboxes... without using MFC or other frameworks. (Examples for such functionalities not using such frameworks being extremely hard to find on the Internet nowadays...)

We are trying to write an OS,
not maintaining an history of half-written applications that noone cares about.

You certainly didn't care about it until I started deleting it, so I am unsure why you start caring about it now.

**Comment by learn-more** [comment]
Considering @HBelusca started committing on this thing shortly after this PR,
after the app not being touched for over 10 years I am going to ignore his comments.

**Comment by binarymaster** [comment]
Quote from the chat:

> I opened a PR because I noticed this application, I saw that it was unmaintained for 10 years, and it works half.

Does it still work half even after some commits were pushed to master recently?

We have quite lot of unmaintained modules, and it's better to spend time writing an OS (as you just pointed above) than removing these modules, especially if they're blocking nothing.

Also I think we require @tbluemel and @gedmurphy opinions here, as module authors.

**Comment by ColinFinck** [comment]
And this is exactly why I have suggested splitting off certain parts of https://github.com/reactos/reactos into standalone repositories a few times already.

I agree with @learn-more that the base repository should be rather small, or we risk getting a PR for the umpteenth screensaver without a clear reason to accept or deny it.
But I also get @HBelusca's position that good and working Win32 code should be preserved. I recall multiple good Win32 apps from @gedmurphy and @tbluemel back in the days, which later served as templates for new projects. ImageSoft was one of them.

Take into account that ReactOS today is also a treasure of documentation, maybe even more than the OS itself. Whenever I talk with people about ReactOS, they usually know it from looking up Windows details for their development work.
Microsoft itself hasn't really released new Win32 example code since they shifted priorities to C# 20 years ago. Hence, our Win32 apps can easily become the better Win32 examples.

Finally, ReactOS is at a point where the basics are mostly working and now everybody has a different idea of what belongs into the OS and what doesn't. We can't make everyone happy with just a single static repository.

**Comment by learn-more** [comment]
> > > oh no! 😢😢
> > > Can we move it instead to a separate github/reactos sub-project?
> > 
> > 
> > For what purpose?
> 
> For the same purposes/reasons as to why we have reactos/reactosdbg, reactos/RosTE, reactos/Qemu_GUI, reactos/Message_Translator or reactos/packmgr : so that people can continue working on it (as part of starter_project). It also offers an example of a lightweight C win32 app that has draggable toolbars that can turn into toolwindows, flat comboboxes... without using MFC or other frameworks. (Examples for such functionalities not using such frameworks being extremely hard to find on the Internet nowadays...)

Are you going to maintain this new repo?

> Quote from the chat:
> 
> > I opened a PR because I noticed this application, I saw that it was unmaintained for 10 years, and it works half.
> 
> Does it still work half even after some commits were pushed to master recently?

The very **first** menu item (File->New) has as sole purpose to slam an 'Unimplemented' messagebox in your face.

> 
> We have quite lot of unmaintained modules, and it's better to spend time writing an OS (as you just pointed above) than removing these modules, especially if they're blocking nothing.

I'd rather remove some of those.

**Comment by learn-more** [comment]
https://github.com/reactos/win32-examples has been created.

**Pull request merged**
