### PR TITLE
[SHLWAPI] Implement SHIsLowMemoryMachine

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

Implement `shlwapi!SHIsLowMemoryMachine` function.

JIRA issue: N/A

### CODE REVIEW

**Comment by ThFabba** [comment]
What does this fix? Introducing ROS-Diffs in Wine code without application benefits is counterproductive.

**Comment by KyleKatarn31** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-shislowmemorymachine
"Note  Always returns FALSE under Windows XP."

Therefore, why would we need the 16 MB threshold for ROS ? (even for compatibility for low end apps eventuelly calling this API)

**Comment by HBelusca** [comment]
> "Note Always returns FALSE under Windows XP"

But not on Win2k3 (which is our target).

**Comment by KyleKatarn31** [comment]
OK !

**Pull request merged**
