### PR TITLE
[syssetup] Change "Select the theme you prefer" to "Select the theme …

### PR DESCRIPTION
**Pull request by JaredSmudde**
…you prefer." to fit in with the other titles in second stage setup.

### CODE REVIEW

**Comment by encodedpr** [comment]
How about just "Select Theme" ?

**Comment by JaredSmudde** [comment]
That's a difficult question. :D

Let's get some other opinions. :)

**Comment by Harteex** [comment]
If you want opinions, another suggestion is "Select your preferred theme."

**Comment by ThFabba** [comment]
https://en.wiktionary.org/wiki/bikeshedding

**Comment by JaredSmudde** [comment]
I have plenty of trivial changes laying around. :D

**Pull request merged**
