### PR TITLE
[EXTRACT] Fix argv leakages in wWinMain of extract32

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Based on a patch created by vicmarcal.
JIRA issue: [CORE-11210](https://jira.reactos.org/browse/CORE-11210)

### CODE REVIEW

**Comment by katahiromz** [comment]
@vicmarcal What's your e-mail address?

**Comment by learn-more** [comment]
@katahiromz If he does not respond, we can go with the one from `dll/cpl/mmsys/sounds.c`, which is:
`Victor Martinez Calvo <victor.martinez@reactos.org>`

**Comment by SergeGautherie** [comment]
Shouldn't we use some `#ifdef __REACTOS__`, as this is Wine Sync'ed?

**Comment by katahiromz** [comment]
Should we send a patch to Wine at first?

**Pull request closed without merging**
