### PR TITLE
[THEMES] Improve text colors of Modern Dark theme

### PR DESCRIPTION
**Pull request by raxracks**
## Purpose

Improve readability of text in the Modern dark theme

## Proposed changes

Use lighter text colors and darker text shadow colors

Before:
image

After:
image

### CODE REVIEW

**Review by learn-more — CHANGES_REQUESTED** [review]
Hello,
Thanks for your interest in ReactOS!
We ask our contributors [to use their full name when committing](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations).
[Please amend your commit with your full name](https://stackoverflow.com/a/3042512), and update this PR.

To change this for future PR's, you can update it for globally (for the system):
```
git config --global user.name "Your Name"
git config --global user.email you@example.com
```

Or just for the current repository:
```
git config user.name "Your Name"
git config user.email you@example.com
```

Regards,

**Comment by raxracks** [comment]
I've used my full name for this commit and added the new values to the other font weights too

**Review by binarymaster — DISMISSED** [review]
There are some commits that have correct author name and some are not:

image

Also you need to set up your GitHub account correctly, so maintainers can use Squash and Merge button without getting the author field modified back to nickname by GitHub, it's done in two steps:

1. Set your full name in [GitHub profile settings](https://github.com/settings/profile)
1. Uncheck `Keep my email addresses private` in [GitHub email settings](https://github.com/settings/emails)

Regards,

**Comment by raxracks** [comment]
I've fixed the issues with my account, do I need to fix the name in the old commit somehow?

**Comment by binarymaster** [comment]
I think it should be mergeable now by Squash & Merge.

**Review by HBelusca — APPROVED** [review]

**Review by binarymaster — APPROVED** [review]

**Comment by HBelusca** [comment]
@raxracks For the future, please create your PRs from separate branches (one for each of your PRs) of your fork, and not directly from "master".

**Pull request merged**
