### PR TITLE
[SYSSETUP] Tweak IDD_COMPUTERPAGE positioning

### PR DESCRIPTION
**Pull request by JoachimHenze**
- make all 3 input boxes IDC_COMPUTERNAME, IDC_ADMINPASSWORD1, IDC_ADMINPASSWORD2 on this page the same length for all languages and start and end at same x-coord, e.g. sk-SK.rc, uk-UA.rc
- let the input boxes end at the same x as the edits in the previous dlg IDD_OWNERPAGE
- respect the right margin of the dialog with all controls for all languages, makes it look more harmonic to previous and next dlg, see video: [ro-RO_after_Demo.webm](https://user-images.githubusercontent.com/33393466/227831629-78708075-c977-4a70-994e-cc65058c538b.webm)
- make the input fields as wide as possible, but not wider, depending on what the language allowed I used width of 139, 148, 163 (163 is same as the EDITs in IDD_OWNERPAGE used)
- fix too small x offset for some controls in some languages like bg-BG.rc, that looked very off
- in zh-CN.rc fix the maximum allowed length for computer name from 63 to 15

I did test ALL localizations and all do look fine now. I will attach all pics to the PR.

I worked 2 full days on that.

### CODE REVIEW

**Comment by JoachimHenze** [comment]
An after-video:
[ro-RO_after_Demo.webm](https://user-images.githubusercontent.com/33393466/227831629-78708075-c977-4a70-994e-cc65058c538b.webm)

And all the after-pics for each and every language:
bg-BG
cs-CZ
da-DK
de-DE
el-GR
en-GB
en-US
es-ES
et-EE
eu-ES
fr-FR
he-IL
hi-IN
hr-HR
hu-HU
id-ID
it-IT
ja-JP
nl-NL
no-NO
pl-PL
pt-BR
pt-PT
ro-RO
ru-RU
sk-SK
sq-AL
sv-SE
th-TH
tr-TR
uk-UA
zh-CN
zh-HK
zh-TW

**Comment by katahiromz** [comment]
`zh-HK` is something wrong.

**Comment by JoachimHenze** [comment]
> `zh-HK` is something wrong.

Yes, but this was not caused by my changes. It affected all hk-HK dialogs, not just the one I touched. But as you can see in the screenshot, we can see that the words before the 3 edits are not cut off (meaning that my changes are correct and left enough room for those words).

I tested all languages on master head except the following 4 that I tested differently: ja-JP, zh-CN, zh-HK, zh-TW. For those 4 I used the 0.4.14release 1st stage setup (which does offer the needed fonts in 2nd stage unlike master head), and then copied the syssetup.dll from master onto the HDD, replacing the existing one. This is kind of fancy, but it worked. Since zh-HK did not exist in the 0.4.14release yet, that may explain the weird looking result where every dlg had the wrong size.
But like I said: I could see, what I wanted to see anyway: enough room for the words before the EDIT-controls. I could verify my changes to be correct!

**Review by katahiromz — APPROVED** [review]

**Review by KRosUser2 — CHANGES_REQUESTED** [review]
Seen on chat : "Administrator password:" text is cropped in some languages on your "after" screenshots - namely id-ID and uk-UA.

**Review by KRosUser2 — APPROVED** [review]
Lgtm

**Review by HBelusca — APPROVED** [review]
I'm fine with that as long as all the text is correctly visible and not cropped, and the changes are done consistently across all translations.

**Comment by JoachimHenze** [comment]
[pl-PL.webm](https://user-images.githubusercontent.com/33393466/228235404-90e5e213-dfff-4ca2-8a9f-72f361afb420.webm)
after the last commit

**Review by katahiromz — APPROVED** [review]

**Pull request merged**
