### PR TITLE
Create bg-BG.rc

### PR DESCRIPTION
**Pull request by WindowxDeveloper**
## Purpose

_Do a quick recap of your work here._

JIRA issue: [CORE-XXXX](https://jira.reactos.org/browse/CORE-XXXX)

## Proposed changes

_Describe what you propose to change/add/fix with this pull request._

- 
- 

## TODO

_Use a TODO when your pull request is Work in Progress._

- [ ] 
- [ ]

### CODE REVIEW

**Comment by katahiromz** [comment]
It seems like English.

**Comment by WindowxDeveloper** [comment]
> It seems like English.

That's because I was busy with so many things getting in the way of making some language files for ReactOS. But if you look again, some words are in Bulgarian. I might edit it as soon as I use free time.

**Comment by HBelusca** [comment]
> > It seems like English.
> 
> That's because I was busy with so many things getting in the way of making some language files for ReactOS. But if you look again, some words are in Bulgarian. I might edit it as soon as I use free time.

So I mark this PR as work-in-progress.

**Comment by learn-more** [comment]
Looking at your profile, you are not someone we want to be associated with.

**Pull request closed without merging**
