### PR TITLE
[REACTOS] Fix '\NLS\' typos

### PR DESCRIPTION
**Pull request by SergeGautherie**
Use `\Nls\`, as everywhere else.

NB:
1 case remains in `dll/win32/kernel32/winnls/string/lang.c`: to be WineSync'ed...

### CODE REVIEW

**Comment by ThFabba** [comment]
Registry keys are case-insensitive, so this is a non-issue.
[I'm not going to close this since it's not wrong, but I'm also not willing to spend time on this.]

**Comment by SergeGautherie** [comment]
> Registry keys are case-insensitive, so this is a non-issue.

Yeah, nonetheless using same (expected) case everywhere improves consistency, and makes searching much simpler, for example.

> [I'm not going to close this since it's not wrong, but I'm also not willing to spend time on this.]

(This PR is similar to a1c13a964f56626dd704cd07c63d03699b6f5043, for example.)

**Comment by learn-more** [comment]
It is not really similar,
that PR changes strings that are next to each other for consistency,
this PR change strings all over the codebase.

**Comment by SergeGautherie** [comment]
> It is not really similar

Well, it probably depends on which similarity/difference one looks at :-|
I didn't expect this trivial search and replace to create a debate :-(

**Comment by ThFabba** [comment]
Enough bikeshedding

**Pull request closed without merging**
