### PR TITLE
[TASKMGR] Allow to kill critical system processes

### PR DESCRIPTION
**Pull request by feel-the-dz3n**
## Purpose

Why not to allow to kill critical system processes

## Proposed changes

- Allow to kill critical system processes
## Before:
before_gif
## After:
after_gif

## TODO

- [x] Allow to kill system processes
- [x] Update text in all Resource Files
- [x] Update Ukrainian and Russian because I know these languages
- [ ] Keys

### CODE REVIEW

**Comment by katahiromz** [comment]
Funny but it smells like dangerous impression.

**Comment by learn-more** [comment]
I don't see the value in this.

**Comment by feel-the-dz3n** [comment]
> I don't see the value in this.

Similar thing appeared in Windows 7
image
Maybe it would be useful for testing some system programs. But I don't know, maybe it's useless :sweat_smile:

**Comment by katahiromz** [comment]
Knife is also useful even on deskwork but police won't allow it at public space. That is not demand.

**Comment by katahiromz** [comment]
That dialog will be implemented in the ghosting feature.

**Comment by binarymaster** [comment]
Well, actually this feature can be useful while fixing that reddish BSoD with corrupted VGA display.

**Comment by katahiromz** [comment]
To implement as "developers´ mode"?

**Comment by binarymaster** [comment]
> To implement as "developers´ mode"?

Exactly. ReactOS is for advanced users. :slightly_smiling_face:

**Comment by katahiromz** [comment]
OK, then, can we use the registry?

HKEY_LOCAL_MACHINE\...\DevelopersMode==1

**Comment by binarymaster** [comment]
I believe some documented local policy in the registry already exists to control that behaviour.

**Comment by katahiromz** [comment]
I had Google'd such registry key but not found.
We can also use Shift key and/or Ctrl key.

**Comment by feel-the-dz3n** [comment]
> I had Google'd such registry key but not found.
> We can also use Shift key and/or Ctrl key.

or start task manager with some arguments

**Comment by katahiromz** [comment]
`GetKeyState(VK_SHIFT) < 0 && GetKeyState(VK_CONTROL) < 0`

**Comment by feel-the-dz3n** [comment]
> `GetKeyState(VK_SHIFT) < 0 && GetKeyState(VK_CONTROL) < 0`

Well, I will make it later. Also, remove the second confirmation dialog?

**Comment by katahiromz** [comment]
The 2nd dialog is needed.

**Comment by feel-the-dz3n** [comment]
> The 2nd dialog is needed.

OK. I will do everything later)

**Comment by tkreuzer** [comment]
@binarymaster 
> Well, actually this feature can be useful while fixing that reddish BSoD with corrupted VGA display.
We have a mechanism to bugcheck the system manually, if that is what you are looking for. No need to kill a system process.

**Comment by MailYouLater** [comment]
@tkreuzer: If you watch the second GIF above, where CSRSS gets killed, you'll see what appears to be some form of graphical corruption in the bugcheck screen. i.e. the background is red instead of blue, and the whole thing is crammed at the very top section of the screen, while the rest of the screen remains as it was before the bugcheck occured. This is what @binarymaster was referring to.

I don't know if this is an issue caused by killing CSRSS in this way, or if it's specific to the emulation environment in use, but it doesn't look right. Perhaps @feel-the-dz3n can shed more light on what it is, and if necessary, report it on JIRA.

**Comment by ThFabba** [comment]
It's a bug in VirtualBox, it doesn't handle the graphics mode switch right. This happens with every bluescreen, including Windows's. Clicking the VM window's Close button, then canceling the shutdown/pause/turn off dialog should fix it.

**Comment by MailYouLater** [comment]
Weird. Thanks for the info. Is it something that should be reported to the VirtualBox developers?

**Comment by blackcrack** [comment]
@feel-the-dz3n , @binarymaster ,  @katahiromz 
would maybe useful if this able to use 
as admin group too ?

**Comment by binarymaster** [comment]
> We have a mechanism to bugcheck the system manually, if that is what you are looking for. No need to kill a system process.

Ok, here is another point: Malware often mask their file names as critical processes to make it harder to terminate its process. So it still would be useful to allow to terminate such processes at user's risk.

> as admin group too ?

I don't get the idea what you're asking. Non-admin users would never be able to kill system processes.

**Comment by blackcrack** [comment]
> I don't get the idea what you're asking. Non-admin users would never be able to kill system processes.
you have get it in direction :) how ever.. yes as admin.. to have a possible for kill/terminate some prozesses who be mark as system, to have a possible be able for handle that . :+1:

**Comment by ale5000-git** [comment]
@feel-the-dz3n: Not strictly related but what about displaying in different color processes that can't be terminated?

**Comment by Mouvedia** [comment]
@ale5000-git simpler would be to just disable the button (and remove the action from the context menu) when such a process is selected.

**Comment by ale5000-git** [comment]
@Mouvedia: In your way you cannot see all critical system processes without mouse click.

**Comment by Mouvedia** [comment]
There's a column for that.

**Pull request closed without merging**
