### PR TITLE
[BOOTDATA] Comment out vgaoem.fon

### PR DESCRIPTION
**Pull request by archeYR**

### CODE REVIEW

**Review by katahiromz — APPROVED** [review]

**Comment by binarymaster** [comment]
If this doesn't introduce any problems with Vista+ x64 Winload described in https://github.com/reactos/reactos/pull/3272#issue-498532992 I'm ok with it.

**Comment by archeYR** [comment]
> 
> 
> If this doesn't introduce any problems with Vista+ x64 Winload described in [#3272 (comment)](https://github.com/reactos/reactos/pull/3272#issue-498532992) I'm ok with it.

Well, currently both Winload x64 and NTLDR are broken due to the missing vgaoem.fon file within the ISO. This change makes ROS again bootable with NTLDR out of the box (as in, no additional files/changes are needed), but makes booting with Winload x64 again a bit more complicated (you need both the file and a change in registry). So yeah, you can either have ROS again bootable with NTLDR (only) without any additional changes, or have ROS bootable with both Winload x64 and NTLDR but with need of manually copying the vgaoem.fon file from sources into the ROS install (which also could potentially cause regressions like [CORE-17327](https://jira.reactos.org/browse/CORE-17327) on your end).

**Comment by binarymaster** [comment]
> Well, currently both Winload x64 and NTLDR are broken due to the missing vgaoem.fon file within the ISO.

But you added this file in #3272 and Katayama didn't deleted it... :thinking:

**Comment by archeYR** [comment]
> 
> But you added this file in #3272 and Katayama didn't deleted it... thinking

Yes, it is in the sources, but it has been [excluded](https://github.com/reactos/reactos/blob/0089291751837d977431c85b6d8d6b1232fbb67b/media/fonts/CMakeLists.txt#L68) from builds and it doesn't exist in ISO images anymore.

**Comment by binarymaster** [comment]
Now I see it, thanks!

**Pull request merged**
