### PR TITLE
[WIN32SS] Fix DrawTextExWorker extent for Spotify

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

JIRA issue: [CORE-16747](https://jira.reactos.org/browse/CORE-16747)

BEFORE:
before
Spotify won't start up.

AFTER:
after
Spotify starts up.

Double checked.

### CODE REVIEW

**Comment by gonzoMD** [comment]
Cc @jimtabor

**Comment by HBelusca** [comment]
@katahiromz : can you check whether this also fixes some winetests?

**Comment by katahiromz** [comment]
BEFORE:
```txt
font: 27061 tests executed (0 marked as todo, 1186 failures), 60 skipped.
text: 885 tests executed (0 marked as todo, 35 failures), 0 skipped.
DrawText: 1081 tests executed (0 marked as todo, 2 failures), 0 skipped.
```
AFTER:
```txt
font: 27061 tests executed (0 marked as todo, 1187 failures), 60 skipped.
text: 885 tests executed (0 marked as todo, 35 failures), 0 skipped.
DrawText: 1081 tests executed (0 marked as todo, 2 failures), 0 skipped.
```
So, no go.

**Comment by JoachimHenze** [comment]
I doubt that this was a proper fix, make sure to read:
https://jira.reactos.org/browse/CORE-16747?focusedCommentId=123459&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-123459
and
https://jira.reactos.org/browse/CORE-16747?focusedCommentId=123464&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-123464

**Pull request merged**
