### PR TITLE
[SYSSETUP][MAIN] Fix Mouse Properties UI and improve French translation

### PR DESCRIPTION
**Pull request by KyleKatarn31**
## Purpose

- PS2 Mouse Advanced Properties : Missing Static control (frame)
- PS2 Mouse Advanced Properties : Not translated in French
- Mouse CPL > Wheel > Sroll line text box shall only allow numbers (missing ES_NUMBER style)
- ReactOs Setup  : Not translated in French

mousefix1
mousefix2

## Proposed changes

image
mousefix4
mousefix5

- PS2 Mouse Advanced Properties : Static control (frame) added
- PS2 Mouse Advanced Properties : French translation added and control layout adapted accordingly
- Mouse CPL > Wheel > Sroll line text box ES_NUMBER style added
- ReactOs Setup  : French translation added

### CODE REVIEW

**Comment by KyleKatarn31** [comment]
Update following merge of https://github.com/reactos/reactos/pull/2749 (conflict resolution on SYSSETUP FR-fr)

**Comment by katahiromz** [comment]
Update

**Comment by KyleKatarn31** [comment]
> 
> 
> Update screenshots

Done, in order to reflect #2749 conflict resolution.

**Comment by KyleKatarn31** [comment]
@HBelusca : Would you accept to be reviewer on this one ?

**Comment by KyleKatarn31** [comment]
Thank you @katahiromz.
Ready for merge ?

**Pull request merged**
