### PR TITLE
[SNDVOL32] Add missing graphic resources for Sound Mixer application

### PR DESCRIPTION
**Pull request by dsp2003**
## Purpose

Adds missing graphic resources for Sound Mixer application.

JIRA issue: none

## Proposed changes

This pull request:
- adds 16x16 4, 8 and 32-bit icon resources for balance sliders
- adds icon for muted state
- improves 4 and 8-bit icons within sndvol32.ico

All these icons are either edited from existent sndvol32.ico or redrawn from scratch by me, thus require no attribution.

### CODE REVIEW

**Comment by learn-more** [comment]
Hello,
Thanks for your interest in ReactOS!
We ask our contributors [to use their full name when committing](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations).
[Please amend your commit with your full name](https://stackoverflow.com/a/3042512), and update this PR.

Regards,

**Comment by dsp2003** [comment]
I refuse to reveal my full name. It's illegal to forcefully ask for your real name.

**Comment by HeisSpiter** [comment]
Thanks for your contribution, we've to refuse it then.

**Comment by dsp2003** [comment]
Well, fuck you too.

**Comment by binarymaster** [comment]
@dsp2003 you should read the rules first before contributing.

If you do not accept our rules, you should not open Pull Requests then.

**Pull request closed without merging**
