### PR TITLE
[SHELL32] Improve DragEnter of CFSDropTarget

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Reduce failures of `DragDrop` testcase.
JIRA issue: [CORE-11238](https://jira.reactos.org/browse/CORE-11238)

### CODE REVIEW

**Comment by katahiromz** [comment]
BEFORE:
```txt
DragDrop.cpp:298: Test failed: Line 61: dwEffects2 was 00000002
DragDrop.cpp:322: Test failed: Line 61: dwEffects3 was 00000002
DragDrop.cpp:336: Test failed: Line 61: src not exists
DragDrop.cpp:322: Test failed: Line 62: dwEffects3 was 00000002
DragDrop.cpp:322: Test failed: Line 63: dwEffects3 was 00000002
DragDrop.cpp:298: Test failed: Line 64: dwEffects2 was 00000002
DragDrop.cpp:322: Test failed: Line 64: dwEffects3 was 00000002
DragDrop.cpp:336: Test failed: Line 64: src not exists
DragDrop.cpp:322: Test failed: Line 65: dwEffects3 was 00000002
DragDrop.cpp:322: Test failed: Line 66: dwEffects3 was 00000002
DragDrop.cpp:298: Test failed: Line 67: dwEffects2 was 00000002
DragDrop.cpp:322: Test failed: Line 67: dwEffects3 was 00000002
DragDrop.cpp:346: Test failed: Line 67: src not exists
DragDrop.cpp:347: Test failed: Line 67: dest not exists
DragDrop.cpp:348: Test failed: Line 67: link not exists
DragDrop.cpp:286: Test failed: Line 71: dwEffects2 was 00000002
DragDrop.cpp:310: Test failed: Line 71: dwEffects3 was 00000002
DragDrop.cpp:351: Test failed: Line 71: src not exists
DragDrop.cpp:322: Test failed: Line 72: dwEffects3 was 00000002
DragDrop.cpp:322: Test failed: Line 73: dwEffects3 was 00000002
DragDrop.cpp:286: Test failed: Line 74: dwEffects2 was 00000002
DragDrop.cpp:310: Test failed: Line 74: dwEffects3 was 00000002
DragDrop.cpp:351: Test failed: Line 74: src not exists
DragDrop.cpp:322: Test failed: Line 75: dwEffects3 was 00000002
DragDrop.cpp:322: Test failed: Line 76: dwEffects3 was 00000002
DragDrop.cpp:294: Test failed: Line 77: dwEffects2 was 00000002
DragDrop.cpp:318: Test failed: Line 77: dwEffects3 was 00000002
DragDrop.cpp:359: Test failed: Line 77: src not exists
DragDrop.cpp:360: Test failed: Line 77: dest not exists
DragDrop.cpp:286: Test failed: Line 82: dwEffects2 was 00000004
DragDrop.cpp:310: Test failed: Line 82: dwEffects3 was 00000004
DragDrop.cpp:352: Test failed: Line 82: link exists
DragDrop.cpp:286: Test failed: Line 83: dwEffects2 was 00000004
DragDrop.cpp:310: Test failed: Line 83: dwEffects3 was 00000004
DragDrop.cpp:352: Test failed: Line 83: link exists
DragDrop.cpp:290: Test failed: Line 86: dwEffects2 was 00000004
DragDrop.cpp:322: Test failed: Line 86: dwEffects3 was 00000004
DragDrop.cpp:290: Test failed: Line 97: dwEffects2 was 00000001
DragDrop.cpp:322: Test failed: Line 97: dwEffects3 was 00000001
DragDrop.cpp:355: Test failed: Line 97: It must be either None or Move
DragDrop.cpp:290: Test failed: Line 98: dwEffects2 was 00000001
DragDrop.cpp:322: Test failed: Line 98: dwEffects3 was 00000001
DragDrop.cpp:355: Test failed: Line 98: It must be either None or Move
DragDrop.cpp:294: Test failed: Line 99: dwEffects2 was 00000001
DragDrop.cpp:318: Test failed: Line 99: dwEffects3 was 00000001
DragDrop.cpp:360: Test failed: Line 99: dest not exists

DragDrop: 535 tests executed (0 marked as todo, 46 failures), 0 skipped.
```

AFTER:
```txt
DragDrop.cpp:322: Test failed: Line 62: dwEffects3 was 00000002
DragDrop.cpp:322: Test failed: Line 63: dwEffects3 was 00000002
DragDrop.cpp:298: Test failed: Line 64: dwEffects2 was 00000000
DragDrop.cpp:322: Test failed: Line 64: dwEffects3 was 00000000
DragDrop.cpp:322: Test failed: Line 65: dwEffects3 was 00000002
DragDrop.cpp:322: Test failed: Line 66: dwEffects3 was 00000002
DragDrop.cpp:286: Test failed: Line 71: dwEffects2 was 00000002
DragDrop.cpp:310: Test failed: Line 71: dwEffects3 was 00000002
DragDrop.cpp:351: Test failed: Line 71: src not exists
DragDrop.cpp:322: Test failed: Line 72: dwEffects3 was 00000002
DragDrop.cpp:322: Test failed: Line 73: dwEffects3 was 00000002
DragDrop.cpp:286: Test failed: Line 74: dwEffects2 was 00000002
DragDrop.cpp:310: Test failed: Line 74: dwEffects3 was 00000002
DragDrop.cpp:351: Test failed: Line 74: src not exists
DragDrop.cpp:322: Test failed: Line 75: dwEffects3 was 00000002
DragDrop.cpp:322: Test failed: Line 76: dwEffects3 was 00000002
DragDrop.cpp:294: Test failed: Line 77: dwEffects2 was 00000002
DragDrop.cpp:318: Test failed: Line 77: dwEffects3 was 00000002
DragDrop.cpp:359: Test failed: Line 77: src not exists
DragDrop.cpp:360: Test failed: Line 77: dest not exists
DragDrop.cpp:286: Test failed: Line 82: dwEffects2 was 00000004
DragDrop.cpp:310: Test failed: Line 82: dwEffects3 was 00000004
DragDrop.cpp:352: Test failed: Line 82: link exists
DragDrop.cpp:286: Test failed: Line 83: dwEffects2 was 00000004
DragDrop.cpp:310: Test failed: Line 83: dwEffects3 was 00000004
DragDrop.cpp:352: Test failed: Line 83: link exists
DragDrop.cpp:290: Test failed: Line 86: dwEffects2 was 00000004
DragDrop.cpp:322: Test failed: Line 86: dwEffects3 was 00000004
DragDrop.cpp:290: Test failed: Line 97: dwEffects2 was 00000001
DragDrop.cpp:322: Test failed: Line 97: dwEffects3 was 00000001
DragDrop.cpp:355: Test failed: Line 97: It must be either None or Move
DragDrop.cpp:290: Test failed: Line 98: dwEffects2 was 00000001
DragDrop.cpp:322: Test failed: Line 98: dwEffects3 was 00000001
DragDrop.cpp:355: Test failed: Line 98: It must be either None or Move
DragDrop.cpp:294: Test failed: Line 99: dwEffects2 was 00000001
DragDrop.cpp:318: Test failed: Line 99: dwEffects3 was 00000001
DragDrop.cpp:360: Test failed: Line 99: dest not exists

DragDrop: 535 tests executed (0 marked as todo, 37 failures), 0 skipped.
```

**Comment by katahiromz** [comment]
NOTE: `DragDrop` testcase sometimes terminates abnormally.

**Comment by learn-more** [comment]
Does it terminal abnormally also without this PR?

**Comment by katahiromz** [comment]
Yes, it does.

**Comment by learn-more** [comment]
if `s_pDesktop->GetUIObjectOf` fails (line 270) you cannot use `pDropTarget` so you have to directly go to `clean up`

**Comment by katahiromz** [comment]
NULL check is added at https://github.com/reactos/reactos/commit/14478887df3ce4166bf0dd384071cb9ed9bb9d03.

**Pull request merged**
