### PR TITLE
[USETUP] Use "L" key instead of "D" for deleting partitions at 1st setup stage

### PR DESCRIPTION
**Pull request by oleg-dubinskiy**
## Purpose

Use "L" key instead of "D" for deleting partitions in 1st text mode setup stage in `DeletePartitionPage
` (after selecting partition and clicking "D" first on `SelectPartitionPage` and then passing `ConfirmDeleteSystemPartitionPage` when deleting the partition with ReactOS installed before that), same as it done in Win2k3.

JIRA issue: [CORE-16150](https://jira.reactos.org/browse/CORE-16150)

## Proposed changes

- Change key from "D" to "L" which user presses for confirmation of deleting the partition;
- Update all translations accordingly with reverting and then converting them again to 8-bit clean string literals via code7bit tool: https://github.com/katahiromz/code7bit.

Before:
ros_setup_before
After:
ros_setup_after
Win2k3:
win2k3_setup

### CODE REVIEW

**Comment by HBelusca** [comment]
I'm not convinced it makes much more sense than "D" that is most logical (in english, I mean).

**Comment by oleg-dubinskiy** [comment]
I chose the "L" key only because it is used in Win2k3. Isn't Windows functional repetition one of the main targets of the project?
> in english, I mean

So you suggest to revert only English translation?

**Comment by Extravert-ir** [comment]
> Isn't Windows functional repetition one of the main targets of the project?

Yes, but not the dumb repetition

**Comment by gigaherz** [comment]
Question here would be WHY they chose it that way: did they make it L to make 100% sure the user didn't delete by mistake? Or some other reason?
And, is it L in all languages? If so, what does D do?

**Comment by oleg-dubinskiy** [comment]
> is it L in all languages?

Hmm, at least in English language is "L" key, same as in Russian on the 3rd screenshot above.
win2k3_setup_english
I'm not sure about other languages, but I think if English is generic, all others are the same.
> If so, what does D do?

"D" is already used on `SelectPartitionPage` for selecting the partition for deletion, same as in ROS.
win2k3_setup_d

**Comment by binarymaster** [comment]
> Question here would be WHY they chose it that way: did they make it L to make 100% sure the user didn't delete by mistake? Or some other reason?

The screenshot above suggests `L` means the user is agree that all data on selected partition will be **L**ost.

**Comment by gigaherz** [comment]
Sound to me like it's specifically designed to ensure the user is aware of the action, and didn't just press D twice by mistake, so I'm ok with this change, if the others are.

**Comment by tkreuzer** [comment]
Please make sure, the checks succeed. I'm not sure, why it fails, looks unrelated. Maybe simply force-pushing helps (you can amend, change commit time and commit, that should allow to force push a new revision).

**Comment by oleg-dubinskiy** [comment]
@tkreuzer done. Looks like checks were failed due to @EricKohl's storport commit, which broke OS compilation for me and was the latest at that moment. I hope that now checks will be successful, since that failure was fixed.
I double rechecked: after my changes, compilation still succeeds.

**Comment by Mouvedia** [comment]
> All data on this partition will be _l_ost.

It probably stands for "lost" in the same way that D stands for "deleted".

**Pull request merged**
