### PR TITLE
[DRIVERS] Fix MSVC C4700 error of storahci

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
This PR will fix "uninitialized local variable" error (C4700) in driver storahci.

### CODE REVIEW

**Comment by katahiromz** [comment]
OK.

**Comment by SergeGautherie** [comment]
Would a `#pragma` work and be better?

**Comment by katahiromz** [comment]
@SergeGautherie How to do?

**Comment by katahiromz** [comment]
Sorry, branch is messed up. Closed.

**Comment by learn-more** [comment]
@katahiromz You can always force-push to 'fix' a branch

**Pull request closed without merging**
