### PR TITLE
[W32TIME] Add Spanish (es-ES) translation

### PR DESCRIPTION
**Pull request by elhoir**
Spanish translation of w32time service. Created es-ES.rc file.

### CODE REVIEW

**Review by learn-more — CHANGES_REQUESTED** [review]
It looks like you created this file, in that case it should also be included somewhere :)
In your case that would be:
https://github.com/reactos/reactos/blob/8dc8eef8cc304c86843112c11571a8a7ddc91fb6/base/services/w32time/w32time.rc

Should probably look like this:
```
#ifdef LANGUAGE_ES_ES
#include "lang/es-ES.rc"
#endif
```
(With the same indenting as the other languages)

**Comment by elhoir** [comment]
saw it! you´re right! thank you!

**Comment by learn-more** [comment]
Image from @elhoir in Mattermost:
image

**Comment by elhoir** [comment]
imagen

**Pull request merged**
