### PR TITLE
[SHELL32][USER32][USERENV] Improve Portuguese (pt-PT) translation

### PR DESCRIPTION
**Pull request by zecarlos1957**
[SHELL32][USER32] Improve pt-PT translation
[USERENV] Don't translate Documents and Settings folder

### CODE REVIEW

**Comment by KRosUser2** [comment]
[USERENV] Dont translate Documents and Settings folder => Shouldn't this be fixed for all language ? Looks like an error and should be "%SystemDrive%\\Documents and Settings" regardless of the langage isn't it ?

https://git.reactos.org/?p=reactos.git&a=search&st=grep&s=IDS_PROFILEPATH

**Comment by HBelusca** [comment]
I confirm that in both portuguese from Portugal and Brazil Windows XP and 2003 versions, the "Documents and Settings" is not translated:
winxp_pt_docs_settings
Maybe it was translated in Windows 2000 (this is what internet seems to suggest, see e.g. http://www.josevalter.com.br/dicas_windows_2000.htm )

**Comment by HBelusca** [comment]
Correction for commit log: "Dont translate" --> "Don't translate"

**Review by HBelusca — APPROVED** [review]

**Comment by JoachimHenze** [comment]
> [USERENV] Dont translate Documents and Settings folder => Shouldn't this be fixed for all language ? Looks like an error and should be "%SystemDrive%\Documents and Settings" regardless of the langage isn't it ?
> 
> https://git.reactos.org/?p=reactos.git&a=search&st=grep&s=IDS_PROFILEPATH
> 
> Or at least to be checked for other localization...

Done. There **are** other languages where **MS** does indeed translate that folders name, e.g. German where it is called "Dokumente und Einstellungen".

**Pull request merged**
