### PR TITLE
[USETUP][INFLIB] Don't use HEAP_ZERO_MEMORY for malloc

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

The `malloc` function doesn't need `HEAP_ZERO_MEMORY` flag.
JIRA issue: [CORE-18838](https://jira.reactos.org/browse/CORE-18838)

## TODO

- [x] Do tests.

### CODE REVIEW

**Comment by learn-more** [comment]
For this change you'd need to audit _all_ code in usetup, because there might be code that depends on the fact that data was zero'd.

**Comment by katahiromz** [comment]
I grep'ed `malloc` in `usetup`, then I found no `malloc` usage in the usetup module source code.

```txt
target_link_libraries(usetup inflib setuplib zlib_solo ext2lib vfatlib btrfslib chkstk)
```

`inflib`, `zlib_solo`, and `vfatlib` use `malloc`.
`setuplib`, `ext2lib`, and `chkstk` don't use `malloc`.

`zlib_solo` should be ok (this module was independent).
The problem might be in `inflib` and `vfatlib`.

**Comment by katahiromz** [comment]
I found some problems in `inflib`. Fixes are added.

**Comment by HBelusca** [comment]
"cabinet.c" mentions "Needed by zlib, but we don't want the dependency on the CRT", which is the malloc implementation that in principle would be only used by the linked zlib (since, inflib would here not use malloc but RtlAllocateHeap, via the macros it uses).
I suppose the zlib already correctly uses malloc and, if needed, manually zeroes the allocated buffer? (or directly uses calloc)

**Comment by katahiromz** [comment]
Time up. Closed.

**Pull request closed without merging**
