### PR TITLE
[NOTEPAD] Fix About dialog issue (via remove non-standard about dialog)

### PR DESCRIPTION
**Pull request by eersoy93**
## Purpose

Fix About dialog issue via remove non-standard about dialog

## Proposed changes

- Remove non-standard about dialog
- Add copyright (authors) information to Notepad's shell about dialog.

### CODE REVIEW

**Comment by Fraizeraust** [comment]
Removing the About dialog of Notepad is not an improvement, neither a fix. Care to explain what do you mean by "non-standard dialog"?

**Comment by eersoy93** [comment]
This non-standard dialog is IDD_ABOUTBOX in resource files and this can be reached via CMD_ABOUT menu command.

**Comment by sanchaez** [comment]
@eersoy93 
> This dialog is useless, these information in this dialog is in main.c header also.

When people are running the program, they don't see it's sources.

**Comment by eersoy93** [comment]
I think Notepad authors information in "non-standard dialog" can be placed in standard Notepad about dialog.

**Comment by eersoy93** [comment]
I transffered this information to Notepad's shell about dialog.

**Comment by eersoy93** [comment]
NOTE: Translators should check Help menu entries in Notepad.

**Comment by gonzoMD** [comment]
Author removes a dialog box from resources and generates one via API. If nothing gets broken, I am OK with the change.

**Comment by eersoy93** [comment]
virtualbox_windows_7_makinem_ 64-bit _13_06_2018_11_19_06

**Pull request merged**
