### PR TITLE
[VFATLIB] Fix the aligned read and write operations.

### PR DESCRIPTION
**Pull request by HBelusca**
Correctly read or write data on aligned boundaries, taking cross-sector
regions into account.
This fixes potential data corruptions.

NOTE: Code based on the VdReadDisk() and VdWriteDisk() functions of my VHD tester code at:
https://github.com/HBelusca/reactos/blob/VirtualHDSupport/modules/rosapps/applications/vhddump/virtdisk_driver.c

### CODE REVIEW

**Comment by HeisSpiter** [comment]
I'm a bit sceptical about the purpose of that pull request.
For now, that lib relies on cached reads (thing I plan to change!) so, it doesn't matter whether reads/writes are properly aligned (Cc will align).
Furthermore, during my tests with direct IO, I couldn't spot any alignment issue.
Would I have missed anything?

**Comment by HBelusca** [comment]
The fact is that the current code that is run in fs_read/write (ie. these #if 1... with aligned stuff) is currently run, whether or not it's actually needed (note that this has been introduced in [r16873](https://svn.reactos.org/svn/reactos?view=revision&revision=16873), [r16883](https://svn.reactos.org/svn/reactos?view=revision&revision=16883) and [r17049](https://svn.reactos.org/svn/reactos?view=revision&revision=17049).

Considering this, suppose that fs_read is called with pos = 500 and size = 14, in other words, an operation that starts inside the first sector (sector 0) and crosses to the second sector (due to the extra 2 bytes).
With the current code, we get that (due to the fact size % 512 == 14):
readsize_aligned = 512 (which will be also the size of the allocated temporary buffer!), seekpos_aligned = 0 (starts at the beginning of the first sector), and seek_delta = 500.
Now the read operation reads from seekpos_aligned == 0 a number of readsize_aligned = 512 bytes (one full sector only), and will then copy back into the user-mode buffer "data" a number of "size = 14" bytes from the buffer read at offset seek_delta = 500: i.e. it will overflow 2 bytes after the allocated temp buffer when copying the data back to the caller.
Instead the correct behaviour would have been to allocate a temporary buffer to hold two consecutive sectors (sectors 0 and 1), do the read operation, and then correctly copying the data back to the caller.

A same buggy observation can be done for fs_write, which is much more problematic because corrupted data can (and will) be copied back onto disk:
again suppose you want to write size = 14 bytes of data back to disk starting pos = 500.
Then we have: readsize_aligned = 512, seekpos_aligned = 0, seek_delta = 500 (and use_read == TRUE).
A temporary buffer of size readsize_aligned = 512 bytes (so one buffer only!) is allocated, then one full sector is read from disk starting position 0 and size = 512 to initialize the temp buffer, and then the temp buffer is "patched" with user data at its offset seek_delta = 500, for size = 14 bytes, thus overflowing by 2 bytes.
Finally this temporary buffer is written back to disk at position seekpos_aligned = 0 (I suppose), thus writing back the original data (up to position 500) and adding the user data on 12 bytes (until the end of this sector), but not writing the 2 extra bytes the original user data specified, thus *loosing data* !!

**Comment by HeisSpiter** [comment]
Once again, it would be more appropriate to drop all this once IopParseDevice hack is dropped.
FastFAT and Cc will do this more properly ;-).

And until it's dropped, well, the only case where chkdsk is called is pointless.

**Comment by ColinFinck** [comment]
Closing in consent with @HBelusca

**Pull request closed without merging**
