### PR TITLE
[SHELL32_APITEST] Add ShellHook testcase

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

Add a testcase named `ShellHook` for shell hook.

JIRA issue: [CORE-17330](https://jira.reactos.org/browse/CORE-17330)

This testcase will test `HSHELL_WINDOWCREATED` especially. `HSHELL_WINDOWCREATED` affects display of task bar panes.

WinXP:
WinXP
Successful.

Win2k3:
Win2k3
Successful.

Win10:
Win10
Successful.

### CODE REVIEW

**Comment by Doug-Lyons** [comment]
@katahiromz, This test does not find the regression introduced in CORE-17330. Can you add a test for this type of failure that would show a failure in what we have today and then not fail after the fix? Thanks.

**Comment by katahiromz** [comment]
BEFORE `double_taskbar_fix.patch`:
before
AFTER `double_taskbar_fix.patch`:
after

**Comment by Doug-Lyons** [comment]
@katahiromz, Hopefully this test would be able to identify between the two revisions listed below. I have tested reverting the changes made by the guilty revision and there are still 56 failures. Ideally there should be less before the guilty commit. Thanks.

reactos-bootcd-0.4.14-dev-368-gfa26425-x86-gcc-lin-dbg.iso ok
reactos-bootcd-0.4.14-dev-369-g141cf04-x86-gcc-lin-dbg.iso affected GUILTY

**Comment by Doug-Lyons** [comment]
@katahiromz, My testing on W2K3SP2 shows 27 failures now. Can this be fixed? Thanks.

Shell32_apitest_ShellHook_Failures1

**Comment by katahiromz** [comment]
BEFORE `double_taskbar_fix.patch`:
before

AFTER `double_taskbar_fix.patch`:
after

**Comment by katahiromz** [comment]
Ready to go.

**Comment by katahiromz** [comment]
@Doug-Lyons How about W2K3SP2 now?

**Comment by Doug-Lyons** [comment]
@katahiromz, It's perfect. Thanks.
Shell32_apitest_ShellHook_W2K3SP2

**Pull request merged**
