### PR TITLE
[ZIPFLDR][ZIPFLDR_APITEST] Fix date on extraction, add tests for new features

### PR DESCRIPTION
**Pull request by learn-more**
Needed to test the 'EnumParentDir' stuff,
Had the rest already laying around.

[CORE-16908](https://jira.reactos.org/browse/CORE-16908)

### CODE REVIEW

**Comment by learn-more** [comment]
@yagoulas main focus point is the `EnumParentDir` test.
The rest is for later

**Comment by yagoulas** [comment]
So if I understand it right we return the correct attributes for the zip file, right?

**Comment by learn-more** [comment]
> So if I understand it right we return the correct attributes for the zip file, right?

As discussed earlier today:
We are very far from returning the correct attributes,
it is even returned as file instead of as folder atm.

**Comment by learn-more** [comment]
This test needs to be updated slightly:
Instead of hardcoding the order of files, it needs to take into account that filesystem can return out of order.

**Pull request merged**
