### PR TITLE
[TCPIP] Fixes crash when opening multiple tabs in Firefox, etc.

### PR DESCRIPTION
**Pull request by Zero3K**
This is a PR of a patch made by hater (on JIRA) that fixes a crash that occurs when opening multiple tabs in Firefox, etc.

JIRA issues: [CORE-11753](https://jira.reactos.org/browse/CORE-11753) and [CORE-12274](https://jira.reactos.org/browse/CORE-12274)

### CODE REVIEW

**Comment by Zero3K** [comment]
How do I do that?

**Comment by SergeGautherie** [comment]
See https://www.reactos.org/wiki/ReactOS_Git_For_Dummies

**Comment by Zero3K** [comment]
I think I did it properly.

**Comment by SergeGautherie** [comment]
> I think I did it properly.

Quite the opposite: now 2->4 commits, instead of 1 expected.
Ask for help on chat/forum if need be, not on GitHub.

**Pull request closed without merging**
