### PR TITLE
[SHELL32] No new menu and working properties in Drives and NetHood background menu

### PR DESCRIPTION
**Pull request by whindsaks**
- Don't add a class to the My Computer context menu so the "New" item is not added (not a filesystem folder, cannot create new items here).
- Add Properties item to My Network Places context menu.

### CODE REVIEW

**Review by JoachimHenze — APPROVED** [review]
Approved, but I would highly recommend to append a testbot-comparison before doing the merge.

**Review by learn-more — APPROVED** [review]

**Comment by binarymaster** [comment]
iirc there was some ticket about it.

**Comment by JoachimHenze** [comment]
KVM https://reactos.org/testman/compare.php?ids=98384,98386 +1 failure in com:shell32
VBox: not finished yet

The +1 failure in com_shell32 might be interesting to investigate, it might be related to the PR:
image

**Review by yagoulas — APPROVED** [review]

**Comment by whindsaks** [comment]
> iirc there was some ticket about it.

There is CORE-9458 but that is in the context menu of a drive? Not the background menu this PR is about.

**Pull request merged**
