### PR TITLE
[MODULES][WALLPAPERS] Fix build

### PR DESCRIPTION
**Pull request by binarymaster**
Some file names still contained space instead of underline. Addendum to 0760802 (#1294).

### CODE REVIEW

**Comment by ThFabba** [comment]
Why are we renaming the files instead of fixing the CMake?
(I'm not clear on that with the original PR either)

**Comment by binarymaster** [comment]
```cmake
add_cd_file(FILE "${CMAKE_CURRENT_SOURCE_DIR}/Angelus.ROS A_New_Hope_16x9.jpg" DESTINATION reactos/Web/Wallpaper FOR all)
add_cd_file(FILE "${CMAKE_CURRENT_SOURCE_DIR}/Angelus.ROS A_New_Hope_4x3.jpg" DESTINATION reactos/Web/Wallpaper FOR all)
```

Also this worked for me. Any suggestions what to do? :sweat_smile: 
- Leave PR as is
- Fix CMake file for this wallpaper
- Rename all wallpapers back and fix all CMake files

**Comment by HBelusca** [comment]
Are the wallpaper files *correctly installed* when you install ROS from bootcd?

**Comment by HBelusca** [comment]
Ah, I remember now why we used to place underscores in the filenames: it was to have ISO 9660:1988 conformant ISOs.

**Pull request merged**
