### PR TITLE
[USBXHCI] Import and fix compiling the 2017 XHCI Driver

### PR DESCRIPTION
**Pull request by BelleNottelling**
## Purpose

The easy stuff from what Thomas had said here: https://github.com/reactos/reactos/pull/1694#issuecomment-506628455

This driver doesn't truly work, but is at a state where if actually compiled and enabled, the virtualbox USB 3.0 controller is recognized and it doesn't crash or anything, however having a USB plugged in / enabled results in some asserts, so until more work is done it should be enabled

Ideally, this will make it easy for someone to continue developing the driver. 

JIRA issue: [CORE-13344](https://jira.reactos.org/browse/CORE-13344)

## Proposed changes

- Merged master onto the XHCI branch so it's up to date 
- Fixed errors related to our current headers so the driver compiles. 
- Disable the driver as it's still not functional

### CODE REVIEW

**Comment by BenNottelling** [comment]
image
I was a little of on my initial description.
To get this far on with the driver not only does it have to be added to  txtsetup.sif, but so does usbport.sys as it's actually a dependency to it. 
However, we hit two asserts in `../drivers/usb/usbhub/fdo.c`
Line 1830: 
`HubDeviceExtension->HubDescriptor.bDescriptorLength == sizeof(USB_HUB_DESCRIPTOR)`
and line 1832
`ASSERT(HubDeviceExtension->HubDescriptor.bDescriptorType == 0x29);`

Either way this isn't supposed to work yet :P

**Comment by BenNottelling** [comment]
I'm feeling like this driver is so far from our current drivers in terms of design and how they function that it should be closed and rewritten based off of the current drivers
Not to mention that it's kinda a mess with horrid commit history and initialized variables being used
I'll leave it up to someone more experienced than me to decide which is better though, if you guys agree with me just close it :)

**Comment by tkreuzer** [comment]
It doesn't look that bad to me. I would prefer though, if we merged the additional fixes to the original branch. We might also consider fixing the commit messages, so that the first like actually contains a summery. Then we can merge (and I would prefer a merge, not a rebase) to master.

**Comment by BenNottelling** [comment]
> Out of curiosity: has anyone tested the driver from Lesan's fork?

I did open a PR for it
https://github.com/reactos/reactos/pull/1694
But never really did testing, and I think virtualbox was set to use PS/2

**Comment by Extravert-ir** [comment]
The new storage stack has landed so
- all commits where *_new drivers are moved around should be removed.
- commit [`eabe6e5` (#1823)](https://github.com/reactos/reactos/pull/1823/commits/eabe6e580810edffa8fffea6052eba7a4a1c9a30) needs to copy the driver from `usbehci`

Besides that it should be fine to merge, but I'd ask to format file headers according to our current style as well

**Comment by BenNottelling** [comment]
Rebased!
Well kinda. I did cherry picks and manually fixed issues that arrived. 
Test in GCC. It will compile and load in virtualbox without issue, connecting anything USB causes an infinite interrupt loop.
Also modified commit messages so there display some kind of summary

**Pull request closed without merging**
