### PR TITLE
[WINVER] Add an icon for winver.exe

### PR DESCRIPTION
**Pull request by user0-tb**
## Purpose

Almost all system components have icons, I've added an icon for winver.exe. If you don't like it, I can create another icon.

Preview: 
winver

### CODE REVIEW

**Comment by HBelusca** [comment]
> If you don't like it, I can create another icon.

Well there is already at least one "reactos.ico" existing in our repo, so just use that one instead of "recreating" a new one.

**Review by binarymaster — CHANGES_REQUESTED** [review]
winver.exe is not supposed to have an icon - confirmed missing icon on Windows XP and Windows 10.

image | image |
|----|----|

**Comment by TAN-Gaming** [comment]
Suggested icon:
[https://github.com/reactos/reactos/blob/master/base/setup/reactos/res/roslogo.ico](https://github.com/reactos/reactos/blob/master/base/setup/reactos/res/roslogo.ico)

**Comment by user0-tb** [comment]
Now based on suggestion from @TAN-Gaming.

**Comment by user0-tb** [comment]
@binarymaster Work is in progress.

**Comment by TAN-Gaming** [comment]
> winver.exe is not supposed to have an icon - confirmed missing icon on Windows XP and Windows 10.

I wonder if we can make the app looks better than Windows. I don't think doing this will break compatibility in any way.

**Review by JoachimHenze — CHANGES_REQUESTED** [review]
winver.exe is not supposed to have an icon. No need to discuss which one would look best. No approval from my side neither.

**Comment by user0-tb** [comment]
@JoachimHenze Why it's not supposed to have? It don't break any compatibility.

**Comment by user0-tb** [comment]
For example ntvdm.exe also hasn't an icon in windows. @binarymaster @JoachimHenze

**Comment by binarymaster** [comment]
Adding an icon to this application doesn't solve any practical problems, because it's a technical utility and it's not commonly used, so no UI/UX problem here.

Let me quote Thomas:

> Can you please focus on actual problems? Our time is valuable.

**Comment by user0-tb** [comment]
Ok. I understand.

**Pull request closed without merging**
