### PR TITLE
[TASKMGR] *.rc: Fix accelerator collisions &Priority <-> &Properties

### PR DESCRIPTION
**Pull request by JoachimHenze**
We had them in almost all languages.
Try to fix them in a uniform way:
&Priority
P&roperties

We introduced them during 0.4.15-dev'ing when
MENUITEM ID_PROCESS_PAGE_PROPERTIES
and
MENUITEM ID_PROCESS_PAGE_OPENFILELOCATION
were added.

Yes, I know that kind of stuff is hard to review. Not my fault. I will PR anyway.

nl-NL.rc had another collision.

### CODE REVIEW

**Review by HBelusca — CHANGES_REQUESTED** [review]
Please change. Keep Properties with & on 'P': "&Properties", but change the priority accelerator to another letter (not P).
Otherwise you break usage compatibility with Windows' taskmgr.

**Comment by JoachimHenze** [comment]
> Please change. Keep Properties with & on 'P': "&Properties", but change the priority accelerator to another letter (not P). Otherwise you break usage compatibility with Windows' taskmgr.

Oof. Which letter does Priority have in english then? In my german XPSP3 it is **R**.
Please tell me what the english letter it is at least, if you want me to change that @hbelusca .

**Comment by JoachimHenze** [comment]
Btw I am not breaking anything. Currently **both accelerators** do not work. Even if they may be like more recent Windows in your eyes. :D
Because on older Windows the new options are not even available. And therefore the accelerators (may) be used differently.

**Comment by JoachimHenze** [comment]
Found it: here is the english 2k3sp2 taskmgr:
image
I will change accordingly.

**Comment by JoachimHenze** [comment]
@hbelusca my picture of 2k3sp2 clearly proves you to be wrong:
Priority must be P, that is exactly what I did here,
And Properties (which does not exist on 2k3sp2) I tried to assign to R.
Yy PR is good in this regard. **Your expectation is what is wrong**

**Comment by HBelusca** [comment]
But Properties exist in WinVista+ taskmgr. I don't currently have an english version of Vista+ (or 7) taskmgr to test. You would have to ask e.g. @DarkFire01. Instead here's the french version:
image

(Also, one needs to use e.g. OSK.EXE and press on the "Menu" key in order to get the accelerators to show up, because they are off by default.)

**Comment by JoachimHenze** [comment]
I did attach an **english 2k3sp2** screenshot, which proves that I did that correctly. Everything else (especially that review comment of yous) is just your personal taste.

**Comment by HBelusca** [comment]
OK then what you can do is this: change Properties/Priority in english language, and in other languages where such changes are obvious; in french, keep &Properties and change P&riority. :thinking:

**Comment by JoachimHenze** [comment]
> OK then what you can do is this...

Ofc I will respect the french speciality. There is 0% dispute in that. All I want is to act like Windows and to not have collisions. So that the accelerators do actually work.

**Review by HBelusca — APPROVED** [review]

**Pull request merged**
