### PR TITLE
[RASAPI32] Add stub for RasGetConnectionStatistics

### PR DESCRIPTION
**Pull request by binarymaster**
That's my patch from [CORE-10426](https://jira.reactos.org/browse/CORE-10426).

### CODE REVIEW

**Comment by binarymaster** [comment]
@learn-more that's my real name, I already commited (sent patches) with it.

See: https://github.com/reactos/reactos/search?utf8=%E2%9C%93&q=Stas%27M&type=Commits

**Comment by learn-more** [comment]
@binarymaster : the commit lists as author: 'From: binarymaster <redacted@gmail.com>'

**Comment by binarymaster** [comment]
UPD: just noticed, there was nickname instead of name in commit author field, thanks!

**Comment by binarymaster** [comment]
Fixed author field, and rebased with latest changes.

**Comment by HeisSpiter** [comment]
This shouldn't be merged here. This is a Winesynced DLL. You should propose upstream (either Wine or Wine-Staging).

**Comment by binarymaster** [comment]
> You should propose upstream (either Wine or Wine-Staging).

Could you do this? The patch is pretty simple.

I found it a bit complicated (still cloning wine repo, about a hour).

**Comment by binarymaster** [comment]
UPD: filed a patch to Wine-Staging: https://dev.wine-staging.com/patches/203/

**Comment by gonzoMD** [comment]
Got accepted \o/

**Comment by feikname** [comment]
> I found it a bit complicated (still cloning wine repo, about a hour).

@binarymaster you can clone big repos with the `--depth` and `--single-branch` options to decrease download size by limiting the amount of history that will be downloaded and which branch you want downloaded. Like this:
```text
git clone protocol://URL.git --branch master --single-branch --depth 1
```

It's very useful for quick patches in big repositories.

Diff history will be ommited in your local clone, so you won't be able to view the changes a file has gotten beyond the depth you specify. In case you ever need/want to finish downloading the remaining history, you can use `git fetch --unshallow`.

**Comment by tkreuzer** [comment]
@AmineKhaldi: Shall we still apply the patch, or import the related wine-staging instead?

**Comment by AmineKhaldi** [comment]
@tkreuzer I'd prefer picking this up from the Wine Staging side if that's okay, otherwise we would for example need to go over the sync commits (that list of changes you see in the commit log of each module sync) with a fine tooth comb to eliminate all the commits that we already merged outside the syncs.

**Comment by binarymaster** [comment]
Along with this commit https://github.com/reactos/reactos/commit/5048dc8930fb01e6c3c6fd69263d39f90667a611 the patch resolves the issue!

image

**Comment by learn-more** [comment]
In that case we can close this PR?

**Comment by binarymaster** [comment]
@learn-more see my last comment in [CORE-10426](https://jira.reactos.org/browse/CORE-10426), without this patch service fails to start.

**Comment by binarymaster** [comment]
Commit https://github.com/reactos/reactos/commit/5048dc8930fb01e6c3c6fd69263d39f90667a611 only allows to pass the install without errors.

**Comment by learn-more** [comment]
Yes but this exact commit comes from the staging side, so we do not need this PR anymore.

**Comment by binarymaster** [comment]
Well, it would be better to sync this first, then close the PR. :roll_eyes:

**Comment by sanchaez** [comment]
Is this done?

**Comment by binarymaster** [comment]
Awaits to be synced.

**Comment by binarymaster** [comment]
https://source.winehq.org/git/wine.git/commit/290aec59aa18e0bdd481c9ae36e24a75e1254bc8

My patch just got into Wine!

**Comment by jeditobe** [comment]
https://www.winehq.org/announce/2.22

Stanislav Motylkov (1):
      rasapi32: Add stub for RasGetConnectionStatistics.

Congratz!

**Pull request merged**
