### PR TITLE
[WALLPAPERS] Optimize PNG images

### PR DESCRIPTION
**Pull request by ace-dent**
## Purpose

- Lossless optimization with `pngslim` saving ~1-9%.
- Restricted to RGB color mode (‘c2’), for maximum compatibility.

## Proposed changes
- Optimize images.

### CODE REVIEW

**Comment by ace-dent** [comment]
Ooppss. May have deleted the wrong branch?...

**Comment by ace-dent** [comment]
Closed in error.

**Review by JoachimHenze — APPROVED** [review]
Approved.

**Review by katahiromz — APPROVED** [review]

**Review by HBelusca — APPROVED** [review]
@jeffbox12 @Splitwirez @foxlet Could you quickly check whether Mizu wallpapers are still fine and give approval if so?

**Pull request merged**
