### PR TITLE
[USETUP] Fix typo in Japanese (ja-JP)

### PR DESCRIPTION
**Pull request by kkebo**
## Purpose

`\274\336\304\336\263\303\306` (ジドウテニ) is a typo of `\274\336\304\336\263\303\267\306` (ジドウテキニ). The word "ジドウテキニ", "自動的に" in Kanji, means "automatically".

I've fixed this typo.

### CODE REVIEW

**Comment by katahiromz** [comment]
Welcome, Mr. Kubo, from a far, far away foreign land in the East that Mr. Bean doesn't know about. The brain data of the person in charge is currently sleeping, so please wait a moment. I wonder who made the typo, really.

**Comment by binarymaster** [comment]
> I wonder who made the typo, really.

This commit: https://github.com/reactos/reactos/commit/379ce6f163acf7f2c3cc90f6e0c7ba0c63b488b9#diff-e7b9f912f9624f4de4935067059c37e035dc3be09576293588ef5a8bea6d9161R582

**Review by katahiromz — APPROVED** [review]
image
OK, your fix is valid. The encoding is `Shift_JIS`.

**Comment by katahiromz** [comment]
@binarymaster Ready?

**Comment by kkebo** [comment]
@katahiromz Thank your for testing.

**Comment by kaushikp020603** [comment]
looks good , keep it up

**Comment by binarymaster** [comment]
@kkebo before I merge your PR, please uncheck `Keep my email addresses private` in [GitHub email settings](https://github.com/settings/emails).

This is needed per our contributing rules.

**Comment by katahiromz** [comment]
I can help you in Japanese.
お困りですか？

**Comment by kkebo** [comment]
Thank you for pointing that out. I've read [CONTRIBUTING.md](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md) again and force-pushed the commit created with my real email address.

**Comment by katahiromz** [comment]
`Keep my email addresses private`のチェックを外してくれませんか？

**Comment by binarymaster** [comment]
Squash button still reports noreply email:

image

**Comment by kkebo** [comment]
@katahiromz 

I would follow your procedure if that was the only way, but as you can see, the commit I pushed has my real email address. Is this insufficient?

```console
$ git clone -b fix-typo-ja-jp-usetup https://github.com/kkebo/reactos.git
Cloning into 'reactos'...
remote: Enumerating objects: 1043472, done.
remote: Counting objects: 100% (17792/17792), done.
remote: Compressing objects: 100% (1279/1279), done.
remote: Total 1043472 (delta 17086), reused 16574 (delta 16512), pack-reused 1025680
Receiving objects: 100% (1043472/1043472), 457.99 MiB | 11.02 MiB/s, done.
Resolving deltas: 100% (807086/807086), done.
Updating files: 100% (27001/27001), done.
$ cd reactos
$ git log | head
commit b54613d02c701bd4b2bf30e949310081161d9c2b
Author: Kenta Kubo <kabuto669@icloud.com>
Date:   Wed Aug 7 22:12:56 2024 +0900

    [USETUP] Fix typo in Japanese (ja-JP)
    
    \274\336\304\336\263\303\306 (ジドウテニ) is a typo of \274\336\304\336\263\303\267\306 (ジドウテキニ). The word "ジドウテキニ", "自動的に" in Kanji, means "automatically".

commit 90de2b660b12919c2f60f2f31ad41e37c123d662
Author: Doug Lyons <douglyons@douglyons.com>
```

```
Author: Kenta Kubo <kabuto669@icloud.com>
```

**Comment by kkebo** [comment]
I just made my email public. Sorry for the inconvenience.

**Comment by binarymaster** [comment]
Thanks!

**Pull request merged**
