### PR TITLE
CORE-15930. [UNIATA] Upgrade UniATA to 0.47a from 0.47

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

JIRA issue: [CORE-15930](https://jira.reactos.org/browse/CORE-15930)

### CODE REVIEW

**Comment by gigaherz** [comment]
Maybe just me, but I'd love to see this kind of commit include a summary of the changes included. What does the update to 0.47a bring? What's fixed? What do we gain from it? Maybe it's available somewhere, but that means I have to sort through the info (jira ticket, or the uniata website, or wherever it comes from), and it would be a LOT more convenient if that info was included in the commit message.

**Comment by ThFabba** [comment]
Some devs find this sort of patch useful, but I generally don't -- because my way of reviewing it would be to do the sync myself and compare the diff, which is both more time-consuming and less reliable than doing it myself.

**Comment by SergeGautherie** [comment]
The main goal is to try to fix/sort-out filed 0.47 regressions.

@gigaherz: on one hand, I would partly wish the same as you, on the other hand, that doesn't seem to be current policy. Not for UniATA, mbedTLS, global "WineSyncs", ...
Then, yes, PR to Jira to WebSite to sources...

@ThFabba: I understand, though I am not sure what your point is.
Jira issue is still assigned to "Bug Zilla". 'UniATA' is not listed in 'MAINTAINERS'.
What is the upgrade process then, if not a PR?

**Comment by gigaherz** [comment]
@SergeGautherie The winesync Amine did back in October last year, did have changelogs, the last one back in January didn't, probably because Amine was too busy to include them. "Other people didn't do it so I won't do it either" is no excuse, if you have the chance to do better, it just sounds lazy. In any case, I was just stating my opinion that this is something I'd like to see improved, if I thought it was an issue that prevents the PR from being merged, I'd have used the review feature and set it to "changes requested", which I didn't do, so no need to act defensively. If you agree with me that including changelogs on the 3rdparty syncs is good, then do it, and your PRs will be all the better thanks to it.

**Comment by ThFabba** [comment]
The update process is: a dev does the sync.
To verify that you (or anyone else) did the sync correctly and did not add or omit code (in larger syncs, even added a backdoor), I have to do the sync myself and then compare. That is more work than just doing it myself, so a PR of this type is not useful to the project. Sorry.

**Comment by SergeGautherie** [comment]
@gigaherz, why would I "have no excuse" and "be lazy", but other people simply "be too busy"?
Note especially that "this PR" was eventually committed as 3fb5ca3beee8a0310c4cc70fb9448206de29fe9c, though Thomas did not include details either, even after your comments.
My suggestion stands: discuss commit descriptions on the forum and set "rules"...

**Pull request closed without merging**
