### PR TITLE
Resources

### PR DESCRIPTION
**Pull request by jsoref**
These match my expectations as a long time Windows user (checked against Windows 10).

this supersedes #18

### CODE REVIEW

**Comment by AmineKhaldi** [comment]
Hi Josh, thank you for contributing to ReactOS!
Please note that the current iteration creates an inconsistency between the English version and the other translations. Could you please apply your work into the other language files too?

**Comment by jsoref** [comment]
@AmineKhaldi: is there a tool to help me do that, or do I get to do it by hand?

**Comment by jsoref** [comment]
Updating localizations is a bit of a disaster. It's generally better to rely on localizers to recognize that their versions are stale and decide how to update files themselves.

There are a couple of things here:
1. The strings already aren't well synced (e.g. for Notepad, some Print menuitem translations already had `...`, some didn't, and some were missing the Ctrl+P marker). -- I can fix these
2. Some changes require understanding languages. Changing `About` to `About Notepad` is something I can't do for localizations. -- I'd rather not be forced to make that change
3. Accesskeys are their own adventure in hell. A language might use the English flavor (esp if it doesn't use latin characters), but it could also have its own character, so I can't really fix these.

**Comment by AmineKhaldi** [comment]
That's what I meant, I especially looked at the ... situation, so the general changes like point 1 are what makes sense (not points 2 and 3).

**Comment by gigaherz** [comment]
@jsoref The idea is that it's really good to make sure that all the languages contain the controls/stringtable entries/menuitems (and details like markers and "..." I guess, although some languages may not use "..."), so that the translators going through the resource files don't have to do side-by-side comparisons to find missing strings/ui changes. You don't have to translate them yourself, that IS the translator's jobs.

**Comment by jsoref** [comment]
In principle, all languages should be using `...` although they could use `…` and at least one did occasionally.

The bigger issues are access keys (which are technically optional) and accelerators.
Past that are the cases where they need a new translation (or where they should go get the standard one)...

**Comment by AmineKhaldi** [comment]
Committed in r72677. Thanks!

**Pull request closed without merging**
