### PR TITLE
[REGEDIT] Improve arrow button visual

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

JIRA issue: N/A

BEFORE (Japanese):
japanese-before
AFTER (Japanese):
japanese-after

### CODE REVIEW

**Comment by katahiromz** [comment]
BEFORE (English):
english-before
AFTER (English):
english-after

**Comment by katahiromz** [comment]
Arrow icon:
icon

**Comment by HBelusca** [comment]
The symbol looks too large (at least as it shows in your previews), is it possible to reduce it a bit like this?
image
(I'm also surprised that we could not use a Marlett symbol with enlarged font size there... ?)

**Comment by binarymaster** [comment]
> I'm also surprised that we could not use a Marlett symbol with enlarged font size there... ?

In Marlett there is no such character. The most close are these:

image

How about making it with actual text like "Go"?

**Comment by HBelusca** [comment]
> > I'm also surprised that we could not use a Marlett symbol with enlarged font size there... ?
> 
> In Marlett there is no such character. [...]

Oh yes, indeed!

> How about making it with actual text like "Go"?

That would the require extra translations. With the image you just introduce 1 resource and that's it.

**Comment by ThFabba** [comment]
Your screenshots are from ROS -- when editing apps please always make sure you're also testing that there's an improvement in Windows (because if that's not the case, the fix belongs elsewhere). Thanks!

**Comment by katahiromz** [comment]
Arrow icon (12 x 12px):
noname
Regedit in Windows 10:
regedit

**Pull request merged**
