### PR TITLE
[OSK] Implement the maximize and minimize buttons

### PR DESCRIPTION
**Pull request by Fraizeraust**
## Purpose
Currently only the Close button is shown in the window dialog. With this patch the maximize and minimize buttons are now shown.
## Presentation
AFTER
 <a href="http://it.tinypic.com?ref=eefk7" target="_blank">Image and video hosting by TinyPic</a>

### CODE REVIEW

**Comment by gonzoMD** [comment]
Wasn't it intended that the osk only has a close button?

**Comment by Fraizeraust** [comment]
@gonzoMD At contrary, the On-Screen Keyboard has the three buttons. If you're unsure, just look for some images of Windows XP's OSK on Google.

**Comment by HBelusca** [comment]
Now the window icon needs to be fixed :stuck_out_tongue:

**Comment by learn-more** [comment]
Not in this PR it don't.

**Pull request merged**
