### PR TITLE
[FONTS] Tahoma: Remove bitmap glyph workaround

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

Our Tahoma font file had a workaround to make bitmap glyphs working.
This workaround is no more necessary because new FontForge doesn't have this bug.
https://github.com/reactos/reactos/pull/7009#issuecomment-2159652855
JIRA issue: [CORE-9616](https://jira.reactos.org/browse/CORE-9616)

## Proposed changes

- Remove 「いうかひのん」 workaround (See http://www.electronicdissonance.com/2010/01/raster-fonts-in-visual-studio-2010.html ).
- Remove Traditional Chinese codepage.

## TODO

- [x] Do tests.

## Screenshots

ReactOS (AFTER):
after
Bitmap glyphs are still working.

## Version

Tahoma: 0.020 khmz.

### CODE REVIEW

**Comment by HBelusca** [comment]
Dunno but this doesn't look like "remove" stuff to me :joy:
image

**Comment by HBelusca** [comment]
> Our Tahoma font file had a workaround to make bitmap glyphs working.

Do you know which past ReactOS commit(s) introduced the workaround?

**Comment by katahiromz** [comment]
> > Our Tahoma font file had a workaround to make bitmap glyphs working.
> 
> Do you know which past ReactOS commit(s) introduced the workaround?

I think it's #789 or earlier.

**Comment by HBelusca** [comment]
> I had modified the generation options.

It may be of interest to have somewhere (reactos wiki page? ....) a place that explains the best generation options to choose in fontforge when (re)generating our fonts.

**Review by HBelusca — APPROVED** [review]

**Review by JoachimHenze — APPROVED** [review]

**Pull request merged**
