### PR TITLE
[NOTEPAD] Localize default font name

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
JIRA issue: [CORE-16468](https://jira.reactos.org/browse/CORE-16468)

## Proposed changes
- Add `STRING_DEFAULTFONT` resource string to localize the font name.
- Use `DEFAULT_CHARSET`.

### CODE REVIEW

**Comment by HBelusca** [comment]
It seems to be always the same, so why "localizing" it? (Also, shouldn't it be the purpose of win32k to use a default fallback font in that case?)

**Comment by katahiromz** [comment]
Japanese people wants to display `FIXED_PITCH` Japanese font (especially MS Gothic) in Japanese Notepad. However "Lucida Console" was already specified. "Lucida Console" can't show Japanese or Asian text (in current system without font linking).

**Comment by katahiromz** [comment]
We might be able to use the empty `lfFaceName`...

**Comment by katahiromz** [comment]
no-good
No good. Specified font is not selected. ???

**Comment by katahiromz** [comment]
Ah huh, there is no `FIXED_PITCH` Japanese font...

**Comment by katahiromz** [comment]
I can't fix. Closed.

**Pull request closed without merging**
