### PR TITLE
Add theme "Watercolor Emico: Olive"

### PR DESCRIPTION
**Pull request by A-Rafael**
The author of a theme "Watercolor Emico: Olive" allowed to add it to ReactOS. The theme is drawn from scratch. I will ask him to wrote here and confirm.
Theme on deviantart.com - https://www.deviantart.com/jamush/art/Watercolor-Emico-Olive-91448120

### CODE REVIEW

**Comment by marminino** [comment]
Good theme

**Comment by HBelusca** [comment]
Hi, does the author also have other colors in stock (Blue and/or grey-silver)?

**Comment by A-Rafael** [comment]
@HBelusca Hi, yes, can also add them

**Comment by feel-the-dz3n** [comment]
It's nice but as for me it looks old. Perhaps another color will be better? Windows XP had 3 colors, but I liked only blue)

**Comment by feel-the-dz3n** [comment]
Also, how about to set this flat ReactOS icon (on start menu button) in all themes? I think it will look nice.

**Comment by doho2** [comment]
Watercolor Blue was my favorite XP theme, please add blue.

**Comment by gigaherz** [comment]
Hello, since the original theme says

>Modification:
>For personal use only.

I think this wouldn't be compatible with our general license choices, if not by law, at least in spirit. If we add a license, and we don't have a license that is compatible with sharing and modifying, it means we can't easily fix issues in the theme and distribute those changes.

I believe we would need to ask the author if they are OK with providing it with a license like [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/), or GPL3.

**Comment by blackcrack** [comment]
Hi @gigaherz ,
there be many peoples and many Themes, so, why not a Theme-DB like Rapps-DB or in Rapps-DB
then is a fair distribution given if there a possibility for upload from theme-makers and take from users what they want and then it is give a good place for share the whole themes.
I have many themes uploaded :
http://www.blackysgate.de/files/folder-root/ros/WinXP-Themes/
this themes can use for fill up the Themes-DB and there are a lot of them.

best regards
Blacky

**Comment by gigaherz** [comment]
I don't see why we couldn't link it in Rapps? If we don't have a themes category yet, one could easily be created. The only question would be how to host them. 

But that is a discussion for IRC, not this PR, let's not litter the comments any further.

**Comment by Jamushroom** [comment]
Hello everyone. I am the original designer of the Watercolor Emico for XP theme. At the time of creating the theme I only gave permission to modify the theme for personal use only. Since XP is ages ago, I'm giving you guys the go-ahead to add this theme to ReactOS. 

However, there's also a newer version of the theme called Novus. This only has a blue color theme because that's the color I liked the best. I'm giving you guys the go-ahead to add that to ReactOS as well if you like.

Do credit me for the work on the original theme though.

**Comment by jeditobe** [comment]
@Jamushroom hello!

Could you please also mention this information in the original theme  https://www.deviantart.com/jamush/art/Watercolor-Emico-Olive-91448120

**Comment by HBelusca** [comment]
Hi! I've tried to see whether it is possible to add your themes in our RAPPS database, where static download links are needed, and it seems to be impossible as the download links provided by deviantart appear to be dynamic (with a dynamic token valid for a limited amount of time).
Is it possible to provide an alternate way of downloading?

**Pull request closed without merging**
