### PR TITLE
[RICHED20] Fix assert in editpad due to excessive tab count

### PR DESCRIPTION
**Pull request by Doug-Lyons**
CORE-8452

## Purpose

_Riched20 partial Wine sync to fix excessive tab count._

JIRA issue: [CORE-8452](https://jira.reactos.org/browse/CORE-8452)

## Proposed changes

_Partial Wine sync of riched20. No 'ifdef' used because this is already in Wine._

### CODE REVIEW

**Comment by SergeGautherie** [comment]
Notice  #6949.

**Comment by maj113** [comment]
> Notice #6949.

Doug made it separate from my PR so it gets merged faster

**Review by HBelusca — APPROVED** [review]

**Review by JoachimHenze — APPROVED** [review]
Approved for bulletproofing of ros corrupting the memory here. But just for my understanding I would like to have confirmation: That specific Editpad binary, which triggered that, does contain a programming error, right?

**Comment by Doug-Lyons** [comment]
> Approved for bulletproofing of ros corrupting the memory here. But just for my understanding I would like to have confirmation: That specific Editpad binary, which triggered that, does contain a programming error, right?

@JoachimHenze, It is not so much a programming error (It runs successfully on W2K3SP2) as a limitation of the current implementation of our riched20.dll which comes from Wine. There is a parameter which is ```MAX_TAB_STOPS``` (in riched.h) and in our sources and Wine's this value is 32 (0x20). So only this much memory is allocated to hold this many positions. But this version of editpad requests 256 (0x100) tab stop positions. So when the 256 tab stop positions are copied into the space reserved for 32 positions, memory is over-written causing an eventual exception. So with this change, we limit the ```memcpy``` to copying only 32 values. Another solution would be to expand the maximum number of values allowed. Thanks.

**Comment by JoachimHenze** [comment]
Does 2k3sp2 actually support 256 tabstops? Or does it "clamp" to 32 as well?

**Comment by Doug-Lyons** [comment]
> Does 2k3sp2 actually support 256 tabstops? Or does it "clamp" internally to 32 as well?

When Wine accepted this patch, it was accompanied by changes to the ```riched20``` winetest shown in this patch.
[winetest_riched20-01.patch](https://github.com/user-attachments/files/15535158/winetest_riched20-01.patch)
I have compiled and run these tests against W2K3SP2 and none of these tests fail.
So in looking at the tests, it seems that in Windows, the maximum number of tab stops is limited to 32.

**Comment by HBelusca** [comment]
> > Does 2k3sp2 actually support 256 tabstops? Or does it "clamp" internally to 32 as well?
> 
> When Wine accepted this patch, it was accompanied by changes to the `riched20` winetest shown in this patch. [...]

Would it be possible to import that winetest patch too, _**iff**_ it has also been merged into their source tree?

**Review by oleg-dubinskiy — APPROVED** [review]
LGTM for the fix itself, but please 1) apply @HBelusca's suggestion about importing the winetest part in this PR too and 2) don't forget to specify the links to the imported commits from Wine source tree in the commit message, as it's important to remember that. Thanks.
N.B.: if #6949 PR has a conflicts with this change, it should necessarily be rebased and updated too, after merging this one.

**Comment by Doug-Lyons** [comment]
Thanks for everyone's help with this.

**Pull request merged**
