### PR TITLE
[MSVCRT_WINETEST][OLEACC_WINETEST] Re-enable MSVC warning C4477

### PR DESCRIPTION
**Pull request by SergeGautherie**

### CODE REVIEW

**Comment by HBelusca** [comment]
We should configure the appveyor/travis to compile the tests too, because so far I don't see them compiled.

**Comment by SergeGautherie** [comment]
> configure the appveyor/travis to compile the tests

Both have `ENABLE_ROSTESTS=1` already. What else are you missing?

**Comment by SergeGautherie** [comment]
Cc @tkreuzer

**Comment by SergeGautherie** [comment]
> "-Wno-format"

Done;

**Comment by SergeGautherie** [comment]
> Remove "-Wno-format"

Eventually, that broke gcc build.
katahiromz reverted that extra part in d1ac13c.

**Pull request merged**
