### PR TITLE
[SHELL32] Fix typo in folder options view

### PR DESCRIPTION
**Pull request by cbialorucki**
## Purpose

Fixes a typo in the folder options window. The new line character in the middle of the string was also unnecessary and removed.

Before:
Before

After:
after

### CODE REVIEW

**Review by JoachimHenze — CHANGES_REQUESTED** [review]
Please fix that typo also for all other languages, e.g. de-DE does have it too, I just checked: at least the \n should be changed to a space there as well. FTR shell32 has 36 rc files.

**Comment by cbialorucki** [comment]
> Please fix that typo also for all other languages, e.g. de-DE does have it too, I just checked: at least the \n should be changed to a space there as well. FTR shell32 has 36 rc files.

Not every language had this issue, but several more did and I corrected the ```\n``` issues in the files I found. Looks like only English had the missing space before the parenthesis. There are more issues in here though. For example, there are some lines that use ```\r\n``` and most others that just use ```\n```.  There are also some strings (```IDS_OVERWRITEFOLDER_TEXT```, ```IDS_FORMAT_WARNING```) that seem to have some unneeded new lines as well as the ```IDD_DRIVE_TOOLS``` dialog.

**Comment by JoachimHenze** [comment]
For now just fix the line everywhere, that you touched already. Meaning: if the space before the opening brace is missing, add it.
If it has a \n in that line, remove it.

Other things you mentioned could be addressed in another PR later. For now it is just about applying constantly, what you applied to english and not yet translated languages yet, to all of them. Then I will approve the PR.

**Comment by JoachimHenze** [comment]
ca-ES.rc still has both issues (the missing space before the brace and the \n). Would you please go through all 36 files by yourself, I don't want to spoonfed 36 times.

**Review by JoachimHenze — APPROVED** [review]
fr-FR, jp-JP, pl-PL, ro-RO, ru-RU, tr-TR, uk-UA, zh-CN, zh-HK, zh-TW were unaffected by the line that was initially touched with this PR.
We do have 36 files, you covered 26. LGTM now regarding the first sentence. Didn't double-check the others that you touched again since then. But I assume you got the idea of keeping things sync.

**Review by HBelusca — APPROVED** [review]

**Pull request merged**
