### PR TITLE
[Translations] Spanish translations #3

### PR DESCRIPTION
**Pull request by julcar**
## Purpose

To finnish my translation pull request series, here is a lot of new translations and fixes to the existents

JIRA issue: [CORE-14767](https://jira.reactos.org/browse/CORE-14767)

### CODE REVIEW

**Comment by julcar** [comment]
Git do what he wants, only the last 6 commits were for the pull request.

**Comment by gigaherz** [comment]
No, git do what you told it to -- if you get old commits, it means you reused the same old branch. You should either create a new branch every time created from the main master, or use `git reset --hard upstream/master` to change your existing branch.

**Comment by gigaherz** [comment]
¯\_(ツ)_/¯ can always use the reflog to recover old heads.

**Comment by gigaherz** [comment]
Anyhow, @julcar create a new branch if you don't know what you are doing, it's the safe choice.

That said, if you want to keep this PR, you can use `git fetch upstream` followed by `git rebase upstream/master` to re-apply your changes on top of the master branch. you will have to force-push afterward so make sure you have the right changes before you use `git push --force-with-lease` to push the changes.

**Comment by julcar** [comment]
Things I did (from git-gui)
1) Checkout origin/master, that downloaded changes from git.reactos.org head
2) checkout master
3) merge origin/master into master, that updated my local copy
4) push master to github-src/master to update my github fork
5) checkout spanish-translations branch
6) merge master into spanish-translations
7) push spanish-translations to github-src/spanish-translations

**Pull request closed without merging**
