### PR TITLE
[DOC] Update Romanian translation notes.txt

### PR DESCRIPTION
**Pull request by AndreiMiloiu**
I proposed more flexible rules. The idea is to be a correct translation that is understandable by any computer user. It will be about both a correct translation and correctly formulated statements.

Rule number 6 does not exist, so it is removed.

Of course, if you agree with these changes I will apply them to every file that needs to be changed.

### CODE REVIEW

**Comment by AndreiMiloiu** [comment]
Cc @reactos/lang-romanian

**Comment by GeoB99** [comment]
> For the rule 17 the subpoint that specify to avoid using accelerator as "s" and "t" is removed. Let's be honest: how many people confuse the letters even if they are some with diacritics? People who do this either don't know the alphabet or they have a very bad eyesight (close to blindness). I never made confusions for "s" and "t" as "ș" and "ț", respectively.

I think the reason behind avoiding the use of these letters as accelerators is due to the fact that an underscore is drawn beneath them. Depending on what font you use, the underscore would probably look ugly and may give the impression it is a badly formatted diacritic.

**Comment by AndreiMiloiu** [comment]
> > For the rule 17 the subpoint that specify to avoid using accelerator as "s" and "t" is removed. Let's be honest: how many people confuse the letters even if they are some with diacritics? People who do this either don't know the alphabet or they have a very bad eyesight (close to blindness). I never made confusions for "s" and "t" as "ș" and "ț", respectively.
> 
> I think the reason behind avoiding the use of these letters as accelerators is due to the fact that an underscore is drawn beneath them. Depending on what font you use, the underscore would probably look ugly and may give the impression it is a badly formatted diacritic.

I understand. I can revert this change if you want, but please, let me know.

**Comment by GeoB99** [comment]
I would say keep it.

**Comment by reactos-contributor** [comment]
_„8. Este recomandată o formulare independentă de gen (gramatical).”_
This means that when you formulate a message (like a question) to the user, it's best to avoid assuming that the user is a male or female. This was necessary because, unlike in English, in Romanian the gender oftentimes gets baked in the message. Unless you have any clue that the message receiver is either male or female, it's a good idea to create gender neutral massage. There's nothing else to it.

_„12. Este de evitat articularea inutilă, însă adaptarea mesajelor traduse trebuie totuși să primeze.”_
Well, this was a preference (of other translators) that produced terser messages, but I don't consider it to be important enough to warrant the extra effort (that has to be invested when one treats it as rule). I'm ok with removal.


_„I still don't understand: why should the reflexive diatesis be prohibited in a translation?”_
It's not about prohibition. It's about logic. Reflexive and passive are there to make distinction between the cases when actions are caused by internal versus external factors. Yes, in the colloquial speech these do not always get respected, but there the stakes are lower too. In here, whatever you write will get consumed over and over by an unspecified number of people, so each extra effort for correctness is warranted (in my book).

**Comment by AndreiMiloiu** [comment]
> > > For the rule 17 the subpoint that specify to avoid using accelerator as "s" and "t" is removed. Let's be honest: how many people confuse the letters even if they are some with diacritics? People who do this either don't know the alphabet or they have a very bad eyesight (close to blindness). I never made confusions for "s" and "t" as "ș" and "ț", respectively.
> > 
> > 
> > I think the reason behind avoiding the use of these letters as accelerators is due to the fact that an underscore is drawn beneath them. Depending on what font you use, the underscore would probably look ugly and may give the impression it is a badly formatted diacritic.
> 
> **I second this.** I have previously referenced to Microsoft's guide on Selecting Access Keys (like [here](https://github.com/reactos/reactos/pull/5564#discussion_r1295994921) or [here](https://github.com/reactos/reactos/pull/5558#discussion_r1296057930)). Having an access key assigned to a letter with descender doesn't render the letter illegible or easy to confuse, yet it they recommend avoiding that kind of assignment. Potential collision of access key marks with diacritics' letters makes an even stronger argument. Think about the case where „ș” or „ț” are also access keys. The user will have a harder time visually parsing the line looking for that access key mark, because at first glance it may be taken as part of the comma bellow. There is also another argument that I don't think I've previously stated (nor seen it presented by others). It's about how that diacritic gets typed. Most users that will make use of access keys won't be at beginner level. They are the type that are focused at improving their work habits, applying customization, which may most likely include keyboard layouts like Romanian programmers (instead of Romanian standard). There, „ș” gets typed by pressing „AltGr”+„s”. (Other Romanian diacritics are typed in a similar way.) However, an access key requires pressing „Alt” (the simple one) + key. You may imagine how it goes when a letter with diacritic gets assigned an access key and how (not) useful that is.

I understand, I will revert this.

**Comment by AndreiMiloiu** [comment]
> _„8. Este recomandată o formulare independentă de gen (gramatical).”_ This means that when you formulate a message (like a question) to the user, it's best to avoid assuming that the user is a male or female. This was necessary because, unlike in English, in Romanian the gender oftentimes gets baked in the message. Unless you have any clue that the message receiver is either male or female, it's a good idea to create gender neutral massage. There's nothing else to it.
> 
> _„12. Este de evitat articularea inutilă, însă adaptarea mesajelor traduse trebuie totuși să primeze.”_ Well, this was a preference (of other translators) that produced terser messages, but I don't consider it to be important enough to warrant the extra effort (that has to be invested when one treats it as rule). I'm ok with removal.
> 
> _„I still don't understand: why should the reflexive diatesis be prohibited in a translation?”_ It's not about prohibition. It's about logic. Reflexive and passive are there to make distinction between the cases when actions are caused by internal versus external factors. Yes, in the colloquial speech these do not always get respected, but there the stakes are lower too. In here, whatever you write will get consumed over and over by an unspecified number of people, so each extra effort for correctness is warranted (in my book).

Maybe at 8 I should change a little bit the rule in order to express that we should avoid use any gender if we don't know it.
Also I propose at 20 to change a little bit the rule in order to tell anyone that we should avoid the reflexive diatesis when it's not needed.

What do you think about that?

**Comment by reactos-contributor** [comment]
> What do you think about that?

Sounds good. I would have worked the contents of the guideline myself back in the day, if I had any feedback that it was not clear enough.

**Pull request merged**
