### PR TITLE
WIP. [NTOS:MM] ARM3/section.c: Use BYTES_TO_PAGES()

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Assumed not to change behavior, especially with regard to overflow...

## TODO

- [ ] Untested.

### CODE REVIEW

**Comment by SergeGautherie** [comment]
Is approval enough to remove WIP? Or what kind of test do you expect?

**Comment by learn-more** [comment]
How about resolve the [ ] untested?

**Comment by SergeGautherie** [comment]
> How about resolve the [ ] untested?

Alright, this is why I asked "what kind of test do you expect?".
Simply booting ROS? Something more specific? ...

**Comment by ThFabba** [comment]
A test that exercises the code you're changing. If it's not clear how to do that, then maybe it shouldn't be changed.

**Comment by Saibamen** [comment]
Please mark this Pull Request as Draft: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request

**Comment by zefklop** [comment]
No activity for years, and still WIP. Closing.

**Pull request closed without merging**
