### PR TITLE
[SPEC2DEF] Omit skipped exports from ordinal numbering.

### PR DESCRIPTION
**Pull request by learn-more**
JIRA issue: [CORE-16769](https://jira.reactos.org/browse/CORE-16769)

### CODE REVIEW

**Comment by ThFabba** [comment]
> JIRA issue: [CORE-16769](https://jira.reactos.org/browse/CORE-16769)

This is just cleanup and doesn't actually fix any bug, right?

**Comment by learn-more** [comment]
> > JIRA issue: [CORE-16769](https://jira.reactos.org/browse/CORE-16769)
> 
> This is just cleanup and doesn't actually fix any bug, right?

It fixes that application failing to snap an ordinal import.
By pure accident one of the ordinals it needs fell in a gap.

**Comment by ThFabba** [comment]
But if it imports by ordinal, and we don't explicitly export the right function by ordinal, it's probably going to get a random incorrect function pointer anyway?

**Comment by learn-more** [comment]
> But if it imports by ordinal, and we don't explicitly export the right function by ordinal, it's probably going to get a random incorrect function pointer anyway?

yeah,
just like on win10 where it gets something completely different as well.

**Pull request merged**
