### PR TITLE
[TRANSLATION] Serbian, SR. Start of a new language.

### PR DESCRIPTION
**Pull request by alexpavlovic**
## Translation to serbian language.

2 files (1 modified, 1 added) for the start just to see how it goes.

### CODE REVIEW

**Comment by peterooch** [comment]
You may want to take look at https://github.com/reactos/reactos/blob/13310b3acf1dfd88ff27c19526d3ca37b24e029c/base/applications/write/rsrc.rc#L87 And
https://github.com/reactos/reactos/blob/13310b3acf1dfd88ff27c19526d3ca37b24e029c/base/applications/write/lang/Sr.rc#L26
Also this MSDN note can be of use:
https://docs.microsoft.com/en-us/windows/desktop/intl/language-identifier-constants-and-strings#language-identifier-notes

The file will not be compiled in the first place because https://github.com/reactos/reactos/blob/master/sdk/cmake/localization.cmake 
lacks a `LANGUAGE_SR_SR` definition.

**Comment by HBelusca** [comment]
@alexpavlovic : please let us know whether you expect to add other commits in this PR (i.e. it is currently work-in-progress) or not.

**Comment by alexpavlovic** [comment]
@HBelusca : Not at this moment, thank you for asking. I shall continue work on translation ReactOS though. This first package was necessary for me to learn basics about Git and Github procedures and it is therefore small. I will have to plan time for this activity on weekends probably. Best regards, Alex.

**Comment by HBelusca** [comment]
You can leave this PR opened though, and I'll merge it, so that you can continue afterwards. Or we can keep the PR open and label it as "WIP".

**Comment by alexpavlovic** [comment]
@HBelusca : WIP is indeed, but if it is practice for this project to merge contributions in smaller chunks it is ok with me. You may decide what you think is better for the project, and I will conform to established work procedure.

**Comment by HBelusca** [comment]
Keeping the PR open as "WIP" is OK for us.

**Comment by HBelusca** [comment]
@alexpavlovic : hi, any news about this translation PR?

**Comment by Saibamen** [comment]
Please mark this Pull Request as Draft if is still WIP: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request

**Comment by gonzoMD** [comment]
No activity for almost 2 years. Let's commit the work done so far?

**Comment by binarymaster** [comment]
> Let's commit the work done so far?

Agree, but only in case there are no problems, we still have to review every line, since we didn't that yet.

**Pull request merged**
