### PR TITLE
[FASTFAT_NEW] Fix uninitialized use

### PR DESCRIPTION
**Pull request by mrmks04**
## Purpose

Fix uninitialized use

### CODE REVIEW

**Comment by SergeGautherie** [comment]
Where is it used uninitialized?
This should be submitted upstream...

**Comment by mrmks04** [comment]
> 
> 
> Where is it used uninitialized?
> This should be submitted upstream...

uninit_use

**Comment by SergeGautherie** [comment]
> uninit_use

I don't know what/how triggered this failure, but it is obviously wrong:
an assignment is not a (uninit) use!

If the failure can be reproduced, file a Jira ticket...

NB:
This PR reminds me of #3679...

**Comment by HBelusca** [comment]
Ahh yes.... Actually this is due to a new bug in the RTC implementation of Visual Studio, see this discussion on Mattermost:
image
and the relevant links:
https://developercommunity.visualstudio.com/t/Broken-runtime-checks-with-CL-19293013/1503629
and the older PR that fixed the problem: PR #3909 .

**Comment by tkreuzer** [comment]
Issue is fixed by PR #3909

**Pull request closed without merging**
