### PR TITLE
Tests are broken

### PR DESCRIPTION
**Pull request by ThFabba**
Grml.

No need to review this, I know these fixes are overly broad and suck.

### CODE REVIEW

**Comment by spetreolle** [comment]
Do we have reports regarding those 3 issues ?

**Comment by learn-more** [comment]
@ThFabba Can you please create an issue regarding those tests and reference that in a comment near the changed code?

**Comment by zamabuvaraeu** [comment]
Why GetModuleHandleA instead GetModuleHandleW or GetModuleHandle?

**Comment by ThFabba** [comment]
Read the description please.

**Pull request closed without merging**
