### PR TITLE
[THEMES] Fix Modern theme bitmaps and some values

### PR DESCRIPTION
**Pull request by oleg-dubinskiy**
## Purpose

Remove the BGRs colour space headers and fix some text values to allow using theme on Windows XP.

JIRA issue: [CORE-15940](https://jira.reactos.org/browse/CORE-15940)

## Proposed changes

- Remove the BGRs from all bitmaps of Dark and Light colour schemes by changing the sequence of colour channels, `*_FRAMECAPTIONSIZING.bmp` and `*_SMALLFRAMECAPTIONSIZING.bmp` were also converted to RGB before changing the colour channels;
- Fix some values in theme configuration files for `Regular*`, `LargeFonts*` and `ExtraLargeFonts*` sizes.

## Result

Dark:
fixed-dark
Light:
fixed-light

### CODE REVIEW

**Comment by gonzoMD** [comment]
In your screenshots, the start button looks strange

**Comment by binarymaster** [comment]
> In your screenshots, the start button looks strange

That's a bug of the theme itself, from the start it was optimized for ReactOS and didn't ever tested in XP.

**Comment by oleg-dubinskiy** [comment]
> In your screenshots, the start button looks strange

Yeah. Before my changes, there was no dark blue line at the top of the taskbar in ReactOS. After removing BGRs, it appeared for some reason and is visible both in ROS and in XP. Start button bitmap has no this line unlike all other taskbar space, so due to that, it looks a bit strange. I wonder what I did wrong.
ROS before:
before-ros
ROS after:
after-ros

**Comment by tkreuzer** [comment]
This white rectangle doesn't look like it should be there:
grafik

**Comment by oleg-dubinskiy** [comment]
Thanks for spotting @tkreuzer. The source of problem was the background of all `*_HELPGLYPH*.bmp` files became white instead of transparent after swapping RGB headers via IrfanView 4.51. Both Dark and Light schemes were affected. I tried a tons of image editing software, but for some reason, all image editors can't save the bmp with transprent background and places the white/black background instead of that. Looks like it's a limitation of bmp format itself, not of editors. After restoring the current state of these bitmaps and swapping again via XnView MP 0.93.1, and re-exporting into alpha channel via Pixelformer 0.9.6.3 RC3, they have a black background instead of white, although in that editor it's visible as transparent. So now it looks much better.
Here is an updated result:
Dark:
updated_dark
Light:
updated_light

P.S.: I wonder how @p01arst0rm was able to save bitmaps with the transparent background. Sorry if I don't know something.

**Comment by learn-more** [comment]
He probably uses 32bit bitmaps

**Comment by oleg-dubinskiy** [comment]
I exported that bitmaps in 32bit on the last step, but background is still black, if enable alpha channel option. If don't enable that, bitmaps have the same white background and some white `?` became invisible.

**Comment by p01arst0rm** [comment]
> This white rectangle doesn't look like it should be there:
> grafik

it should, that should be the help button iirc

**Comment by p01arst0rm** [comment]
> Thanks for spotting @tkreuzer. The source of problem was the background of all `*_HELPGLYPH*.bmp` files became white instead of transparent after swapping RGB headers via IrfanView 4.51. Both Dark and Light schemes were affected. I tried a tons of image editing software, but for some reason, all image editors can't save the bmp with transprent background and places the white/black background instead of that. Looks like it's a limitation of bmp format itself, not of editors. After restoring the current state of these bitmaps and swapping again via XnView MP 0.93.1, and re-exporting into alpha channel via Pixelformer 0.9.6.3 RC3, they have a black background instead of white, although in that editor it's visible as transparent. So now it looks much better.
> Here is an updated result:
> Dark:
> updated_dark
> Light:
> updated_light
> 
> P.S.: I wonder how @p01arst0rm was able to save bitmaps with the transparent background. Sorry if I don't know something.

the transparency of bitmaps is handled within its alpha channel. if your alpha channel is non-existent or broken, transparency will not work

**Comment by learn-more** [comment]
Whilst this might fix something,
it breaks other bitmaps so that is not really an improvement overall.

**Pull request closed without merging**
