### PR TITLE
[FASTFAT_NEW] Sync to upstream 16022c5

### PR DESCRIPTION
**Pull request by SergeGautherie**

### CODE REVIEW

**Comment by Extravert-ir** [comment]
I think this commit: https://github.com/microsoft/Windows-driver-samples/commit/16022c593787aef040b8a37ef697316e07f1322e should be put as a sync-commit, that makes more sense

**Comment by SergeGautherie** [comment]
> should be put as a sync-commit

I am not sure what you mean...

**Comment by Extravert-ir** [comment]
I mean the commit hash which is written in `README.FSD`

**Comment by SergeGautherie** [comment]
> commit hash

I kind of concur, but note current hash is not a FastFAT one either.
What is the rule, then? (Global or by component?)

**Comment by Extravert-ir** [comment]
No rules here, anarchy!
So in order to reduce the chaos, I'd like to introduce one: we should sync with the latest commit touching the target code

**Comment by SergeGautherie** [comment]
> latest commit

Very fine with me.
NB: 'cdfs' and 'floppy_new' hashes are already fine.

**Pull request merged**
