### PR TITLE
[MSAFD][AFD][TCP] Add asynchronous connection support

### PR DESCRIPTION
**Pull request by Zero3K**
This is a PR of a combined patch of patches that was fixed by Oleg Dubinskiy and originally made by hater (on JIRA) which adds asynchronous connection support (thereby allowing torrent programs to work, web browsing to be faster, etc).

JIRA issue: [CORE-12152](https://jira.reactos.org/browse/CORE-12152)

### CODE REVIEW

**Comment by Zero3K** [comment]
The patches made it easier to replicate the crash that is mentioned at https://jira.reactos.org/browse/CORE-12425.

**Comment by JoachimHenze** [comment]
Historically this patch - as is - increased the chance for failure of DNS resolving.

**Comment by Zero3K** [comment]
I didn't notice that when I applied the patch since the DNS Cache service was added a while ago.

**Comment by learn-more** [comment]
Who is going to address review comments?

**Comment by Zero3K** [comment]
I can if its not hard to do so.

**Comment by Zero3K** [comment]
Its leaking memory but @Doug-Lyons doesn't know where. It would be nice if someone could help him figure it out.

**Comment by BenNottelling** [comment]
Maybe he should submit a pull request when it's actually done then, I'm sure he's more than capable.

**Comment by Zero3K** [comment]
> 
> 
> Maybe he should submit a pull request when it's actually done then, I'm sure he's more than capable.

He's out of ideas regarding it.

**Comment by learn-more** [comment]
This is not how a PR works,
dump someone elses code in then spam yet another person to do the fixing for you.

**Comment by Zero3K** [comment]
Then what should I do?

**Comment by BenNottelling** [comment]
@Zero3K learn how to code so you can actually fix it

**Pull request closed without merging**
