### PR TITLE
Delete gitignored files

### PR DESCRIPTION
**Pull request by Saibamen**
## Purpose

This is just result of run this commands:
```
git rm -r --cached .
git add .
```

### CODE REVIEW

**Comment by ThFabba** [comment]
The right fix here is probably to adjust .gitignore.

**Comment by Saibamen** [comment]
So we need those files?
Please check CI for this PR. AppVeyor and Travis has builded successfully

**Comment by ThFabba** [comment]
I don't think we use those files, but they're included to keep the structure of the upstream library.

**Comment by Saibamen** [comment]
I have made alternative solution: https://github.com/reactos/reactos/pull/2538

**Comment by Extravert-ir** [comment]
Looks like `build` folder was added to gitignore for no reason. I don't see anything which creates it

**Comment by Extravert-ir** [comment]
Closed in favor of c42e124

**Pull request closed without merging**
