### PR TITLE
[COMCTL32] [COMDLG32] [ACLUI] [CALCS] Improvements to pt-PT translation

### PR DESCRIPTION
**Pull request by zecarlos1957**
[COMCTL32] Improvement to pt-PT translation
[COMDLG32] Improvement to pt-PT translation
[ACLUI] Improvement to pt-PT translation
[CALCS] Add pt-PT translation
[DEVMGR] Fix typos and improve pt-PT translation 
[SYSDM]  Fix typos and improve pt-PT translation 
[CPL] Readjust objects position to fit all text

In some ReactOS files, 'File' has been translated as 'Arquivo', in others as 'Ficheiro'. 
but in order to maintain the same logic throughout ReactOS, 
we chose to use 'Ficheiro' throughout ReactOS.

### CODE REVIEW

**Comment by jcfb-opensource** [comment]
This translation is incorrect. "arquivo" is usually used in brazillian portuguese while "ficheiro" is more common in european portuguese. In fact windows and most programs translated to european portuguese use ficheiro, as you can see below
In fact [wikipedia](https://pt.wikipedia.org/wiki/Arquivo_de_computador) states that.
Capturar

**Comment by zecarlos1957** [comment]
@jcfb-opensource  

So we chose 'Ficheiro'.
I love it when someone disagrees with me; two things can happen:
Either I have arguments to defend my idea, or it's an opportunity to make it evolve and make it stronger by including other ideas.
Thanks.

**Comment by zecarlos1957** [comment]
Before
After

**Comment by zecarlos1957** [comment]
I marked it as a draft because I was waiting for Gabriel Aguiar to resolve the change requests to give it priority because we have a common file  but there is no conflicts

**Review by binarymaster — APPROVED** [review]

**Pull request merged**
