### PR TITLE
[MSGINA] PL-pl FIX

### PR DESCRIPTION
**Pull request by pithwz**
msgina.dll PL-pl
-FIXED: dialogs, buttons,
msgina_before_after

### CODE REVIEW

**Comment by learn-more** [comment]
Fixed how?

**Comment by HBelusca** [comment]
> Fixed how?

The size of the UI elements.

**Comment by learn-more** [comment]
> > Fixed how?
> 
> The size of the UI elements.

Obviously, but the last commit to this file was also from him, and also changed sizes.
So I was wondering what changed all of a sudden?

**Comment by binarymaster** [comment]
Yeah I'd like to see "before" and "after" too.

Other PRs are changing element sizes as well, if these are just cosmetic changes, they should be applied (synced) to all translations.

**Comment by HBelusca** [comment]
Sometimes UI object sizes need to be changed per language (if strings are longer than e.g. in english...)

**Comment by gonzoMD** [comment]
According to the images, I see no much difference. No cutoff strings etc. Why are these changes needed?

**Review by binarymaster — CHANGES_REQUESTED** [review]
I see only cosmetic changes here like moving icons and labels around. If you want this change merged, you need to perform the same tweaking for all languages/translations, otherwise this is a no go.

**Comment by pithwz** [comment]
end

**Pull request closed without merging**
