### PR TITLE
[USER32] Get gHighestUserAddress in DllMain

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

JIRA issue: N/A

## Proposed changes

- Add `gHighestUserAddress` global variable.
- Get  `gHighestUserAddress`  at `Init`.

### CODE REVIEW

**Comment by JoachimHenze** [comment]
What do you need that address for?

**Comment by learn-more** [comment]
Typically that is something that would be described in the 'purpose' part of your PR.

**Comment by HBelusca** [comment]
Same questions raised here also apply to the already-committed 3d298831d for IMM32.DLL

**Comment by HBelusca** [comment]
Maybe only commit code that you understand.

**Comment by mega-maniac** [comment]
I thought using Windows copyrighted code was problem for ReactOS. Some of katahiromz code
comes directly from Windows source code. He just changes it a little bit then commits it.
And this pull is also from Windows source code.

I became suspicious when he started adding all those Win:: function comments. When I looked them up, it led me 
me to the copyrighted code.

His last commit, [NTUSER] Implement IntCheckImeShowStatusInThread, is just copy of windows code. 

**** Windows version ****
VOID xxxCheckImeShowStatusInThread(PWND pwndIme)
{
     if (IS_IME_ENABLED()) {
         UserAssert(pwndIme);
 
         if (!TestWF(pwndIme, WFINDESTROY)) {
             xxxCheckImeShowStatus(pwndIme, GETPTI(pwndIme));
         }
     }
}

**Comment by katahiromz** [comment]
image

**Pull request closed without merging**
