### PR TITLE
[MEDIA][FONTS] Renewal of Marlett.ttf

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Renewal of `Marlett.ttf` font file.
JIRA issue: [CORE-16226](https://jira.reactos.org/browse/CORE-16226), [CORE-14872](https://jira.reactos.org/browse/CORE-14872)

- Based on Ged Murphy's `Marlett.ttf` (See https://github.com/reactos/reactos/blob/527f2f90577662e8eba1b1b62f958c39b3cd4358/media/fonts/Marlett.ttf).
- Erase the centered triangles.
- Adjustment of glyphs.
- Clarify the copyright ownership.
- Tested with 3 test programs (`RadioAndCheck`, `PixelPerfectGlyph` and `MarlettCompare`).

### CODE REVIEW

**Comment by katahiromz** [comment]
checkmark
radiobutton
minmaxclose
maximized
I can see improvements.

**Comment by feel-the-dz3n** [comment]
Looks good!

**Comment by HBelusca** [comment]
> 
> 
> checkmark
> radiobutton
> minmaxclose
> maximized
> I can see improvements.

Ok there are still room for further improvements:
- checkbox: the sign is one or two pixels too high (and therefore it touches the top of the box),
- minimize button line: too short,
- maximize button icon: too large,
- X button: X symbol is too fat.

**Comment by katahiromz** [comment]
maximized
checkmark
minmaxclose
Improved.

**Comment by katahiromz** [comment]
Needs fixing.

**Comment by katahiromz** [comment]
OK. Let's go.

**Comment by katahiromz** [comment]
SCROLLBAR:
scrollbar
CHECKMARK:
checkmark
RADIOBUTTON:
radiobutton
MIN MAX CLOSE:
minmaxclose
MAXIMIZED:
maximized
COMBOBOX:
combobox
MENU:
menu

**Comment by katahiromz** [comment]
Tested with `RadioAndCheck` test program:

**Comment by katahiromz** [comment]
new-Marlett

**Comment by katahiromz** [comment]
This font file contains the bitmap glyphs of 8-to-16 pixel heights.

**Pull request merged**
