### PR TITLE
[NTDLL_APITEST] Actually fix RtlValidateUnicodeString last case

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Addendum to ef2e1871b18be3a489b1649207f423471332c024.

## Proposed changes

- Use a valid `Length`.

### CODE REVIEW

**Comment by HBelusca** [comment]
>  * Use a valid `Length`.

In case you haven't seen, we are testing how the RtlValidateUnicodeString behaves with invalid lenghts...

**Comment by SergeGautherie** [comment]
> invalid lenghts

Do you actually mean you want to test `Length--` twice (fine though somewhat redundant),
and never `MaximumLength--` alone?

**Comment by HBelusca** [comment]
Testing odd lengths in particular.

**Comment by SergeGautherie** [comment]
Please, try to understand this PR instead of lecturing me about existing code!
I understand you want to keep both existing tests about `Length`: ok.
Nonetheless, I don't understand why you seem not to want to test odd `MaximumLength` by itself (i.e. with a valid `Length`)...

**Comment by HBelusca** [comment]
> Please, try to understand this PR instead of lecturing me about existing code!

Then make it clear from the beginning by writing a correct PR description! Because what I understood from looking at the code is that you just modified the tests for unexplained reasons.

So concerning your second point, instead of modifying existing tests, just add a new one.

**Comment by SergeGautherie** [comment]
> make it clear

Calm down! I would say my guess/PR is not so bad, as your commit that changed that test case reads 'add few simplifications'...

> add a new one

Sure. Please, reopen.

**Pull request closed without merging**
