### PR TITLE
[WIN32SS] Revert text drawing

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Revert drawing text code by using the patch combination of CORE-16742 revert-freetype.patch and revert-PR745.patch.

JIRA issue: [CORE-16747](https://jira.reactos.org/browse/CORE-16747), [CORE-16742](https://jira.reactos.org/browse/CORE-16742), [CORE-15478](https://jira.reactos.org/browse/CORE-15478), [CORE-14896](https://jira.reactos.org/browse/CORE-14896), [CORE-16552](https://jira.reactos.org/browse/CORE-16552)

### CODE REVIEW

**Comment by katahiromz** [comment]
Spotify is OK ([CORE-16747](https://jira.reactos.org/browse/CORE-16747))
spotify

**Comment by katahiromz** [comment]
[CORE-16742](https://jira.reactos.org/browse/CORE-16742)
luna

**Comment by katahiromz** [comment]
CORE-15478 is ok.
CORE-15478

**Comment by katahiromz** [comment]
[CORE-14896](https://jira.reactos.org/browse/CORE-14896) is ok.
CORE-14896

**Comment by katahiromz** [comment]
[CORE-16552](https://jira.reactos.org/browse/CORE-16552) is ok.
CORE-16552

**Comment by Doug-Lyons** [comment]
image

Very Sorry, but it looks like this brings back https://jira.reactos.org/browse/CORE-6993.

**Comment by binarymaster** [comment]
> CORE-15478 is ok.

Window titles, start button caption, taskbar button captions, and language tray icon have text drawing problem - one pixel higher than needed.

I remember I already reported this problem in one of previous PRs.

**Comment by katahiromz** [comment]
Invalid. Closed.

**Pull request closed without merging**
