### PR TITLE
[TCPIP] Fixes crash when opening multiple tabs in Firefox, etc.

### PR DESCRIPTION
**Pull request by Zero3K**
This is a PR of a patch made by hater (on JIRA) that fixes a crash that occurs when opening multiple tabs in Firefox, etc.

JIRA issues: [CORE-11753](https://jira.reactos.org/browse/CORE-11753) and [CORE-12274](https://jira.reactos.org/browse/CORE-12274)

### CODE REVIEW

**Comment by Zero3K** [comment]
It doesn't seem to cause any crashes, etc. when I have been testing it.

**Comment by Zero3K** [comment]
@katahiromz Thanks for approving it.

**Comment by Zero3K** [comment]
Someone else should make the PR for this. It is being difficult to update the name and email of it and I am just a user, not a developer.

**Comment by tkreuzer** [comment]
There are multiple tickets
* CORE-12274 "Crash of r73105 when opening multiple tabs in Firefox" which contains this patch, but which is already marked as resolved. (the link was broken, I fixed it)
* CORE-11753 "Memory related crash (STATUS_ACCESS_VIOLATION) in ReactOS"
* CORE-12073 "Firefox 49 fails to start due to GetUserObjectInformation failure", which refrences  CORE-12828
* CORE-12828 "Firefox 51.0.1 doesn't start"
What is fixed here? Does this actually fix anything?
Also we need the full name of the author ("hater")

**Comment by Zero3K** [comment]
It fixes CORE-12274 and CORE-11753. I think Peter Hater is "hater"'s name.

**Pull request closed without merging**
