### PR TITLE
[APITESTS][GDI32] Add TextTransform testcase

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
This PR will prove text/font transformation functionality (#1238).
JIRA issue: [CORE-15554](https://jira.reactos.org/browse/CORE-15554)

### CODE REVIEW

**Comment by katahiromz** [comment]
Evidence:
evidence

**Comment by Doug-Lyons** [comment]
@katahiromz, can you post a screen shot of the results of these tests from ReactOS before PR#1238 and after so we can see the differences?

**Comment by katahiromz** [comment]
BEFORE #1238:
transform-before
AFTER #1238:
transform-after
Successful.

**Comment by Doug-Lyons** [comment]
@katahiromz, This is excellent and confirms my results as well. Thank you very much.

**Pull request merged**
