### PR TITLE
Convert some utf8 into Ansi escape codes

### PR DESCRIPTION
**Pull request by learn-more**
Please find attached the compiled files,
I am unable to verify the correctness (since the default for both already doesnt work for me)

Cc @peterooch for:
[biditext.zip](https://github.com/reactos/reactos/files/2323519/biditext.zip)

Cc @HeisSpiter for:
[ntdll_apitest.zip](https://github.com/reactos/reactos/files/2323517/ntdll_apitest.zip)

### CODE REVIEW

**Comment by katahiromz** [comment]
JIRA issues: [CORE-14971](https://jira.reactos.org/browse/CORE-14971), [CORE-14972](https://jira.reactos.org/browse/CORE-14972)

**Comment by ThFabba** [comment]
Thanks. Perhaps comparing the generated binaries (or object files) would help verify that it's identical?

**Comment by learn-more** [comment]
@ThFabba Not really, since the original biditext binary only displays crap for me.

**Comment by ThFabba** [comment]
Yes, but I mean the code before and after your changes should compile to the same bytes. I.e. you can verify it's the same as before, without running it.

**Comment by katahiromz** [comment]
https://www.browserling.com/tools/utf16-encode

**Comment by peterooch** [comment]
It works in my end... I would recommend using this->
https://gist.github.com/peterooch/bb224298366069ba182fbfe3f2c01f18
IMO instead of numbers, character names would look more clearer.

**Comment by HeisSpiter** [comment]
[
virtualbox_windows server 2003_01_09_2018_15_37_06
](url)

On the left: the tests as we have them in trunk nowadays.
On the right: the tests run with your apitest build.

**Comment by learn-more** [comment]
[ntdll_apitest_unedited.zip](https://github.com/reactos/reactos/files/2342408/ntdll_apitest_unedited.zip)
Here is a build from master.

**Comment by learn-more** [comment]
@HeisSpiter Could you change this test so it builds correctly on other locales?
(e.g. no embedded utf8 without BOM)

**Pull request closed without merging**
