### PR TITLE
[RAPPS] appview displaymode support

### PR DESCRIPTION
**Pull request by kernelbin**
## Purpose

- move toolbar into app-view.
- support display apps in report and tile mode

### previous screenshot
previous screenshot

previous screenshot

### current screenshot
previous screenshot

previous screenshot

previous screenshot

### CODE REVIEW

**Comment by KyleKatarn31** [comment]
pre/post screenshot please.

**Comment by kernelbin** [comment]
> pre/post screenshot please.

it's still WIP. when it can be displayed, I will update it

**Comment by learn-more** [comment]
This 'card' view is usually called 'tiles' or 'icons',
depending on the windows version.

**Comment by kernelbin** [comment]
> This 'card' view is usually called 'tiles' or 'icons',
> depending on the windows version.

ok, I will rename it as 'tile'

**Pull request merged**
