### PR TITLE
[UTILMAN] Fix content order in IDC_LISTBOX.

### PR DESCRIPTION
**Pull request by zecarlos1957**
Fix the content order in IDC_LISTBOX.

OSK et Magnify are mixed at initialization (language dependent)
LBS_STANDARD includes LBS_SORT style that changes the content in the listbox

JIRA issue: [CORE-18274](https://jira.reactos.org/browse/CORE-18274)
Patch by KRosUser.

### CODE REVIEW

**Review by HBelusca — APPROVED** [review]
lgtm, but let's @GeoB99 think whether using LB_INSERTSTRING with wParam == -1 instead of LB_ADDSTRING would be also better for robustness.

**Review by KRosUser2 — APPROVED** [review]

**Review by GeoB99 — APPROVED** [review]
I don't have a strong preference over the one or the other, both LB_INSERTSTRING and LB_ADDSTRING work identically since the `LBS_STANDARD` style is removed the latter message ListBox message won't sort the elements in the said ListBox.

So use whichever.

**Comment by julenuri** [comment]
Hi @zecarlos1957 , Could you please update `pt-PT.rc` file with the same change too. It has been added recently. Thanks.

**Review by julenuri — CHANGES_REQUESTED** [review]
Please, change all the headers to:
 
```
* PROJECT:     ReactOS Win32 BrowseUI
 * LICENSE:     LGPL-2.1-or-later (https://spdx.org/licenses/LGPL-2.1-or-later)
```

**Review by julenuri — APPROVED** [review]

**Pull request merged**
