### PR TITLE
[NTUSER] Fix system menu mouse handing

### PR DESCRIPTION
**Pull request by Cleverking2003**
## Purpose
Add a check for the system menu opened from the app icon.

JIRA issue: [CORE-19258](https://jira.reactos.org/browse/CORE-19258)

### CODE REVIEW

**Comment by Cleverking2003** [comment]
This breaks keyboard handling...

**Comment by Cleverking2003** [comment]
Should work now.

**Review by JoachimHenze — APPROVED** [review]

**Comment by JoachimHenze** [comment]
Since none of the reqested reviewers approved, rejected or made any suggestions for more than a week, I will merge this regression-fix today.

**Review by HBelusca — APPROVED** [review]
Just to be sure @Cleverking2003 , this IS_SYSTEM_MENU check:
https://git.reactos.org/?p=reactos.git;a=blob;f=win32ss/user/ntuser/menu.c;hb=b3194e320cfd143fa7f3ad4183f8b3305a113b07#l3394
(inside the MENU_ShowSubPopup function) is correct, however?

**Comment by Cleverking2003** [comment]
@HBelusca Yes, that check is correct. Making it the same as in `MENU_ButtonDown` breaks keyboard handling.

**Pull request merged**
