### PR TITLE
Ukrainian Translation Update & OEM-866 Code Page Problem

### PR DESCRIPTION
**Pull request by feel-the-dz3n**
virtualbox_ 0 4 12_14_12_2018_18_15_47
virtualbox_ 0 4 12_14_12_2018_18_16_22
virtualbox_ 0 4 12_14_12_2018_18_16_29
virtualbox_ 0 4 12_14_12_2018_18_16_37
virtualbox_ 0 4 12_14_12_2018_18_20_10

### CODE REVIEW

**Comment by feel-the-dz3n** [comment]
There are some problems with 866 codepage. It has ukrainian characters like `їЇ` `єЄ` but in ReactOS they appear like in OEM-US Codepage:
ros cp866 problem

**Comment by HBelusca** [comment]
@sanchaez , can you help @feel-the-dz3n in sorting the CP problem out? 😃

**Comment by feel-the-dz3n** [comment]
Also there are no Ukrainian `I i` characters, so they were replaced by English ones (`I i`)

**Comment by feel-the-dz3n** [comment]
I updated Ukrainian in SYSSETUP.
Before:
virtualbox_ 0 4 12_14_12_2018_19_15_20
virtualbox_ 0 4 12_14_12_2018_19_15_41
After:
virtualbox_ 0 4 12_14_12_2018_19_23_07
virtualbox_ 0 4 12_14_12_2018_19_23_22

**Comment by feel-the-dz3n** [comment]
virtualbox_ 0 4 12_15_12_2018_18_34_58

**Comment by feel-the-dz3n** [comment]
virtualbox_ 0 4 12_15_12_2018_19_04_00

**Comment by feel-the-dz3n** [comment]
MSGINA Translation Update
msgina

**Comment by HBelusca** [comment]
Hi @feel-the-dz3n , no need to attach screenshots for each module you're translating. We asked you about the screenshots only for usetup (the text-mode installer) because this one is the only one that uses these strange specific code-page-encoded files, where due to that, translation is prone to errors.

**Comment by HBelusca** [comment]
For your last winlogon screenshot "Rozblokuvannya kompyutera", it seems that the size of the first text line is a little bit too large. Have you fixed it?

**Comment by feel-the-dz3n** [comment]
> For your last winlogon screenshot "Rozblokuvannya kompyutera", it seems that the size of the first text line is a little bit too large. Have you fixed it?

Yes. It's Microsoft Paint problem :angry: 
image

**Comment by katahiromz** [comment]
I'm waiting for your commit to update usetup strings.

**Comment by katahiromz** [comment]
The enlarged text of title bar is because of font problem. Not your defect.

**Comment by feel-the-dz3n** [comment]
> I'm waiting for your commit to update usetup strings. What's the problem?

@katahiromz after applying code7bit to usetup's UA lang files there is still the same problem:
image
Symbols `ї` `Ї` `є` `Є` looks like `⌡` and `≤`

**Comment by feel-the-dz3n** [comment]
As far as I know, in 866 codepage there are characters Є and Ї, but it seems there are no such characters in USETUP's font.

**Comment by katahiromz** [comment]
Fork the bitmap font for 866.

**Comment by feel-the-dz3n** [comment]
> Fork the bitmap font for codepage 866.
> See the files in "media/vgafonts".
> Use: $OUTPUT/modules/rosapps/applications/devutils/vgafontedit/vgafontedit.exe

Thank you for information, I need to rebuild ReactOS and it will take some time

**Comment by feel-the-dz3n** [comment]
image
Yeah, the problem is right here.

**Comment by HBelusca** [comment]
These high-and low-parts of integral symbols don't seem to be needed in the fonts (I'm wondering why they are here), so yeah it may be great to fix that.

**Comment by katahiromz** [comment]
Delete vgafonts.cab and build again.

**Comment by feel-the-dz3n** [comment]
image
Finally it works fine

**Comment by katahiromz** [comment]
Enter the final check of screens.

**Comment by feel-the-dz3n** [comment]
> Enter the final check of screens.

What do you mean? Should I send screenshots?

**Comment by HBelusca** [comment]
Yes please.

**Comment by feel-the-dz3n** [comment]
virtualbox_ 0 4 12_18_12_2018_16_21_54
virtualbox_ 0 4 12_18_12_2018_16_22_17
virtualbox_ 0 4 12_18_12_2018_16_29_26
virtualbox_ 0 4 12_18_12_2018_16_29_35
virtualbox_ 0 4 12_18_12_2018_16_29_48
virtualbox_ 0 4 12_18_12_2018_16_29_56
virtualbox_ 0 4 12_18_12_2018_16_30_55
virtualbox_ 0 4 12_18_12_2018_16_31_08
virtualbox_ 0 4 12_18_12_2018_16_31_40
virtualbox_ 0 4 12_18_12_2018_16_31_46
virtualbox_ 0 4 12_18_12_2018_16_22_27
virtualbox_ 0 4 12_18_12_2018_16_22_33
virtualbox_ 0 4 12_18_12_2018_16_22_41
virtualbox_ 0 4 12_18_12_2018_16_22_46
virtualbox_ 0 4 12_18_12_2018_16_29_01

**Comment by katahiromz** [comment]
Find the mistakes carefully. If any, then fix them.

**Comment by feel-the-dz3n** [comment]
> Find the mistakes carefully. If any, then fix them.

Everything is ok

**Comment by HBelusca** [comment]
Looks great! The 'i' letter (with one dot) may need to be re-centered horizontally to the same position as the  ї (two dots) (which is OK), so that the words containing it does not look like containing separating spaces.

**Comment by feel-the-dz3n** [comment]
> Looks great! The 'i' letter (with one dot) may need to be re-centered horizontally to the same position as the ї (two dots) (which is OK), so that the words containing it does not look like containing separating spaces.

image
I can't see horizontal centering problems here, `ї Ї` are the same as `I` and `i` (even in 437 code page).

**Comment by HBelusca** [comment]
> I can't see horizontal centering problems here

OK then it is just an impression.

**Pull request merged**
