### PR TITLE
CORE-13242. Nit: merge duplicate code from r74582.

### PR DESCRIPTION
**Pull request by SergeGautherie**
[INTL]
Nit: merge duplicate code from r74582.
CORE-13242

### CODE REVIEW

**Comment by gonzoMD** [comment]
Lgtm

**Comment by paulsapps** [comment]
I thought the style was to always use braces for single line if statements?

**Comment by ThFabba** [comment]
Yes, that's preferred. But when modifying existing code it's best to stick with the existing style.

**Comment by HBelusca** [comment]
Status?

**Comment by SergeGautherie** [comment]
NB: To commit, use my email from 274ace05b2f5d5cded56345e95bc26ecaf013d32. Thanks.

**Comment by learn-more** [comment]
To commit, you used a masked git email.
Your commit will be used for stuff like this, not something we choose.

**Comment by SergeGautherie** [comment]
Ftr,

> To commit, you used a masked git email.

Exactly.

> not something we choose.

Afaik, not something GitHub web-editor lets me choose either 👎

NB:
Oh, it just occurs to me that Timo could do it on that commit, only because he created that PR, not I.

**Pull request merged**
