### PR TITLE
Fix syntax errors in errcodes.mc

### PR DESCRIPTION
**Pull request by wjk**
## Purpose

This was causing the MSVC build to fail.

## Proposed changes

- Fix syntax errors in translations so that the MSVC build succeeds.
- This also fixes the translations when not built using MSVC, which would still be malformed.

### CODE REVIEW

**Comment by learn-more** [comment]
@wjk Did you untick the option 'allow commits from contributors'?

**Comment by wjk** [comment]
@learn-more No, Allow edits from maintainers is still enabled as far as I can tell. Is there a problem?

**Comment by learn-more** [comment]
I was unable to push to this branch, so that I could commit it with a signed commit.

**Comment by wjk** [comment]
I've toggled the setting off and on again. Maybe that would help?

**Comment by HBelusca** [comment]
The BOM at the beginning of the file has ben removed.

**Pull request merged**
