### PR TITLE
[MMEBUDDY][MMIXER] Fix NDEBUG support

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Fix NDEBUG support, especially on Release builds.

## Proposed changes

- Remove unwanted value.
- Use add_compile_definitions().
- NDEBUG "depends" on DBG.

### CODE REVIEW

**Review by oleg-dubinskiy — COMMENTED** [review]
OK for the change itself, but I think it's better to make `SND_ERR` always printed (just place a `SND_ERR` part outside  of `!defined(NDEBUG)`, only in `#if DBG` condition), but keep the same behaviour for `SND_WARN` and `SND_TRACE`. Logically, it's more correct to always print an errors, unlike warnings and traces, as done in Wine, for example.
Also, seems we can to define `NDEBUG` in the header instead of CMake.
LGTM otherwise.

**Comment by SergeGautherie** [comment]
> I think it's better to [...]

I don't want to handle these changes (in this PR). Nonetheless, feel free to follow up.

**Review by oleg-dubinskiy — APPROVED** [review]
OK, it's no problem to handle them later, in a separate commit then. My suggestion seems to be logically another change, so approved.

**Comment by SergeGautherie** [comment]
> make `SND_ERR` always printed

Submitted as #7226.

> define `NDEBUG` in the header instead of CMake.

I am not interested in doing that.

**Pull request merged**
