### PR TITLE
[IMM32][SDK] Implement IME Soft Keyboard Type T1

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Provide IME Soft Keyboard Type T1.
JIRA issue: [CORE-19268](https://jira.reactos.org/browse/CORE-19268)

## Proposed changes

- Rename `version.rc` as `imm32.rc`.
- Add `resource.h` and `t1keys.h`.
- Add some resource bitmaps.
- Modify `<immdev.h>`.
- Implement Soft Keyboard Type T1.

## TODO

- [x] Do tests.

## Comparison
Press Ctrl+Alt+comma on FreeCJ2004.
Win2k3:
2k3

ReactOS (AFTER):
VirtualBox_ReactOS_21_11_2023_22_14_31

NOTE: There's a visual bug in `PatBlt` with negative values.

### CODE REVIEW

**Comment by katahiromz** [comment]
Cc @roytam1
Can you test this?

**Comment by roytam1** [comment]
> Cc @roytam1 and @reactos/lang-chinese
> Can you test this?

it displays soft keyboard without any text.
image

**Comment by katahiromz** [comment]
@roytam1 Where can I download Chinese IME that supports soft keyboard?

**Comment by roytam1** [comment]
> @roytam1 Where can I download Traditional Chinese IME that supports soft keyboard?

https://web.archive.org/web/20061208204431/http://input.foruto.com/download/Forum/freecj2004.exe

**Comment by katahiromz** [comment]
VirtualBox_ReactOS_21_11_2023_17_23_50
Thanks. I will investigate why the bitmap is not loaded.

**Comment by katahiromz** [comment]
VirtualBox_ReactOS_21_11_2023_18_46_12
Loading bitmaps is fixed. There is a font problem.

**Comment by katahiromz** [comment]
VirtualBox_ReactOS_21_11_2023_19_28_14
The font problem is fixed. The remainder is internal encoding.

**Comment by roytam1** [comment]
> Fixed!!!!

fix confirmed
image

**Comment by roytam1** [comment]
and notice that FreeCJ2004 can't open soft keyboard by clicking 3rd button from right on IME toolbar, with following log:

````
fixme:(/dll/win32/imm32/softkbd.c:1130) stub
(/win32ss/user/ntuser/window.c:2484) err: co_UserCreateWindowEx(SoftKBDClsC1): WM_CREATE message failed
(/win32ss/user/ntuser/window.c:2793) err: co_UserCreateWindowEx failed!
(/win32ss/user/ntuser/winpos.c:3526) err: NtUserSetWindowPos bad window handle!
````

**Pull request merged**
