### PR TITLE
[NTOSKRNL] Additions for IopValidateID().

### PR DESCRIPTION
**Pull request by HBelusca**
- Get rid of MAX_SEPARATORS_DEVICEID/INSTANCEID macros since their
  values are used only inside IopValidateID().
- Improve the DPRINTing by displaying which ID is being analyzed,
  displaying which ID is invalid, and displaying the list of all IDs.
- Make the for-loops more manageable by splitting the original single
  loop in two. This allows in particular to save the beginning of a new
  ID while analyzing each of its characters at the same time.
- Add comments to the code.
- Start implementing error logging as mentioned by Vadim in PR #341.

### CODE REVIEW

**Comment by HBelusca** [comment]
Cc @vgalnt too (I could not add you in the list of reviewers :) ).

**Comment by HBelusca** [comment]
@vgalnt : could you please test something for me: I would like to know how exactly the error logging is presented in the System error log, in particular which event source is used. (Take one or two different drivers you are developing and make them return some invalid bus IDs; Windows should then report that these drivers "reported invalid child ID".)

**Comment by gedmurphy** [comment]
So after all the discussion (115 comments) in the last PR where vgal originally implemented this function, you decided to completely rewrite the whole thing because you think your version is better than his?

I can't believe how rude that is. I'd be so angry if I were vgal

**Comment by HBelusca** [comment]
I don't know if you have looked at the patch, but it's not a rewrite, apart for the for-loop initialisation that has been splitted in two in order to have a "ThisId" pointer that allows to keep the beginning of the ID that is analysed, to be able to DPRINT it if there is a problem (and it makes the code a bit more transparent). Note however that the body of the for-loop is **exactly** the same.
The additions are: more detailed DPRINTs, the implementation of the "FIXME Logging". And the bug-fixing is adding the missing set-up of MaxSeparators in one case as well as resetting SeparatorsCount to zero everytime we look at one ID inside IDs multi-strings (when it's the case). These last two missing points made valid pnp IDs report as "invalid", just look e.g. at [this test log](https://build.reactos.org/builders/Test%20KVM/builds/19958/steps/test/logs/stdio) (search for the `IopValidateID:` lines).

**Comment by gedmurphy** [comment]
It looks like a pretty extensive rewrite to me.
If you think it was worth the rewrite, then I'm sure your version is indeed a better version, and that reactos will certainly benefit from it because you're a talented developer.
It's just that spending months discussing someone's patch, finally getting it merged, only to have it rewritten by a core developer .... it just feels wrong and against the ethos of PRs.

I dunno, maybe I'm taking the whole thing too seriously...

**Comment by binarymaster** [comment]
> I can't believe how rude that is. I'd be so angry if I were vgal

We are here to make ReactOS work better, also on the real hardware. There are different ways and approaches to do it.

It would be rude if Hermes commited this into `master` without making PR for review and discussion.

**Comment by ThFabba** [comment]
I decidedly have no opinion whatsoever on this function.

**Comment by learn-more** [comment]
So what are we gonna do with this?

**Comment by HBelusca** [comment]
Technically it's @vgalnt who can decide what to do with this.

**Pull request closed without merging**
