### PR TITLE
[NTGDI] Return the original weight from the font instead of the requested weight

### PR DESCRIPTION
**Pull request by learn-more**
JIRA issue: [CORE-17011](https://jira.reactos.org/browse/CORE-17011)

### CODE REVIEW

**Comment by learn-more** [comment]
hm...
https://reactos.org/testman/compare.php?ids=83440,83441
- gdi32:CreateFontIndirect 5 failures -> 7 failures
- gdi32:EnumFontFamilies -> 12 tests extra (no extra failures)
- gdi32:font -> 753 tests less, but also 33 failures less
- gdiplus:font -> 2 failures extra.
Will need to investigate a bit more I guess...

**Review by Doug-Lyons — COMMENTED** [review]
@learn-more can you please try using this "if"
```
    if (FontGDI->OriginalWeight != FW_DONTCARE &&
        ((TM->tmCharSet == CHINESEBIG5_CHARSET ||
          FontGDI->CharSet == CHINESEBIG5_CHARSET) &&
        (FontGDI->OriginalWeight != FW_NORMAL)))
```

**Review by katahiromz — COMMENTED** [review]
I can't say anything. Sorry.

**Comment by julenuri** [comment]
@Doug-Lyons I tested your option and still is failing. Sorry.

**Pull request closed without merging**
