### PR TITLE
[INCLUDE] Rename <ddk/imm.h> as <ddk/immdev.h>

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Standardization of system headers. Providing the compatible header to MS DDK `"immdev.h"`.
JIRA issue: [CORE-11700](https://jira.reactos.org/browse/CORE-11700)

## Proposed changes

- Rename `<ddk/imm.h>` as `<ddk/immdev.h>`.
- Delete `sdk/include/reactos/wine/imm.h` (this header is confusing and nonsense).
- Changes related to it.

### CODE REVIEW

**Comment by HBelusca** [comment]
Is it meant to be compatible with the MS WDK ?

**Comment by katahiromz** [comment]
Some MS DDK provides `"immdev.h"`. I mean to provide the compatible header to it.

**Comment by JoachimHenze** [comment]
Isn't imm32.dll Wine-synced code actually?

**Comment by katahiromz** [comment]
> Isn't imm32.dll Wine-synced code actually?

Nope. It's not Wine-synced.

**Pull request merged**
