### PR TITLE
[STOBJECT] Remove #if 0 and #endif in Volume_IsMute

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

Based on KRosUser's `volume.patch`.
The pair of `#if 0` and `#endif` was added in https://github.com/reactos/reactos/commit/180b6fb0834038cd558b2791f6afdbf6063ed30c .
This PR will remove it.

JIRA issue: [CORE-18583](https://jira.reactos.org/browse/CORE-18583)

## TODO

- [x] Do tests.

### CODE REVIEW

**Comment by HBelusca** [comment]
In the commit log, please:
- refer to the JIRA report;
- and mention that it is this commit that added the #if 0 : https://github.com/reactos/reactos/commit/180b6fb0834038cd558b2791f6afdbf6063ed30c

**Comment by HBelusca** [comment]
There is one bug in the re-enabled code, as well as a potentially problem elsewhere in the code:

- the bug: `mixerGetControlDetailsW((HMIXEROBJ) g_mixerId, ....` should read instead: `mixerGetLineControlsW((HMIXEROBJ)UlongToHandle(g_mixerId), ....`

- the potential problem(s):
 * the global `g_hMixer` is not initialized/used, except at one place where there's a comparison for it.
 * the `Volume_FindMixerControl` function contains some potential dead code;
 * i guess it would be better to directly use device handles instead of device ids (personal opionion).

It looks like this code in stobject/volume.cpp is still work-in-progress....

**Review by JoachimHenze — APPROVED** [review]

**Comment by learn-more** [comment]
@yagoulas do you remember why this was disabled?
Is it because the code is incomplete?

**Comment by JoachimHenze** [comment]
> @yagoulas do you remember why this was disabled? Is it because the code is incomplete?

The JIRA ticket reported assertions there in ancient builds, that have been stated/reported by KRosUser to no longer happen.

But the current patch fails to compile on MSVC x64, which is why I revoked my previous approval:
```
2023-11-14T10:54:38.2688183Z FAILED: dll/shellext/stobject/CMakeFiles/stobject.dir/volume.cpp.obj 
2023-11-14T10:54:38.3166035Z C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\HostX64\x64\cl.exe  /nologo /TP -DDBG=1 -DDLL_EXPORT_VERSION=0x502 -DMINGW_HAS_SECURE_API=1 -DUNICODE -DUSE_COMPILER_EXCEPTIONS -DWINVER=0x502 -D_AMD64_ -D_ATL_NO_EXCEPTIONS -D_CRT_NON_CONFORMING_SWPRINTFS -D_DLL -D_M_AMD64 -D_NEW_DELETE_OPERATORS_ -D_SEH_ENABLE_TRACE -D_SETUPAPI_VER=0x502 -D_UNICODE -D_WIN32_IE=0x600 -D_WIN32_WINDOWS=0x502 -D_WIN32_WINNT=0x502 -D_WIN64 -D__REACTOS__ -D__RELFILE__="&__FILE__[__FILE__[0] == '.' ? 6 : 25]" -D__RUNTIME_CHECKS__ -D__STDC__=1 -D__USE_CRTIMP -D__x86_64 -D__x86_64__ -ID:\a\reactos\reactos\build\dll\shellext\stobject -ID:\a\reactos\reactos\src\dll\shellext\stobject -ID:\a\reactos\reactos\src\sdk\include -ID:\a\reactos\reactos\src\sdk\include\psdk -ID:\a\reactos\reactos\src\sdk\include\dxsdk -ID:\a\reactos\reactos\build\sdk\include -ID:\a\reactos\reactos\build\sdk\include\psdk -ID:\a\reactos\reactos\build\sdk\include\dxsdk -ID:\a\reactos\reactos\build\sdk\include\ddk -ID:\a\reactos\reactos\build\sdk\include\reactos -ID:\a\reactos\reactos\build\sdk\include\reactos\mc -ID:\a\reactos\reactos\src\sdk\include\crt -ID:\a\reactos\reactos\src\sdk\include\ddk -ID:\a\reactos\reactos\src\sdk\include\ndk -ID:\a\reactos\reactos\src\sdk\include\reactos -ID:\a\reactos\reactos\src\sdk\include\reactos\libs -ID:\a\reactos\reactos\src\sdk\lib\atl -ID:\a\reactos\reactos\src\sdk\lib\pseh\include /Ob0 /Od /GF /Gy /X /Zl /GS- /FS /Zc:threadSafeInit- /d2FH4- /W3 /wd4244 /wd4290 /wd4800 /wd4200 /wd4214 /wd4018 /we4013 /we4020 /we4022 /we4028 /we4047 /we4090 /we4098 /we4113 /we4129 /we4133 /we4163 /we4229 /we4311 /we4312 /we4313 /we4477 /we4603 /we4700 /we4715 /we4716 /we4101 /we4189 /w14115 /Zi /RTC1 /GR- /EHs-c- /YuD:/a/reactos/reactos/build/dll/shellext/stobject/CMakeFiles/stobject.dir/cmake_pch.hxx /FpD:/a/reactos/reactos/build/dll/shellext/stobject/CMakeFiles/stobject.dir/./cmake_pch.cxx.pch /FID:/a/reactos/reactos/build/dll/shellext/stobject/CMakeFiles/stobject.dir/cmake_pch.hxx /showIncludes /Fodll\shellext\stobject\CMakeFiles\stobject.dir\volume.cpp.obj /Fddll\shellext\stobject\CMakeFiles\stobject.dir\ /FS -c D:\a\reactos\reactos\src\dll\shellext\stobject\volume.cpp
2023-11-14T10:54:38.3184461Z D:\a\reactos\reactos\src\dll\shellext\stobject\volume.cpp(125): error C4312: 'type cast': conversion from 'UINT' to 'HMIXEROBJ' of greater size
```

**Comment by katahiromz** [comment]
Fixed the type cast error by using `UlongToHandle`.

**Pull request merged**
