### PR TITLE
[WIN32SS][NTGDI] Delete mapping hacks

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Fix the hack of the world-to-page and device-to-world mappings.
JIRA issue: [CORE-16047](https://jira.reactos.org/browse/CORE-16047)
nothing-changed
It looks like nothing changed.

### CODE REVIEW

**Comment by HBelusca** [comment]
> It looks like nothing changed.

Run the ROS tests.

**Comment by jimtabor** [comment]
What about " Petzold's WhatSize test application" ?

**Comment by tkreuzer** [comment]
There is a reason why it was done the way it is: Windows sets up DC::dclevel.mxWorldToDevice as a 1:16 transformation. It uses L_TO_FX transformation type to calculate the device coordinates as fix point coordinates (see https://docs.microsoft.com/de-de/windows/desktop/api/wingdi/ns-wingdi-tagpointfx). Please don't change this. The bug is that the XFORM_FORMAT_LTOFX flag is not taken into account. https://reactos.org/wiki/Techwiki:Win32k/MATRIX

**Comment by katahiromz** [comment]
CLOSED.

**Pull request closed without merging**
