### PR TITLE
[USETUP] Shorten the Portuguese translation to fit on one line

### PR DESCRIPTION
**Pull request by zecarlos1957**
## Purpose

Shorten the Portuguese translation to fit on one line.

### CODE REVIEW

**Comment by zecarlos1957** [comment]
Before
Usetup-Before
After
Usetup-After

**Review by binarymaster — COMMENTED** [review]
Despite this minimal change fixes it, maybe it would be better to make it two lines without changing the alignment.

**Comment by JoachimHenze** [comment]
> Despite this minimal change fixes it, maybe it would be better to make it two lines without changing the alignment.

Or even better: Just slightly shrink the text length and keep all the current positions. That would be the superb solution.

**Comment by binarymaster** [comment]
> Just slightly shrink the text length

This might be not applicable, pt-PT is known for long sentences. But it's up to the translator.

**Comment by JoachimHenze** [comment]
It is always possible with some love. Especially for native speakers of the language.

**Comment by zecarlos1957** [comment]
OK. I see a good solution.
Done.

**Review by binarymaster — APPROVED** [review]

**Review by JoachimHenze — APPROVED** [review]

**Review by HBelusca — APPROVED** [review]

**Pull request merged**
