### PR TITLE
[TASKMGR] Fix orthographic error in Portuguese Brazilian (pt-BR) translation

### PR DESCRIPTION
**Pull request by 4nd3r50ncr**
Orthographic error.

### CODE REVIEW

**Review by JoachimHenze — APPROVED** [review]

**Review by binarymaster — CHANGES_REQUESTED** [review]
Hello,
Thanks for your interest in ReactOS!
We ask our contributors [to use their full name when committing](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations).
[Please amend your commit with your full name](https://stackoverflow.com/a/3042512), and update this PR.

To change this for future PR's, you can update it for globally (for the system):
```
git config --global user.name "Your Name"
git config --global user.email you@example.com
```

Or just for the current repository:
```
git config user.name "Your Name"
git config user.email you@example.com
```

Also please set up your GitHub account accordingly, so maintainers can use Squash & Merge button without getting the author field modified back to nickname by GitHub, it's done in two steps:

1. Set your full name in [GitHub profile settings](https://github.com/settings/profile) (it should match your `user.name` setting)
1. Uncheck `Keep my email addresses private` in [GitHub email settings](https://github.com/settings/emails)

Regards,

**Comment by 4nd3r50ncr** [comment]
Right!

**Comment by binarymaster** [comment]
You have set your name, but why PR closed?

image

**Comment by binarymaster** [comment]
image

@4nd3r50ncr last step: Uncheck Keep my email addresses private in [GitHub email settings](https://github.com/settings/emails).

**Comment by 4nd3r50ncr** [comment]
Just a question friend, why all these requirements to send a pull? Email is already released.

**Comment by binarymaster** [comment]
> why all these requirements to send a pull

Legal reasons, same as in projects like WineHQ, Coreboot, etc.

Our support team at https://chat.reactos.org can explain with more details.

**Review by binarymaster — APPROVED** [review]

**Pull request merged**
