### PR TITLE
[REACTOS] Remove PowerPC code remnants

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Complete @Extravert-ir's #3888..

Addendum to 6ef6fab.

## Proposed changes

- Remove now dead code.

## TODO

- [ ] Remove "all" `_M_PPC` and `__powerpc__`... (After you confirm that is wanted.)

### CODE REVIEW

**Comment by SergeGautherie** [comment]
While there, or as a follow-up, should some other architectures, like Alpha, Itanium, MIPS, ... be removed too?

**Comment by gonzoMD** [comment]
Serge. Victor had a PR open for some time and I am quite sure that you reviewed it because 
-a. You are mentioning it here
-b. You opened this PR immediately after he merged it

This stuff here could had happened directly in the origin PR.
I am very annoyed by all those "addendum to xyz" PR's directly after something got pushed.
Do you get horny to see a commit with your name inside the history? Well, there are more than enough unfixed and/or unimplemented things where you could take hands on.
It is a very bad behavior to 'fix' someone's code after PR has been finished. If you have something to suggest, do it in the PR which suggests the changes or stop at all.
If not, I would not be sad if you would get removed here and do this Kindergarten with other projects.

**Comment by SergeGautherie** [comment]
> Victor had a PR open for some time and I am quite sure that you reviewed it because
> -a. You are mentioning it here
> -b. You opened this PR immediately after he merged it

On one hand, I don't see how mentioning and opening implies previously reviewing.
On the other hand, the comment I did put there is more explicit about the latter.

> This stuff here could had happened directly in the origin PR.

Sure, but it did not.

> I am very annoyed by all those "addendum to xyz" PR's directly after something got pushed.

Sorry for your feelings, I am not sure how things could happen differently.

> Do you get horny to see a commit with your name inside the history? Well, there are more than enough unfixed and/or unimplemented things where you could take hands on.

?? What is wrong with doing a bit of both?

> It is a very bad behavior to 'fix' someone's code after PR has been finished. If you have something to suggest, do it in the PR which suggests the changes or stop at all.

I don't know about behavior, but it seems impossible to fix a commit before it is pushed...
I am 100% sure that I did suggest to make the previous PR more consistent.
What I cannot understand is why you blame me for trying to further fix things, rather than commit author (and official reviewers) for pushing a still inconsistent/incomplete PR?

> If not, I would not be sad if you would get removed here and do this Kindergarten with other projects.

?? Yeah, I would then assume you are another of those devs who "gets horny to see inconsistent code being committed to the repository then staying as is for who knows how long"...

**Comment by Extravert-ir** [comment]
Superseded by e372f2b19b6325ce2eaefb750ff375cfbc4fdaba

**Comment by SergeGautherie** [comment]
> Superseded by [e372f2b](https://github.com/reactos/reactos/commit/e372f2b19b6325ce2eaefb750ff375cfbc4fdaba)

Not really: your commit hijacked my first one only.
What about my second one and its related TODO?

**Comment by Extravert-ir** [comment]
The current state is fine, I don't want to remove any more code

**Pull request closed without merging**
