### PR TITLE
[IP] Unlock Connection when TCPAllocatePort() fails

### PR DESCRIPTION
**Pull request by SergeGautherie**
Addendum to 874d317 (0.4.15-dev-5707, #5074).
JIRA issue: [CORE-18371](https://jira.reactos.org/browse/CORE-18371)

### CODE REVIEW

**Comment by binarymaster** [comment]
Is this a bugfix or enhancement? It's not clear from description.

Also, how can you reproduce or confirm the correctness of the change?

**Comment by julenuri** [comment]
Hi @SergeGautherie:
You are missing a valid email (under Git and under your Github) to be valid. Please, [amend](https://reactos.org/wiki/ReactOS_Git_For_Dummies#Amending_your_commit_with_name.2FE-mail) this. Thanks you really much.

Rules for contributing:
https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations
https://github.com/reactos/reactos/blob/master/PULL_REQUEST_MANAGEMENT.md

**Comment by SergeGautherie** [comment]
> Is this a bugfix or enhancement? It's not clear from description.

Bugfix (as in regression): guilty commit added new `return`s but missed related cleanup.

> Also, how can you reproduce or confirm the correctness of the change?

Reproduce: using a narrow range should help. See PR 4958 about where to change that setting.
Confirm: all existing `return`s already had this cleanup.

**Comment by binarymaster** [comment]
> Confirm: all existing `return`s already had this cleanup.

I would not be so sure, since the referenced PR has been reviewed and approved by several people, how this problem could have been missed?

By confirming I meant a practical test or something, like what symptoms are.

**Comment by binarymaster** [comment]
Cc also @Doug-Lyons @KRosUser2 @GGLinnk for review.

**Review by learn-more — APPROVED** [review]

**Review by Doug-Lyons — APPROVED** [review]
This appears to be correct to me. Thanks.

**Review by GGLinnk — APPROVED** [review]

**Review by ThFabba — APPROVED** [review]

**Review by KRosUser2 — APPROVED** [review]
Lgtm

**Review by binarymaster — CHANGES_REQUESTED** [review]
Ok I think this PR has enough approvals now, but this is blocking me from merging it:

image

In your GitHub [e-mail settings](https://github.com/settings/emails) please select a suitable "Primary email address" that will be applied to your commits on merge, and then uncheck the checkbox "Keep my email addresses private".

See https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations

**Review by HBelusca — APPROVED** [review]

**Comment by ThFabba** [comment]
Merged as https://github.com/reactos/reactos/commit/2010a5b8d915beebd64c68cb568b03c29ab64d75
Please check the `Allow edits and access to secrets by maintainers` option and/or update your GitHub settings to a usable email to have PRs show as properly merged.

**Comment by SergeGautherie** [comment]
> See https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations

Yes, I'll look into the new rules, though I assume nothing has really changed since my comments on the related PR.

> Please check the `Allow edits and access to secrets by maintainers` option and/or update your GitHub settings to a usable email to have PRs show as properly merged.

Thanks for merging this PR!
Noted, though that other option would not be my first choice either.
Closed PRs are acceptable by me, for the time being.

**Comment by learn-more** [comment]
> Closed PRs are acceptable by me, for the time being.

They add extra work for our volunteers.

**Pull request closed without merging**
