### PR TITLE
ru calculator translation update

### PR DESCRIPTION
**Pull request by kloun**

### CODE REVIEW

**Comment by learn-more** [comment]
Please amend your commit with your real name instead of 'kloun'

**Comment by kloun** [comment]
How to do it?

**Comment by binarymaster** [comment]
Try this:
```sh
git commit --amend --author "Andrey Bolkonsky <andrey0bolkonsky@gmail.com>" --no-edit
git push -f
```

**Comment by binarymaster** [comment]
Also you can permanently change it:
```bash
git config --global user.name "Andrey Bolkonsky"
git config --global user.email andrey0bolkonsky@gmail.com
git commit --amend --reset-author
git push -f
```

**Comment by kloun** [comment]
Done.

**Pull request merged**
