### PR TITLE
[NTOS:INBV] Modern boot screen

### PR DESCRIPTION
**Pull request by feel-the-dz3n**
JIRA issue: maybe [CORE-9662](https://jira.reactos.org/browse/CORE-9662)

Preview:
gif
(https://raw.githubusercontent.com/feel-the-dz3n/i-love-github/master/ros-final-bootscreen.gif)

### CODE REVIEW

**Comment by Extravert-ir** [comment]
Cool. I suggest using a monochrome logo so nobody can notice a low color depth.
And it looks more modern these days)

**Comment by binarymaster** [comment]
> I suggest using a monochrome logo so nobody can notice a low color depth

How about the bottom rotation bar? I dunno how it would like with a monochrome logo.

**Comment by HBelusca** [comment]
> Cool. I suggest using a monochrome logo so nobody can notice a low color depth.
> And it looks more modern these days)
And more shitty too.

**Comment by feel-the-dz3n** [comment]
> Cool. I suggest using a monochrome logo so nobody can notice a low color depth.
> And it looks more modern these days)

It's mainstream, so I'll keep official:tm: logo, which even with bad color depth looks attractive (especially for advanced users 😄)

**Comment by feel-the-dz3n** [comment]
New rotating line:
gif

The previous one:
gif

**Comment by katahiromz** [comment]
I would choose the previous one.

**Comment by binarymaster** [comment]
I don't like new rotation bar, it's barely noticeable, and it doesn't have the nostalgic look and feel of Win 9x. :roll_eyes:

**Comment by feel-the-dz3n** [comment]
> I don't like new rotation bar, it's barely noticeable, and it doesn't have the nostalgic look and feel of Win 9x. 🙄

why do we need that look and feel?

**Comment by binarymaster** [comment]
> why do we need that look and feel?

It's more noticeable and recognizable by people.

**Comment by feel-the-dz3n** [comment]
Well, I gonna post messages in Mattermost and Telegram chats and ask people what they prefer more, 'cuz I still prefer modern look, so people will choose.

**Comment by feel-the-dz3n** [comment]
According to all comments I received in chats, here is the final one.
gif
P.S.: Modern rotation line - won
image
image

**Comment by oleg-dubinskiy** [comment]
I don't know about you, but personally I prefer the boot screen from Getequ, which is more like that in Win2k3. He included it in his builds with NT6+ APIs. Can it be considered as an alternative?

**Comment by feel-the-dz3n** [comment]
> I don't know about you, but personally I prefer the boot screen from Getequ, which is more like that in Win2k3. He included it in his builds with NT6+ APIs. Can it be considered as an alternative?

i didn't even know about existing of such boot screen

**Comment by oleg-dubinskiy** [comment]
How it looks:
изображение
And it turns out that it's x86corez's work, which Getequ included in his builds.

**Comment by feel-the-dz3n** [comment]
> How it looks:
> изображение
> And it turns out that it's x86corez's work, which Getequ included in his builds.

nice but how it can be alternative?

**Comment by HBelusca** [comment]
> nice but how it can be alternative?

What do you mean? How can we enable this alternative? or...?

**Comment by oleg-dubinskiy** [comment]
> nice but how it can be alternative?
Why it can't? It's very good candidate on my opinion. Let it differs from the current boot screen not so much, but nevertheless it looks more like in Windows.

**Comment by HBelusca** [comment]
At line 54 in https://git.reactos.org/?p=reactos.git;a=blob;f=ntoskrnl/inbv/inbv.c;h=c1ece52461ebfeb8d1c20b075a8cef907661b92c;hb=HEAD#l50, change "RB_PROGRESS_BAR" to "RB_SQUARE_CELLS" and recompile.

**Comment by feel-the-dz3n** [comment]
Closed because it takes MUCH more time to boot

**Comment by feel-the-dz3n** [comment]
Nobody noticed "Contirubutors"

**Comment by blackcrack** [comment]
pity .. i would like also a new with more possible bootscreen..
there i stay behind you ..
(by the other.. was dump.. or you be easy really young and should be become easy more growing up and experience .. (You knew the is not going well..) how ever.. also pity )

best regards
Blacky

**Comment by feel-the-dz3n** [comment]
https://github.com/reactos/reactos/pull/2860

**Pull request closed without merging**
