### PR TITLE
This layout is much better and confortable for eyes +add chat link

### PR DESCRIPTION
**Pull request by jeditobe**
## Purpose

This layout is much better and confortable for eyes +add chat link

### CODE REVIEW

**Comment by HBelusca** [comment]
It is not, because when one reads the contents of the .md file as a text file, all these links are now on the same line, which makes reading.... harder!!

**Comment by binarymaster** [comment]
Multi-line version is better IMO.

**Comment by Mouvedia** [comment]
Try
```
[Website](https://reactos.org) &bull; 
[Official chat](https://chat.reactos.org) &bull; 
[Wiki](https://reactos.org/wiki) &bull; 
[Forum](https://reactos.org/forum) &bull; 
[JIRA Bug Tracker](https://jira.reactos.org/issues) &bull; 
[ReactOS Git mirror](https://git.reactos.org) &bull; 
[Testman](https://reactos.org/testman/)
```

Unless you end a line with 2 spaces, you won't have a \n. Problem solved.

**Comment by ThFabba** [comment]
Now, excuse my ignorance but how do I even preview this?

**Comment by gigaherz** [comment]
Go to "files", and click on "view file", should point you to, 
https://github.com/reactos/reactos/blob/4025a798a65245fd38f65f3dea193e4537ed828e/README.md

**Comment by gigaherz** [comment]
Alternatively, you can click on "display rich diff, to preview the differences inline -- 
image
(yes I just discovered that)

**Comment by Mouvedia** [comment]
> Now, excuse my ignorance but how do I even preview this?

@ThFabba Files changed > edit README.md > edit > preview

**Comment by BenNottelling** [comment]
I quite like what @Mouvedia has suggested

**Comment by jeditobe** [comment]
adopted the idea of Mouvedia

**Comment by Mouvedia** [comment]
BTW the release tag is outdated.

**Comment by jeditobe** [comment]
I do not see any release tag any where in my diff. Release tag may be updated by different commit

**Comment by Mouvedia** [comment]
@jeditobe the release _badge_ is outdated.
It should be 0.4.11 with a link to https://reactos.org/project-news/reactos-0411-released

**Comment by jeditobe** [comment]
There is another PR for that purpose

https://github.com/reactos/reactos/pull/1418

**Comment by MailYouLater** [comment]
Commits should probably be squashed.

**Pull request merged**
