### PR TITLE
Linux Buildbot test for mkhive

### PR DESCRIPTION
**Pull request by HBelusca**

### CODE REVIEW

**Comment by HBelusca** [comment]
So WHY THE HELL IN GCC Linux, "*ptr++ = tolower(*ptr);" is understood as "I take the lowercase of *ptr and I put it in *(ptr++)", while everywhere else it's "I put it in (*ptr), then ptr++" ??

**Comment by blackcrack** [comment]
it's not long ago where was linux one of the best systems.. behind Unix but for free..
make it not on , on a system, make it on the "does and the code" because the Ordering system 
make it only what the human say .. so, can you say, "why the hack do anyone it in this way!"
Linux is the "Bro' in GPL" and helps many peoples over a time , with M$ and his politic.
Not the Linux it is, the Peoples who make the bullschit.. in code.. ;)
best regards
Blacky

**Comment by ThFabba** [comment]
Hermès, it's because that's Undefined Behavior. You doing `ptr++` means you can't use `ptr` again before the next sequence point, and a `=` is not a sequence point.
blackcrack, stop it with the useless ranting comments.

**Comment by blackcrack** [comment]
@HBelusca 
ohh, why thump down ? :flushed:

**Pull request merged**
