### PR TITLE
[WINMM] MMIO_ParseExtA: Don't parse extension if the file name is empty

### PR DESCRIPTION
**Pull request by TAN-Gaming**
## Purpose

JIRA issue: [CORE-18810](https://jira.reactos.org/browse/CORE-18810)

### CODE REVIEW

**Comment by JoachimHenze** [comment]
Can you send this upstream?

**Comment by KRosUser2** [comment]
Tested with build artifact and correctly fixes the regression.

**Review by KRosUser2 — APPROVED** [review]

**Comment by TAN-Gaming** [comment]
> Can you send this upstream?

Dunno how to do that.

**Review by learn-more — APPROVED** [review]

**Comment by gonzoMD** [comment]
> > Can you send this upstream?
> 
> Dunno how to do that. Where should the patch goes, WineHq or Wine-staging?

Winehq, but dont refer to ReactOS when you send it.

**Comment by SergeGautherie** [comment]
Why not import WINE code, instead of adding a ROS diff?

**Comment by KRosUser2** [comment]
Serge, do you see a similar fix in current Wine master ?

**Review by Extravert-ir — CHANGES_REQUESTED** [review]
This is already fixed in Wine. Please, either import their commits win winmm, or we may merge this change as-is, but leave a comment about this `#ifdef __REACTOS__` block not needed to be synced in future

**Comment by TAN-Gaming** [comment]
superseded by #5050

**Pull request closed without merging**
