### PR TITLE
[GITHUB:WORKFLOWS] Restore 2 features, from AppVeyor/Travis

### PR DESCRIPTION
**Pull request by SergeGautherie**
Addendum to a0283ecea3c10d081320a6fab0821a03cda6b7f8.

### CODE REVIEW

**Comment by Extravert-ir** [comment]
What does msvc change do?
You pass -k 0 to ninja, but what's the default value? Why everything works so far?

**Comment by SergeGautherie** [comment]
> What does msvc change do?

It removes lines like
`[1/13215] Building C object sdk\lib\wdmguid\CMakeFiles\wdmguid.dir\wdmguid.c.obj`
See
https://git.reactos.org/?p=reactos.git;a=commit;h=b6f2c9fc5c608749d0404c9e20a4fa7abc704e98

> You pass -k 0 to ninja, but what's the default value?

Default is `1` (first error).
See
https://git.reactos.org/?p=reactos.git;a=commit;h=496b1cb9514698d819ff554fa6d03b43296490ed
https://git.reactos.org/?p=reactos.git;a=commit;h=cf8c9bc312a4527efcb5b0771d29533ddefc8cdf

> Why everything works so far?

I am not sure what you are asking about?

**Comment by learn-more** [comment]
He is asking to elaborate on your changes.
If there is a PR with just 'Fixes', 'Features' or a comment like that,
it means someone first has to spend time reverse-engineering the code to see what the intend could be,
then review the code based on that.

**Comment by SergeGautherie** [comment]
> He is asking to elaborate on your changes.

I tried to.
I simply don't understand how these features can be working for him: they obviously regressed (for me) since he removed their code.

> If there is a PR with just 'Fixes', 'Features' or a comment like that,
> it means someone first has to spend time reverse-engineering the code to see what the intend could be,
> then review the code based on that.

Wait a minute: so Victor did remove these 2 features without understanding them, and now I get the blame for lack of explanation on commits initially done by others? That is not right!

>  closed

Why?

**Pull request closed without merging**
