### PR TITLE
[FONTS][SETUP][BOOTDATA] Add Lucida Console font

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Add "Lucida Console" fonts.
JIRA issue: [CORE-16264](https://jira.reactos.org/browse/CORE-16264)

- Add "Lucida Console" font by duplicating "DejaVu Sans Mono" font and renaming it.
- Delete some "Lucida Console" font substitutes.
- Add LICENSE file.

I used FontForge to rename it. Its family name is "Lucida Console". Its display name is "Lucida Console". Its font filename is lucon.ttf. The Underline Positions are hacked by adding an integer value for workaround of FontForge's bug.

### CODE REVIEW

**Comment by katahiromz** [comment]
Copyright (c) 2003 by Bitstream, Inc. All Rights Reserved.
DejaVu changes are in public domain
Copyright (c) 2019 Katayama Hirofumi MZ.

License: Bitstream Vera Fonts Copyright

**Comment by katahiromz** [comment]
lucida

**Comment by katahiromz** [comment]
Lucida-Console-vs-DejaVu-Sans-Mono

**Comment by katahiromz** [comment]
Lucida Console vs DejaVu Sans Mono:
Lucida-Console-vs-DejaVu-Sans-Mono

**Comment by SSJ9899TDylan** [comment]
God Damn it!



Sent from myMail for iOS


Sunday, 4 August 2019, 4:39 pm +1000 from notifications@github.com  <notifications@github.com>:

**Comment by BenNottelling** [comment]
@SSJ9899TDylan what the fuck is your problem?

**Pull request merged**
