### PR TITLE
[MSPAINT] Optimize images for help docs

### PR DESCRIPTION
**Pull request by ace-dent**
## Purpose

- Lossless optimization of png images using `pngslim`. Saves some bytes.

## Proposed changes

- As above. No code impact.

### CODE REVIEW

**Review by katahiromz — APPROVED** [review]

**Review by JoachimHenze — APPROVED** [review]
Nice contribution!
I would very much welcome similar contributions to other modules that may also use png in a future PR.

**Comment by HBelusca** [comment]
Funny "disclaimer" from the pngslim readme:
> WARNING: Although this software produces fully compliant PNG images, a
minority of image editors, viewers and certain mobile phones contain bugs
which may cause problems displaying these optimized images.

**Comment by ace-dent** [comment]
Thanks @katahiromz @JoachimHenze and @HBelusca for your review and comments.
Regarding the 'warning'... Yes, all pngs display fine on Windows and therefore *should* display on ReactOS.
Really the issue was from early 2000's and on pre-smart phone devices. Some software still has issues with grayscale pngs.

If you are still concerned, I can re-optimize and just use the RGBA type- avoiding paletted or 'indexed' images- to ensure the highest compatibility at the cost of compression. However, ideally ReactOS should fully support decoding this common format.

**Comment by binarymaster** [comment]
Hi @ace-dent! Any chance to set a full name in your [profile settings](https://github.com/settings/profile)?

Since you have already specified it in the commit author field, I hope it would be not a problem. This would allow easier PR merging.

**Comment by ace-dent** [comment]
Thanks @binarymaster - done.
However, your guidelines for artwork submissions says that a nickname is acceptable...

**Comment by binarymaster** [comment]
> However, your guidelines for artwork submissions says that a nickname is acceptable...

Yes this is correct, it's not required for artwork, however I asked this to be sure that author field in commit is consistent with profile, i.e. :

> Since you have already specified it in the commit author field

**Review by binarymaster — APPROVED** [review]

**Pull request merged**
