### PR TITLE
[TASKMGR] Add version info

### PR DESCRIPTION
**Pull request by TAN-Gaming**
## Proposed changes
- Add task manager version info

### CODE REVIEW

**Review by HBelusca — APPROVED** [review]

**Comment by gingerlol334** [comment]
this one has an operating system that shit on VMware because after installing the drivers, the Blue screen does not start and it is not olestur I would recommend someone Better is normal Windows XP or something, not that shit, so please fix the problem with the fifth gateway, the possibility of installing drivers Vmware tools the topic of the package system is the shit that does not allow you to install the drivers it hangs the blue screen after installing the drivers is just rubbish and not about SM I do not recommend reactos to anyone, this is shit and not the operation system.

**Comment by gingerlol334** [comment]
fuck off of the reactos!

**Comment by HBelusca** [comment]
@gingerlol334 And you, you definitively need to fix your temper, your vocabulary and your orthography.

**Comment by TAN-Gaming** [comment]
> this one has an operating system that shit on VMware because after installing the drivers, the Blue screen does not start and it is not olestur I would recommend someone Better is normal Windows XP or something, not that shit, so please fix the problem with the fifth gateway, the possibility of installing drivers Vmware tools the topic of the package system is the shit that does not allow you to install the drivers it hangs the blue screen after installing the drivers is just rubbish and not about SM I do not recommend reactos to anyone, this is shit and not the operation system.

Try latest build, not an old one.

**Comment by TAN-Gaming** [comment]
@gingerlol334 Try latest build, not an old one. I can play old Windows games just fine on VMs and the live cd works fine on my old PC as well.

**Pull request merged**
