### PR TITLE
[CPL][DESK] Don't enable 'Apply' button initially

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
JIRA issue: [CORE-16280](https://jira.reactos.org/browse/CORE-16280)
BEFORE:
before
AFTER:
after

- Add `BOOL InChangingUI` member to `DATA` structure.
- Set `pData->InChangingUI` to `TRUE` and `FALSE` in `OnInitDialog`.
- In case of `IDC_SCREENS_TIMEDELAY` and `IDC_SCREENS_LIST`, check notification code and `InChangingUI` member.

### CODE REVIEW

**Comment by Fraizeraust** [comment]
This looks more like a hack. And I assume you weren't aware of #1795 PR (which is also a temporary hack in its own), right?

**Comment by katahiromz** [comment]
I think this is a straightforward fix.
`EN_CHANGE` generation in `OnInitDialog` is inevitable.

**Comment by Fraizeraust** [comment]
You actually misunderstood. The culprit here is the edit box control receiving EN_CHANGE/EN_UPDATE notification codes in a bad way. I wrote a comment in the ticket specifically explaining the occurrence of the regression.

UNLESS you did some further tests confirming that EN_CHANGE/EN_UPDATE are received unconditionally on Windows XP/Server 2003.

**Comment by katahiromz** [comment]
You are correct. Closed.
you-are-correct

**Pull request closed without merging**
