### PR TITLE
[SDK][TOOLS] Add do_code_format.sh to sdk/tools

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

JIRA issue: N/A

### CODE REVIEW

**Comment by HBelusca** [comment]
Cc @Extravert-ir

**Comment by Extravert-ir** [comment]
I think this should be done in cmake

**Comment by katahiromz** [comment]
Closed.

**Comment by katahiromz** [comment]
Imperfect is better than nothing.

Reopened.

**Pull request merged**
