### PR TITLE
[SHELL32] Allow to hide My Computer icon from desktop

### PR DESCRIPTION
**Pull request by binarymaster**
Related issues: [CORE-8427](https://jira.reactos.org/browse/CORE-8427), [CORE-14060](https://jira.reactos.org/browse/CORE-14060) - fixes last one

Cc @yagoulas

### CODE REVIEW

**Comment by binarymaster** [comment]
According to [this comment](https://github.com/reactos/reactos/blob/57aa1f1fc6744733020e800e45ffa86481337179/dll/win32/shell32/folders/CDesktopFolder.cpp#L39):
```
The CDesktopViewCallback is responsible for filtering
it from the view by handling the IncludeObject query to return S_FALSE. The enumerator
always shows My Computer.
```
This PR should be re-implemented properly.

**Comment by HBelusca** [comment]
The question is also valid for "My Documents": If you choose to hide it, does it still display in the address bar tree or not?

**Comment by binarymaster** [comment]
@HBelusca "My Documents" disappears too, in both places.

**Comment by HBelusca** [comment]
And is it what happens on real Windows?

**Comment by binarymaster** [comment]
On real Windows it only hides icons from desktop:

image

**Comment by HBelusca** [comment]
Ah ok, so the My-Documents case hiding code that is after your modification, needs fixing too.

**Comment by yagoulas** [comment]
> This PR should be re-implemented properly.
And will be merged then :P

I am not sure what problems this can cause to applications. My computer is one of the most important items ofthe shell namespace. Considering that we don't even have the ability to hide it with the gui I don't see any reason to merge these changes.

**Comment by sanchaez** [comment]
A general note: I'd prefer a new pull request if you need to start over.

**Comment by binarymaster** [comment]
PRs can be force-pushed instead opening new ones, but for now I have no idea how to implement this right, so closing.

**Comment by HBelusca** [comment]
Simple: you play on your local copy (including rebasing), then you `git push --force-with-lease` . It will force-push your changes back to the github fork, and the PR will automatically update.

**Comment by sanchaez** [comment]
@HBelusca I guess he meant the actual topic of this pull request 😄

**Pull request closed without merging**
