### PR TITLE
[TASKMGR] Pixel-perfection for left border CORE-18061

### PR DESCRIPTION
**Pull request by JoachimHenze**
This makes the left border 2 pixels smaller in
IDD_APPLICATION_PAGE and IDD_PROCESS_PAGE.

The goal is:
- matching XPSP3 taskmgr to 100% on left border.
- leaving more room for the content of the 2 SysListView32.
- better aligning left border of IDD_APPLICATION_PAGE and IDD_PROCESS_PAGE to IDD_PERFORMANCE_PAGE upon tab-switching

see before-and-after-pics and vid in:
JIRA issue: [CORE-18061](https://jira.reactos.org/browse/CORE-18061)

### CODE REVIEW

**Comment by HBelusca** [comment]
Please sure it doesn't collide with stuff from https://github.com/reactos/reactos/pull/4168/files#diff-10e3856c6a100b1b247a930d75c29a3fe5beafefa5ae1ae9e013cb7e4a1e4e33

**Comment by JoachimHenze** [comment]
I would prefer to merge the two commits in unsquashed form, since they are not really related.
Work done. Fine to review.

**Comment by JoachimHenze** [comment]
> Please sure it doesn't collide with stuff from https://github.com/reactos/reactos/pull/4168/files#diff-10e3856c6a100b1b247a930d75c29a3fe5beafefa5ae1ae9e013cb7e4a1e4e33

That's super close, but luckily it shouldn't collide. We touched lines extremely close next to each other, direct neighbors even. But we did not touch the same. I am fine with merging this in the order you'd prefer.

**Review by katahiromz — APPROVED** [review]
Using Resource Hacker, I can confirm the validness of this PR.

**Review by HBelusca — APPROVED** [review]

**Pull request merged**
