### PR TITLE
[MYCOMPUT] This is a shell extension, so move it where it belongs to

### PR DESCRIPTION
**Pull request by gonzoMD**
Nothing more to say

### CODE REVIEW

**Comment by HBelusca** [comment]
I dont' know... it's used in a hardcoded manner by shell32 so far as I can see...

**Comment by gonzoMD** [comment]
Isn't it the dll that represents the my computer folder?

**Comment by learn-more** [comment]
It is a resource-only dll, not a shell extension?

**Comment by Prince-Kassad** [comment]
> Isn't it the dll that represents the my computer folder?

lol no, it's used by the Computer Management snapin (compmgmt.msc) on XP/2003.

**Comment by gonzoMD** [comment]
OK. Then it's fine where it is. I was misleaded by mydocs.dll.

**Pull request closed without merging**
