### PR TITLE
[ROSSYM] Fix "seeking to" typo

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Follow-up to PR 1767.

NB:
['seek to'](https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=seek+to) cases would be for another time...

### CODE REVIEW

**Comment by SergeGautherie** [comment]
> 'seek to'

@HBelusca, one for you:
```
boot/freeldr/freeldr/lib/fs/ntfs.c
 948         FileSystemError("Failed to seek to Master File Table record.");
```

**Comment by HBelusca** [comment]
@SergeGautherie : just add the freeldr one in the PR.

**Comment by SergeGautherie** [comment]
Added.

**Comment by learn-more** [comment]
What is wrong with 'seek to' ?

**Comment by HBelusca** [comment]
The construction "to seek to (do sthg)" means "to try to do something":
https://www.macmillandictionary.com/dictionary/british/seek-to-do-something
https://dictionary.cambridge.org/dictionary/english/seek
https://www.oxfordlearnersdictionaries.com/definition/american_english/seek (point 4)
https://www.collinsdictionary.com/dictionary/english/seek (point 5)

**Comment by ThFabba** [comment]
Programming language does not always align with regular grammar. "Seek" in the sense of "move the file pointer" is not found in the dictionary, but is always used with "to" -- "to seek to a position" does not mean "search", so changing it to "to seek something" changes the meaning to something less accurate.
These changes make the messages less obvious to a C programmer (and rsym is a tool for those, not regular users). Messages aimed at regular users should arguably not use the technical term "seek" at all.

**Pull request closed without merging**
