### PR TITLE
[USER32] Fix CascadeWindows()

### PR DESCRIPTION
**Pull request by KRosUser**
## Purpose

- Current implementation of CascadeWindows is broken, the sequence of Z-Order is not correct when finally rendered

JIRA issue: [CORE-18343](https://jira.reactos.org/browse/CORE-18343)

## Proposed changes

- The root cause is about the use of NtUserEndDeferWindowPosEx(hDWP, TRUE) which does an ASYNC processing of the defered positionning. 

## Before

image

## After

TBD

### CODE REVIEW

**Comment by KRosUser** [comment]
@katahiromz : For review, please.

**Comment by katahiromz** [comment]
Investigating by API Monitor:
無題
Looks like correct.

You can also fix `TileWindows` function.

**Comment by KRosUser** [comment]
Fix for TileWindow added, even if less functional impact (as no "Z order challenge" in tiles). But at least it makes design consistent and deterministic.
Thanks !

@katahiromz : Would you approve the PR as such ?

**Review by katahiromz — APPROVED** [review]

**Comment by HBelusca** [comment]
> Investigating by API Monitor: [...]

As you can see, you haven't told it to display the actual NtUser*** functions, so you don't know whether NtUserEndDeferWindowPosEx was actually directly called, and with which parameters.

**Comment by HBelusca** [comment]
> The root cause is about the use of NtUserEndDeferWindowPosEx(hDWP, TRUE) which does an ASYNC processing of the defered positionning. Need to have a SYNC processing to ensure sequence is preserved.

This does *not* explain why an ASYNC does not preserve the windows sequence, which seems to be the actual root of the problem...

**Comment by KRosUser** [comment]
> > Investigating by API Monitor: [...]
> 
> As you can see, you haven't told it to display the actual NtUser*** functions, so you don't know whether NtUserEndDeferWindowPosEx was actually directly called, and with which parameters.

**Comment by KRosUser** [comment]
Sorry, my mistake, I closed the PR, while I wanted to post a comment... reopened

**Comment by KRosUser** [comment]
> > The root cause is about the use of NtUserEndDeferWindowPosEx(hDWP, TRUE) which does an ASYNC processing of the defered positionning. Need to have a SYNC processing to ensure sequence is preserved.
> 
> This does _not_ explain why an ASYNC does not preserve the windows sequence, which seems to be the actual root of the problem...

I do agree on the fact that something has to be investigated, but design with a SYNC update is totally fine here. Maybe should we need a separate PR & ticket ? Or would you prefer to keep the whole stuff open until someone make it clear about NtUserEndDeferWindowPosEx ? (to be honest, this is beyond my skills)

**Comment by learn-more** [comment]
> > > The root cause is about the use of NtUserEndDeferWindowPosEx(hDWP, TRUE) which does an ASYNC processing of the defered positionning. Need to have a SYNC processing to ensure sequence is preserved.
> > 
> > 
> > This does _not_ explain why an ASYNC does not preserve the windows sequence, which seems to be the actual root of the problem...
> 
> I do agree on the fact that something has to be investigated, but design with a SYNC update is totally fine here. Maybe should we need a separate PR & ticket ? Or would you prefer to keep the whole stuff open until someone make it clear about NtUserEndDeferWindowPosEx ? (to be honest, this is beyond my skills)
> 
> @HBelusca : Would you accept to go on with this specific PR as is ?

Why is a SYNC update totally fine here?
That it appears to work does not mean it is correct.

**Comment by KRosUser** [comment]
> > > > The root cause is about the use of NtUserEndDeferWindowPosEx(hDWP, TRUE) which does an ASYNC processing of the defered positionning. Need to have a SYNC processing to ensure sequence is preserved.
> > > 
> > > 
> > > This does _not_ explain why an ASYNC does not preserve the windows sequence, which seems to be the actual root of the problem...
> > 
> > 
> > I do agree on the fact that something has to be investigated, but design with a SYNC update is totally fine here. Maybe should we need a separate PR & ticket ? Or would you prefer to keep the whole stuff open until someone make it clear about NtUserEndDeferWindowPosEx ? (to be honest, this is beyond my skills)
> > @HBelusca : Would you accept to go on with this specific PR as is ?
> 
> Why is a SYNC update totally fine here? That it appears to work does not mean it is correct.

Yes something may be wrong in the lower level NtUserEndDeferWindowPosEx. But alternatively, why would NtUserEndDeferWindowPosEx be needed here and not the standard EndDeferWindowPos which finally works totally fine ?

**Comment by HBelusca** [comment]
> But alternatively, why would NtUserEndDeferWindowPosEx be needed here and not the standard EndDeferWindowPos which finally works totally fine ?

Precisely in order *not* to hang the caller of the Cascade/TileWindows functions, by doing an ASYNC window positioning (by specifying the flag to the NtUserEndDeferWindowPosEx function. The standard EndDeferWindowPos doesn't do ASYNC repositioning.)

**Comment by KRosUser** [comment]
> > But alternatively, why would NtUserEndDeferWindowPosEx be needed here and not the standard EndDeferWindowPos which finally works totally fine ?
> 
> Precisely in order _not_ to hang the caller of the Cascade/TileWindows functions, by doing an ASYNC window positioning (by specifying the flag to the NtUserEndDeferWindowPosEx function. The standard EndDeferWindowPos doesn't do ASYNC repositioning.)
> 
> And if a function X (here, the Cascade/TileWindows) calls a buggy function Y that doesn't fully do what it's supposed to do, you don't "fix" X. Instead you have to fix Y .

OK, got it. In this case, I have no clue at where the problem lies with WM_ASYNC_SETWINDOWPOS. Should I close this PR and leave the floor to somebody else ? Or does anyone has a clue to guide me ?

**Comment by KRosUser** [comment]
Second thoughts on the topic looking at how CascadeWindow is built, it's a sequence of positionning with HWND_TOP with no relative Z-Order between each windows

As a conseqence, i'm not even sure that using a ASYNC way to manage the processing of defered Windows position would work, as we would loose the guarantee of the sequence, isn't it ?

Furthermore : Looking at @katahiromz capture of API calls, Windows used EndDeferWindowPos, which means the "sync" implementation, likely for this reason. Furthermore, would using a different API interface lead to other inconsistent dynamic behavior ?

Not sure, so please let me know if I miss something obvious.

**Comment by HBelusca** [comment]
One cannot conclude anything just by the screenshot, because it doesn't tell whether CascadeWindows/TileWindows was called.

**Comment by katahiromz** [comment]
On Win2k3:
```txt
(Break by WinDBG)
kd> !process 0 0
...(process list)...
kd> .process (The process address of explorer.exe)
kd> .reload /user
kd> bp USER32!EndDeferWindowPos
kd> bp win32k!NtUserEndDeferWindowPosEx
kd> g
...(Choose Cascade)...
Breakpoint 0 hit
kd> kb
```
無題

**Review by katahiromz — CHANGES_REQUESTED** [review]
Thus, we have to fix `NtUserEndDeferWindowPosEx(***, TRUE)`.

**Comment by KRosUser** [comment]
To be continued by @katahiromz

**Comment by katahiromz** [comment]
Closed.

**Pull request closed without merging**
