### PR TITLE
[GITHUB] build.yml: Separate Debug/Release artifacts, Add 2 i386-Release builds

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Addendum to a9a22ae.

## Proposed changes

- Fix Dbg/Rel artifact handling.
- Complete supported i386-Release build list.

### CODE REVIEW

**Comment by SergeGautherie** [comment]
Rebased, after being hijacked by #3838.

**Comment by learn-more** [comment]
> Rebased, after being hijacked by #3838.

Not as much hijacked, as being unclear what this PR actually does without investigating the diff, considering the cryptic description used.

**Comment by SergeGautherie** [comment]
> unclear [...] cryptic description

What is unclear/cryptic?

**Comment by learn-more** [comment]
> > unclear [...] cryptic description
> 
> What is unclear/cryptic?

image

**Comment by tkreuzer** [comment]
@SergeGautherie The reason for this hijacking is simple: @Extravert-ir didn't know of your PR and he just followed up on my previous PR, which you also did. And you tend to "hijack" stuff quite often, by randomly opening PRs on code that someone else has recently modified and might still be working on. That is ok, if your PR fixes an actual bug, but it's not, if it only "fixes" some style issues, etc. Please realize, that every time someone opens a PR it needs developers time to review it. The more important stuff a PR fixes and the easier it is to review and validate, the greater the chance, someone will review it. Fixing a bugcheck in the kernel with 5 lines of code: you're in. Refactoring 50 lines of kernel code: you are out. If you want your PRs to get respected, stop doing style changes and minor "improvements" and do actual bugfixes. Yes, that might be more difficult and less fun, but if you actually want to help, then you need to go there. There is plenty of tasks, but refactoring kernel code is not one of them. If you want to know what a good task would be: Go over all our failed apitests, make sure they test succeeds on Windows 2003 and it always fails on ReactOS (not just randomly failing), then add a todo_ros before it. Once I have finished the whitelisting feature, you could go though the failing winetests and add whitelist entries for them. Yes, that is somewhat boring work, but it would be useful and I would review it.

**Comment by SergeGautherie** [comment]
> This is how I read this PR, before just closing it.

I feel the root cause is your point 2: this PR does target @tkreuzer's commit, and I assume he should know what he did hence what this PR does. If they look unclear to you, well, sorry.

NB: Oddly, you did not complain about #3838, which even reads 'No description provided.'...

--

> @Extravert-ir didn't know of your PR

How come, as I did comment on his PR?

> you tend to "hijack" stuff quite often

Do I? Let me know when that happens...

> That is ok, if your PR fixes an actual bug, but it's not, if it only "fixes" some style issues,

This PR does fix a bug!

> [...]

I'll be happy to discuss your other points elsewhere, as they seem to me totally unrelated to this PR...

**Comment by learn-more** [comment]
> > This is how I read this PR, before just closing it.
> 
> I feel the root cause is your point 2: this PR does target @tkreuzer's commit, and I assume he should know what he did hence what this PR does. If they look unclear to you, well, sorry.

The root cause is what you type in this issue / title.
Do you really expect someone to open all links provided when looking at a PR?
I (and most humans) open those links to read _details_, not to check whether this PR is relevant for X Y or Z.

> 
> NB: Oddly, you did not complain about #3838, which even reads 'No description provided.'...
> 

That title explains more than enough.
No ambiguity, no vague references.

> --
> 
> > @Extravert-ir didn't know of your PR
> 
> How come, as I did comment on his PR?
> 
> > you tend to "hijack" stuff quite often
> 
> Do I? Let me know when that happens...
> 

Most of your pr's are a change following someone else's commit.

> > That is ok, if your PR fixes an actual bug, but it's not, if it only "fixes" some style issues,
> 
> This PR does fix a bug!

Where in the description / title provided by you did you indicate this?

> 
> > [...]
> 
> I'll be happy to discuss your other points elsewhere, as they seem to me totally unrelated to this PR...

Generally, stuff like this should be discussed in our [mattermost chat](https://chat.reactos.org/) indeed.

**Comment by SergeGautherie** [comment]
> Do you really expect someone to open all links provided when looking at a PR?

I am not sure how relevant that question is here:
this PR has only 1 (commit) link and it displays 'tkreuzer', even without opening it.

> I (and most humans) open those links to read _details_, not to check whether this PR is relevant for X Y or Z.

I am not sure what your point is.

> That title explains more than enough.
> No ambiguity, no vague references.

I obviously have a different point of view about that:
'Build Release builds for all compilers' does not tell (me) anything about fixing artifacts!

> Most of your pr's are a change following someone else's commit.

It may be so. What's wrong with that? How is that hijacking anything?

> Where in the description / title provided by you did you indicate this?

'Addendum' and 'Fix'.

**Pull request closed without merging**
