### PR TITLE
[USRMGR] Increase name sizes to 'UNLEN + 1'

### PR DESCRIPTION
**Pull request by SergeGautherie**
`UNLEN` + `\0`, as everywhere else.

### CODE REVIEW

**Comment by HBelusca** [comment]
Has this been accepted in Wine?

**Comment by SergeGautherie** [comment]
> Has this been accepted in Wine?

Does this code exist in Wine? Where?

**Comment by Saibamen** [comment]
No `groupprops.c` in Wine: https://github.com/wine-mirror/wine/search?q=groupprops.c&unscoped_q=groupprops.c

**Comment by HBelusca** [comment]
Thanks for the info @Saibamen !

**Review by GeoB99 — APPROVED** [review]

**Pull request merged**
