### PR TITLE
[TASKMGR] *.rc Deduplicate dynamic menu strings

### PR DESCRIPTION
**Pull request by JoachimHenze**
Some of the Menu-controls are just dummies in the RC, because those controls are dynamically replaced at runtime based on which tab/propsheet is active in taskmgr. They are replaced by the IDS_MENU_* strings then.

Deduplicating them has many advantages:
1.) It shrinks binary size:
    master taskmgr.exe RosBEWin2.2.2 GCC8.4.0dbg  708.608 -> 696.832

2.) Translators don't get lured into translating dead stuff,
    assuming they translated the menu properly, while in fact they did not.
    This is **real**. Happened even to me multiple times already, although
    I am actually aware of the design.

3.) Some of them were offsync already between the dummy and the real thing.

4.) It reduces diff between en-US and others.

--------

* Aside of that improve alignment in some languages rcs in the "Shutdown"-menu-section,
* and improve a translation in de-DE, and zh-CN.
* id-ID.rc 2 accelerators in the same string is definitely wrong
* add some FIXMEs in rc for existing accelerator collisions, let the translators handle them later

JIRA issue: none

### CODE REVIEW

**Comment by JoachimHenze** [comment]
@hbelusca I double-checked: none of that will conflict with your unmerged PR5343.

**Comment by HBelusca** [comment]
There are two problems with this:
- When editing resources now, we don't know easily to which menu item these entries refer;
- Taking the example of the "Show 16-bit tasks" thing, I actually wonder why the code has been made this way:
```c
        LoadStringW(hInst, IDS_MENU_16BITTASK, szTemp, 256);
        AppendMenuW(hOptionsMenu, MF_STRING, ID_OPTIONS_SHOW16BITTASKS, szTemp);
```
instead of just adding or removing the existing menu item from the resources.

So basically what seems to be "trivial" at first is not, and needs thinking and investigation.

**Comment by HBelusca** [comment]
Since this PR doesn't fix any actual bug it's low-priority. I'll handle it later with other taskmgr fixes.

**Comment by JoachimHenze** [comment]
> Since this PR doesn't fix any actual bug it's low-priority. I'll handle it later with other taskmgr fixes.

It does fix a few trivial bugs with accelerators. But yes, nothing that couldn't wait a bit until the merge.


> When editing resources now, we don't know easily to which menu item these entries refer

Imho this is still pretty easy because the IDS_MENU_* strings have rather sane names which make the mapping easy to the corresponding control. The biggest problem that I see with it, is that it is harder to have those accelerators listed nearby and in a tree-like-fashion that have to be guarded against collisions. But when looking closer that was also not the case before, because many of the MENUITEMs were already offsync in translation and especially accelerators compared to their corresponding IDS_MENU_* string. That was an inevitable consequence of our unneeded duplication and external translation-contributors.


> I actually wonder why the code has been made this way

Well one obvious reason is, that the menu layout changes dynamically if the tabs are changed.
Interesting watch: Dave Plummer even explained recently in one of his publically available videos https://www.youtube.com/watch?v=1YGD94lSor8 (he stated that he got ok from MS to broadcast that information) that the real MS taskmgr loads all of its strings dynamically and caches them in some internal structure. I am not sure, whether it would make sense for us to go **that** far. That would come with at least some drawbacks. So I mention it here just as a sidenote.

**Pull request merged**
