### PR TITLE
[NOTEPAD] Accept shortcut file correctly

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
JIRA issue: N/A

BEFORE:
before

AFTER:
after

### CODE REVIEW

**Comment by BenNottelling** [comment]
No
Sorry, but that's not what the issue is about. 
The JIRA issue is that shell commands (such as menu items) need to be performed on the shortcut's target, not on the shortcut. It's not an issue with notepad but rather the path provided to it. I appreciate the effort, but this is a workaround for behavior that differs from windows.

Download notepad++ in window and in reactos, now make a shortcut to a text file and do right click -> edit with notepad++
You'll see in windows it will open in text file, in ReactOS it will open the shortcut.

**Comment by katahiromz** [comment]
This PR is not compatible to Win2k3.

Win10 seems using SHCreateItemFromParsingName to get the target path of a shortcut file.

**Comment by BenNottelling** [comment]
Reactosfanboy reported notepad++ behaving the same between w10 and wXP, at least in the scope of this issue, so it's definitely achievable

**Comment by katahiromz** [comment]
This is for Notepad issue, not for Notepad++.

**Comment by BenNottelling** [comment]
I believe a patch that fixes notepad++ would fix this too though?
But you know more than me so I'm gonna step to the side on this one

**Comment by learn-more** [comment]
I doubt this should be fixed in notepad.
If you try this experiment in windows:
* Create a shortcut to text file
* Open notepad by doubleclicking on the shortcut

Observe the process command line with something like process explorer, and you should see that explorer already translated the link to the text file before passing it to notepad.

**Pull request closed without merging**
