### PR TITLE
[KERNEL32] GetPriorityClass(): Enforce PriorityClass alignment

### PR DESCRIPTION
**Pull request by SergeGautherie**
JIRA issue: [CORE-16757](https://jira.reactos.org/browse/CORE-16757)

### CODE REVIEW

**Comment by JoachimHenze** [comment]
I marked this PR as WIP until you prove by a screenshot, that https://jira.reactos.org/browse/CORE-17106 will not be broken retrospectively after your commit.

**Comment by HBelusca** [comment]
Wasn't this coming from @ThFabba 's study patch from Mattermost?

**Comment by SergeGautherie** [comment]
> CORE-17106

I can't test that issue.
Also, as written on Jira, I assume it is irrelevant to this PR, as in separate bug.

> not be merged

Well, do it your way...

---

> Wasn't this coming from @ThFabba 's study patch from Mattermost?

I don't know (about Mattermost).
I know about option3.patch on [CORE-17247](https://jira.reactos.org/browse/CORE-17247)

**Comment by JoachimHenze** [comment]
> I know about option3.patch on CORE-17247
So you obviously are aware of why we did not commit that **yet**. It is documented in there, Because it breaks other - hard to fix - ticket https://jira.reactos.org/browse/CORE-17106 . Unless you can accompany your suggestion with something that prevents this to break, we will not commit it **yet**. Even in case it would be correct.

> I can't test that issue.
PR closed then. Can be reopened as soon as someone is capable to handle and fix that case as well. Currently we have no issue with that.

**Comment by JoachimHenze** [comment]
> I know about option3.patch on CORE-17247
So you obviously are aware of why we did not commit that **yet**. It is documented in there, Because it breaks other - hard to fix - ticket https://jira.reactos.org/browse/CORE-17106 . Unless you can accompany your suggestion with something that prevents this to break, we will not commit it **yet**. Even in case it would be correct.

> I can't test that issue.
PR closed then. Can be reopened as soon as someone is capable to handle and fix that case as well. Currently we have no issue with that.

**Comment by SergeGautherie** [comment]
> closed

5 months later, CORE-17106 was not re-tested, @ColinFinck committed the same fix as fd8080b.
Anyway...

**Pull request closed without merging**
