### PR TITLE
[WALLPAPERS] Add a new Wallpaper "Underwater"

### PR DESCRIPTION
**Pull request by user0-tb**
## Purpose

Add a new Wallpaper with the name "Underwater"

## Proposed changes

_Describe what you propose to change/add/fix with this pull request._

A better Wallpaper selection

### CODE REVIEW

**Comment by JoachimHenze** [comment]
I would recommend to delete another wallpaper in return, that we do consider the least professional one.
If we wouldn't come to any conclusion, I would vote with a thumbs down for adding another one.

**Comment by ace-dent** [comment]
This is quite a large file. Please consider whether a more optimized version is appropriate; does it need ~700 bytes of colorprofile metadata? (Check with `exiftool`). Artistically speaking, the photograph also seems rotated?

**Comment by user0-tb** [comment]
@JoachimHenze and @ace-dent, the File is now replaced with a smaller one.

**Comment by HBelusca** [comment]
We should consider having a separate github repo for the wallpapers.....

**Comment by cbialorucki** [comment]
> We should consider having a separate github repo for the wallpapers.....

Perhaps better still, what if we added a "Wallpaper" section to RAPPS?

**Comment by HBelusca** [comment]
> > We should consider having a separate github repo for the wallpapers.....
> 
> Perhaps better still, we could add a "Wallpaper" section to RAPPS.

Having a Themes/Wallpapers section in RAPPS would be a plus, yes. But those themes/wallpapers (if they are for ReactOS) should also be stored somewhere (hence the repo suggestion too).

**Pull request closed without merging**
