### PR TITLE
Ac97 import new2

### PR DESCRIPTION
**Pull request by MANIKLEON**
Purpose
Import of AC97 sample driver

Proposed changes
Import AC97 sample driver into drivers\wdm\audio\drivers\ac97
Insert missing definitions required to build into ddk

-- Explanation of commit "fixed buffer issue" --
Every time the DMA enable bit is written to 1, the emulated hardware also increments the buff index. The DMA enable bit was being set repeatedly during playback which screwed up the buffering. The fix checks if DMA is enabled, and if so it does not try and enable it again.

### CODE REVIEW

**Review by binarymaster — DISMISSED** [review]
Hello. Thanks for the Pull Request, however it comes from a branch of other person.

Can you confirm you got an explicit permission from the original author (i.e. @TheDeadFish) to work on this piece of code?

**Comment by MANIKLEON** [comment]
@TheDeadFish hasn't responded to another user's attempt at contacting him for a couple of months. So, I am willing to work on it in his place and want to see if he will ever work on it again. If not, then the continuation of his work can be merged when it is accepted by you all.
@binarymaster

**Comment by TheDeadFish** [comment]
I stopped working on this because Virtuabox is broken. It does not like any driver except the AC97 official driver. Virtualbox gets buffer underuns internally with this driver. And there was absolutely nothing I could do to fix it, drove me almost entirely mad

**Comment by Doug-Lyons** [comment]
@TheDeadFish, Do you have any experience with VMware Workstation to know if you might get better results testing with it?

**Comment by TheDeadFish** [comment]
I have never used VMware Workstation. But I do not think it emulates the ICH AC97 anyway.

That reminds me of the other reason why I stopped working on this stuff, I recently bought a new computer, but like a retard I bought into the hype and bought AMD. Turns out AMD is all fucky and does not work with virtual machines properly. I will never buy AMD again.

**Comment by Doug-Lyons** [comment]
@TheDeadFish, According to this post below, VMware can emulate the "Sound Blaster PCI 64/Ensoniq ES1371 (AC'97)."
https://communities.vmware.com/t5/VMware-Workstation-Pro/No-Soundblaster-in-VM-Ware-Workstation-12/td-p/918140
It appears that you have to manually edit the VMX file to make this work and set sound.virtualDev = "es1371" though.

**Comment by TheDeadFish** [comment]
Ok technically the DMA controller is part of AC97, but its the other half, the es1371 only uses the CODEC part

**Comment by GeoB99** [comment]
Closing as per the reason on #3653

**Pull request closed without merging**
