### PR TITLE
[COMDLG32] Fix extra scrollbars in choose font dialog

### PR DESCRIPTION
**Pull request by Doug-Lyons**
## Purpose

_Remove empty vertical scrollbars in choose font dialog style selection._

JIRA issue: [CORE-15945](https://jira.reactos.org/browse/CORE-15945)

## Proposed changes

_Remove flag for CBS_DISABLENOSCROLL in language resource files_
_for Choose Font Dialog in ComDlg32._

This appears to match what Windows Server 2003 SP2 has:

comdlg32_dll_resource_choose_font_w2k3sp2

### CODE REVIEW

**Review by HBelusca — CHANGES_REQUESTED** [review]
@Doug-Lyons Please recheck how this dialog looks like on Windows.
I'll check whether they only kept this flag in the PSDK header, but removed it in the comctl32 resources, or not.

Note also that the official PSDK has the definition templates for these dialogs.
For the choose-font dialog, you can see it there:
https://github.com/tpn/winsdk-10/blob/master/Include/10.0.16299.0/um/Font.Dlg#L24
and as you can see, the combo-boxes all have the `CBS_DISABLENOSCROLL` style, so I would tend to prefer you keep it that way.

**Comment by Doug-Lyons** [comment]
> @Doug-Lyons Please recheck how this dialog looks like on Windows. I'll check whether they only kept this flag in the PSDK header, but removed it in the comctl32 resources, or not.
> 
> Note also that the official PSDK has the definition templates for these dialogs. For the choose-font dialog, you can see it there: https://github.com/tpn/winsdk-10/blob/master/Include/10.0.16299.0/um/Font.Dlg#L24 and as you can see, the combo-boxes all have the `CBS_DISABLENOSCROLL` style, so I would tend to prefer you keep it that way.

@HBelusca, Now only the "Style" "Choose Font Dialog" is modified. Thanks.

**Review by HBelusca — APPROVED** [review]

**Review by JoachimHenze — APPROVED** [review]
Approved. Nice: you even remembered that it has to be done twice in cdlg_Zh!

**Review by cbialorucki — APPROVED** [review]

**Review by DarkFire01 — APPROVED** [review]

**Comment by Doug-Lyons** [comment]
Thanks for everyone's help with this and thanks for the approvals from
@JoachimHenze, @DarkFire01, @cbialorucki, and @HBelusca.

**Pull request merged**
