### PR TITLE
[MEDIA:FONTS] Add Greek glyphs to tahoma.ttf

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Make Greek characters available in `Tahoma` font.
JIRA issue: [CORE-14343](https://jira.reactos.org/browse/CORE-14343)

## Proposed changes

- Copy Greek vector glyphs from `DejaVu Sans` font by using FontForge.
- Add Greek bitmap glyphs by hand with using FontForge.
- Add Greek charset on font info.
- Underline position is hacked because FontForge has a bug in saving Underline position.

## TODO

- [x] CORE-14343.
- [x] Get Greek character map of `Tahoma` font.
- [x] Tested on wordpad.

## Comparison

Win10:
Win10

BEFORE:
before
Greek characters were tofu blocks.

AFTER:
after
Greek chacters are correctly displayed.

## Copyright

tahoma.ttf Version 0.019 khmz

Copyright (c) 2004 Larry Snyder, Based on Bitstream Vera Sans Copyright (c) 2003 by Bitstream, Inc. Font renamed in accordance with former's license. Please do not contact Bitstream Inc. for any reason regarding this font.

### CODE REVIEW

**Comment by katahiromz** [comment]
AFTER:
charmap-after

**Comment by HBelusca** [comment]
I indeed confirm that on standard english Win2k3, tahoma also has greek glyphs (amongst others).

**Review by HBelusca — APPROVED** [review]

**Comment by katahiromz** [comment]
BEFORE:
before

AFTER:
after

**Comment by HBelusca** [comment]
Nice :+1:
What I don't understand however, is that in the "before" case, since Tahoma didn't have any greek glyphs, where those shown in the Tahoma-non-bold (that actually appeared bold...) came from?

**Comment by HBelusca** [comment]
OK, but then this means our existing `Tahoma Bold` already had greek glyphs?!

**Comment by katahiromz** [comment]
https://github.com/reactos/reactos/commit/55251a0a8e24bad72def1389351b00e349a917a5

**Comment by HBelusca** [comment]
Aha so here it was! :joy: But then, does our non-bold Tahoma have Cyrillic letters too? (If so, then that's nice, it's on par with its bold version.)

**Comment by katahiromz** [comment]
It has Cyrillic but low quality.

**Pull request merged**
