### PR TITLE
[RPCRT4] Stub I_RpcSNCHOption(). CORE-12534

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Based on @learn-more's [comment](https://jira.reactos.org/browse/CORE-12534?focusedCommentId=87173&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-87173)

JIRA issue: [CORE-12534](https://jira.reactos.org/browse/CORE-12534)

## Proposed changes

- Stub only.

## TODO

- [X] @JoachimHenze, could you try these commits incrementally? Thanks. // Done by @oleg-dubinskiy :-)

### CODE REVIEW

**Comment by SergeGautherie** [comment]
@oleg-dubinskiy, maybe you could try this PR, if @JoachimHenze don't? Thanks.

**Comment by SergeGautherie** [comment]
> rpcrt4 problem seems to be fixed

You reproduce the reported issue without this PR, don't you?
And it is fixed with both commits.
Is the first commit enough or are both needed? Thanks.

**Comment by oleg-dubinskiy** [comment]
> You reproduce the reported issue without this PR, don't you?

Yes, I do.
> Is the first commit enough or are both needed?

Oh, as it appeared, it is no longer reproducible for me even only with the first commit (`74 stub I_RpcSNCHOption`), without applying the second. So yes, the 2nd one is not required.

**Comment by SergeGautherie** [comment]
Not WIP anymore:
commit 1 is needed, commit 2 is optional for the time being.

**Comment by learn-more** [comment]
If the first commit is suffient, please just keep that.
A stub that crashes when used is simpler to debug than one that silently does do nothing.

**Comment by SergeGautherie** [comment]
2nd commit removed.

**Comment by Saibamen** [comment]
Please mark this Pull Request as Draft if is still WIP: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request

**Comment by learn-more** [comment]
@Saibamen please stop responding to all tickets?

**Comment by SergeGautherie** [comment]
> Please mark this Pull Request as Draft if is still WIP:

No, it is neither (now)!

**Pull request merged**
