### PR TITLE
[MEDIA][FONTS] Add 'ReactOS Sans Serif' font

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Add a TrueType font compatible to Microsoft Sans Serif.
JIRA issue: [CORE-16435](https://jira.reactos.org/browse/CORE-16435)

## Proposed changes

- Copy "Noto Sans Regular" font.
- Modify the metrics of the font with confirming by `FontMetrics2` test program and using `FontForge`.
- Modify its name as `ReactOS Sans Serif` and licensing and copyright text by `FontForge`.
- Add license text.
- Add font substitute (`Microsoft Sans Serif` → `ReactOS Sans Serif`)

## TODO

- [ ] Do tests.

## Copyrights and license

Copyright 2015 Google Inc. All Rights Reserved.
Copyright 2021 Katayama Hirofumi MZ.
Licensed under the SIL Open Font License Version 1.1.

### CODE REVIEW

**Comment by katahiromz** [comment]
PS Names:
PS Names
TTF Names:
TTF Names

**Review by HBelusca — CHANGES_REQUESTED** [review]
Please rename this new font to "ReactOS Sans Serif". I think we are far past and more evolved than other people using "Micro$oft", "Microshaft" and other deformations of the "Microsoft" name in order to refer to the company.
And since the font name has been changed anyways, this means that there will always be a font-substitution entry in the registry that links the actual "Microsoft Sans Serif" name to whatever name the font is called.

**Comment by gonzoMD** [comment]
> Please rename this new font to "ReactOS Sans Serif". I think we are far past and more evolved than other people using "Micro$oft", "Microshaft" and other deformations of the "Microsoft" name in order to refer to the company.
> And since the font name has been changed anyways, this means that there will always be a font-substitution entry in the registry that links the actual "Microsoft Sans Serif" name to whatever name the font is called.

Iirc Katayama had to rename all our free fonts for compatibility reason.
If not happened so far this must be documented somewhere. 

Another question: is the Z a typo or is it some special CJK variation of the font?

**Comment by katahiromz** [comment]
PS Names:
PS Names

TTF Names:
TTF Names

**Comment by katahiromz** [comment]
> Another question: is the Z a typo or is it some special CJK variation of the font?

No, that was intensional.

**Comment by katahiromz** [comment]
VirtualBox_ReactOS_12_07_2021_20_56_52
Same as normal.

**Comment by katahiromz** [comment]
exists
Microsoft Sans Serif does exist.

**Comment by katahiromz** [comment]
image
Yes. Similar font.

**Comment by katahiromz** [comment]
image
image
Yes. Similar font.

**Comment by HBelusca** [comment]
> 
> 
> image
> Yes. Similar font.

In this picture we can note that there is a bit more space between capital I and capital J in this modified sans-serif font, than in the original MS Sans Serif. Also the capital C letter seems to be a bit rounder (and thus, taking slightly more space) than in the original MS Sans Serif.

**Comment by katahiromz** [comment]
NOTE: "MS Sans Serif" and "Microsoft Sans Serif" are different fonts.

**Comment by HBelusca** [comment]
I meant "Microsoft Sans Serif"

**Comment by katahiromz** [comment]
To realize 100% compatibility, the font name must be the same name.

**Comment by HBelusca** [comment]
> To realize 100% compatibility, the font name must be the same name. I fear trademark violation.

Don't care about that. Any well-behaved application will use CreateFont with whatever name, and then the font substitution mechanism will do its job.

**Review by JoachimHenze — CHANGES_REQUESTED** [review]
Thank you for your investigation Katayama, but I really think we should wait with fixing that ticket until we can properly resolve it with a proper rasterfont. I don't think it that ticket is urgent enough to use a ttf instead of proper .fon just because we can not properly render rasterfonts yet. Better let's wait for the real deal. We will most likely never get PixelPerfect metrics otherwise.

**Comment by SergeGautherie** [comment]
> properly resolve it with a proper rasterfont

Current PR seems to match CORE-16435 comments.
Which ticket and raster font are you talking about?

**Comment by katahiromz** [comment]
MS Sans Serif is a raster font.
And Microsoft Sans Serif is a TrueType font.
We are confusing about their names.

**Comment by katahiromz** [comment]
I follow human's order. Closed.

**Comment by katahiromz** [comment]
> Can you please add a before-and-after picture of nLite 1.4.9.3 of that patch with DisplayResolution 800x600=

dotNet framework 2.0 fails with BSoD. I cannot test.
VirtualBox_ReactOS_13_07_2021_11_45_23

**Comment by katahiromz** [comment]
@JoachimHenze mistook Microsoft Sans Serif with MS Sans Serif. Reopened.

**Comment by katahiromz** [comment]
AFTER:
after
The problem isn't fixed. My investigation was something wrong. Closed.

**Pull request closed without merging**
