### PR TITLE
[THEMES] Fix Mizu theme bitmaps

### PR DESCRIPTION
**Pull request by binarymaster**
## Purpose

Remove BGRs color space headers to allow using theme on Windows XP.

JIRA issue: [CORE-15936](https://jira.reactos.org/browse/CORE-15936)

## Result

image

### CODE REVIEW

**Comment by jeditobe** [comment]
But I see some strange colors now on lables

**Comment by binarymaster** [comment]
@jeditobe I couldn't reproduce this problem with the same msstyle file on ReactOS.

So this is something half-implemented in the theme itself. Not big surprise, since it was never tested in Windows XP. Cc @foxlet

**Comment by foxlet** [comment]
I have my own patch for this coming in a bit.

**Comment by binarymaster** [comment]
Superseded by #1490.

**Pull request closed without merging**
