### PR TITLE
[DEVCPUX] Add russian translation

### PR DESCRIPTION
**Pull request by binarymaster**
A new translation here! :+1: 

Also make MHz string translatable.

### CODE REVIEW

**Comment by HBelusca** [comment]
So, "megaherz" should be written as "megahertz".

**Comment by learn-more** [comment]
@EricKohl Does this not cause conflicts with your local work?

**Comment by binarymaster** [comment]
> So, "megaherz" should be written as "megahertz".

I blame @gigaherz! 😅

**Comment by EricKohl** [comment]
@learn-more This does not conflict with my local work. I have no more changes for devcpux.dll in my queue.

**Pull request merged**
