### PR TITLE
Review Turkish translations [WIP]

### PR DESCRIPTION
**Pull request by eersoy93**
## Purpose

Review Turkish translations.

## Proposed changes

- [DOC] Delete For_Turkish_Translations.txt
- [SOL] [SPIDER] [WINMINE] [NOTEPAD] [MSPAINT] [WORDPAD] [MPLAY32]
  [SNDREC32] [WINHLP32] [SNDVOL32] [TASKMGR] [CALC] Update Turkish translations
- [SNDVOL32] [CALC] Add Turkish translations

## TODO

- Review entire Turkish translations (except I have reviewed)
- Add Turkish translations for untranslated strings

### CODE REVIEW

**Comment by eersoy93** [comment]
Oh, again! Sorry.

**Comment by ThFabba** [comment]
Don't use `git pull` (except if you specify the `--rebase` option or have the corresponding config entry set) and you shouldn't have this sort of problem.
But also, there's no harm in merging master into your branch. As long as "Files changed" looks good, everything is fine.

**Comment by HBelusca** [comment]
Any updates @eersoy93 ?

**Comment by eersoy93** [comment]
> Any updates @eersoy93 ?

I'll update my branch but you can merge this PR.

**Pull request merged**
