### PR TITLE
[MSAFD] Improve WSPGetSockOpt/WSPSetSockOpt

### PR DESCRIPTION
**Pull request by tambry**
## Purpose

This allows more winetest ws2_32:sock tests to pass.

JIRA issue: [CORE-12104](https://jira.reactos.org/browse/CORE-12104)

### CODE REVIEW

**Comment by gonzoMD** [comment]
Is there any reason why you rename all those variables?

**Comment by tambry** [comment]
@gonzoMD To match the official function declarations. From yesterday on #reactos-dev:
```
<tambre> Is it preferable in cases where the official Windows function declarations don't match ROS's style guide for variable names to convert them to match?
<RosBridge> <hbelusca> No
<RosBridge> <hbelusca> For official functions one must keep the official style.
```

**Comment by ThFabba** [comment]
I would recommend simply not making any style changes. It just makes it harder to review the PR.

**Comment by Mouvedia** [comment]
> This allows more winetest ws2_32:sock tests to pass.

How many exactly?

**Comment by tambry** [comment]
@Mouvedia At least 2, but I can't remember excactly.

**Comment by Mouvedia** [comment]
Could you add the WIP patches to CORE-12104?

**Comment by tambry** [comment]
@Mouvedia Sure, done.

**Pull request closed without merging**
