### PR TITLE
[USETUP][NTDLL_APITEST][KBDROST] Fix source code codepage problem 

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Convert some source files by a converter to make them 8-bit clean.
JIRA issue: [CORE-15447](https://jira.reactos.org/browse/CORE-15447)
The converter is code7bit I made.

code7bit: https://github.com/katahiromz/code7bit

To convert:
```bash
# bash
code7bit -c base/setup/usetup/lang/*.h modules/rostests/apitests/ntdll/RtlGenerate8dot3Name.c dll/keyboard/kbdrost/kbdrost.c
```

You can successfully and completely revert these changes. To revert:
```bash
# bash
code7bit -r base/setup/usetup/lang/*.h modules/rostests/apitests/ntdll/RtlGenerate8dot3Name.c dll/keyboard/kbdrost/kbdrost.c
```

### CODE REVIEW

**Comment by katahiromz** [comment]
AFTER:
after

Asian Visual Studio Community 2017 can build this.

**Comment by katahiromz** [comment]
```txt
../../dll/keyboard/kbdrost/kbdrost.c:389:11: error: universal character names are only valid in C++ and C99 [-Werror]
...
../../modules/rostests/apitests/ntdll/RtlGenerate8dot3Name.c:47:88: error: universal character names are only valid in C++ and C99 [-Werror]
```
We have to use C99 for non-MSVC.

**Comment by katahiromz** [comment]
success
Successfully.

**Comment by HBelusca** [comment]
Question: isn't it possible to have the code converter issue `\xXX` character encoding (hexadecimal)? This is what has been already used in some files e.g. the italian translation and is IMHO more readable.

**Comment by katahiromz** [comment]
`code7bit` uses octal sequence (`\OOO`) or UCN (`\uXXXX`). Not hexademical. If there was already octal sequence or UCN, then error message will be shown.

**Comment by ThFabba** [comment]
Hmm. `.rc` files shouldn't need this treatment since they support the code_page pragma. Can you check what the other files do to avoid this problem?
Also, using \x123 escapes in comments doesn't seem useful. If it's really necessary, perhaps just switch to the asciified version of the letter in question there? (áàâäå -> a, etc)

**Comment by ThFabba** [comment]
Question: shouldn't, for example, ever .c file that has Hermès's name in it (https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=Herm%C3%A8s) have a problem? Is it only certain characters that cause trouble?

**Comment by katahiromz** [comment]
The resource compiler accepts UTF-8 text correctly, so the resource files have no problem.

The characters in comments seems like ignored, so no problem.

**Comment by HBelusca** [comment]
> I think conversion in comments is useful for perfect reverse conversion.

And it makes reading the comment completely complicated. The compiler should not care about these, so....

**Comment by katahiromz** [comment]
Temporarily closed.

**Pull request closed without merging**
