### PR TITLE
Merging Vgal's changes of hal, part 1: zapping UP

### PR DESCRIPTION
**Pull request by mifritscher**
## Purpose

Changes on the HAL by vgaInt, part one: structural

## Proposed changes

zapping UP into PIC and MINIHAL directories.

Remark: this my first PR doing merge stuff ;)

### CODE REVIEW

**Comment by ThFabba** [comment]
This is not of merge-able quality. There are magic numbers and commented out code. Also comments that question the purpose of the code.
Also, this needs the description of what it achieves. Change for the sake of change is nonesense.

**Comment by mifritscher** [comment]
The purpose of these PR is to split vgal's work into reviewable parts. For instance, this was simply renaming files of which, honestly, I don't know whether there are useful, but wanted to start a discussion about. But there weren't any things you criticized about comments, hard coded constants or commented out code...

**Comment by vgalnt** [comment]
2. mifritscher, did you try to build a reactos after these commits? This PR is unfinished. The second commit is not enough.
.
1. The first commit was made in order to avoid confusion between UP and PIC:
/*
UP - Uniprocessor
MP - Multiprocessor
PIC - Programmable Interrupt Controller
APIC - Advanced Programmable Interrupt Controller
ACPI - Advanced Configuration and Power Interface
.
The PIC is always on UP, but the APIC can be on both UP and MP.
*/
For example, the function HalpInitPhase0(), which is called from the function HalInitSystem().
On x86 HalpInitPhase0() is now in modules:
hal/halx86/apic/halinit_apic.c
hal/halx86/mp/halinit_mp.c
hal/halx86/up/halinit_up.c
.
That is, APIC is compared to UP. This is where I see real nonsense.
.
Btw, one more nonsenses from CMakeLists:
    # hal
    add_hal(hal SOURCES up/halup.rc COMPONENTS generic legacy up pic)
    add_hal(halacpi SOURCES acpi/halacpi.rc COMPONENTS generic acpi up pic)
    add_hal(halapic SOURCES acpi/halacpi.rc COMPONENTS generic legacy up apic)
    add_hal(halaacpi SOURCES acpi/halacpi.rc COMPONENTS generic acpi up apic)

    #add_hal(halmps SOURCES up/halup.rc COMPONENTS generic legacy smp pic)
    #add_hal(halmacpi SOURCES acpi/halacpi.rc COMPONENTS generic acpi smp pic)
    #add_hal(halmapic SOURCES acpi/halacpi.rc COMPONENTS generic legacy smp apic)
    #add_hal(halmaacpi SOURCES acpi/halacpi.rc COMPONENTS generic acpi smp apic)

... smp pic) - ???
halmapic and halmaacpi - ???  :)

**Comment by mifritscher** [comment]
Ah, hello Vadin :-) Thanks for your comments and the explanations!

It seems that at your second commit, also new code slipped in (the "if (Prcb->CpuType == 3) // 80387 ?" block). There is already code to block booting at a 386er in the kernel:
 `if (Prcb->CpuType == 3) KeBugCheckEx(UNSUPPORTED_PROCESSOR, 0x386, 0, 0, 0);`

Btw, I tried to "packetize" your changes at the hal a bit and did some first comments as a first step trying to get them upstream. Do you think that this is useful? As a remark, I'm _not_ a expert in this area, I just want to help to get your work upstream.

dividing https://github.com/vgalnt/reactos/commits/boot_with_nt_drv:

HALX86:
  * Structure: 
cb433a58284767f7396cd55437bb1767f30c748d : [HALX86] Move files from "UP" dir to "PIC" and "MINIHAL" dirs, correcting CMakeLists files.
44ae18975515a77d5dc4ed0697d6b0e141fda7ec : [HALX86] "pic\halinit_pic.c" <== "pic\halinit_up.c"

  * Initialisation:
a247ebabddcd19f4471f08874382ae9842b4a4d8 : [HALX86] Correcting hals initialization.

  * 64 bit fixes:
0e20bde01eb12ec42d05f4cce3ff5d8f0c67ebb1 : [HALX86] Correcting struct _SUPPORTED_RANGE and struct _SUPPORTED_RANGES.
  Why the change to ULONGLONG? It seems that it is LONGLONG (https://www.vergiliusproject.com/kernels/x64/Windows%2010%20|%202016/1803%20Redstone%204%20%28Spring%20Creators%20Update%29/_SUPPORTED_RANGE). The C_ASSERTS are looking good for me to help identifing broken compilers.

  * Added range functions:
02ed7b2197c82c99a307aa4a43cbf2d3bfbefe9c : [HALX86] Add stubs for handle SUPPORTED_RANGES. 
967378283a043704baae9c2bd858956d65508b2b : [HALX86] Implement HalpMergeRanges().
2762ec55ee1d803918b5ac7d61c55c8e0e7bba62 : [HALX86] Implement HalpAllocateNewRangeList().
d464848b52dc9bdbb23ce11252772494965413a1 : [HALX86] Implement HalpMergeRangeList(). 
7d292c4731d0166737b1757f125e3486d1ffb206 : [HALX86] Implement HalpAddRangeList().
e347778f70afebc8a9cf2fc7dd3c46bc7e06f45a : [HALX86] Implement HalpAddRange().
548bce7d3a4f6d41f561575f4642c5d1b418b298 : [HALX86] Implement HalpFreeRangeList().
d9abe4430f4a9dbde2a6d8cc2e02a8af5dc37625 : [HALX86] Implement HalpConsolidateRanges().


  * Fixes for existing bus address funktions:
f8cc5c9be65b9c2d02064f82ec7fcf99de4fa25d : [HALX86] Correcting HalpRegisterInternalBusHandlers(). Add stubs for eisa bus functions in new file "hal\halx86\legacy\bus\eisabus.c". Correcting CMakeLists files.
  Perhaps splitting this in 2 commits?  
f2f676eb7969a943daa28d64852c8eda7f707f96 : [HALX86] Correcting HalpTranslateSystemBusAddress().
cd1c5af222d64fddcc1fbc1ca11a9f6c27dd837a : [HALX86] Correcting HalpFixupPciSupportedRanges(). 
  I feel uncompfortable with the added assert - why not simply warn (as before) + ignore this bridges for now?

 * Bugfixes for HalpReportResourceUsage:
4f283c131b66a8df7ac7a4f52719c0c09e8aa731 : [HALX86] Fixing the creation of incorrect Raw and Translated lists in HalpReportResourceUsage().
38740ce8bd6a379b0850541b54547c01d1ef04a5 : [HALX86] Correcting IoReportHalResourceUsage(). 
  Follow-up in ntoskrnl side
  
 * Debug functions:
e78b345f43e70cc3df7d7fb9d2683063a18135a6 : [HALX86] Add "hal/halx86/generic/debug.c", HalpDumpCmResourceList().
190de874bf99fe6d075a2189729b35fac0e878a5 : [HALX86] Experimental changes for COM - ports on real HW. 
  Not needed, is it?

**Pull request closed without merging**
