### PR TITLE
[EXPLORER] Crash on backspace while editing folder panel

### PR DESCRIPTION
**Pull request by atharva1910**
JIRA issue: [CORE-18646](https://jira.reactos.org/browse/CORE-18646)
Tested issuing a backspace while editing multiple folder names: No crash

Suspected Duplicates:
[CORE-18504](https://jira.reactos.org/browse/CORE-18504) Tested right clicking on left panel folders: No crash
[CORE-18746](https://jira.reactos.org/browse/CORE-18746) Tried renaming Recycle Bin: No crash

### CODE REVIEW

**Review by KRosUser2 — APPROVED** [review]

**Comment by katahiromz** [comment]
What was the cause of crash?

**Comment by JoachimHenze** [comment]
[atharva1910](https://github.com/atharva1910) you seem to be a first-time-contributor. Can you set your email address to be public in your github profile, please? Our merge-policy does require that.

**Comment by KRosUser2** [comment]
Cause was message passed to CDefView unduly leading to the navigate to parent function, then leading to status bar update with a NULL member

**Comment by KRosUser2** [comment]
This solution implement in Explorer Band for its TV what is implement in CDefView for its LV

**Comment by atharva1910** [comment]
> [atharva1910](https://github.com/atharva1910) you seem to be a first-time-contributor. Can you set your email address to be public in your github profile, please? Our merge-policy does require that.

Done

**Review by katahiromz — APPROVED** [review]

**Review by learn-more — CHANGES_REQUESTED** [review]
Hello,
Thanks for your interest in ReactOS!
We ask our contributors [to use their full name when committing](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations).
[Please amend your commit with your full name](https://stackoverflow.com/a/3042512), and update this PR.

To change this for future PR's, you can update it for globally (for the system):
```
git config --global user.name "Your Name"
git config --global user.email you@example.com
```

Or just for the current repository:
```
git config user.name "Your Name"
git config user.email you@example.com
```

Regards,

**Comment by KRosUser2** [comment]
@atharva1910 your latest commit does not reflect the request from Mark and my code change suggestion. Patch has been updated in the ticket to share what is needed here.

**Comment by learn-more** [comment]
@ Whoever is gonna merge this, please note that in the user profile is an alias so this will need manual merging.

**Comment by atharva1910** [comment]
@learn-more Hi Mark, Is there something remaining from my end to be resolved for this PR to be merged in? If not could you approve?

**Comment by learn-more** [comment]
Thanks for your contribution @atharva1910 .

**Comment by KRosUser2** [comment]
Bad news, when i test with the final commit i'm still facing the bug.
I think the cause is the last change introduced nesting the m_isEditing in the brace with theResult as condition when leads to NOT setting m_isEditing to TRUE (unlike in the initial patch)

so 

if (SUCCEEDED(hr) && (dwAttr & SFGAO_CANRENAME) && theResult)
                {
                    *theResult = 0;
                    m_isEditing = TRUE;
                }

should be

if (SUCCEEDED(hr) && (dwAttr & SFGAO_CANRENAME))
                {
                 m_isEditing = TRUE;
                 if (theResult)
                      *theResult = 0;                    
                }

**Pull request merged**
