### PR TITLE
[IMM32] Renaming: s/pImmHeap/ghImmHeap/

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

I had confirmed the name of `pImmHeap` on WinDBG, but @HBelusca thinks it's bad name. Renaming correctly...

JIRA issue: [CORE-11700](https://jira.reactos.org/browse/CORE-11700)

## Proposed changes

- Rename `pImmHeap` as `ghImmHeap`.

### CODE REVIEW

**Comment by learn-more** [comment]
Is the name exported somewhere, or is it only present in symbol files?
@HBelusca what's your take on this?

**Comment by katahiromz** [comment]
It's present in symbol files.

**Comment by HBelusca** [comment]
> Is the name exported somewhere, or is it only present in symbol files? @HBelusca what's your take on this?

Turns out it's only from symbol files, as katayama mentions, but not an exported variable. That's why I was doubtful about the usefulness of the change in master. (The only time when matching exactly a symbol name is necessary is when we know e.g. WinDbg -- via one of its standard commands -- expects to see such symbol in the module in question, in order to implement some debugging support for something.)

**Comment by katahiromz** [comment]
Go or not?

**Pull request merged**
