### PR TITLE
shell32: Make drive property sheet modeless

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

JIRA issue: [CORE-14035](https://jira.reactos.org/browse/CORE-14035)

## TODO

- [ ] Enable OK and Cancel buttons

### CODE REVIEW

**Comment by gigaherz** [comment]
You can force-push to the same branch and keep the old PR open, no need to make new branch and new PR if you just want to squash changes.

**Comment by sanchaez** [comment]
Also check those builds.

**Comment by katahiromz** [comment]
I tried C function interface, but failed.
I added definitions of C interface functions SH_AddDrivePropSheet, SH_IsDrivePropSheetMessage, and SH_DeleteAllDrivePropSheets in File "dll/win32/shell32/dialogs/drive.cpp".
But, at File "dll/win32/shell32/shelldesktop/CDesktopBrowser.cpp", error happens: undefined reference to `SH_DeleteAllDrivePropSheets'.
How can I fix this build?

**Comment by katahiromz** [comment]
An external module, named 'rshell' depends on the shelldesktop static
library. There are my new functions I tried to add in drive.c. They should
be referred by shelldesktop library. Can a static library include other
library? How can we associate the functions in drive.c to shelldesktop?

**Comment by sanchaez** [comment]
It's not drive.c, it's drive.cpp. 
Quick guess: maybe you forgot to define your functions in a header somewhere.

**Comment by katahiromz** [comment]
Modality is later work. I will do workaround for now.

**Pull request closed without merging**
