### PR TITLE
[GITHUB] build.yml: Re-enable 'build-msbuild-i386'

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Something fixed it in the meantime.

Revert 56a4501 (0.4.15-dev-6069).
JIRA issue: [CORE-18911](https://jira.reactos.org/browse/CORE-18911)

## Proposed changes

- Re-enable 'build-msbuild-i386'

### CODE REVIEW

**Comment by SergeGautherie** [comment]
2 failed 'arm*' builds on irrelevant/technical issues.

**Comment by Saibamen** [comment]
Next time, you can use `if: ${{ false }}  # disable for now` to disable GH Action job. No need to comment out all lines of code

https://code-maven.com/slides/github-ci/disable-single-github-action-job

**Comment by SergeGautherie** [comment]
> `if: ${{ false }} # disable for now`

Tell that to initial commit author, not to me.

**Comment by Saibamen** [comment]
Done: https://github.com/reactos/reactos/commit/56a450147c2915618d3f8527801b7dc69364738e#r138494284

**Pull request merged**
