### PR TITLE
[FONTS] Add Hebrew glyphs into Trebuchet MS font

### PR DESCRIPTION
**Pull request by omeritzics**
## Purpose

_The Hebrew letters aren't displayed in Mizu theme because there was no Hebrew glyph in some fonts, this PR fixed this._

## Proposed changes

_1. Merge Hebrew Open Sans into Trebucit fonts._
_2. Merge Noto Sans into DejaVu fonts._

### CODE REVIEW

**Comment by HBelusca** [comment]
So you are adding (previously unexisting) hebrew letters in the fonts?
It's strange then that in total, the files reduced in size:
image

**Comment by omeritzics** [comment]
I merged the fonts in FontForge and then replaced the unmerged font files with the merged font files.

**Comment by omeritzics** [comment]
> Yes, It is really strange. I'll turn draft mode on and take a look in this PR.

FontForge compressed the fonts maybe, I can see the merged fonts.

**Comment by binarymaster** [comment]
Cc @reactos/lang-hebrew for check. Also @foxlet for the Mizu theme.

Needs testing.

**Comment by JoachimHenze** [comment]
I added Katayama Hirofumi MZ to the reviewers. Katayama there was some bug in FontForge iirc that required some hack to be applied everytime a font was touched with FontForge to restore the underline positions iirc. Is this needed here? Is the font "properly hacked" already after the modification of omeritzics?

I am talking about what you earlier referred to as: "The Underline Positions are hacked by adding an integer value for workaround of FontForge's bug."

**Comment by katahiromz** [comment]
There is no change in underline position.
underline-unchanged

**Comment by katahiromz** [comment]
hebrew-charset-is-not-selected
Hebrew charset is not selected in font settings.

**Comment by katahiromz** [comment]
I can see the Hebrew glyphs are added.
hebrew-glyphs-added

**Review by katahiromz — CHANGES_REQUESTED** [review]
I request change:

1. Add Hebrew charset in font settings.
2. Update font file version info (with author info and version up).
3. Restore kerning table (or modify the original without dropping kerning table).

**Comment by katahiromz** [comment]
kerning-dropped
You have dropped kerning info.

**Comment by katahiromz** [comment]
When you generate a TTF file, you can choose the options. And you can add checkmark on `kern` in the options.
kern

**Comment by omeritzics** [comment]
Hello, I made the requested changes to the font.

> I request change:
> 
>     1. Add Hebrew charset in font settings.
> 
>     2. Update font file version info (with author info and version up).
> 
>     3. Restore kerning table (or modify the original without dropping kerning table).

**Comment by omeritzics** [comment]
> I request change:
> 
>     1. Add Hebrew charset in font settings.
> 
>     2. Update font file version info (with author info and version up).
Hello, I made these changes to the fonts.
>     3. Restore kerning table (or modify the original without dropping kerning table).
How to make this change?

**Comment by katahiromz** [comment]
Sorry, I was incorrect. See this figure:
kerning
Disable "OpenType". Enable "Prefer native kerning". Enable "Windows-compatible 'kern'".

**Comment by katahiromz** [comment]
https://en.wikipedia.org/wiki/Kerning
> ...however PostScript-based (CFF) OpenType fonts do not have this option.
> ...The more recent font releases by Adobe no longer have kern tables at all, but only specify kerning via GPOS.

**Comment by katahiromz** [comment]
Sorry, I was incorrect. See this figure:
kerning2
Enable OpenType. Enable old 'kern'.

**Comment by katahiromz** [comment]
It seems we have to enable OpenType's kern table.

**Comment by katahiromz** [comment]
https://fontdrop.info/
This site can check the existence of the kern table.

**Comment by katahiromz** [comment]
>How to restore the kerning table?
FontForge doesn't support the feature of restoring kern table (or GPOS). Maybe instead modify the original without dropping kerning table.

**Comment by omeritzics** [comment]
Hello, I made the requested changes to the font.

**Comment by peterooch** [comment]
(Not to downplay the effort being put here)
I have commented about this before, I dont think modifying every font would be the proper course of action if there are glyphs missing.
One method is to use `ScriptString` functions with automatic font-fallback or to use `ScriptGetCMap` to check and apply temporarily a font that has the required glyphs if current font is missing glyphs.

And on a another note, I'm going to check if the theme doesn't have those pesky squares anymore.

**Comment by katahiromz** [comment]
Give me a few days. I will analyze.

**Comment by katahiromz** [comment]
warning
Sorry, opening the modifed ttf files cause new warning.

Probably we have to disable OpenType specification.
kern
Thanks.

**Comment by omeritzics** [comment]
> 
> 
> warning
> Sorry for trial and error, opening the modifed ttf files cause new warning.
> 
> Probably we have to disable OpenType specification.
> kern
> Thanks.

Is it fixed on https://github.com/reactos/reactos/pull/3270/commits/ebbe5857dac6f3faaa36e8ade885669a00b28110?

**Review by katahiromz — APPROVED** [review]
Approved! Let's go to the testing stage! @reactos/lang-hebrew

**Comment by omeritzics** [comment]
Hello, I tested it and discovered that I was wrong, Trebuchet MS isn't the font of Mizu theme. I'll add Hebrew glyphs to this font too.

**Comment by katahiromz** [comment]
not-fixed-yet
Not fixed yet. The target font is `"Source Sans Pro"`.

**Comment by katahiromz** [comment]
trebuchet-ms-can-display
Trebuchet MS can display Hebrew.

**Comment by katahiromz** [comment]
https://docs.microsoft.com/en-us/typography/font-list/trebuchet-ms
dont-support
Microsoft "Trebuchet MS" doesn't support Hebrew. We have to revert `trebu*.ttf`.

**Comment by omeritzics** [comment]
I'll Add Hebrew glyphs to Source Sans Pro and open another PR.

**Comment by katahiromz** [comment]
"Source Sans Pro" is not standard font.
You can also use Font Substitutes.

**Comment by omeritzics** [comment]
> 
> 
> "Source Sans Pro" is not standard font.
> You can also use Font Substitutes.

Is it safe to add Hebrew glyphs to it anyway?

**Comment by omeritzics** [comment]
Using Noto Sans in Mizu theme is more ideal.

**Comment by katahiromz** [comment]
Please ask reactosfanboy about that in our chat room.

**Pull request closed without merging**
