### PR TITLE
[APPWIZ] Fix the build for windows hosts

### PR DESCRIPTION
**Pull request by learn-more**
## Purpose

There seems to be a missing dependency between `appwiz.exe` and `reactos_cab`.
Manually building `ninja appwiz.exe` and then `ninja reactos_cab` works,
but `ninja reactos_cab` on a clean dir complains about a missing `appwiz.exe`

My best guess is that somewhere in the `add_cd_file` magic the `appwiz.exe` target is mangled to the target `appwiz` (which is `appwiz.cpl`.

Problem occurs at least on a windows host, with ninja+msvc

### CODE REVIEW

**Review by zefklop — COMMENTED** [review]
Did you try to pass appwiz.exe as a string, i.e. put that between double quotes?

**Comment by jimtabor** [comment]
On an older Slackware 14.1 build system, getting,

ERROR: Directive file contains error at line 1222.

Not sure if this helps.

**Comment by jimtabor** [comment]
On an older Slackware 14.1 build system, getting,

ERROR: Directive file contains errors at line 1222.

Not sure if this helps.

**Comment by jimtabor** [comment]
On an older Slackware 14.1 build system, getting,

ERROR: Directive file contains errors at line 1222.

Not sure if this helps.

**Comment by learn-more** [comment]
Now obsolete

**Pull request closed without merging**
