### PR TITLE
[KERNEL32] LCMapString: Fullwidth/halfwidth conversion

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

In Far East Asia, the fullwidth characters (a.k.a. `全角`) are used. The non-fullwidth characters are called as halfwidth characters (`半角`). The Chinese, Japanese, and Korean (CJK) users might want character type conversion between fullwidth characters (`ＡＢＣ１２３アイウ`) and halfwidth characters (`ABC123ｱｲｳ`). `LCMapString` function will realize it.

JIRA issue: [CORE-11700](https://jira.reactos.org/browse/CORE-11700)

## Proposed changes

- Add file `dll/win32/kernel32/winnls/string/dakuten.h`.
- Add file `dll/win32/kernel32/winnls/string/full2half.h`.
- Support `LCMAP_FULLWIDTH` and `LCMAP_HALFWIDTH` flags in `LCMapString` function.

## TODO

- [x] Do small tests.
- [x] Do big tests.

### CODE REVIEW

**Comment by katahiromz** [comment]
KVM BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86660
KVM AFTER: add9b2c

VBox BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86661
VBox AFTER: add9b2c

**Comment by katahiromz** [comment]
KVM BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86660
KVM AFTER: ffc332d

VBox BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86661
VBox AFTER: ffc332d

**Comment by katahiromz** [comment]
KVM BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86660
KVM AFTER: a12a90a

VBox BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86661
VBox AFTER: a12a90a

**Comment by katahiromz** [comment]
KVM BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86660
KVM AFTER: 91d74e1

VBox BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86661
VBox AFTER: 91d74e1

**Comment by katahiromz** [comment]
KVM BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86660
KVM AFTER: bbacd50 https://reactos.org/testman/compare.php?ids=???
https://reactos.org/testman/compare.php?ids=86660,???

VBox BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86661
VBox AFTER: bbacd50 https://reactos.org/testman/compare.php?ids=???
https://reactos.org/testman/compare.php?ids=86661,???

**Comment by katahiromz** [comment]
KVM BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86660
KVM AFTER: f95bcc8 https://reactos.org/testman/compare.php?ids=???
https://reactos.org/testman/compare.php?ids=86660,???

VBox BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86661
VBox AFTER: f95bcc8 https://reactos.org/testman/compare.php?ids=???
https://reactos.org/testman/compare.php?ids=86661,???

**Comment by katahiromz** [comment]
KVM BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86660
KVM AFTER: 00ac228 https://reactos.org/testman/compare.php?ids=???
https://reactos.org/testman/compare.php?ids=86660,???

VBox BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86661
VBox AFTER: 00ac228 https://reactos.org/testman/compare.php?ids=???
https://reactos.org/testman/compare.php?ids=86661,???

**Comment by katahiromz** [comment]
KVM BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86660
KVM AFTER: 107892c https://reactos.org/testman/compare.php?ids=???
https://reactos.org/testman/compare.php?ids=86660,???

VBox BEFORE: 3c0ba6b https://reactos.org/testman/compare.php?ids=86661
VBox AFTER: 107892c https://reactos.org/testman/compare.php?ids=???
https://reactos.org/testman/compare.php?ids=86661,???

**Comment by katahiromz** [comment]
Let's go!

**Comment by gonzoMD** [comment]
You removed some #ifdef __REACTOS__. Are those changes imported/synced from Wine? Or is this forked now?

**Comment by katahiromz** [comment]
> Are those changes imported/synced from Wine? Or is this forked now?

Our sync was quite oldie. I had referred some code in Wine but the task of sync is far away. That is "out of sync".

**Comment by katahiromz** [comment]
Wine did move `kernel32` code into `kernelbase`.
The filename was also changed.

**Comment by gonzoMD** [comment]
> Wine did move some `kernel32` code into `kernelbase`. The filename was also changed.

Alright. Like they did with much comctl/win32 Code. So it's quite unsyncable. Understood.

**Pull request merged**
