### PR TITLE
[WIN32SS][NTGDI] usWinAscent and usWinDescent must be treated as signed

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
JIRA issue: [CORE-14994](https://jira.reactos.org/browse/CORE-14994)
`TT_OS2.usWinAscent` and `TT_OS2.usWinDescent` must be treated as `FT_Short`. These values affect font metrics. This PR will fix CORE-14994.

### CODE REVIEW

**Comment by katahiromz** [comment]
BEFORE:
spotify-before
AFTER:
spotify-after
The icon positions will be fixed.

**Comment by katahiromz** [comment]
fixing-metrics
Spotify's 3rd font metrics will be fixed.

**Comment by katahiromz** [comment]
signedness
The test program `DumpMetrics` suggests signedness of `usWinDescent`.

**Comment by katahiromz** [comment]
OK. Let's go for the testing stage...

**Comment by HBelusca** [comment]
Wow I didn't have the time to see the review request during this small few hours window !!

**Pull request merged**
