### PR TITLE
Email address changes, take spam precaution and a note for Turkish translation

### PR DESCRIPTION
**Pull request by eersoy93**
## Purpose

Email address changes, take spam precaution and a note for Turkish translation

JIRA issue: None

## Proposed changes

- Change my email address
- Take spam precaution for my and Arda Tanrıkulu's email addresses
- A new note for Turkish translations (see media/doc/For_Turkish_Translation.txt, old note deleted)

## TODO

No TODOs

### CODE REVIEW

**Comment by ThFabba** [comment]
Please use a more descriptive title. Every pull request makes changes.

**Comment by eersoy93** [comment]
@AmineKhaldi I don't understand you. I have separated into two commits, not as previous PR.

**Comment by AmineKhaldi** [comment]
@eersoy93 Actually the commits do not matter as these changes get combined into one commit (aka squashing) and this is why this looked exactly like the previous PR.
As to my request, @encodedpr clarified what seems to be the reason of your change that stood out (the rest being all email changes) so I will land this.

**Comment by eersoy93** [comment]
Why my commits weren't merged as my commits? The commit broke my ReactOS repository.

**Comment by gigaherz** [comment]
Because when we merge, the commits are changed to reflect who from the team accepted the commits. This is unavoidable. You should always keep a clean "master" branch and work on separate "work branches" that you can later discard. If you need to clean your repository, you can reset it to the upstream/master state. See the "git reset" command.

**Comment by eersoy93** [comment]
Thank you. :)

**Pull request merged**
