### PR TITLE
[GITHUB] build.yml: Split RosBE caching into restore and save actions

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Save RosBE immediately after its compilation,
and no matter the outcome of remaining/ReactOS steps.

Follow-up to fa7d5db.

## Proposed changes

- Use [actions/cache](https://github.com/actions/cache) v3 new feature.

### CODE REVIEW

**Review by maj113 — APPROVED** [review]

**Comment by maj113** [comment]
Since your PR didn't actually test the save function (because caches already exist so it wasn't ran) I tested this on my fork with no prior caches and got a couple warnings:
```
Run actions/cache/save@v3
  with:
    path: RosBE-CI
    key: RosBE-CI-Linux-8ce17749606c36b104f9dd3fe630f8de8d8[2](https://github.com/maj113/reactos/actions/runs/5990845173/job/16248609782#step:5:2)8498-f94ba214bd0582e7cbd2ef5d0d60cd749a17aa21-
    enableCrossOsArchive: false
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/reactos/reactos --files-from manifest.txt --use-compress-program zstdmt
Failed to save: Unable to reserve cache with key RosBE-CI-Linux-8ce17749606c[3](https://github.com/maj113/reactos/actions/runs/5990845173/job/16248609782#step:5:3)6b10[4](https://github.com/maj113/reactos/actions/runs/5990845173/job/16248609782#step:5:4)f9dd3fe630f8de8d828498-f94ba214bd0[5](https://github.com/maj113/reactos/actions/runs/5990845173/job/16248609782#step:5:5)82e7cbd2ef5d0d[6](https://github.com/maj113/reactos/actions/runs/5990845173/job/16248609782#step:5:7)0cd[7](https://github.com/maj113/reactos/actions/runs/5990845173/job/16248609782#step:5:8)49a17aa21-, another job may be creating this cache. More details: Cache already exists. Scope: refs/heads/Cache-changes, Key: RosBE-CI-Linux-[8](https://github.com/maj113/reactos/actions/runs/5990845173/job/16248609782#step:5:9)ce17749606c36b104f9dd3fe630f8de8d828498-f94ba214bd0582e7cbd2ef5d0d60cd749a17aa21-, Version: 6732a6573a3df3e663b14bf97f4a47eae57d17ce3e0d650b3183b57f6b25033c
Warning: Cache save failed.
```

image

**Comment by SergeGautherie** [comment]
> Since your PR didn't actually test the save function (because caches already exist so it wasn't ran)

Actually, [build-linux (clang, i386, Debug, 0x502)](https://github.com/reactos/reactos/actions/runs/5912736006/job/16036423057?pr=5593#logs) did compile and save successfully.

> I tested this on my fork with no prior caches and got a couple warnings:

Hum, you added a change of your own, which is wrong and broke the restore step,
hence the save step outcome looks like a fallout.

**Comment by maj113** [comment]
> Hum, you added a change of your own, which is wrong and broke the restore step, hence the save step outcome looks like a fallout.

ah yeah you are right  missed the fact it gets hashed here `${{hashfiles('./build_rosbe_ci.sh')`

**Comment by JoachimHenze** [comment]
What is the benefit/purpose of this PR? How does it help us?

**Comment by SergeGautherie** [comment]
> What is the benefit/purpose of this PR? How does it help us?

To cache RosBE (asap), especially if ROS build does not succeed. It saves computer and human resources.

**Comment by SergeGautherie** [comment]
This PR may be blocked by [ONLINE-911](https://jira.reactos.org/browse/ONLINE-911).

**Pull request closed without merging**
