### PR TITLE
[MEDIA][INF] Improve network adapter names

### PR DESCRIPTION
**Pull request by binarymaster**
Use more explicit names for network adapters.

JIRA issue: None

### CODE REVIEW

**Comment by ThFabba** [comment]
What's the source of these names?

**Comment by Extravert-ir** [comment]
They are from here: https://github.com/reactos/reactos/blob/d57f7becc3f320408008649fa21c86926d9d16b6/drivers/network/dd/e1000/hardware.c#L14

**Comment by binarymaster** [comment]
If there is a better list with friendly names of these adapters somewhere, please let me know.

**Comment by Mouvedia** [comment]
@binarymaster there is: http://ftp.elvitec.fr/Pleora/TECHNOTES-DEMOS/Network%20Adapters%20Knowledge%20Base%20Tech%20Note.pdf

But using the chipset is safer IMHO.

**Pull request merged**
