### PR TITLE
[TRANSLATION][WHOAMI] Add Italian resource

### PR DESCRIPTION
**Pull request by SebastianoPistore**
Review and fix based on @Fraizeraust translation.

### CODE REVIEW

**Comment by HBelusca** [comment]
Why does it look like a duplicate of PR #626 ?

**Comment by Fraizeraust** [comment]
You could've just submitted your review on my Pull Request (as in form of feedback -- like you did before) than duplicating it. I've committed your fixes nevertheless. Thank you!

**Comment by HBelusca** [comment]
Superseded by PR #626.

**Comment by SebastianoPistore** [comment]
Ops!

**Pull request closed without merging**
