### PR TITLE
[TRANSLATIONS] Estonian translation for Notepad and mspaint

### PR DESCRIPTION
**Pull request by cernodile**
## Purpose

Add initial et-EE translations for Notepad and mspaint applications under base/applications.

## Reason

I noticed there's little to no translations for Estonian other than the setup. This enticed me to start translating some applications by myself.

### CODE REVIEW

**Comment by HBelusca** [comment]
Hi! In our [rules and recommendations](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations) for new contributions we want the contributors to use their real name. I suppose this implies specifying both a first name and a (family) name. You should then fix your commits, thanks!

**Comment by cernodile** [comment]
@HBelusca Hello! Does this commit what you asked for? Both .rc files now include first and full name under the `TRANSLATOR:` section.

**Comment by HBelusca** [comment]
Hello! I meant the Git committer name. See the second line in e.g. https://github.com/reactos/reactos/commit/58b5afc89181600c86c34bc1c6d69d6cee232d49.patch
But the code header you added, it's ok, BUT we use a modified code header now, see https://www.reactos.org/wiki/Coding_Style#File_Structure.

**Comment by cernodile** [comment]
Due to me being a total flop, I'll have to redo the whole thing. You'll find it true once you see what my "fix" resulted in. `=?UTF-8?q?Joann=20M=C3=B5ndresku?= <joann.mondresku@gmail.com>`, oh well.. I'll keep trying until I get it right.

**Comment by cernodile** [comment]
@HBelusca Hello, seems like I can't comply with one of the rules without breaking GitHub. It seems as if I include `õ` from my name (Joann Mõndresku), it breaks the `From:` field to `=?UTF-8?q?Joann=20M=C3=B5ndresku?= <joann.mondresku@gmail.com>`. Unless it's okay to make my name be "Joann Mondresku" (note the õ is replaced with o), I can't do ANY commits to the repository. Kind of sad, because I already took the effort to do this and attempt fix it for a long time. I've verified the `õ` character truly is the issue (even from the web interface and Git client both!)

**Comment by binarymaster** [comment]
@cernodile this is quite normal representation of name, when it contains unicode characters.

**Comment by cernodile** [comment]
@binarymaster so is it okay to keep it with `o`, or does it have to stay in the broken format?

**Comment by binarymaster** [comment]
See this for example:

https://github.com/reactos/reactos/commit/9e07da5ccb84b5aad5d3ca1dee82af5efaffdd30.patch

**Comment by cernodile** [comment]
@binarymaster I see.. so it's completely fine. I'll remake the branch and open new PR. Thank you for your time.

**Comment by HBelusca** [comment]
Hi! Sorry for not having replied sooner.
You can keep your existing branch as is, and just modify the committee name with git.
I'll write later the commands. Actually I could be able to fix myself your branch before committing.

**Pull request closed without merging**
