### PR TITLE
[CODEOWNERS] Add UniATA

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Follow-up to #1517 comments.

Cc @ThFabba

### CODE REVIEW

**Comment by Mouvedia** [comment]
While you are at it, remove the `, learn_more` duplicates.

**Comment by cernodile** [comment]
> While you are at it, remove the `, learn_more` duplicates.

Likely intentional to match all variants of the username on each platform. (learn_more on roslogin, learn-more on gh)

**Comment by learn-more** [comment]
@cernodile correct.

**Comment by SergeGautherie** [comment]
> While you are at it

I assume you could submit your own PR...

**Comment by tkreuzer** [comment]
Is there a reason we are not using a CODEOWNERS file instead? https://github.blog/2017-07-06-introducing-code-owners/

**Comment by SergeGautherie** [comment]
> CODEOWNERS

See #1705 then.

**Comment by SergeGautherie** [comment]
Rebased, after #1705.

**Pull request merged**
