### PR TITLE
[USER32_APITEST][INCLUDE] Add MessageStateAnalyzer testcase

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
I want to visualize the message stream and verify the states of each message.
JIRA issue: [ROSTESTS-328](https://jira.reactos.org/browse/ROSTESTS-328)

- Add a testcase named `MessageStateAnalyzer` into `user32_apitest`.
- Also fix type casts in `<windowsx.h>`.

### CODE REVIEW

**Comment by katahiromz** [comment]
Win2k3:
MessageStateAnalyzer-Win2k3
Successful.
Win10:
MessageStateAnalyzer-Win10
Successful.

**Comment by learn-more** [comment]
This issue is also related to message ordering:
https://jira.reactos.org/browse/CORE-12052
the attached `splits.rar` contains a test application that reproduces the exact crash.

**Comment by BenNottelling** [comment]
`Trivial 1`
Make trivial changes in a local branch then push as one commit. Should `Simplify 1` commit history

**Comment by katahiromz** [comment]
Let's go!

**Comment by learn-more** [comment]
This seems very closely related to tests like https://git.reactos.org/?p=reactos.git;a=blob;f=modules/rostests/apitests/user32/CreateWindowEx.c;hb=34bf24756a6ebad1bac8954670a30570cd2f7479 ?

**Comment by katahiromz** [comment]
It looks like caching some message data.

**Comment by katahiromz** [comment]
Win2k3:
MessageStateAnalyzer-Win2k3
Still successful.
Win10:
MessageStateAnalyzer-Win10
Successful.

**Comment by HBelusca** [comment]
@katahiromz : Please let us know when your PR is not work-in-progress anymore.

**Comment by katahiromz** [comment]
@learn-more Can you write the better code than this PR? Is this PR useful?

**Comment by katahiromz** [comment]
I'm ready to go if you approve this PR.

**Pull request merged**
