### PR TITLE
[SHELL32] Refresh folder icon and synchronize folder view

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

This PR makes the folder icon automatically refreshed.
JIRA issue: [CORE-11407](https://jira.reactos.org/browse/CORE-11407), [CORE-12336](https://jira.reactos.org/browse/CORE-12336)

### CODE REVIEW

**Comment by katahiromz** [comment]
folder-shot

**Comment by yagoulas** [comment]
I think that the workaround you removed in changenotify is needed for a reason there.

**Comment by katahiromz** [comment]
@yagoulas: I dare go to kill the workaround.

**Comment by katahiromz** [comment]
Renaming files won't be synchronized... Is SHChangeNotify wrong?

**Comment by learn-more** [comment]
@katahiromz There might be some problem in explorer with listening to SHChangeNotify listeners.

**Comment by yagoulas** [comment]
I bet most of your problems disappear when you try again in something other than the desktop

**Comment by katahiromz** [comment]
`SHChangeNotify(SHCNE_RENAMEITEM, ...)` was surely called from `CFSFolder::SetNameOf`, but the control won't reach to `CDefView::OnChangeNotify`. In the other place than Desktop (ex. C:\), it also happens.

**Comment by katahiromz** [comment]
I confirmed SHChangeNotify(SHCNE_RENAMEITEM, ...) was surely called from CFSFolder::SetNameOf,
but the SHCNE_RENAMEITEM won't reach CDefView::OnChangeNotify.

The check list:
- [ ] Investigate whether every DefView window handle is registered.
- [x] Investigate whether SHChangeNotify(SHCNE_RENAMEITEM, ...) was called in renaming the file.
- [ ] Investigate the control path of SHChangeNotify(SHCNE_RENAMEITEM, ...).
- [ ] Investigate why SHCNE_RENAMEITEM won't reach CDefView::OnChangeNotify.

**Comment by katahiromz** [comment]
Time is up.

**Pull request closed without merging**
