### PR TITLE
[THEMES] New theme - Breeze

### PR DESCRIPTION
**Pull request by EnterWINE**
I made a new "Breeze" theme. The design is made in the style of KDE 5. The design is made in the style of KDE 5. 
VirtualBox_Windows_05_03_2020_11_22_23
VirtualBox_Windows_05_03_2020_11_23_08
VirtualBox_Windows_05_03_2020_11_23_58

### CODE REVIEW

**Comment by JoachimHenze** [comment]
Imho whenever we add a new theme into the tree, we should choose an old one to replace. In case Breeze would be using the stock fonts and enough people would agree, then I recommend to replace the Mizu theme in this case with Breeze, as the Mizu theme currently still requires us to ship non-2k3sp2-stock-fonts, which is a burden. "EnterWINE", can you confirm that Breeze just relies on the stock fonts (and does not depend on SourceSans*)? In this case I would personally upvote the replacement of Mizu with Breeze.

**Comment by BenNottelling** [comment]
If Mizu get's replaced I'd quite like to see it easily addable from RAPPS, it's a great theme IMO

**Comment by EnterWINE** [comment]
Breeze it only uses standard fonts. I didn't touch the fonts

**Comment by cernodile** [comment]
@JoachimHenze 
> Imho whenever we add a new theme into the tree, we should choose an old one to replace. 

What about trimming the most heaviest msstyle - currently Modern uses 2.71MB compared to every other theme being 1.00-1.15MB. Currently Mizu and Modern look very similar, whereas Mizu looks more polished. If the fonts do add up more space, I believe a substitute could be found with original author of Mizu.

To OP:
As for the this theme - it does look adequate, but could use a bit of detailing and paddings on the taskbar. Your font configuration does look a bit off - so I'm curious about how it looks on XP/2003 as well. I'm also curious about the overall stats of the theme such as size added to the ISO.

**Comment by blackcrack** [comment]
i use openmandriva, Fedora .. i hope, Breeze become never a Theme Standard in Reactos
We should have a Theme-Repository like Rapps from an external hosting, maby on the Ros-Servers, but not by side of the Codes, because it inflates Reactos unnecessarily.
best

**Comment by EnterWINE** [comment]
> I'm also curious about the overall stats of the theme such as size added to the ISO.
1.1 Mb

**Comment by blackcrack** [comment]
naaa, it's not only breeze, the whole other summarize it too, think about ;)

**Comment by JoachimHenze** [comment]
> @JoachimHenze
> 
> > Imho whenever we add a new theme into the tree, we should choose an old one to replace.
> 
> What about trimming the most heaviest msstyle - currently Modern uses 2.71MB compared to every other theme being 1.00-1.15MB. Currently Mizu and Modern look very similar, whereas Mizu looks more polished. If the fonts do add up more space, I believe a substitute could be found with original author of Mizu.

My focus on the additional fonts in Mizu is, because they require memory even when the theme is not used. Whereas other themes just require iso and HDD space when not used. Modern is memory-neutral when not used, Mizu is not. As said this is just my reasoning. Substituting with stock-fonts would be an excellent solution as well ofc, but foxlet did not seem to like that idea.

Eventually it makes sense to have a poll, which one to replace then (keeping the existing instead of adding Breeze ofc should be a possible option as well)

**Comment by Fraizeraust** [comment]
Put Breeze in RAPPS. Problem solved, everyone's happy.

**Comment by HBelusca** [comment]
Regarding new extra themes: we need to find a reliable way to have them available from the internet in a reliable manner (hosted where? separate github repo like the rapps?...) so that they can be made available as downloads from rapps while not cluttering the ISO.

**Comment by oleg-dubinskiy** [comment]
Yes. And move all current themes there except Lautus too.
Probably it is possible to create a separate directory in our current software repo, like this: https://svn.reactos.org/packages/.

**Comment by cuchma19** [comment]
The theme takes up little space.  Why not just add Breeze?

**Comment by ghderty** [comment]
>cuchma19 
>EnterWINE
>ConLenov

[Deja Vu](https://github.com/reactos/reactos/pull/1946)

**Comment by learn-more** [comment]
> > cuchma19
> > EnterWINE
> > ConLenov
> 
> [Deja Vu](https://github.com/reactos/reactos/pull/1946)

thanks.

**Comment by EnterWINE** [comment]
Why did you close? I invested in design. I have nothing to do with these guys. I am registered much earlier than them. Proof https://github.com/EnterWINE/Kaomoji-Manager

**Comment by blackcrack** [comment]
@HBelusca don't forget the Themes pack from my files, where i have collecting, this can you use also
and the "home" pages could be linked from deviantart .. or directly the adresses from deviantart.. but if they on this place deletet it's gone, but if on a extra GH-Repo uploaded have Reactos the hand over it
and the Homepages could still linked on the Deviantart.. because if the Member Die or never be in deviantart could the Theme stay still for download on the repo from Reactos .. maybe on github..

**Comment by learn-more** [comment]
Ok, maybe I judged too early.

**Comment by HBelusca** [comment]
> Why did you close? I invested in design. I have nothing to do with these guys. I am registered much earlier than them. Proof https://github.com/EnterWINE/Kaomoji-Manager

Then somebody else (ConLeonov) is imitating you:
https://github.com/ConLenov/kaomoji_manager

**Comment by Zero3K** [comment]
Does it really matter what he was involved with before? This theme looks nice and I agree with the adding of it to ROSAPPS or the replacing of one of the themes it comes with.

**Comment by learn-more** [comment]
> Why did you close? I invested in design. I have nothing to do with these guys. I am registered much earlier than them. Proof https://github.com/EnterWINE/Kaomoji-Manager

Ok, clearly you are trying to bullshit us.
ConLenov == EnterWINE == cuchma19

Regardless of the fact if you did invest time in this, you are using multiple accounts with fake names to comment on your own pull requests.

Please do not make another PR.

**Comment by ghderty** [comment]
>I have nothing to do with these guys.

https://vk.com/reactos_witnesses?w=wall-162753964_1355
https://vk.com/reactos_witnesses?w=wall-162753964_1434
https://vk.com/reactos_ru?w=wall-1086956_79791_r79793
https://vk.com/enterwine

https://github.com/reactos/reactos/pull/1956#pullrequestreview-297837513

**Comment by EnterWINE** [comment]
I'm not ConLenov. My VK: https://m.vk.com/elijahmahone
My Instagram: https://www.instagram.com/elijah_mahone
Look at the date of registration on the github with me and he. It’s not my fault that my nickname matches his address

**Comment by HBelusca** [comment]
> I'm not ConLenov. My VK: https://m.vk.com/elijahmahone
> My Instagram: https://www.instagram.com/elijah_mahone
> Look at the date of registration on the github with me and he. It’s not my fault that my nickname matches his address

https://github.com/EnterWINE/Kaomoji-Manager/blob/dea5eb57b077d9e3f71081a3993659c6e50898e3/kaomoji/Debug/CL.write.1.tlog#L1-L15

And I'm not Hermes Belusca but it's not my fault that my account matches this name :trollface:

**Comment by EnterWINE** [comment]
At that time, I was making a program from his computer through teamviewer. We stream then did.

**Comment by cernodile** [comment]
> I have nothing to do with these guys.
> I was making a program from his computer through teamviewer

You're going circles here, you are now contradicting yourself. The decision has been made, you're altering the public perception of your PRs.

**Comment by Zero3K** [comment]
Its not going to be added. You messed up by associating yourself with them. Get rid of all references to them and start from scratch and then you might be able to make another PR.

**Comment by EnterWINE** [comment]
Where did you hate ConLenov? what does it all mean?

**Comment by ghderty** [comment]
>I have nothing to do with these guys.
>I'm not ConLenov.
>It’s not my fault that _my nickname matches his address_

[Does that mean that this PR contains someone else's work?](https://vk.com/wall-1086956_79564?reply=79578)

**Comment by Zero3K** [comment]
Maybe he modified that person's code?

**Comment by ghderty** [comment]
>I made a new "Breeze" theme

In that case that person's work not even credited, which is even more shady than #1946 and #1956.

**Comment by EnterWINE** [comment]
Why not just add a Breeze theme to ReactOS? No need to do a "show"

**Comment by spetreolle** [comment]
New Theme *is* KDE

**Comment by spetreolle** [comment]
New Theme *is* KDE

**Pull request closed without merging**
