### PR TITLE
[NTUSER] co_UserDestroyWindow: Check Window->pcls is not NULL

### PR DESCRIPTION
**Pull request by TAN-Gaming**
## Purpose

JIRA issue: [CORE-18821](https://jira.reactos.org/browse/CORE-18821)

### CODE REVIEW

**Review by JoachimHenze — APPROVED** [review]

**Review by learn-more — CHANGES_REQUESTED** [review]
This seems like a hack?
How can a window be destroyed when it has no class?
Then it should not even be created.

**Comment by KRosUser2** [comment]
> This seems like a hack? How can a window be destroyed when it has no class? Then it should not even be created.

Yes but here we have access to a member of Null.  Maybe an ERR message to be added since this is not supposed to happen ?

**Comment by TAN-Gaming** [comment]
> How can a window be destroyed when it has no class?

From JIRA issue: This happens after WM_CREATE message failed.

**Comment by TAN-Gaming** [comment]
@KRosUser2 I agree that an ERR message is better than a BSOD.

**Comment by yagoulas** [comment]
Yes, but why does it happen? Not understanding wtf is going on in our code is recipe for disaster.

**Comment by TAN-Gaming** [comment]
Incorrect fix, closed.

**Pull request closed without merging**
