### PR TITLE
[BTRFS] sha256.c: Restore upstream code. CORE-16679

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

2 commits, so you can choose.

Addendum to 3ba423996c41f9d8a6284a0aac1a44aa332815a6.
JIRA issue: [CORE-16679](https://jira.reactos.org/browse/CORE-16679)

### CODE REVIEW

**Comment by ColinFinck** [comment]
We are compiling with C99 enabled now, so this should no longer be necessary.
Can you check if we can restore the original code without any `#ifdef __REACTOS__`?

**Comment by SergeGautherie** [comment]
> Can you check

Not yet, as a VS2015 env is still missing...

**Comment by SergeGautherie** [comment]
Not `WIP` anymore.

**Comment by Extravert-ir** [comment]
It makes sense to either restore all of the code to original (in places where we changed the style to C89), or just wait for a next release.
I prefer the latter

**Comment by ColinFinck** [comment]
Closing this PR then as we're going to fix this when importing a new WinBtrfs release.
Which shouldn't be too far away considering the current daily commits to the winbtrfs upstream repository.

**Pull request closed without merging**
