### PR TITLE
[SHELL32] Don't show taskbar button of Folder Options

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

JIRA issue: [CORE-10481](https://jira.reactos.org/browse/CORE-10481)

## Proposed changes

- Create a stub window "MSGlobalFolderOptionsStub".
- Create Folder Options dialog owned by the stub window.

### CODE REVIEW

**Comment by katahiromz** [comment]
BEFORE:
folder-options-ros
AFTER:
folder-options-ros-after

**Comment by binarymaster** [comment]
> Now if the folder options dlg is totally covered by something else, it can not longer be accessed.

Should be accessible via Alt+Tab, as in Windows.

**Comment by katahiromz** [comment]
Windows 7 Taskbar Guidelines:
https://docs.microsoft.com/en-us/windows/desktop/uxguide/winenv-taskbar

>Make the following window types appear on the taskbar (for Windows 7, by using a taskbar button thumbnail):
>- Property sheets
>- ...

The Windows 7 guidelines say a standalone property sheet window should appear on the taskbar. However we are implementing a Windows 2003 clone.

>it can not longer be accessed.
Yes, Alt+Tab can access it.

**Comment by gigaherz** [comment]
In any case, we should prefer consistency. If we are hiding most property
sheet windows, we should hide all. If we choose to change to the win7
guidelines, we do that for all too.

**Comment by katahiromz** [comment]
This "flying stub" technique enables to make modal property sheets modeless-like. We have to use flying stubs in file property sheets or make them modeless all. Modeless property sheets are complicated to implement.

**Comment by JoachimHenze** [comment]
From end users perspective (usability), I'd personally prefer the cpls to show a taskbar pane, like in Win7.
I doubt anything on earth relies on the "proper 2k3"way of not showing them.
I would appreciate some of our devs participating that poll:
https://linkto.run/p/UII65IFE

**Pull request merged**
