### PR TITLE
[HAL:APIC] Ensure the interrupt gets requested immediately in ApicRequestSelfInterrupt.

### PR DESCRIPTION
**Pull request by ThFabba**
## Purpose
First, wait for the APIC to be idle before requesting an interrupt. Then, wait until we actually see the interrupt request bit set.
This will ensure that if we're at a low enough IRQL, the software interrupt will happen immediately (which is an invariant that Windows's IRQL mechanism relies on).

JIRA issue: [CORE-17663](https://jira.reactos.org/browse/CORE-17663)

### CODE REVIEW

**Comment by ThFabba** [comment]
@DarkFire01 I can't add you as a reviewer, but would appreciate if you had a look.

**Comment by HBelusca** [comment]
Could it be possible that it fixes what was (temporarily?) disabled by PR #3609 ?

**Review by HBelusca — APPROVED** [review]
lgtm

**Comment by ThFabba** [comment]
> Could it be possible that it fixes what was (temporarily?) disabled by PR #3609 ?

I'm not sure if the two are related, it's possible. But this PR fixes an active bug in master, so if the two are related then it would appear that disabling lazy IRQLs actually did not completely fix whatever the issue was.

**Review by DarkFire01 — APPROVED** [review]
Ah cool :D that looks great to me!
You're going to have situations where interrupts targeting other groups (IPIs) will still do this, but honestly if we do something similar in nature to what you do here we'll be fine when it comes to master.
Thank you for looking at this!

**Comment by Extravert-ir** [comment]
> Could it be possible that it fixes what was (temporarily?) disabled by PR #3609 ?

This change is not relevant anymore - lazy IRQL was fixed since than and turned back on.

**Pull request merged**
