### PR TITLE
[GLU32] Sync with glu 9.0.1

### PR DESCRIPTION
**Pull request by omasanori**
## Purpose

This PR introduces changes incorporated into the latest upstream release to `dll/opengl/glu32/`.

### CODE REVIEW

**Comment by omasanori** [comment]
Travis CI's failure is a mismatch in code formatting. Is it OK to introduce an exception to clang-format like e92ab76d0d60314c49207be3930f9e6b9f92aea6 since glu is a third party code?

**Comment by katahiromz** [comment]
Modifying original code formatting will make maintenance harder. Don't change code format.

**Comment by omasanori** [comment]
@katahiromz I agree.
There are two options then: a) ignoring CI statuses, or b) adding `.clang-format` to exclude `dll/opengl/glu` from code formatting check. I prefer b), but there might be some concerns about adding too many exceptions throughout the codebase. Any thoughts?

**Comment by HBelusca** [comment]
For the time being, just do a).

**Comment by omasanori** [comment]
@HBelusca Thank you for the suggestion!

Then, I am ready for review. :-)

**Pull request merged**
