### PR TITLE
Ac97 import

### PR DESCRIPTION
**Pull request by TheDeadFish**
## Purpose
Import of AC97 sample driver

## Proposed changes
Import AC97 sample driver into drivers\wdm\audio\drivers\ac97
Insert missing definitions required to build into ddk

-- Explanation of commit "fixed buffer issue" --
Every time the DMA enable bit is written to 1, the emulated hardware also increments the buff index. The DMA enable bit was being set repeatedly during playback which screwed up the buffering. The fix checks if DMA is enabled, and if so it does not try and enable it again. 

## issues
Garbled buffers (sometimes it works perfectly)
Crashes

### CODE REVIEW

**Comment by Zero3K** [comment]
The crash's debug log is attached.

[ac97-crash-reactos.log](https://github.com/reactos/reactos/files/5180406/ac97-crash-reactos.log)

**Comment by JoachimHenze** [comment]
Colin, I added you for review to check the license one last time. We discussed it here the last time https://jira.reactos.org/browse/CORE-16999?focusedCommentId=122887&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-122887 and you found it to be ok (assumed MIT-licensed).

**Comment by TheDeadFish** [comment]
Original driver source:
https://github.com/microsoftarchive/msdn-code-gallery-microsoft/tree/master/Official%20Windows%20Driver%20Kit%20Sample/Windows%20Driver%20Kit%20(WDK)%208.1%20Samples/%5BC++%5D-windows-driver-kit-81-cpp/WDK%208.1%20C++%20Samples/AC97%20Driver%20Sample/C++

**Comment by Doug-Lyons** [comment]
When I opened the "Original driver source" as shown  and navigate up a few levels to find a reference to a license, I find this page:
https://github.com/microsoftarchive/msdn-code-gallery-microsoft/tree/master/Official%20Windows%20Driver%20Kit%20Sample/Windows%20Driver%20Kit%20(WDK)%208.1%20Samples 
 It shows: "License - MS-LPL" and if we look at https://jira.reactos.org/browse/CORE-16365 we can see Colin's statements as follows:
"Many of these samples have been released under Ms-LPL (not Ms-PL), which limits derivative works to run on the "Microsoft Windows operating system product". This may or may not pose a problem for ReactOS, but I want to stay away from Ms-LPL if possible."

**Comment by TheDeadFish** [comment]
msdn-code-gallery-microsoft repo appears to have conflicting licenses. There is an MIT license at the root of the entire thing. https://github.com/microsoftarchive/msdn-code-gallery-microsoft/blob/master/LICENSE. Very confusing.

**Comment by Doug-Lyons** [comment]
@TheDeadFish, That is a very good point. It seems that the license at the TOP should be the controlling one.

**Comment by Zero3K** [comment]
This might apply to the repository that is being linked to:

https://github.com/microsoft/Windows-classic-samples/issues/24

**Comment by JoachimHenze** [comment]
@TheDeadFish does this driver work **flawlessly** in Windows 2003 Server?

**Comment by TheDeadFish** [comment]
The driver does work pretty well on win2k3. I am not sure about flawless as in without any dropouts because I am not sure my VM runs perfectly. It must be noted that it only works on windows if built with the microsoft tools, the reactos ddk does not produce functioning audio drivers for windows.

**Comment by Zero3K** [comment]
The only issue with it when installed on 2K3 is that it gets stuck in a loop of a couple of seconds of recently played audio after playing some for a while. It might be related to the noise occurring in ReactOS when playing audio with it installed.

**Comment by ColinFinck** [comment]
With GitHub clearly stating "microsoftarchive/msdn-code-gallery-microsoft is licensed under the MIT License" [1] and Raymond Chen officially confirming the relicensing [2], I see the imported AC97 sample driver being available under the permissive MIT license, which is perfect for us!
May even be worth to check if some more code we imported under MS-PL is now available under MIT.

To eradicate any doubts, I suggest copying the LICENSE file [1] to the root of the imported AC97 driver.

[1] https://github.com/microsoftarchive/msdn-code-gallery-microsoft/blob/master/LICENSE
[2] https://github.com/microsoft/Windows-classic-samples/issues/24

**Comment by Zero3K** [comment]
@ColinFinck Its already there as license.txt.

**Comment by Zero3K** [comment]
Here's a debug log of a different crash caused by the same lines of code shown in the previous one that I made with WinDbg:

[ac97-crash-reactos-msvc.log](https://github.com/reactos/reactos/files/5210800/ac97-crash-reactos-msvc.log)

**Comment by Zero3K** [comment]
The garbled and hanging audio is caused by a "bug" in VirtualBox 5.x and up.

**Comment by blackcrack** [comment]
https://www.virtualbox.org/ticket/19927

( @all : for some should you announcing here and add a ticket by Oracle, make a login by oracle and you can add some Bugreports at VBox ;) therewith have we are !all a advantage of this and a better running Virtualbox (i meant there with a better **open source** VirtualMashin )

[https://www.virtualbox.org/wiki/Bugtracker](https://www.virtualbox.org/wiki/Bugtracker)

best regards
Blacky

**Comment by learn-more** [comment]
@NailYggdrago aka Brian Kirk has been blocked for continuing his harassment, even though he has been banned under multiple accounts already.

**Pull request closed without merging**
