### PR TITLE
[SHELL32][SHELL32_APITEST] FindExecutable: Add PRF_FIRSTDIRDEF flag

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

Follow-up to #6635. The directory search without this flag didn't work.
JIRA issue: [CORE-19493](https://jira.reactos.org/browse/CORE-19493)

## Proposed changes

- Add `PRF_FIRSTDIRDEF` flag for `PathResolveW` call.
- Delete needless macro definitions in `PathQualifyExW`.
- Remove an assertion in `IsLFNDriveW`.
- Fix `shell32_apitest:FindExecutable` testcase.

## TODO

- [ ] Do big tests.

### CODE REVIEW

**Comment by katahiromz** [comment]
Test KVM (BEFORE): 558ab78 https://reactos.org/testman/compare.php?ids=94333
Test KVM (AFTER): ba22f65

Test VBox (BEFORE): 558ab78 https://reactos.org/testman/compare.php?ids=94332
Test VBox (AFTER): ba22f65

**Comment by katahiromz** [comment]
Retrial.

Test KVM (BEFORE): 558ab78 https://reactos.org/testman/compare.php?ids=94333
Test KVM (AFTER): ba22f65

Test VBox (BEFORE): 558ab78 https://reactos.org/testman/compare.php?ids=94332
Test VBox (AFTER): ba22f65

**Review by HBelusca — APPROVED** [review]
looks OK from code point of view, but let's wait until our infra gets fixed.

**Comment by katahiromz** [comment]
Test KVM (BEFORE): 558ab78 https://reactos.org/testman/compare.php?ids=94333
Test KVM (AFTER): eed310a

Test VBox (BEFORE): 558ab78 https://reactos.org/testman/compare.php?ids=94332
Test VBox (AFTER): eed310a

**Pull request merged**
