### PR TITLE
[SDK:REACTOS][SHELL32] Clarify RosGetProcessEffectiveVersion() a bit

### PR DESCRIPTION
**Pull request by SergeGautherie**
Split off of #6170.

## Purpose

Clarify variable uses, ...

Addendum to 7fb91d9 (0.4.15-dev-6915).

## Proposed changes

- Clarify RosGetProcessEffectiveVersion() a bit

### CODE REVIEW

**Comment by learn-more** [comment]
Re-formatting/ re-writing code that has just been committed like this to your personal taste is a bit rude imo, and I don't see any obvious gains from this change.

**Comment by JoachimHenze** [comment]
> Re-formatting/ re-writing code that has just been committed like this to your personal taste is a bit rude imo, and I don't see any obvious gains from this change.

Well personally I think I **do** see a benefit in the proposed change: In case shimVer != 0 we do save a function call to NtCurrentPeb();
I think the PR deserves a chance.

**Comment by learn-more** [comment]
> > Re-formatting/ re-writing code that has just been committed like this to your personal taste is a bit rude imo, and I don't see any obvious gains from this change.
> 
> Well personally I think I **do** see a benefit in the proposed change: In case shimVer != 0 we do save a function call to NtCurrentPeb(); I think the PR deserves a chance. Unless you can prove it to be wrong ofc, or would have a bit more profound reasons to reject it / request changes on it.

What function call?
And no, I am not going to 'prove' anything, nor am I going to spend even a second more on this.
I know that you like to 'optimize' code by renaming stuff to have shorter names, but all that is doing is generate noise that serves literally no purpose.

**Comment by whindsaks** [comment]
> we do save a function call to NtCurrentPeb

NtCurrentPeb is usually a memory access through a register, not a function call.

Anyway, I don't mind the re-write although the PR was open for over a month and I'm generally responsive to suggestions.

**Comment by SergeGautherie** [comment]
> a bit rude

It may be, sorry, but sometimes things happen in such order.

--

> the PR was open for over a month and I'm generally responsive to suggestions.

I did not participate in your PR.
I noticed these tweaks while reviewing MSVC warnings after its merge to master.

**Review by JoachimHenze — APPROVED** [review]

**Comment by whindsaks** [comment]
Go away

**Comment by learn-more** [comment]
> Go away

In this case the bot was correct to do something.
I as maintainer noted that I did not see any obvious gains,
and the contributor did not respond to clarify any potential gains at all.

**Pull request closed without merging**
