### PR TITLE
[SHELL32] Shift-Right-Click patch: Plan A

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

JIRA issue: [CORE-16519](https://jira.reactos.org/browse/CORE-16519)

Please compare with Plan B: https://github.com/reactos/reactos/pull/2082

### CODE REVIEW

**Comment by JoachimHenze** [comment]
Wouldn't that make *all* extended entries available in standard context menu?
If yes, then this is not what I had in mind. I really just wanted to have the cmd thingy added to default menu.
But eventually I misread the patch?

**Comment by HBelusca** [comment]
You should definitively support the "Extended" registry value setting, per Windows compatibility.

**Comment by katahiromz** [comment]
> Wouldn't that make all extended entries available in standard context menu?

Yes. It affects all extended menu items.

**Comment by katahiromz** [comment]
CLOSED.

**Pull request closed without merging**
