### PR TITLE
[BOOTDATA] Fix path to temp folder for some locales

### PR DESCRIPTION
**Pull request by Harteex**
## Purpose

Fix the path to the temp folder for some locales. Having an invalid temp folder will cause issues, for example copying files as part of driver installation (device manager -> upgrade driver) will fail.

## Proposed changes

- Sync the path of the temp folder from the userenv resource files for some locales where the path didn't match the English one.

Note: For the locales I added the correct path I added the other English strings. This was done for a few reasons:
- Some of the existing languages already had all the English untranslated strings, so match the current style
- Make it easer to get started for translators in the future
- Prevent having the path accidently overwritten with the English path when a new translator starts working in this file

### CODE REVIEW

**Comment by Harteex** [comment]
@HBelusca Here is a screenshot from the Swedish version where "Local Settings" is localized, but not the actual Temp folder. For the other locales, I matched the translated strings in userenv. I don't know if the strings in userenv are correct for the other languages, but as the mismatch will cause errors for those locales, it's better now than before.

593d0c08a2f37_documentsandsettings

**Comment by HBelusca** [comment]
Thanks. I was asking, because i think everything inside "Local Settings" remains unlocalized. This should be checked ofc. with e.g. thai or whatever. Also since you've mentioned it: I suppose those ppl who translated also in userenv didn't check on windows (xp/2k3) whether "Temp" was localized or not (and I don't really see why it should be localized actually)

**Comment by Harteex** [comment]
What would you prefer me to do with this PR?
1. Leave it as is. This fixes the problem for the these locales, even though it might not be correct according to the localized xp versions.
2. Only fix the problem for the Swedish version, where I know the change is correct. This leaves the other locales in a broken state.

I do not have Windows XP in other languages so I can not check the folder names there.

**Comment by Harteex** [comment]
After consulting HBelusca we decided to only fix the Swedish locale for now (as it's the only one that I'm sure has the correct paths).
I've amended the commit.

**Pull request merged**
