### PR TITLE
[APPWIZ.CPL] PL Translate update

### PR DESCRIPTION
**Pull request by pithwz**
[APPWIZ.CPL} PL Translate update

appwiz

### CODE REVIEW

**Comment by pithwz** [comment]
apply only this
https://github.com/reactos/reactos/pull/2337/commits/038c0f8fefe9d374deeb20bfee0cca063ffa8c26

**Comment by HBelusca** [comment]
Please fix your PR or close it (you just deleted completely the translation).

**Comment by binarymaster** [comment]
@pithwz use this:

```sh
git reset --hard 038c0f8fefe9d374deeb20bfee0cca063ffa8c26
git push --force-with-lease
```

**Comment by binarymaster** [comment]
@pithwz please enable this checkbox so I can handle your PRs.

image

**Pull request merged**
