### PR TITLE
Update Simplified Chinese translation.

### PR DESCRIPTION
**Pull request by njlyf2011**
I have corrected my mistakes.

### CODE REVIEW

**Comment by binarymaster** [comment]
Thanks for corrections! But your commit author name is still `njlyf2011`:

https://patch-diff.githubusercontent.com/raw/reactos/reactos/pull/169.patch

**Comment by njlyf2011** [comment]
My God ...
I will try again...

**Comment by binarymaster** [comment]
You can force-push your PR branch instead of creating new PRs. :wink:

**Comment by njlyf2011** [comment]
What should I do ...
Change git user name in Git command prompt and commit again?

**Comment by binarymaster** [comment]
Looks like you're commiting directly from GitHub, so add your name here:

https://github.com/settings/profile

**Comment by gigaherz** [comment]
You can use `git commit --amend --author "Name <email>"`, then force-push to your branch.

**Comment by njlyf2011** [comment]
How to force-push my PR branch in website ...
You know in China we cannot "git clone" a large project to local disk because we visit GitHub is very slow.

**Comment by gigaherz** [comment]
I see. Then you may have to do as @binarymaster says, I guess. Or one of us from the dev team can fix it for you if you say your git name & email here in a comment.

**Comment by binarymaster** [comment]
@gigaherz use these: `Luo Yufan <njlyf2011@hotmail.com>`

**Comment by gigaherz** [comment]
I have gone ahead and fixed your commit.

**Comment by njlyf2011** [comment]
Thank you very much ...

**Pull request merged**
