### PR TITLE
[CODEOWNERS] Add /dll/win32/msafd/ entry

### PR DESCRIPTION
**Pull request by SergeGautherie**

### CODE REVIEW

**Comment by SergeGautherie** [comment]
Cc @HeisSpiter

**Comment by HeisSpiter** [comment]
Nope.

**Comment by SergeGautherie** [comment]
> Nope.

Hum. Why should this entry not be listed?

**Comment by ThFabba** [comment]
Because clearly, Pierre doesn't want to maintain it.
It's not just a question of "who last touched this code".

**Comment by SergeGautherie** [comment]
Then, as a reviewer? And/Or someone else? Or simply an assigned entry for the time being?

**Comment by ThFabba** [comment]
Or, nothing?

**Pull request closed without merging**
