### PR TITLE
[MOUNTMGR] Properly look for device and break when found

### PR DESCRIPTION
**Pull request by SergeGautherie**
Addendum to a7f97cc70f62f6805e71b28eba51f52b942d22b4.

### CODE REVIEW

**Comment by HBelusca** [comment]
Cc @HeisSpiter

**Comment by BenNottelling** [comment]
Slightly different version was committed, this can be closed

**Comment by SergeGautherie** [comment]
> Slightly different version was committed

Which difference?

**Comment by BenNottelling** [comment]
> > Slightly different version was committed
> 
> Which commit? Which difference?

My bad I saw the OG commit :P

**Pull request merged**
