### PR TITLE
[PSDK][SHELL32] Make CLSID_NetworkConnections the default name

### PR DESCRIPTION
**Pull request by SigmaTel71**
## Purpose

Followup to discussion in [#7249](https://github.com/reactos/reactos/pull/7249#issuecomment-2294900531). @learn-more suggested me to guard it due to true `CLSID_` is not known yet, @HBelusca [suggested to link](https://github.com/reactos/reactos/pull/7266#issuecomment-2313322102) currently used by ReactOS name to the proper one to avoid breaking too much code.

NOTE: Early comments are related to the early version of this PR about 0x600 guarding for this CLSID name.

JIRA issue: None

## Proposed changes

Make `CLSID_NetworkConnections` available by default via `shlguid.h` and `#define` the currently used `CLSID_ConnectionFolder` to it in `shlguid_undoc.h`.

### CODE REVIEW

**Comment by whindsaks** [comment]
I don't agree with this. Shell CLSIDs are often undocumented (for a long time or forever) and putting anything other than functions behind a pre-processor version check is highly annoying. The shell is going to be in a 5.2 to 6.0 limbo for a long time without officially targeting 6.0 outright and these fences will get in the way. SHELL32 already declares `const GUID CLSID_NetworkConnections = { ...` for its own usage which is pointless if we can have it in a common header.

If you want to be pedantic, anything outside the `IShellFolder` implementation itself should not care what the CLSID of a virtual folder is, in this case they should use `CSIDL_NETWORK` to get a PIDL and then ask for the parsing name or the folders class which returns the CLSID in shell path form or the CLSID respectively. The only exception to this should be SHELL32 (ideally only CRegFolder.cpp but pidl.c currently knows too much about various folders).

**Comment by whindsaks** [comment]
It's not unreasonable to think that CLSID_ConnectionFolder is the internal name of the IShellFolder implementation but if this was spotted in a symbol somewhere, it would be useful to know if it was in SHELL32 or NETxyz.

CLSID_NetworkConnections clearly already exists in NT5:
XP CLSID_NetworkConnections

**Comment by SigmaTel71** [comment]
> CLSID_NetworkConnections clearly already exists in NT5

Given that, I would like to hear @JoachimHenze's opinion whether should I take the `CLSID_ConnectionFolder` out of `shlguid_undoc.h` and replace all occurencies in our codebase with the name stated in shell32 from XP/Server 2003, basically partially reverting what @ThFabba did. Looking forward for @learn-more's response as he participated in the discussion.

**Comment by learn-more** [comment]
In the past we did add guards like these, but I have no strong preference either way.
Whatever is decided, I would prefer it if there was a reference from one to the other (and probably back) as comment or whatever,
since both names seem to be used.

**Comment by whindsaks** [comment]
I have a strong hatred for these guards on anything other than exported functions. The internals of a .dll should be allowed to use Vista+ features even though it looks like NT5 from the outside.

A comment would be nice though.

**Comment by SigmaTel71** [comment]
> Whatever is decided, I would prefer it if there was a reference from one to the other (and probably back) as comment or whatever,
> since both names seem to be used.

In a way like this?
```c
DEFINE_GUID(CLSID_NetworkConnections, 0x7007ACC7, 0x3202, 0x11D1, 0xAA, 0xD2, 0x00, 0x80, 0x5F, 0xC1, 0x27, 0x0E); // also known as CLSID_ConnectionFolder
```
or

```c
DEFINE_GUID(CLSID_NetworkConnections, 0x7007ACC7, 0x3202, 0x11D1, 0xAA, 0xD2, 0x00, 0x80, 0x5F, 0xC1, 0x27, 0x0E);
#define CLSID_ConnectionFolder CLSID_NetworkConnections
```
I would be okay with the second option as it retains backwards compatibility with what we already have, just needs the header file to be changed from `shlguid_undoc.h` to `shlguid.h` (if other undocumented headers are not used) for those who use the unproven (?) current name.

**Comment by HBelusca** [comment]
The `#define CLSID_ConnectionFolder CLSID_NetworkConnections` solution (this define added in the shlguid_undoc.h, while the more official `CLSID_NetworkConnections` definition added in our public headers) would probably allow to avoid too many changes in our code base.

**Comment by SigmaTel71** [comment]
> The `#define CLSID_ConnectionFolder CLSID_NetworkConnections` solution (this define added in the shlguid_undoc.h, while the more official `CLSID_NetworkConnections` definition added in our public headers) would probably allow to avoid __too many changes in our code base__.

This way makes sense to me. I will add related `#define` to `shlguid_undoc.h` then and will contribute my future code using the official name. This PR will be converted to draft until I get things ready for merging.

**Comment by SigmaTel71** [comment]
Ready for code review; cc @JoachimHenze for diff size review.

**Review by whindsaks — APPROVED** [review]

**Review by learn-more — APPROVED** [review]

**Pull request merged**
