### PR TITLE
[FONTS][SETUP][BOOTDATA] Add Times New Roman fonts

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Add "Times New Roman" fonts.
JIRA issue: [CORE-16272](https://jira.reactos.org/browse/CORE-16272)

- Add "Times New Roman" and "Times New Roman Italic" fonts by duplicating "Liberation Serif" fonts and renaming them.
- Delete some "Times New Roman" font substitutes.
- Add LICENSE file.

I made these font files by using FontForge. Their family name is "Times New Roman". Their display names are "Times New Roman", "Times New Roman Bold", "Times New Roman Bold Italic" and "Times New Roman Italic". Their font filenames are times.ttf, timesbd.ttf, timesbi.ttf and timesi.ttf. The Underline Positions are hacked by adding an integer value for workaround of FontForge's bug.

### CODE REVIEW

**Comment by katahiromz** [comment]
Digitized data copyright (c) 2010 Google Corporation.
Copyright (c) 2012 Red Hat, Inc.
Copyright (c) 2019 Katayama Hirofumi MZ.

License: SIL Open Font License Version 1.1.

**Comment by katahiromz** [comment]
times

**Comment by shytzedaka** [comment]
@katahiromz if i am not wrong Firefox Uses Times New Roman Font by Default. So this may be interesting Text drawing wise.

**Comment by katahiromz** [comment]
Times New Roman vs Liberation Serif:
Times-New-Roman-vs-Liberation-Serif
Difficult to distinguish each other.

**Pull request merged**
