### PR TITLE
[BOOTLIB] Remove a useless 'FontDirectory' check. CORE-11590

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Reduce confusion.

Author = Victor Martinez.

JIRA issue: [CORE-11590](https://jira.reactos.org/browse/CORE-11590)

### CODE REVIEW

**Comment by SergeGautherie** [comment]
Cc @ionescu007, if he is still active.

**Comment by learn-more** [comment]
If it removes, confusion, why is there now a comment that indicates that it is null there?
Seems that it was not entirely clear...

**Comment by SergeGautherie** [comment]
> why is there now a comment that indicates that it is null there?

I don't think there is.
If my added comment is not clear to you, please suggest a better one.

**Comment by SergeGautherie** [comment]
> That's wrong too

What is wrong (too)?

> you may have run into the Line 95 code path.

Yes, that exactly is the trigger for this issue/PR...

**Comment by tkreuzer** [comment]
The only problematic path I see is when BlGetBootOptionString succeeds, but FontDirectory is NULL. I'm unsure, whether this can happen, but in any case, there should probably be a ```CustomDirectory = FALSE;``` in that path, too, because obviously, we don't want to free a static string.

**Comment by SergeGautherie** [comment]
> I'm unsure, whether this can happen,

It cannot:
https://git.reactos.org/?p=reactos.git;a=blob;f=boot/environ/lib/misc/bcdopt.c;hb=HEAD#l144
eventually only succeeds at lines 211-212.

> there should probably be a `CustomDirectory = FALSE;` in that path, too.

(For the Nth time, I can't help to notice that when I try to improve code, some people ask me not to, yet when I try not to, some people ask me to :-< Anyway...)

I agree that would be easier to read, yet it would be redundant.
My suggestions, to choose from:
1. Add `CustomDirectory = FALSE;` as and with a comment :-(
2. Add an `ASSERT(FontDirectory)` when `BlGetBootOptionString()` succeeds :-|
Somewhat useless and done nowhere else.
https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=BlGetBootOptionString
3. Merge the `if (!FontDirectory)` block into the `if (!NT_SUCCESS(Status))` one :-)

**Comment by HBelusca** [comment]
> (For the Nth time, I can't help to notice that when I try to improve code, some people ask me not to, yet when I try not to, some people ask me to :-< Anyway...)

Next time please work on actual bug fixes or implementation of missing features.

**Comment by SergeGautherie** [comment]
> work on actual bug fixes or implementation of missing features.

I do that too, but not only:
this PR is part of resolving a group of existing (`CID`) Jira issues, whether they eventually are major or minor.

**Pull request closed without merging**
