### PR TITLE
[BROWSEUI] Add ITaskbarList implementation

### PR DESCRIPTION
**Pull request by learn-more**
JIRA issue: [CORE-15424](https://jira.reactos.org/browse/CORE-15424)

### CODE REVIEW

**Comment by Biswa96** [comment]
Which file has these functions? Windows 2K3 hasn't.

**Comment by learn-more** [comment]
2k3 has this in shdocvw

**Comment by Biswa96** [comment]
This may help: [test.h.txt](https://github.com/reactos/reactos/files/2682974/test.h.txt)

**Comment by ThFabba** [comment]
Please don't do that. Decompiling is a last resort, not our method of choice for development.

**Comment by ThFabba** [comment]
What's the reason to have this in browseui rather than shdocvw? Avoiding Wine-synced code / compat with later Windows versions?

**Comment by Mouvedia** [comment]
@Biswa96 version got `SetActiveAlt` and `MarkFullscreenWindow` implemented.

**Comment by yagoulas** [comment]
@ThFabba : In windows shdocvw implement various stuff related to the shell but we decided to move them to either browseui or shell32. This allows us to have one less dependency when testing in windows. Another reason is that the two things, the shell and the web browser are kept completely separate.

**Pull request merged**
