### PR TITLE
[DESK] Fix crash when selecting 3D Text screen saver CORE-8217

### PR DESCRIPTION
**Pull request by zecarlos1957**
[DESK] Fix crash when selecting 3D Text screen saver
JIRA issue: [CORE-8217](https://jira.reactos.org/browse/CORE-8217)

CreateProcess needs dwCreationFlags parameter

### CODE REVIEW

**Comment by JoachimHenze** [comment]
There were concerns rised within CORE-8217 whether this fix is the correct way to approach the problem. And even after the fix it may hang (moving the parent window). I don't think it is right to touch desk.cpl at all here! I do vote for not committing this PR.

**Comment by SergeGautherie** [comment]
Is this issue/fix reproducible on Windows XP/S03?

**Comment by zecarlos1957** [comment]
This is not the correct  approach. So i close this PR

**Comment by zecarlos1957** [comment]
This is not the correct  approach

**Pull request closed without merging**
