### PR TITLE
[SHELL32] Implement 'New Link' (shortcut) menu item

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Right-Click Desktop, and Choose [New] --> [New Link]. Wizard will start up.
JIRA issue: [CORE-15511](https://jira.reactos.org/browse/CORE-15511)

Movie:
https://jira.reactos.org/secure/attachment/52364/ShortcutSuccessful.webm

### CODE REVIEW

**Comment by HBelusca** [comment]
I wonder thed, if memory serves well, why we did have the "new link" menu item working more or less ok some time ago, that used the settings from the `HKEY_CLASSES_ROOT\.lnk\shellnew` registry key?

**Comment by katahiromz** [comment]
@HBelusca, it may be my mistake. My ego is not trustworthy.

**Comment by HBelusca** [comment]
@katahiromz : I will try to check on older ReactOS versions tomorrow, to see whether my supposition was correct or not.

**Comment by katahiromz** [comment]
I will wait.

**Comment by HBelusca** [comment]
@katahiromz : Here is how it goes on ROS 0.4.8_REL:
New_link_on_ROS_0.4.8_REL
Note that it works **ONLY once**!! The question is: why?

**Comment by HBelusca** [comment]
UPDATE: I also have re-checked on master: it behaves exactly the same as in the screenshot above: the new-link wizard displays **only once** after a new clean installation; afterwards it doesn't display anymore.

**Comment by katahiromz** [comment]
grep NewLinkHere.

**Comment by HBelusca** [comment]
Yes I did that already, and the only relevant result is from hivesft.inf, pointing to HKCU\.lnk\shellnew .
I think that we have to look more into what CNewMenu::LoadAllItems() and the associated functions do there...

**Comment by katahiromz** [comment]
`rundll32` needs a short path. When I used `GetShortPathNameW`, the `ShellNew` command worked.

**Comment by katahiromz** [comment]
Because `CNewMenu::UnloadAllItems` doesn't clear `m_pItems`, `CNewMenu::InsertShellNewItems` won't call `LoadAllItems` after first time. That is the reason.

**Comment by katahiromz** [comment]
Cache for ".lnk" is not created. That's the second reason.

**Comment by katahiromz** [comment]
Retrial in #1518. CLOSED.

**Comment by HBelusca** [comment]
@katahiromz : You know that you can create brand new commits in the same branch, then do a `git push --force-with-lease` and the old commits will disappear and be replaced by the new ones. There is no need to recreate new PRs each time.

**Pull request closed without merging**
