### PR TITLE
[SETUPLIB] Do not lock the BtrFS volume twice when installing the bootcode

### PR DESCRIPTION
**Pull request by GeoB99**
## Purpose

Remove useless code in `InstallBtrfsBootCode` that locks the BtrFS volume when it has already been locked in `InstallBootCodeToDisk`. Locking a volume twice poses no problem, at least in the case of BtrFS. Its **FSCTL_LOCK_VOLUM**E implementation uses **ERESOURCES** (see the [lock_volume() implementation](https://github.com/reactos/reactos/blob/master/drivers/filesystems/btrfs/fsctl.c#L2237)) which permit recursive locking (at least for the time being). 

But `InstallBootCodeToDisk` tries to unlock the volume which fails with **STATUS_NOT_LOCKED**, as per the debug log:
```
(base\setup\lib\bootsup.c:676) Unable to unlock the volume after installing boot code. Status 0xc000002a. Expect problems.
```
It's an innocuous symptom, not that it's of a big deal or anything but the developer(s) of WinBTRFS may choose to adopt an entirely different locking mechanism (e.g. push locks or whatever) that probably don't allow recursive locking in the future. Suppose that this was the case, the current code in SETUPLIB would lock the volume twice and hang the current calling thread.

I stumbled upon this when I was doing investigations on why ROS temporarily freezes when installing the BtrFS bootsector to the target partition.

### CODE REVIEW

**Comment by HBelusca** [comment]
> Its FSCTL_LOCK_VOLUME implementation uses ERESOURCES (see the [lock_volume() implementation](https://github.com/reactos/reactos/blob/master/drivers/filesystems/btrfs/fsctl.c#L2237)) which permit recursive locking (at least for the time being).

It actually better be recursive, because otherwise it would be very easy from user-mode to trigger deadlocks in kernel-mode ^^
There is also no big warning (in MSDN) that someone who calls `FSCTL_LOCK_VOLUME` must not do it more than once.

**Comment by HBelusca** [comment]
> I stumbled upon this when I was doing investigations on why ROS temporarily freezes when installing the BtrFS bootsector to the target partition.

Out of curiosity, does your fix reduces the time ROS freezes?

**Comment by GeoB99** [comment]
> > Its FSCTL_LOCK_VOLUME implementation uses ERESOURCES (see the [lock_volume() implementation](https://github.com/reactos/reactos/blob/master/drivers/filesystems/btrfs/fsctl.c#L2237)) which permit recursive locking (at least for the time being).
> 
> It actually better be recursive (or, the driver has a `IsLocked` flag associated to the per-device lock so that if it's already locked, it doesn't get locked again), because otherwise it would be very easy from user-mode to trigger deadlocks in kernel-mode ^^ There is also no big warning (in MSDN) that someone who calls `FSCTL_LOCK_VOLUME` must not do it more than once.

Ah ok, that makes perfect sense. Might as well close this then.

**Comment by HBelusca** [comment]
Now I wasn't suggesting you close this though! I was currently looking at which commit introduced the lock here (and the lock in the InstallBootCodeToDisk) in order to give a more enlightened suggestion or approval ^^

**Comment by HBelusca** [comment]
> > > Its FSCTL_LOCK_VOLUME implementation uses ERESOURCES (see the [lock_volume() implementation](https://github.com/reactos/reactos/blob/master/drivers/filesystems/btrfs/fsctl.c#L2237)) which permit recursive locking (at least for the time being).
> > 
> > 
> > It actually better be recursive (or, the driver has a `IsLocked` flag associated to the per-device lock so that if it's already locked, it doesn't get locked again), because otherwise it would be very easy from user-mode to trigger deadlocks in kernel-mode ^^ There is also no big warning (in MSDN) that someone who calls `FSCTL_LOCK_VOLUME` must not do it more than once.
> 
> Ah ok, that makes perfect sense. Might as well close this then.

Just checking, the BTRFS driver checks whether the volume to lock has already been locked, and returns success if so. So it supports "re-locking" (even if it wasn't using ERESOURCE):
https://github.com/reactos/reactos/blob/master/drivers/filesystems/btrfs/fsctl.c#L2259-L2260
Of course when unlocking, the driver checks whether the volume was already locked:
https://github.com/reactos/reactos/blob/master/drivers/filesystems/btrfs/fsctl.c#L2346-L2347

**Pull request closed without merging**
