### PR TITLE
Romanian translation maintenance

### PR DESCRIPTION
**Pull request by reactos-contributor**
Update the existing resources, bring up translation contents for some new ones

I've split the changes in a batch of three commits. One that only translates new strings, other that improves the consistency of used terminology or reformulates things a bit better, and another that adds translated strings to devcpux, rosapps airping, rosapps mazescr, rosapps fontsub, and intl.inf (which is not used yet, but better to have it ready).

JIRA issue: [CORE-15690](https://jira.reactos.org/browse/CORE-15690)

### CODE REVIEW

**Comment by Fraizeraust** [comment]
Did you test the patch which has changes on USETUP if the translated strings are encoded properly?

**Comment by reactos-contributor** [comment]
Yes, I've tested the μsetup thing, that's how I come about to comment the strings in the first (initializing) screen, BTW. The encoding was not yet enacted in there, so I've left them without diacritics, for now. Why do you ask? Did you encountered any issues?

**Comment by Fraizeraust** [comment]
> Why do you ask? Did you encounter any issues?

I was merely asking because USETUP hates files which are encoded on UTF-8. I wasn't aware of the comments, apologies.
> Edit: I'm glad you're here so quick. I presume you'll also review my work?

Kind of, yeah. I couldn't be able to review all of the changes you've made to your branch yesterday night. The PR looks OK. :+1:

**Comment by reactos-contributor** [comment]
Thanks for promptitude.

**Pull request merged**
