### PR TITLE
[CPL][DESK] Add icons to 'Background' tab

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

JIRA issue: [CORE-16665](https://jira.reactos.org/browse/CORE-16665)

BEFORE:
before
AFTER:
after

### CODE REVIEW

**Comment by HBelusca** [comment]
Regarding the icon, can't we use one that already exists in shell32?

**Comment by katahiromz** [comment]
Because the shell icon image list is unchangeable.
And because the target image list wants "None" icon.

**Comment by katahiromz** [comment]
I borrowed the shell32 icon.

**Comment by ThFabba** [comment]
> Does our desk.cpl work **_unchanged_** under Windows XP/2003?

It's also missing the icon in 2003 (among other differences).

image

**Comment by katahiromz** [comment]
whats
What's up? The None icon is wrong...

**Comment by katahiromz** [comment]
OK, fixed.
fixed

**Pull request merged**
