### PR TITLE
[NTOS] Remove an old hack

### PR DESCRIPTION
**Pull request by tkreuzer**
This removes an old hack, that isn't needed anymore.

### CODE REVIEW

**Review by learn-more — APPROVED** [review]

**Review by erkinalp — APPROVED** [review]

**Review by ThFabba — APPROVED** [review]

**Review by binarymaster — APPROVED** [review]

**Review by HBelusca — APPROVED** [review]

**Comment by erkinalp** [comment]
Why was it needed in the first place?

**Comment by HBelusca** [comment]
> Why was it needed in the first place?

How difficult is it to look at the git history (using e.g. the "blame" functionality) so as to find which commit introduced it: https://github.com/reactos/reactos/commit/380f89c205d72db68dfdfa93ac61b19029879fa8 , and why?

**Comment by erkinalp** [comment]
I looked at that commit and no obvious reason. Just that it happens after the last driver loaded.

**Comment by HBelusca** [comment]
> I have looked at that commit and seen no obvious reason. Just that it happens after the last driver loaded.

The logic deduction is that there was some code later that was looking at that list again and supposed that if it was not empty, there were drivers again that needed to be loaded (but this was not the case), and thus, to not introduce a bug in that old code (that was obviously not fixed by that commit), the small workaround was to "reinitialize" the list.

**Comment by erkinalp** [comment]
By doing that, @ionescu007 went further than Microsoft does in terms of backwards compatibility. You are marvellous in creating a binary-compatible Windows alternative.

**Comment by HBelusca** [comment]
I'm not sure you understood my point @erkinalp , but OK....

**Review by Extravert-ir — APPROVED** [review]

**Comment by ionescu007** [comment]
Nice :)

**Pull request merged**
