### PR TITLE
[CMD] Fix 'DIR .' and 'DIR ..' behavior

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

There was a problem in cmd.exe that 'DIR .' and 'DIR ..' commands won't show normal file.
This PR fixes it.

JIRA issue: [CORE-13961](https://jira.reactos.org/browse/CORE-13961)

## Proposed changes

- Add inline function "IsIgnoredDots".
- Fix the handling about dots.

### CODE REVIEW

**Comment by Mouvedia** [comment]
Here's a test for you: [`DIR ...`](https://blogs.msdn.microsoft.com/oldnewthing/20160202-00/?p=92953)

**Comment by katahiromz** [comment]
Win10:
win10-dotdotdot
Ros:
ros-dotdotdot

**Comment by Mouvedia** [comment]
Yup seems like directories named `...` are not supported. Maybe that's another issue entirely.

**Comment by katahiromz** [comment]
Done. The problem of 3 dots ("...") remains.

**Comment by HBelusca** [comment]
That's because "." and ".." can be understood as "special" files (also they appear in the results of FindFirstFile / FindNextFile), while "..." (3 or more points by the way...) simply don't exist.

**Comment by binarymaster** [comment]
@Mouvedia ReactOS targets Windows NT 5.2.

**Comment by katahiromz** [comment]
Updated. See attachment of [CORE-13961](https://jira.reactos.org/browse/CORE-13961).

**Comment by katahiromz** [comment]
Updated. See attachements of [CORE-13961](https://jira.reactos.org/browse/CORE-13961)

**Comment by HBelusca** [comment]
Improved bugfix with support for pathological cases containing many-dots-directories followed by "." or ".." committed in the above-mentioned commits.

**Pull request closed without merging**
