### PR TITLE
[BUGCODES] Update Romanian translation

### PR DESCRIPTION
**Pull request by AndreiMiloiu**

### CODE REVIEW

**Comment by julenuri** [comment]
Hi, as the bugchecks are splashed in the BSODs, and that will start the bootvid, the character enconding will only be splashed in ANSI English (actually ANSI OEM), the great majority of the special characters you use in this PR won't be shown. 
Please, check if it still readable.

**Comment by AndreiMiloiu** [comment]
Hi, please try again! I made some changes. However, I don't know the code for capital Î letter. I was able to change any diacritics, but this. I changed to capital I letter.

**Comment by GeoB99** [comment]
Hi! Could you please show a screenshot of BSoD showing the resources translated in Romanian? I would like to see how does it look before I make my own judgement whether to review the PR first and merge it.

**Comment by AndreiMiloiu** [comment]
Hello, I don't know how to make my ReactOS VM show BSODs. Also, I don't know which file to replace with my translation. I edited the text file bugcodes.mc, but I don't know what to do further.

**Comment by SigmaTel71** [comment]
> Hello, I don't know how to make my ReactOS VM to show BSODs. Also, I don't know which file to replace with my translation. I edited the text file named bugcodes.mc, but I don't know what to do further.

https://learn.microsoft.com/en-us/sysinternals/downloads/notmyfault

**Comment by AndreiMiloiu** [comment]
Good, thank you! I will try it. But what file should I replace with my translation and what is the path of that file?

**Comment by AndreiMiloiu** [comment]
I listened to all your advice. I downloaded and tried notmyfault but I still cannot show you any BSOD because of an execution error. I attached you a screenshot with the error.

ReactOS-2023-05-22-17-05-32

**Comment by SigmaTel71** [comment]
> I attached you a screenshot with the error.

Try [this one](https://archive.org/download/pasmafaute/NotMyFault/notmyfault.exe).

**Comment by AndreiMiloiu** [comment]
Yes, it works! This is my first BSOD.

ReactOS-2023-05-22-23-09-57

**Comment by AndreiMiloiu** [comment]
Still wondering how to test my translation in bugcodes.mc file.

**Comment by AndreiMiloiu** [comment]
[GeoB99](https://github.com/GeoB99) I don't know how to do it.

> Hi! Could you please show a screenshot of BSoD showing the resources translated in Romanian? I would like to see how does it look before I make my own judgement whether to review the PR first and merge it.

**Comment by AndreiMiloiu** [comment]
I uploaded a version without diacritics (only ANSI code or English letters). I still don't know how to test my translations, but I hope now it's good.

**Comment by reactos-contributor** [comment]
> I uploaded a version without diacritics (only ANSI code or English letters). I still don't know how to test my translations, but I hope now it's good.

ReactOS doesn't use your translated content (yet).
For my testing I've took your work (`git fetch origin pull/5300/head:PR5300 && git checkout PR5300`), then set up a configuration with Romanian as pre-selected and default if present (`../src/configure.sh -DI18N_LANG:STRING=ro-RO` called from a "bin-ro" directory), but the first line (MessageId=0x7F, for which translation clearly exists) in all BSOD screens is still in English.
@AndreiMiloiu, you should ask the developers for support on if and how such localization may be activated.

**Comment by AndreiMiloiu** [comment]
Ok, I will. Thank you very much for the answer.

**Comment by GeoB99** [comment]
Hey! Sorry for late reply.

It seems like we do not support custom locales for the bugcheck display other than English. Until someone is willing to volunteer to implement the necessary code to support this, I think this PR is worth to be closed for the time being. Please keep a backup copy of your branch and keep it safe somewhere so that when the time will come we already have a branch that we can test with.

**Comment by AndreiMiloiu** [comment]
I saved all of the versions of the file.

**Comment by GeoB99** [comment]
Alright, I'm going to close this PR. As usual, don't forget to keep your backups!

**Pull request closed without merging**
