### PR TITLE
[CPL][INPUT] Fix keyboard layout saving

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

JIRA issue: [CORE-16625](https://jira.reactos.org/browse/CORE-16625)

BEFORE:
before
AFTER:
after

- Also modify `HKU\\.DEFAULT` registry key.
- Check `INPUT_LIST_NODE_FLAG_DELETED` flag.

### CODE REVIEW

**Comment by katahiromz** [comment]
NOTE: Our keyboard layout won't work without modifying `HKU\.DEFAULT` registry key.

**Comment by ThFabba** [comment]
Looks like a hack at first glance. Does the old version of input.cpl do the right thing on Windows?

**Comment by katahiromz** [comment]
In Win2k3:
fr1
fr2
Win2k3 didn't write `.DEFAULT` user registry key. Why does ReactOS use `.DEFAULT` user settings for keyboard layout?

**Comment by katahiromz** [comment]
I assume `HKEY_CURRENT_USER` is not for default user. Why is `HKEY_CURRENT_USER` interpreted as the default user's one?

**Comment by katahiromz** [comment]
ReactOS keyboard layout uses .DEFAULT user registry key wrongly.

**Comment by HBelusca** [comment]
The correct rules:
- There is a HKEY_CURRENT_USER associated to each different user.
- HKEY_LOCAL_MACHINE or HKEY_USERS\.DEFAULT will contain stuff that will be the default for any user, except if data overrides these defaults when being specified in the corresponding HKEY_CURRENT_USER.

**Comment by katahiromz** [comment]
```txt
(win32ss/user/ntuser/desktop.c:3313) err: The process 0xB0C3F628 'winlogon.exe' didn't have an assigned startup desktop before, assigning it now!
(win32ss/user/ntuser/desktop.c:3251) err: Attempted to change thread desktop although the thread has windows!
(win32ss/user/winsrv/usersrv/init.c:166) We are logged off
(ntoskrnl/mm/ARM3/sysldr.c:176) Loading: \SystemRoot\System32\kbdus.dll at F80D9000 with 5 pages
```
We are not logged on yet...

**Pull request closed without merging**
