### PR TITLE
[PSDK] Add 'Network Connections' CLSID

### PR DESCRIPTION
**Pull request by SigmaTel71**
## Purpose

Allow to refer to 'Network Connections' folder via CLSID, e.g. via `ShellExecute(Ex)[A|W]` functions when you form the path to do something to the network adapter, like opening its properties.

JIRA issue: Not found

## Proposed changes
- Add CLSID of 'Network Connections' folder to fix compilation errors caused by referring to unknown CLSID.

Error example:
<details>
<summary>G++ will fail <strong>without</strong> this change</summary>

```
FAILED: dll/shellext/wlanwiz/CMakeFiles/wlanwiz.dir/wlanwiz_advsettings.cpp.obj
F:\RosBE\i386\bin\g++.exe -DDBG=1 -DDLL_EXPORT_VERSION=0x502 -DMINGW_HAS_SECURE_API=1 -DPAL_STDCPP_COMPAT -DUNICODE -DUSE_COMPILER_EXCEPTIONS -DWINVER=0x502 -D_ATL_NO_EXCEPTIONS -D_CRT_NON_CONFORMING_SWPRINTFS -D_DLL -D_GLIBCXX_HAVE_BROKEN_VSWPRINTF -D_M_IX86 -D_NEW_DELETE_OPERATORS_ -D_SEH_ENABLE_TRACE -D_SETUPAPI_VER=0x502 -D_UNICODE -D_USE_32BIT_TIME_T -D_USE_PSEH3=1 -D_WIN32_IE=0x600 -D_WIN32_WINDOWS=0x502 -D_WIN32_WINNT=0x600 -D_X86_ -D__REACTOS__ -D__USE_CRTIMP -D__USE_PSEH2__ -D__i386__ -Di386 -IG:/Git/reactos/output-MinGW-i386/dll/shellext/wlanwiz -IG:/Git/reactos/dll/shellext/wlanwiz -IG:/Git/reactos/sdk/include -IG:/Git/reactos/sdk/include/psdk -IG:/Git/reactos/sdk/include/dxsdk -IG:/Git/reactos/output-MinGW-i386/sdk/include -IG:/Git/reactos/output-MinGW-i386/sdk/include/psdk -IG:/Git/reactos/output-MinGW-i386/sdk/include/dxsdk -IG:/Git/reactos/output-MinGW-i386/sdk/include/ddk -IG:/Git/reactos/output-MinGW-i386/sdk/include/reactos -IG:/Git/reactos/output-MinGW-i386/sdk/include/reactos/mc -IG:/Git/reactos/sdk/include/crt -IG:/Git/reactos/sdk/include/ddk -IG:/Git/reactos/sdk/include/ndk -IG:/Git/reactos/sdk/include/reactos -IG:/Git/reactos/sdk/include/reactos/libs -IG:/Git/reactos/sdk/lib/atl -IG:/Git/reactos/sdk/lib/pseh/include -std=gnu++11 -ffile-prefix-map=G:/Git/reactos= -ffile-prefix-map=../= -pipe -fms-extensions -fno-strict-aliasing -fno-common -mlong-double-64 -fno-aggressive-loop-optimizations -gdwarf-2 -gstrict-dwarf -femit-struct-debug-detailed=none -feliminate-unused-debug-symbols -march=pentium -mtune=generic -Werror -Wall -Wpointer-arith -Wno-char-subscripts -Wno-multichar -Wno-unused-value -Wno-unused-const-variable -Wno-unused-local-typedefs -Wno-deprecated -Wno-unused-result -Wno-maybe-uninitialized -O1 -fno-optimize-sibling-calls -fno-omit-frame-pointer -mstackrealign -mpreferred-stack-boundary=3 -fno-set-stack-executable -fno-rtti -fno-exceptions -MD -MT dll/shellext/wlanwiz/CMakeFiles/wlanwiz.dir/wlanwiz_advsettings.cpp.obj -MF dll\shellext\wlanwiz\CMakeFiles\wlanwiz.dir\wlanwiz_advsettings.cpp.obj.d -o dll/shellext/wlanwiz/CMakeFiles/wlanwiz.dir/wlanwiz_advsettings.cpp.obj -c G:/Git/reactos/dll/shellext/wlanwiz/wlanwiz_advsettings.cpp
G:/Git/reactos/dll/shellext/wlanwiz/wlanwiz_advsettings.cpp: In member function 'LRESULT CWlanWizard::OnAdvancedSettings(WORD, WORD, HWND, BOOL&)':
G:/Git/reactos/dll/shellext/wlanwiz/wlanwiz_advsettings.cpp:15:29: error: 'CLSID_NetworkConnections' was not declared in this scope
  HRESULT hr = StringFromIID(CLSID_NetworkConnections, &lpwszNetConCLSID);
                             ^~~~~~~~~~~~~~~~~~~~~~~~
G:/Git/reactos/dll/shellext/wlanwiz/wlanwiz_advsettings.cpp:15:29: note: suggested alternative: 'CLSID_NetworkDomain'
  HRESULT hr = StringFromIID(CLSID_NetworkConnections, &lpwszNetConCLSID);
                             ^~~~~~~~~~~~~~~~~~~~~~~~
                             CLSID_NetworkDomain
[15/16] Building CXX object dll/shellext/wlanwiz/CMakeFiles/wlanwiz.dir/wlanwiz_scan.cpp.obj
ninja: build stopped: subcommand failed.
```
</details>

### CODE REVIEW

**Review by whindsaks — APPROVED** [review]

**Review by Doug-Lyons — APPROVED** [review]

**Comment by Doug-Lyons** [comment]
Confirmed from: https://stackoverflow.com/questions/78393276/powershell-command-does-not-work-when-powershell-is-called-from-cmd-exe

**Review by JoachimHenze — APPROVED** [review]
Approved.

**Comment by Doug-Lyons** [comment]
@binarymaster, Is the name used in the PR OK to use for a merge?

**Comment by learn-more** [comment]
We already have this in `shlguid_undoc.h` under the name of `CLSID_ConnectionFolder`.

Is `CLSID_NetworkConnections` the name used by Microsoft?
Because it is now in a psdk header?

**Comment by SigmaTel71** [comment]
> Is `CLSID_NetworkConnections` the name used by Microsoft? Because it is now in a psdk header?

Defined in shobjidl_core.h as

```c++
EXTERN_C const CLSID CLSID_NetworkConnections;

#ifdef __cplusplus

class DECLSPEC_UUID("7007ACC7-3202-11D1-AAD2-00805FC1270E")
NetworkConnections;
#endif
```

**Comment by SigmaTel71** [comment]
@learn-more, also the same CLSID is mentioned [in our mailing lists](https://reactos.org/archives/public/ros-diffs/2014-December/055430.html) but I can't find the commit that caused the rename from `CLSID_NetworkConnections` to `CLSID_ConnectionFolder`.

**Comment by learn-more** [comment]
> @learn-more, also the same CLSID is mentioned [in our mailing lists](https://reactos.org/archives/public/ros-diffs/2014-December/055430.html) but I can't find the commit that caused the rename from `CLSID_NetworkConnections` to `CLSID_ConnectionFolder`.

bea0b47db66519925a707cf67bbbcde9c8adf180
With the commit message:

> [NETSHELL]
> - Use the correct names for netshell's CLSIDs as indicated by the registry and public symbols

**Pull request merged**
