### PR TITLE
[MSVIDC32] Don't confuse CRAM_MAGIC with MSVC_MAGIC

### PR DESCRIPTION
**Pull request by katahiromz**
Partially reverts https://github.com/reactos/reactos/pull/6118. It had caused a regression.

JIRA issue: [CORE-19453](https://jira.reactos.org/browse/CORE-19453), [CORE-15382](https://jira.reactos.org/browse/CORE-15382)

### CODE REVIEW

**Review by JoachimHenze — APPROVED** [review]
The partial revert will hurt a bit in CORE-15382 context, but I do suspect that it is more correct than what we are doing currently, and comes with less side effects. Therefore approved (until someone will come up with a better idea on how to have best of both worlds).

**Review by binarymaster — COMMENTED** [review]
This installable driver checks for CRAM_MAGIC to validate the internal info structure, you can change it to MSVC_MAGIC in other places instead:

https://git.reactos.org/?p=reactos.git;a=blob;f=dll/win32/msvidc32/msvideo1.c;hb=118869f69cf8fec59a38097a96a0338c02524a28#l304

**Comment by binarymaster** [comment]
Actually I might have a better solution... please wait

**Review by binarymaster — APPROVED** [review]

**Review by binarymaster — COMMENTED** [review]
So, the partial revert is absolutely correct here, just report the main FourCC as "MSVC".

> until someone will come up with a better idea on how to have best of both worlds

This way it would fix the regression, while reporting the expected codec id.

**Review by Doug-Lyons — COMMENTED** [review]
I tested the state of the present PR and both problems are fixed with it. Thanks, @binarymaster

**Pull request merged**
