### PR TITLE
[WDFLDR][WDF01000][INCLUDE] Add kernel mode driver framework

### PR DESCRIPTION
**Pull request by mrmks04**
## Purpose

Add Windows Driver Framework driver, implementation of version 1.9. It's can run echo.sys driver from WinDDK samples. Based on code from Microsoft git repository. Tested in Windows Server 2003R2 and ReactOS. Work still in progress.

## TODO

- [ Implement other WDF api functions ] 
- [ Need more test ]

### CODE REVIEW

**Comment by HBelusca** [comment]
So how does this PR relates to the older one #1976 ?

**Comment by mrmks04** [comment]
> 
> 
> So how does this PR relate to the older one #1976 ?

Wdf01000 import functions from wdfldr

**Comment by BenNottelling** [comment]
> So how does this PR relate to the older one #1976 ?

Looks like the first two commits are the other  PR, so effectively, it's that plus the 140 commits afterwards

**Comment by Extravert-ir** [comment]
No longer relevant. WDF 1.17 is backported, wdfldr.sys and wdfdriverentry.lib are being done as part of #3276

**Pull request closed without merging**
