### PR TITLE
[BROWSEUI_APITEST] SHEnumClassesOfCategories: Hack for ReactOS. CORE-11711

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Fix `CO_E_NOTINITIALIZED` on ReactOS:
VBox: [Jun 10 20:38 	33604e014768... 	success 	#11213](https://build.reactos.org/builders/Test%20VBox/builds/11213)
```
Running Wine Test, Module: browseui, Test: SHEnumClassesOfCategories
...
err:(dll/win32/ole32/compobj.c:3326) apartment not initialised
CSHEnumClassesOfCategories.cpp:178: Unexpected failure 800401f0.
CSHEnumClassesOfCategories.cpp:72: Unexpected failure 800401f0.
CSHEnumClassesOfCategories.cpp:271: Unexpected failure 800401f0.
CSHEnumClassesOfCategories.cpp:345: Unexpected failure 800401f0.
SHEnumClassesOfCategories.cpp:239: Test failed: Wrong value for 'hr', expected: ((HRESULT)0L) (0x0), got: 0x800401f0

SHEnumClassesOfCategories: 48 tests executed (0 marked as todo, 15 failures), 0 skipped.
```

JIRA issue: [CORE-11711](https://jira.reactos.org/browse/CORE-11711)

Cc @HBelusca

## Proposed changes

- Trivial improvements.
- ROS hack: Call CoInitializeEx(), with FIXME.

## TODO

`// FIXME: On Windows, CoInitializeEx() call is not needed. Why is it on ReactOS?`
Does anyone know the answer? (I found no Jira issue about that "misbehavior"...)

### CODE REVIEW

**Comment by yagoulas** [comment]
It is astounding how much energy one can spend doing absolutely nothing at all.

**Comment by yagoulas** [comment]
> 
> 
> > nothing at all
> 
> That is exactly what I feel such a comment achieves...

Of course but If I were to reiterate it in every PR of yours I would be wasting too much time.

**Comment by SergeGautherie** [comment]
> If I were to reiterate it in every PR of yours I would be wasting too much time.

I wonder: did you truly find no value in any of my PRs or is your purpose to spam only?

**Comment by ThFabba** [comment]
Stop. Now.

**Comment by learn-more** [comment]
Too many unrelated changes

**Pull request closed without merging**
