### PR TITLE
[REACTOS][CMAKE][BOOTDATA] Replace reactos with ReactOS for bootcd/livecd

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

JIRA issue: [CORE-14005](https://jira.reactos.org/browse/CORE-14005)

## Proposed changes

- Replace `'reactos'` with `'ReactOS'` in `bootcd`/`livecd` paths.

## TODO

- [x] Do small tests.
- [x] Do big tests.

### CODE REVIEW

**Comment by katahiromz** [comment]
bootcd
I have booted on bootcd.

**Review by ericsomto — APPROVED** [review]
:-)

**Comment by katahiromz** [comment]
Test KVM BEFORE: c3644fd https://reactos.org/testman/compare.php?ids=85704
Test KVM AFTER: 0457746 Testing...
https://reactos.org/testman/compare.php?ids=85704,???

Test VBox BEFORE: c3644fd https://reactos.org/testman/compare.php?ids=85705
Test VBox AFTER: 0457746 Testing...
https://reactos.org/testman/compare.php?ids=85705,???

**Review by Extravert-ir — APPROVED** [review]

**Review by learn-more — CHANGES_REQUESTED** [review]
I am not sure which problem this is fixing?

**Comment by katahiromz** [comment]
> I am not sure which problem this is fixing?

Consistency and speed (not confirmed yet).

**Review by HBelusca — CHANGES_REQUESTED** [review]
Not convinced this makes any sense. Indeed, those paths in the bootcd/livecd are only used when ReactOS is running from the CD itself, in which case e.g. BTRFS is not used to read the system files from the CD.
And when ReactOS is installed, it will use whatever the user has specified as the installation path during the 1st-stage installation, and it can be anything (`ReactOS`, `rEaCtOs`, `MyLittlePony`, etc.)

**Comment by katahiromz** [comment]
OK. Won't Fix. Closed.

**Pull request closed without merging**
