### PR TITLE
[MEDIA][FONTS] Delete many fonts CORE-16407

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Delete some fonts to reduce memory consumption.
JIRA issue: [CORE-16407](https://jira.reactos.org/browse/CORE-16407)

## Proposed changes
- Delete many font files and related document files.

### CODE REVIEW

**Comment by katahiromz** [comment]
Any objections?

**Comment by JoachimHenze** [comment]
I would not comment the obsolete ones, but really delete the lines.
That's not just easier to review, but will also leave us with a cleaner file.
Don't be afraid, we have a version control system. There is always a safe way back.

But I would go even further:
Why not eliminating all SourceCodePro*? (2k3sp2 does not have it)
Why not eliminating OpenSans*.ttf? (the important ones were duped to Trebuchet*.ttf already)
Why not eliminating LiberationSans*.ttf (you copied that to Arial*.ttf)
Why not eliminating LiberationSerif*.ttf? (you duped that into 4 TimesNewRoman now instead)
Why not eliming all LibreFranklin? (the important ones have been duped into  framd.ttf and framdit.ttf)
Why not eliminating all DejaVuSerif*? (we have timesNewRmn and no substitute uses them anymore)
Why not eliminating DejaVuSans*.ttf (but keeping the Mono ones for now)? (you duped those into verdana)
Why not eliminating Ubuntu*.ttf?

Are any of those super-important for Asian maybe? They are not really needed in the Western World at least.
-----------
After the above has been done/answered, we should find out why we still have substitutes to "FreeSans", "FreeMono", and "DejaVu Sans Mono" to be able to delete those as well later, but I would leave that part to a second PR, so we can leave the substitutes unchanged within this one. Keep those 3 for now. Also keep UniVGA16.ttf

**Comment by JoachimHenze** [comment]
Definitely keep all visible in https://jira.reactos.org/secure/attachment/54636/a_possible_goal.png
and additionally keep "FreeSans*", "FreeMono*", and "DejaVu Sans Mono*" (at least for now, those 3 families are still erroneously referenced by the substitutes atm!)

**Comment by katahiromz** [comment]
I really delete many fonts. Is it alright?

**Comment by foxlet** [comment]
The Source Sans family is required by the Mizu theme for proper UI scaling.

**Comment by katahiromz** [comment]
@foxlet Please post a JIRA issue for that.

**Pull request merged**
