### PR TITLE
[NTOS:MM] Add MiStandbyRepurposedByPriority variable

### PR DESCRIPTION
**Pull request by andrew-boyarshin**
## Purpose

`MiStandbyRepurposedByPriority` is to be filled later (everincreasing, uptime-long counter of repurposed standby pages by priority).
Also add some safe enough list consistency asserts.

JIRA issue: None

### CODE REVIEW

**Comment by andrew-boyarshin** [comment]
@Extravert-ir so much for minimal and self-contained changes in 1 PR. Windows definitely has this variable, since that is how it provides information for `NtQuerySystemInformation` (class 80). You can verify it by looking at any tool that can display standby memory lists (PH 3.0+, Process Explorer, Memory Map).
And to crown it all, I cannot expand this PR with usage until #1073 is merged.

**Comment by HBelusca** [comment]
Does that variable also exist on Windows 2003?

**Comment by andrew-boyarshin** [comment]
> 5.2 from Windows Server 2003 SP1, and higher
[0x50 (SystemMemoryListInformation)](https://www.geoffchappell.com/studies/windows/km/ntoskrnl/api/ex/sysinfo/class.htm)

**Comment by ThFabba** [comment]
According to symbols, there's only MmStandbyPageListByPriority -- and that one we already have.
As for minimal changes, adding a global in ntoskrnl makes sense if it's used by a Windbg extension... otherwise there's no point in adding it until there's actually code that uses it.

**Comment by andrew-boyarshin** [comment]
Yeah, I verified now, Windows Server 2003 R2 SP2 does not support `0x50 (SystemMemoryListInformation)` despite being mentioned on the site I linked. Since Windows Server 2003 is the current target, I'll modify this PR to only contain `ASSERT`s for transition pages lists.

**Comment by ThFabba** [comment]
Hi @andrew-boyarshin! It looks like you were going to make some changes to this but haven't gotten around to it yet. Any update or ETA?
Thanks!

**Comment by andrew-boyarshin** [comment]
@ThFabba I don't plan completing this PR. After the conversation on this PR, the only interesting part here are the asserts I've added and one moved variable decrement. I'm not sure of it's worth. I'll close this PR, but if you find these changes interesting, you can incorporate them yourself (the changes in this PR are now in public domain).

**Pull request closed without merging**
