### PR TITLE
[INETCPL] Update Romanian (ro-RO) translation

### PR DESCRIPTION
**Pull request by AndreiMiloiu**
Attendum to https://github.com/reactos/reactos/pull/6517

### CODE REVIEW

**Comment by AndreiMiloiu** [comment]
Cc @reactos/lang-romanian

**Comment by GeoB99** [comment]
Your PR has merge conflicts, I'm not able to ship the PR.
Capture
Please fix them or just re-create a new PR based on top of latest updates from the master branch.

**Comment by AndreiMiloiu** [comment]
> Your PR has merge conflicts, I'm not able to ship the PR. Capture Please fix them or just re-create a new PR based on top of latest updates from the master branch.

Fixed!

**Comment by AndreiMiloiu** [comment]
> Your PR has merge conflicts, I'm not able to ship the PR. Capture Please fix them or just re-create a new PR based on top of latest updates from the master branch.

Fixed!

**Pull request merged**
