### PR TITLE
[TRANSLATION][MC] Add Romanian messages

### PR DESCRIPTION
**Pull request by katahiromz**
JIRA issue: [CORE-11898](https://jira.reactos.org/browse/CORE-11898)

Based on patch by @reactos-contributor.

### CODE REVIEW

**Comment by HBelusca** [comment]
@learn-more or @gigaherz : the baseaddresses surely will need to be re-calculated.

**Comment by learn-more** [comment]
I can't do that before wednesday.

**Comment by katahiromz** [comment]
Done.

**Comment by reactos-contributor** [comment]
"Would be convenient if Ştefan Fulea creates a GitHub account and come here."
Ștefan here. Thank everyone for involvement and sorry for making things more difficult (through absence) than they have to be.

**Comment by katahiromz** [comment]
@reactos-contributor Do you have e-mail address?

**Comment by katahiromz** [comment]
Done.

**Comment by katahiromz** [comment]
You can identify your account by setting e-mail address to your account.

**Comment by katahiromz** [comment]
@learn-more Go or not?

**Comment by reactos-contributor** [comment]
Thank you all!

**Pull request merged**
