### PR TITLE
[NTOS:CM] Fix unlocking on failure

### PR DESCRIPTION
**Pull request by tkreuzer**
## Purpose

Properly unlock registry on failure in NtUnloadKey2.
Fixes random hang when loading user profile.

Jira Issue: [CORE-19539](https://jira.reactos.org/browse/CORE-19539)

## Proposed changes
- Add lock debugging code
- Unlock on failure

## Tests
- KVM x86: https://reactos.org/testman/compare.php?ids=95136,95142,95154,95160,95167
- KVM x64: https://reactos.org/testman/compare.php?ids=95087,95088,95096,95115,95161

### CODE REVIEW

**Review by oleg-dubinskiy — APPROVED** [review]

**Comment by tkreuzer** [comment]
Remark on the debug code: The backtrace made it super easy to catch the offender. It does add some overhead though, especially on x64. And considering how often CM will be locking and unlocking, we might rather use a special macro to enable it on demand. We still have the ASSERT that will catch issues like this, and whenever something like this happens, we can decide to enable it, until the issue is fixed. Opinions on this are welcome.

**Review by HBelusca — APPROVED** [review]

**Review by GeoB99 — APPROVED** [review]
Nice catch here. Regarding the overhead, I like the idea of having a special macro that enables certain chunks of code such as `CM_LOCK_DEBUG` (think of like `NDEBUG` style) or whatever name that fits its purpose.

**Review by cbialorucki — APPROVED** [review]

**Review by JoachimHenze — APPROVED** [review]
Approved. Although I didn't test it yet. I do confirm existance of the bug though. Code looks ok, I do assume that only the change in ntapi.c is needed actually and the rest is just debug-code, right?

**Review by binarymaster — APPROVED** [review]

**Review by binarymaster — COMMENTED** [review]
When merging, be sure to tag CORE-ID on the commits.

**Review by DarkFire01 — APPROVED** [review]

**Comment by tkreuzer** [comment]
> Nice catch here. Regarding the overhead, I like the idea of having a special macro that enables certain chunks of code such as `CM_LOCK_DEBUG` (think of like `NDEBUG` style) or whatever name that fits its purpose.

@Doug-Lyons found that there are more instances of this issue. Seemingyl related to recent CM locking changes. I will keep the debug code for now and merge it as it is. I will wrap it into a macro, once we don't see this issue anymore.

**Comment by binarymaster** [comment]
> When merging, be sure to tag CORE-ID on the commits.

My request was ignored... :(

**Pull request merged**
