### PR TITLE
[IP] Upgrade lwip library to 2.1.2

### PR DESCRIPTION
**Pull request by zefklop**
## Purpose

Upgrade lwip library to 2.1.2 (latest)

### CODE REVIEW

**Comment by HeisSpiter** [comment]
Is the doxygen doc inclusion wanted?

**Comment by zefklop** [comment]
> Is the doxygen doc inclusion wanted?

Not really, but I intentionally chose to modify nothing in the lwip package, since those people are nice enough to now provide an easy integration with any cmake-built project.

**Comment by tkreuzer** [comment]
> 
> 
> > Is the doxygen doc inclusion wanted?
> 
> Not really, but I intentionally chose to modify nothing in the lwip package, since those people are nice enough to now provide an easy integration with any cmake-built project.

I'm usually in favor of keeping things unmodified, but this is a huuge lot of stuff that we don't need. It could impact repository size and performance quite a bit without any benefit. I suggest removing the doxygen folder.

**Comment by KyleKatarn31** [comment]
Beware of potential conflict with https://github.com/reactos/reactos/pull/2582 from @sdever

Is the fix proposed by Sylvain included in 2.1.2 ? If not, is it worth being shared with LWIP devs ?

**Comment by KyleKatarn31** [comment]
@zefklop any update on the above question ?

**Comment by SergeGautherie** [comment]
This PR "is" [CORE-13098](https://jira.reactos.org/browse/CORE-13098).

**Comment by Zero3K** [comment]
I think that https://git.savannah.nongnu.org/cgit/lwip.git/commit/?id=a7b43dae4977b7ca5097f9eda23a14642eeb7487 does the same thing as https://github.com/reactos/reactos/pull/2582.

**Comment by KRosUser** [comment]
@zefklop why was this abandoned? This looked like a valuable upgrade with numerous bug fixes in the IP stack. Should we retry ?

**Comment by KRosUser** [comment]
superseeded by : https://github.com/reactos/reactos/pull/4712

**Pull request closed without merging**
