### PR TITLE
[SHORTCUTS] Addition of Wine IE Shortcuts in Start Menu

### PR DESCRIPTION
**Pull request by KyleKatarn31**
## Purpose

- Addition of Wine IE Shortcuts in Start Menu. This was proposed as an improvement 4 years ago with a preliminary patch but never implemented. Dektop icon to be added in a dedicated PR (see comment from @binarymaster) 

JIRA issue: [CORE-11257](https://jira.reactos.org/browse/CORE-11257)

## Proposed changes

- Wine IE shortcut added to Start Menu Program with creation of additionnal string for localization.
- %16422% is used as per https://docs.microsoft.com/en-us/windows-hardware/drivers/install/using-dirids instead of %ProgramFiles% because of https://jira.reactos.org/browse/CORE-17016

image

### CODE REVIEW

**Comment by gonzoMD** [comment]
Please use 'Wine Internet explorer' also on desktop so that there is no confusion with the official Microsoft application.

**Comment by KyleKatarn31** [comment]
> 
> 
> Please use 'Wine Internet explorer' also on desktop so that there is no confusion with the official Microsoft application.

OK fixed.

**Comment by binarymaster** [comment]
There should be a special desktop shell object called `Internet Browser` with CLSID `{871C5380-42A0-1069-A2EA-08002B30309D}` (in Windows it's Internet Explorer) that will invoke default browser in the system. A desktop shortcut is a hack.

I'm ok with a shortcut in start menu / programs though.

**Comment by KyleKatarn31** [comment]
So you'd be OK if I limit the scope of this PR to the "Start menu" part only ?
Unless somebody would like to push something for the {871C5380-42A0-1069-A2EA-08002B30309D} part here ?

**Comment by binarymaster** [comment]
> So you'd be OK if I limit the scope of this PR to the "Start menu" part only ?

Yes I think this would be ok

**Comment by KyleKatarn31** [comment]
OK done.

**Comment by KyleKatarn31** [comment]
Title and description updated to reflect latest change following discussion with @binarymaster.

Ready for final review, then approval if ok.

**Comment by SergeGautherie** [comment]
> There should be a special desktop shell object called `Internet Browser` with CLSID `{871C5380-42A0-1069-A2EA-08002B30309D}` (in Windows it's Internet Explorer) that will invoke default browser in the system.

I confirm a special object on XP VM.

> A desktop shortcut is a hack.

Meanwhile, it is better than nothing...

**Comment by gonzoMD** [comment]
@SergeGautherie adding hacks for a non-prior issue is a no-go. And even if there would be priority it would need a good reason to do.

**Comment by KyleKatarn31** [comment]
@gonzoMD @SergeGautherie : What is your final word for Desktop ?
So far I propose to go on with Serge proposal (Start menu only, proper desktop implementation later).

If OK for you => Approve and merge please

**Comment by KyleKatarn31** [comment]
@binarymaster What would be your preferred decision ?

**Comment by HBelusca** [comment]
> @binarymaster What would be your preferred decision ?

Answer from Mattermost:
> Stas'M:14:16 - Start menu shortcut only, as I stated in https://github.com/reactos/reactos/pull/2726#issuecomment-623097889

**Comment by KyleKatarn31** [comment]
Thank you @HBelusca

**Pull request merged**
