### PR TITLE
[NTUSER] Fix region updating in IntScrollWindowEx() for Abiword

### PR DESCRIPTION
**Pull request by turican0**
## Purpose

I found out that the problem with redrawing in Abiword is in the `IntScrollWindowEx()` function. It should update the window part after scrolling. Ideally scroll part of the graphic and redraw the missing piece. Apparently the function also sets the area to be redrawn in the future.
And at least that was the problem after running this function, most of the window stopped updating(when typing or cursor blinking) because the area to update was set to only the missing piece of graphics. 
In this patch I set the redraw area to the whole region, instead of just that region.
I'm not sure exactly how the code is supposed to work, and whether this is unnecessarily rendering an already rendered region. However, this solves the Abiword problem.
And in the future, this part will need to be revised anyway - analyze all the variations of behavior in Win, add regression tests (ideally on the graphical part), etc. Unfortunately, I don't have enough experience to do it right now.

JIRA issue: [CORE-13149](https://jira.reactos.org/browse/CORE-13149)

## Proposed changes

The `RgnUpdate` area was originally sent to the `co_UserRedrawWindow()` function - that is, the part of the rendered window that needs to be filled in after descrolling. I have replaced this with the entire area for drawing the window (`RgnClip`).

### CODE REVIEW

**Comment by turican0** [comment]
usefull-scrolling

**Comment by HBelusca** [comment]
> The `RgnUpdate` area was originally sent to the `co_UserRedrawWindow()` function - that is, the part of the rendered window that needs to be filled in after descrolling.

In this Abiword case, what are the coordinates of this region? Is its width/height correct but the coordinates wrong?

**Comment by HBelusca** [comment]
> The scrollex.c code would need to be refactored in the future.

It was originally based from Wine code (with supplemental fixes etc. on top). I'm curious: do you have linux and Wine (possibly latest) available for you to test? If so, how does Abiword behave regarding scrolling there?

**Comment by turican0** [comment]
Now I don't have a log with coordinates, but it's like this:
I want to scroll through the area with this(left, top, right, bottom):
0, 0, 500, 1000
I want to scroll it by 60px in the Y axis.
Then in the original code, RgnUpdate was called with the coordinates:
440, 0, 500, 1000
i.e. only the strip that wasn't displayed before.
In my modification the whole area(0, 0, 500, 1000) is rendered.

**Comment by turican0** [comment]
In the next few days I will investigate how this is handled in the latest wine. I had assumed that most things were synced, but you're right, maybe they've got it sorted, or at least give us a hint.

**Comment by turican0** [comment]
You are right in wine they have that function as NtUserScrollWindowEx and at least according to the code it looks much better. That code is quite different from ours. But if it works well, it would make sense to use it. I'll try how it goes under wine and if it works well I'll try to overwrite it from wine.

**Comment by turican0** [comment]
image

**Comment by HBelusca** [comment]
> You are right in wine they have that function as NtUserScrollWindowEx and at least according to the code it looks much better. That code is quite different from ours. But if it works well, it would make sense to use it. I'll try how it goes under wine and if it works well I'll try to overwrite it from wine.

Instead of just going to blindly "overwrite" it, you should instead understand what the actual functional differences are.

**Comment by turican0** [comment]
You're right, it's important to understand, but working code would help. I already partially rewrote it in https://github.com/turican0/reactos/tree/fix-CORE-13149-test_wine_integration but I still lack an alternative to several functions. I've already tried it and it still doesn't render correctly. But it helps to understand if I display the variables to see what it actually does.

**Comment by turican0** [comment]
@HBelusca I have updated my solution, which hopefully is no longer a hack.
-everything is rendered as it was in the original code - only the RgnUpdate area is rendered again
-but then sets the area for future rendering to the entire area

```
PREGION RgnClip = IntSysCreateRectpRgnIndirect(&rcClip);
IntInvalidateWindows(Window, RgnClip, rdw_flags);
REGION_Delete(RgnClip);
```

**Comment by turican0** [comment]
The original code worked well e.g. for scrollbars where nothing new is drawn, but not for the canvas where it is drawn in the next step.

**Comment by turican0** [comment]
I'll check the wine code to see if it solves this more elegantly(especially the NtUserRedrawWindow function), but the code is very different there, I don't know if their method is easily portable.

**Comment by turican0** [comment]
They have it handled quite differently, so I haven't found any inspiration in the wine code on how to do it differently.

**Comment by turican0** [comment]
I haven't tested a similar bug, and there the problem persists, so I'm going to investigate it again. My guess is that it will be something similar, and if I find this problem, I may come up with a better fix.
https://jira.reactos.org/browse/CORE-13920
scrolling-openoffice

**Comment by turican0** [comment]
I have revised my proposal, now addressing both
https://jira.reactos.org/browse/CORE-13149
as well as
https://jira.reactos.org/browse/CORE-13920 .

In OpenOffice, minor rendering inconsistencies will still have to be worked out, but that's not related to this PR anymore.
@HBelusca Please let me know what you think of the current version, thanks.
usefull-scrolling2

**Comment by turican0** [comment]
I did a test in windows where I made a call in an 800x600 window
RedrawWindow(hwnd, NULL, RgnUpdate, flags);
RgnUpdate 0,500-800,600
flags = RDW_INVALIDATE | RDW_NOCHILDREN (same as scrolling in AbiWord)
And this is the result. The rectangle for future rendering(detected by GetUpdateRect) is similar to ReactOS. So the error is not in the RedrawWindow/co_UserRedrawWindow, but before.
So the correct solution, in my opinion, is the one from the previous commit:
https://github.com/reactos/reactos/pull/7138/commits/552f644c1bc40e0504478e41ce139b94a415101b
+ similar code in co_VIS_WindowLayoutChanged in vis.c(for OpenOffice).
image

**Comment by turican0** [comment]
I worked out flag tests for RedrawWindow, see my branch:
https://github.com/turican0/reactos/tree/test--extension-of-RedrawWindow-apitest-by-flags
And with that result(left WinXP/right ReactOS). Everything is ok, except for the missing WM_ERASEBKGND message calls. I'll try to fix it. It's possible that it's related to this PR, but it also may not be. Either way, it should fix it:
image

**Comment by turican0** [comment]
I've developed more tests this time for the ScrollWindowEx API, so far without applying my patches. The differences are in the SW_ERASE and SW_SMOOTHSCROLL flags (the latter is not implemented yet).
image

**Comment by mega-maniac** [comment]
This line [https://github.com/reactos/reactos/blob/master/win32ss/user/ntuser/scrollex.c#L410](url)
should be changed to: 

if (flags & SW_INVALIDATE) from if (flags & (SW_INVALIDATE | SW_ERASE))

because you can't erase without including the SW_INVALIDATE flag. The way it is now, it will send an WM_ERASEBKGND without the SW_INVALIDATE flag being set.

**Comment by turican0** [comment]
> This line [https://github.com/reactos/reactos/blob/master/win32ss/user/ntuser/scrollex.c#L410](url) should be changed to:
> 
> if (flags & SW_INVALIDATE) from if (flags & (SW_INVALIDATE | SW_ERASE))
> 
> because you can't erase without including the SW_INVALIDATE flag. The way it is now, it will send an WM_ERASEBKGND without the SW_INVALIDATE flag being set.

Thanks, I'll try it, but I'll try this patch first, because there is already a similar bug in RedrawWindow, which is called from ScrollWindowEx.
https://github.com/turican0/reactos/tree/fix-RDW_ERASE-in-co_UserRedrawWindow

**Comment by mega-maniac** [comment]
This test should be removed. if (Wnd->hrgnUpdate).
https://github.com/reactos/reactos/blob/master/win32ss/user/ntuser/painting.c#L444

When IntGetNCUpdateRgn is called during the WM_NCPAINT section (Line: 430), the Wnd->hrgnUpdate region can be deleted preventing a WM_ERASEBKGND from being sent.  It's okay to use a NULL update region for WM_ERASEBKGND.

Once I deleted this test, AbiWord works as intended.

**Comment by turican0** [comment]
@mega-maniac Thanks, I tried both of your recommendations and it doesn't affect this AbiWord error. When I unscroll, and type the text, it doesn't show up. Anyway, I'll try again to see if this hasn't fixed my API tests, or I'll create API tests that will verify that these modifications are correct.

**Comment by turican0** [comment]
Your first modification solves API TEST with SW_ERASE.
`if (flags & SW_INVALIDATE) from if (flags & (SW_INVALIDATE | SW_ERASE))`
image

**Comment by turican0** [comment]
@mega-maniac Anyway, my solution is HACK, because without it the API tests run fine and with it the API tests get messed up. It might be in painting.c as you write, but a little different. Did AbiWord really break the characters you typed after scrolling, if so, didn't you have another patch included in the code?

**Comment by turican0** [comment]
I still can't figure it out.
Here's what works for Abiword:
`Window->hrgnUpdate = NULL;`
or this:
```
GreDeleteObject(Window->hrgnUpdate);
Window->hrgnUpdate = NtGdiCreateRectRgn(0, 0, 0);
```
per co_UserRedrawWindow (line 625) in scrollex.c.
But then it breaks the tests. The fix must be in painting.c, probably in the IntBeginPaint function, maybe somewhere else. So that in certain cases, after drawing, it leaves the modified area for future rendering to the whole area again.

**Comment by turican0** [comment]
Can't be helped, I'll have to create API tests for BeginPaint/EndPaint.

**Comment by mega-maniac** [comment]
This should be removed https://github.com/reactos/reactos/blob/master/win32ss/user/ntuser/painting.c#L1521-L1524
Because the WM_ERASEBKGND is being sent during the BeginPaint function, if the user returns 0 it sets the PaintStruct fErase flag to TRUE, else FALSE.  There is no need to set the Window->state repaint flags to erase again.

**Comment by turican0** [comment]
@mega-maniac I tried that, but it didn't help either. I don't want to change code in this PR that is not related to the problem.

**Pull request closed without merging**
