### PR TITLE
[COMCTL32] Allow only one instance to 'Properties' dialog boxes

### PR DESCRIPTION
**Pull request by zecarlos1957**
[COMCTL32] Allow only one instance to 'Properties' dialog boxes

Expected behavior:
  As in Windows, only one instance of the 'Properties' dialogs box is possible.

Because psInfo->strPropertiesFor is only affected when creating the dialog in PROPSHEET_CreateDialog and we need this data before this stage, we implemented the helper function ExtractPropSheetStr(PropSheetInfo* psInfo) to get the Title "Properties for %s' from the IDD_PROPSHEET DLGTEMPLATE structure.

### CODE REVIEW

**Review by binarymaster — COMMENTED** [review]
Is this a new feature or a bug fix? (is this also behavior on Windows?) It would be nice so see tests results comparison as well.

**Comment by zecarlos1957** [comment]
As in Windows, only one instance of the 'Properties' dialogs box is possible.

**Review by learn-more — CHANGES_REQUESTED** [review]
I very much doubt that comctl32 is blocking a duplicate property sheet like that.
If anything, I'd say that the shell itself is managing this.

image

**Comment by zecarlos1957** [comment]
@learn-more  Seems to be a bigger problem than me.
Any complaints if I delete this PR?

**Comment by learn-more** [comment]
If you think a PR is no longer needed, it is fine to close it

**Pull request closed without merging**
