### PR TITLE
[SHELL32] fr-fr translation update and component size fix

### PR DESCRIPTION
**Pull request by KyleKatarn31**
translation update and component size fix
As per CORE-16895

### CODE REVIEW

**Comment by KyleKatarn31** [comment]
Why is the control failed ?

**Comment by SergeGautherie** [comment]
Please, remove all the empty commits.

**Comment by SergeGautherie** [comment]
> As per CORE-16895

Use the template, to add a link. Thanks.

**Comment by KyleKatarn31** [comment]
How can I remove the empty commits ?

**Comment by SergeGautherie** [comment]
> How can I remove the empty commits ?

In short, rebase then force push.
For additional support, ask on chat or forum, not on GitHub. Thanks.

**Comment by KyleKatarn31** [comment]
I've found how to fix

**Comment by KyleKatarn31** [comment]
Superseeded by PR2587

**Comment by SergeGautherie** [comment]
> Superseeded by #2587

Please, from now on, update open PRs instead of opening new ones.

**Comment by KyleKatarn31** [comment]
OK, sure !
Is there a button in Git to update/overwrite a given PR rather than creating a new one ? I could not find it :-(

**Comment by ThFabba** [comment]
Each PR has an origin branch (here: `KyleKatarn31:master`). Whatever you push to that branch will be reflected in the PR.

**Comment by KyleKatarn31** [comment]
OK, great !

**Pull request closed without merging**
