### PR TITLE
[REGEDIT] Adjustment of column widths

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Registry Editor's default column widths are improper. This PR will fix them.
JIRA issue: [CORE-15187](https://jira.reactos.org/browse/CORE-15187)

### CODE REVIEW

**Comment by katahiromz** [comment]
BEFORE:
column-widths-before
AFTER:
column-widths-after

**Comment by Extravert-ir** [comment]
Shouldn't it go to Wine?

**Comment by Doug-Lyons** [comment]
@Extravert-ir please review the readme.wine file and you can see that regedit.exe is not wine-synced, but reg.exe is still wine-synced.

**Comment by katahiromz** [comment]
The resizing codes of regedit is shit! It should be totally rewritten!

**Pull request closed without merging**
