### PR TITLE
[SHELL32][BOOTDATA] Don't select filename extension upon renaming

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

JIRA issue: [CORE-15242](https://jira.reactos.org/browse/CORE-15242)

BEFORE:
before
AFTER:
after

### CODE REVIEW

**Comment by HBelusca** [comment]
Please make this functionality optional with a way to change the behaviour + keep the default with selecting extensions.
E.g. personally when I select filenames for renaming it's 80% times for changing the extension too.

**Comment by katahiromz** [comment]
What's the registry key to make it optional?

**Comment by HBelusca** [comment]
> What's the registry key to make it optional?

First we need to check whether Windows (Vista/7+) has this feature, and if so, check for the registry key/value. Otherwise we will have to invent our own.

**Comment by katahiromz** [comment]
I think the default behavior must be extension unselected.

**Comment by tkreuzer** [comment]
I like it, since it's much easier to press Ctrl-A to select everything, when you want to replace the entire name, than it is to select only the name or manually delete each character.

**Comment by katahiromz** [comment]
The poll result says the user wants to unselect the extension.
https://chat.reactos.org/reactos/pl/bpny19dtrjf8ub5hhk6qgjspay
poll

**Comment by JoachimHenze** [comment]
I also think we should have a registry setting for that in the registry. I don't MS has such a setting, as 5minutes of googling reveals tons of forums of angry users that aim to change the default behavior. We can do better than MS here and show that ros is about freedom of choice.

**Comment by JoachimHenze** [comment]
Windows XP by default does select also the extension. I have not checked 2k3sp2 yet, but I would expect the same.

**Comment by katahiromz** [comment]
Now we have a setting in the registry:
```txt
HKCU,"SOFTWARE\ReactOS","SelectExtOnRename",0x00010001,0x00000000
```

**Comment by HBelusca** [comment]
> Now we have a setting in the registry:
> 
> ```
> HKCU,"SOFTWARE\ReactOS","SelectExtOnRename",0x00010001,0x00000000
> ```

Maybe put it in some Explorer subkey? `"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer"`

**Comment by katahiromz** [comment]
Moved to `Explorer` key.

**Pull request merged**
