### PR TITLE
[CMD][BOOTDATA] Populate 'Command Processor' registry data

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

Improve compatibility.
JIRA issue: [CORE-8002](https://jira.reactos.org/browse/CORE-8002)

## Proposed changes

- Fix the default values of `AutoCompletionChar` and `PathCompletionChar` in `cmd.exe`.
- Populate `"SOFTWARE\Microsoft\Command Processor"` registry key like Win2k3 does.

## TODO

- [x] Do tests.

## Comparison

WinXP Japanese (`HKLM`):
WinXP
Populated.

WinXP Japanese (`HKCU`):
winxp-hkcu
Populated.

Win2k3 (`HKLM`):
Win2k3
Populated.

Win2k3 (`HKCU`):
win2k3-hkcu
Populated.

ReactOS (AFTER, `HKLM`):
after2
Populated.

ReactOS (AFTER, `HKCU`):
after-hkcu
Populated.

### CODE REVIEW

**Comment by katahiromz** [comment]
The value of `0x40` is mismatching with the `cmd` settings. Hmm...

**Comment by HBelusca** [comment]
I'll investigate. But 0x40 is a character (ASCII `@`)

**Comment by HBelusca** [comment]
> I'll investigate. But 0x40 is a character (ASCII `@`)

So yes, there is no specific interpretation for why they used 0x40. Maybe because it's >= 0x20 (so it disables using this keychar for doing the completion), but isn't an alphabetical character.... What's clear is that in Windows cmd.exe there is no specific handling for 0x40. All character codes >= 0x20 are ignored for the autocompletion.

**Review by HBelusca — APPROVED** [review]
LGTM: one suggestion I would like to see (the adjustment in the comment) and a minor suggestion for a value in the hivedef.inf file.

**Comment by HBelusca** [comment]
> JIRA issue: [CORE-13906](https://jira.reactos.org/browse/CORE-13906)

This bug report isn't the best one to choose for this PR.
[CORE-8002](https://jira.reactos.org/browse/CORE-8002) seems better suited.

**Pull request merged**
