### PR TITLE
[EXPLORER] Check IsHungAppWindow before minimizing

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

Reduce system freezing on `Win+D`.
Normal minimizing causes message transfer.
If the window was hanging, then it fell into endless message loop. (We have to support `SW_FORCEMINIMIZE`)

JIRA issue: [CORE-19673](https://jira.reactos.org/browse/CORE-19673)

## Proposed changes

- In `CanBeMinimize` function of `traywnd.cpp`, check the return value of `IsHungAppWindow` function.
- Before minimizing, check the value of `IsHungAppWindow(...)` in `taskswnd.cpp`.

## TODO

- [x] Do tests.

## Comparison

BEFORE:
before
`Win+D` won't work expectedly if any hung apps.

after
`Win+D` has worked within 6 seconds even if any hung apps.

### CODE REVIEW

**Comment by HBelusca** [comment]
1st commit title: "CanBeMinimize" --> "CanBeMinimized"

**Comment by HBelusca** [comment]
> We have to support `SW_FORCEMINIMIZE`

I think you could still try to use it so that our explorer does "the right thing" on Windows, and since it seems we have it half(?)-plemented, or at least, falling back to `SW_MINIMIZE` behaviour otherwise:
https://git.reactos.org/?p=reactos.git;a=blob;f=win32ss/user/ntuser/winpos.c;hb=71a3be249753653b690e3db81737a448daac6d1e#l2439
(and other places in that file)

**Comment by katahiromz** [comment]
Our current `SW_FORCEMINIMIZE` doesn't help stop the system freezing.

**Comment by HBelusca** [comment]
> Our current SW_FORCEMINIMIZE doesn't help stop the system freezing.

I don't think using it in the code would be a "problem".
You could use that value (which would be the correct one to use, if I correctly understand what you wrote in the PR description and what's in MSDN), but in addition, you check for hung window(s) as you do here, either as a temporary workaround/hackfix/whatever or as an extra safety measure.

**Review by HBelusca — APPROVED** [review]

**Pull request merged**
