### PR TITLE
[TRANSLATION][CPL][CONSOLE] Italian translation update

### PR DESCRIPTION
**Pull request by Fraizeraust**

### CODE REVIEW

**Comment by ale5000-git** [comment]
@gonzoMD
I'm Italian and this PR makes me shiver, I appreciate the efforts but it can't be called Italian.
I can understand only if the author isn't Italian.

**Comment by Fraizeraust** [comment]
@ale5000-git If you believe there needs some improvements then pushing a PR is always welcomed.

And yes, I'm not Italian even though I do speak that language. The thing is, choosing the right words for a correct translation for an Operating System isn't so easy as you might think. So, I'm up to criticism and we can discuss if you want.

**Comment by ale5000-git** [comment]
I appreciate the commitment, but in general there are some word that mustn't be translated because they are became in-use (despite being in English) like "console".
Instead "consola" mean "cheer up" that is a different thing.

There are also a lot of other problems but I currently don't have time to look at all of them, but I will do when I have some free time.

**Comment by Fraizeraust** [comment]
@ale5000-git When you have time drop me a mail (check my E-mail from my profile) and we'll talk.

**Pull request merged**
