### PR TITLE
[MMSYS] Fix left speaker volume track bar

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

Based on KRosUser's `mixer.patch`.
JIRA issue: [CORE-19189](https://jira.reactos.org/browse/CORE-19189)

## Proposed changes

- Delete some code in `OnMixerControlChange` function.

## TODO

- [ ] Do tests.

### CODE REVIEW

**Comment by HBelusca** [comment]
@katahiromz Could you also add [CORE-19190](https://jira.reactos.org/browse/CORE-19190) to the list of JIRA issues this PR may fix? Also could you test the following: in that JIRA report there's a video showing the problem. There is also a checkbox in that dialog saying "Move all bars together". If checked, then whenever you move the right (or left) speaker cursor, the other one should move accordingly. The question is: Is this functionality still working after the PR?

**Comment by JoachimHenze** [comment]
requested @EricKohl for review, as he dealt with that loop before.

**Review by TAN-Gaming — CHANGES_REQUESTED** [review]
I can't reproduce the bug with our mmsys.cpl binary running on Win2k3 SP2 so the bug is not in the applet.

ReactOS:
MMSYS_Volume_ROS

Win2k3:
MMSYS_Volume_Win2k3

**Comment by katahiromz** [comment]
Wrong implementation. Closed.

**Pull request closed without merging**
