### PR TITLE
[EXPLORER] Better preview for classic start menu

### PR DESCRIPTION
**Pull request by feel-the-dz3n**
### Before:

ros_tb_before

### After:

ros after

### CODE REVIEW

**Comment by feel-the-dz3n** [comment]
Why nobody likes?

**Comment by katahiromz** [comment]
Looking must be standard one.

**Comment by jhm0799** [comment]
I personally don't like it because, by default, ReactOS has the Classic theme selected. It would be weird if the end-user kept the classic theme and saw the preview image, which depicts one of the other themes.

**Comment by feel-the-dz3n** [comment]
> I personally don't like it because, by default, ReactOS has the Classic theme selected. It would be weird if the end-user kept the classic theme and saw the preview image for the start menu, which depicts one of the other themes.

What if user selects Lautus theme and sees classic preview? 🤔

**Comment by katahiromz** [comment]
Switching images takes cost. Postponed into the future.

**Comment by blackcrack** [comment]
Yaroslav/ @jhm0799  & @katahiromz ,

the other theme do you not see, if you use the classictheme,
you can't say you don't love it, because you , if you use only the classic theme,
because you do if see never an other Preview as the classic one..
so, can you only say you don't like the funtion, but why, if you never see 
the Function as so on the surface, the preview only .. and this as "classic" in realtime..

so think around the corner ! This function supports the Users and does not restrict him,
Yaroslav you, restrict only the function .. and the users who could have this function.. but why ?

best regards
Blacky

( @feel-the-dz3n : pretty good idea, like it really !! )

**Comment by yagoulas** [comment]
Why was this closed?

**Comment by katahiromz** [comment]
The image wasn't the Classic theme.

**Comment by yagoulas** [comment]
I actually liked it

**Comment by gonzoMD** [comment]
In Windows, the preview image also has a themed taskbar even If set to classic theme. Look here: https://www.adminxp.com/windowsxp/start2e.gif

I would reopen the issue but I am not able to

**Comment by feel-the-dz3n** [comment]
> In Windows, the preview image also has a themed taskbar even If set to classic theme. Look here: https://www.adminxp.com/windowsxp/start2e.gif
> 
> I would reopen the issue but I am not able to

I'm not able to restore a branch or reopen this anymore

**Pull request closed without merging**
