### PR TITLE
WIP. CORE-15384. [NTOS:CC] CcWriteVirtualAddress(): Move ROUND_TO_PAGES(Size) up

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Addendum to 2a80ae2bb6fdb4135d41244335caa2dadb6c8fa9.

JIRA issue: [CORE-15384](https://jira.reactos.org/browse/CORE-15384)

## TODO

- [ ] Untested. Does it help CORE-15384?

### CODE REVIEW

**Comment by HBelusca** [comment]
That's a mere copy (without all the extra debugging stuff) of my patch https://jira.reactos.org/secure/attachment/49716/cc_diagnostics.diff , that doesn't help fixing the problem at all as explained in the debug log.

**Comment by SergeGautherie** [comment]
Updated PR.
Could you reopen?
Then, later, commit with you as author?

**Comment by HBelusca** [comment]
Certainly not, the patch doesn't fix anything, it was just for diagnostics. So I won't commit the PR.

**Comment by SergeGautherie** [comment]
@HeisSpiter, could you have a look at his?
Hermès then I thought current order looks odd...

**Comment by SergeGautherie** [comment]
Eventually superseded by #1668.

**Pull request closed without merging**
