### PR TITLE
[FONT][WIN32SS] Refactor rendering text background

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
JIRA issue: [CORE-14856](https://jira.reactos.org/browse/CORE-14856)
Simplify the background filling codes.

### CODE REVIEW

**Comment by katahiromz** [comment]
BEFORE:
ss1-before
AFTER:
ss1-after
BEFORE:
ss2-before
AFTER:
ss2-after

I found no change.

**Comment by learn-more** [comment]
Did you also test drawing right aligned / centered text?
And multiline text?

**Comment by katahiromz** [comment]
Here is screenshots:
https://jira.reactos.org/secure/attachment/50145/TestOutTest-ros-after-ScreenShot.zip
https://jira.reactos.org/secure/attachment/50144/TextOutTest-win10-ScreenShot.zip

**Comment by katahiromz** [comment]
ros-right.png:
ros-right
win10-right.png:
win10-right
Right alignment is 1-pixel different. I will fix it.

**Comment by katahiromz** [comment]
right-align-fixed
FIXED.

**Comment by katahiromz** [comment]
Retrial.
https://jira.reactos.org/secure/attachment/50158/TextOutTest-ros-retrial-ScreenShot.zip
ros-right

**Comment by katahiromz** [comment]
I tested again:
tested-again
Those 5 failures seem like accidental.

**Comment by JoachimHenze** [comment]
This commit introduced regression CORE-16177 (slowdown).

**Pull request merged**
