### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by sanchaez**
Turns out we miss a LICENSE file.

### CODE REVIEW

**Comment by sanchaez** [comment]
LICENSE file should replace COPYING but this needs approval.

**Comment by ColinFinck** [comment]
Any reason why LICENSE is to be preferred over COPYING? Does GitHub parse it somehow?

Regarding the multiple licenses we're using within the project, I would prefer a solution that states which parts are under GPL 2.0, BSD, MS-PL, etc.
Not yet sure what this is going to look like though. We first need to finish changing the file headers for SPDX license identifiers, then scan the entire tree for used licenses.

**Comment by sanchaez** [comment]
@ColinFinck actually it doesn't matter. But GitHub shows a neat badge with a license: 
Image
Maybe it doesn't apply to us however, if we have multiple licenses in a project.

**Comment by sanchaez** [comment]
I'll close this pull request since it doesn't matter much.

**Pull request closed without merging**
