### PR TITLE
[SHELL32] Enable background image of folder view

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
This PR enables the user to set the background image of the folder view, by the desktop.ini file.
JIRA issue: [CORE-5516](https://jira.reactos.org/browse/CORE-5516)

## Todo
- [x] Refresh the background on navigation.
- [x] Refresh the background on view refresh.
- [x] Text Color.
- [x] Scroll.

### CODE REVIEW

**Comment by katahiromz** [comment]
Done.

**Comment by katahiromz** [comment]
How to access CDefView::m_ListView from CFSFolder? I don't know...

**Comment by katahiromz** [comment]
What callbacks can we use?

**Comment by learn-more** [comment]
`SFVM_GET_CUSTOMVIEWINFO` seems like it could be relevant.

**Comment by katahiromz** [comment]
Thanks for info.

IShellFolderViewCB::MessageSFVCB
https://msdn.microsoft.com/en-us/library/windows/desktop/bb774968.aspx

Currently SFVM_GET_CUSTOMVIEWINFO is undocumented.

**Comment by katahiromz** [comment]
I will retry about callback. Temporarily closed.

**Comment by yagoulas** [comment]
I would try to see if the following can be done:
1) implement the iobjectwithsite interface in the callbqck object and make the cdefview set itself as the site of the callback object. We nees to verify if windows do that.
2) when thw cfsfolder creates the callback, make it pass its path to the callback object
3) make SFVM_WINDOWCREATED do 
IUnknown_GetWindow to its site to get the hwnd of the defview. Thwn it will reqd the desktop.ini file to see if it needs to show a background picture.

We also need to investigate if the listview control has a feature for background pictures.

**Pull request closed without merging**
