### PR TITLE
[SHELLEXT][BTRFS] Fix Compression ComboBox style in BTRFS Properties (shall not be editable)

### PR DESCRIPTION
**Pull request by KyleKatarn31**
## Purpose

_ Fix Compression ComboBox style in BTRFS Properties (shall not be editable). Current implementation allow to enter Freetext, while only 3 types are supported : ZLIB, LZO and ZSTD

JIRA issue: [CORE-16971](https://jira.reactos.org/browse/CORE-16971)

image

## Proposed changes

_ Change CBS_DROPDOWN to CBS_DROPDOWNLIST  in component styles.

image

## TODO

- Waiting for upstream PR to get approved : https://github.com/maharmstone/btrfs/pull/258

### CODE REVIEW

**Comment by HBelusca** [comment]
To be sent upstream.

**Comment by Extravert-ir** [comment]
Need to check how it looks like on Windows

**Comment by KyleKatarn31** [comment]
> 
> 
> To be sent upstream.

Upstream to which repo please ?

**Comment by KyleKatarn31** [comment]
> 
> 
> Need to check how it looks like on Windows

How can I use BTRFS in Win10 ?

**Comment by HBelusca** [comment]
> > To be sent upstream.
> 
> Upstream to which repo please ?

To here: https://github.com/maharmstone/btrfs

**Comment by KyleKatarn31** [comment]
OK, i'll do and, if accepted, i'll come back to this PR for "cherry picking" the change before next sync.
@HBelusca : Would you please add the "WIP" tag on this one ?

**Comment by Saibamen** [comment]
Please mark this Pull Request as Draft: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request

**Comment by KyleKatarn31** [comment]
> 
> 
> Please mark this Pull Request as Draft: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request

Not draft. It's the correct definitive design, but waiting for upstream validation (WIP)

**Comment by KyleKatarn31** [comment]
Upstream PR created : https://github.com/maharmstone/btrfs/pull/258 ,wating for merge.

**Comment by KyleKatarn31** [comment]
Trivial fix reported upstream. No need to rush on an early implementation. Will be integrated with next BTRFS library

**Comment by ale5000-git** [comment]
It got merged.

**Comment by KyleKatarn31** [comment]
Yes thanks. I assume it will have to wait for the next sync to get here.

**Pull request closed without merging**
