### PR TITLE
[BROWSEUI_APITEST] Add ACLMulti testcase

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Add a testcase for `CLSID_ACLMulti`, that owns zero or more AutoComplete list(s) and enumerates.

JIRA issue: [CORE-9281](https://jira.reactos.org/browse/CORE-9281)

## Proposed changes

- Add `ACLMulti.cpp` and modify `CMakeLists.cpp` and `testlist.c`.
- Define `CEnumString` class.
- Add test codes.

WinXP:
WinXP
Successful.

Win2k3:
Win2k3
Successful.

Win10:
Win10
Successful.

### CODE REVIEW

**Comment by HBelusca** [comment]
Maybe you could mention somewhere (commit log?) that these tests complete those from browseui_winetest.

**Comment by katahiromz** [comment]
VirtualBox_ReactOS_27_09_2020_11_24_02
`browseui_winetest` doesn't have detailed tests on `ATLMulti`.

**Comment by katahiromz** [comment]
`browseui_winetest` has `test_ACLMulti` tests. Is it enough?

**Comment by katahiromz** [comment]
Closed.

**Comment by HBelusca** [comment]
> `browseui_winetest` has `test_ACLMulti` tests. Is it enough?

You can always add more tests for the same thing, so as to test more thoroughly different aspects (of the ACLMulti thing, in your case) that may not be tested enough, or at all, by the winetest.

**Pull request closed without merging**
