### PR TITLE
Translate readme.md to Russian

### PR DESCRIPTION
**Pull request by SashaVolohov**
## Purpose

_This PR adds a translation of readme.md into Russian._

## Proposed changes

_I suggest adding a translation of readme.md into Russian._

### CODE REVIEW

**Comment by Fraizeraust** [comment]
Is that necessary (the README markdown file is even barely translated in the first place)?

**Comment by binarymaster** [comment]
Since GitHub doesn't offer a feature for readme localization, and this stuff can be easily translated with an online translator in your browser, I don't see a point in the translation.

Please correct me if I'm wrong.

**Comment by A-Rafael** [comment]
Сan add flags icons with links to translations on top of readme (like on multi-language web sites).

**Comment by ColinFinck** [comment]
We have decided to have user-facing content (the website, forums, and OS user-mode applications) translated into multiple languages while keeping developer-facing content (the wiki, RosBE, Git repos) English-only. Furthermore, we can barely maintain one README file right now (I see that it still points to 0.4.12..)

Therefore I'm closing this PR.
Your help is very much appreciated though as soon as we implement multi-language support to our new website at https://github.com/reactos/web-content

**Pull request closed without merging**
