### PR TITLE
[HOST-TOOLS] Use 'VCVARSALL_ARCH amd64_x86' when needed only

### PR DESCRIPTION
**Pull request by SergeGautherie**
Addendum to 5f94b23.
JIRA issue: [CORE-17542](https://jira.reactos.org/browse/CORE-17542)

### CODE REVIEW

**Comment by SergeGautherie** [comment]
> closed

Why?

**Comment by learn-more** [comment]
> > closed
> 
> Why?

Because I am not going to keep asking for reasoning behind pr's.

**Comment by SergeGautherie** [comment]
> asking for reasoning

I assumed PR title is explicit enough:
Why apply the workaround to unaffected cases?
Why not match code and comment?

**Comment by learn-more** [comment]
> > asking for reasoning
> 
> I assumed PR title is explicit enough:
> Why apply the workaround to unaffected cases?
> Why not match code and comment?

The PR title once again explains what is happening, not _why_.

**Comment by SergeGautherie** [comment]
> The PR title once again explains what is happening, not _why_.

Well, 'when needed only' is _why_: GitHub VMs are amd64 and host-tools compile fine as amd64, except 1 case.
Note that you never explained/answered why you did otherwise.

**Pull request closed without merging**
