### PR TITLE
Core 14023 : Fix SetWorldTransform for metafiles

### PR DESCRIPTION
**Pull request by zefklop**
## Purpose

Forward SetWorldTransform to wine's metafile implementation.

JIRA issue: [CORE-14023](https://jira.reactos.org/browse/CORE-14023)

## Proposed changes
- Do not forward it to ModifyWorldTransform, for which the metafile implementation doesn't know what to do with MWT_MAX+1

### CODE REVIEW

**Comment by HBelusca** [comment]
Hi @zefklop, in your branch, you can squash the three last commits together: "Dispatch SetWorldTransform to lower wine driver", "Fix build" and "update gdi32p.h", so that each of the resulting commits will compile OK.

**Comment by JoachimHenze** [comment]
I manually built on top 0.4.8-dev-180 + manually applying your changes until 9f745d2.
I could not see any improvement for CORE-14023. It still crashed for me when navigating to page5.

**Comment by zefklop** [comment]
@joachimhenze : if that ever builds, please try with the latest commit applied.

**Comment by jimtabor** [comment]
SetWorldTransform and EMF call does not work, it will create a loop in ModifyWorldTransform which should have a call to EMF subsystem.

**Comment by jimtabor** [comment]
MWT_MAX+1 tells EMF to use EMFDRV_SetWorldTransform so,

ModifyWorldTransform,

if (MWT_MAX+1)
 HANDLE_METADC(BOOL, SetWorldTransform, FALSE, hdc, pxform);
else
HANDLE_METADC(BOOL, ModifyWorldTransform, FALSE, hdc, pxform, dwMode);


This will prevent the loop and the additional code to fix the loop.

**Comment by learn-more** [comment]
@jimtabor You comitted with your nickname, not your full name.
@zefklop You comitted with an anonymous users.noreply.github.com email address

**Comment by jimtabor** [comment]
Posted a patch https://jira.reactos.org/secure/attachment/43996/roswine.patch

**Comment by jimtabor** [comment]
I see some issues with calling SetWorldTransform directly. I'll have an updated patch soon.

**Comment by jimtabor** [comment]
Updated patch,
https://jira.reactos.org/secure/attachment/44005/roswine_1.patch

**Comment by sanchaez** [comment]
I assume it is merged now by e1e79f2 ?

**Comment by jimtabor** [comment]
I guess it's okay to close?

**Pull request closed without merging**
