### PR TITLE
[SHELL32] Remove now unused HCR_GetIconA(). CORE-11713

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Addendum to r75607.

JIRA issue: [CORE-11713](https://jira.reactos.org/browse/CORE-11713)

PS:
Unless you would want to resync' these functions from Wine?

### CODE REVIEW

**Comment by SergeGautherie** [comment]
Cc @yagoulas

**Comment by tkreuzer** [comment]
Don't hack wine code, unless absolutely required.

**Comment by SergeGautherie** [comment]
> wine code

Well, not anymore: `dll/win32/shell32             # Forked at Wine-20071011`.
If you prefer (for the time being), I could add `#ifndef __REACTOS__` instead.
Otherwise, how is the issue going to be fixed (ever)?

**Comment by SergeGautherie** [comment]
@tkreuzer, ping for answer.

**Pull request closed without merging**
