### PR TITLE
[THEMES] Mizu Theme

### PR DESCRIPTION
**Pull request by foxlet**
## Purpose

This is the theme component from Project Mizu, inspired by the looks of Windows 10, KDE Plasma, and macOS. The `mizu-public` branch only includes theme resources and necessary fonts.

JIRA issue: [CORE-15936](https://jira.reactos.org/browse/CORE-15936)

## Proposed changes

- Add Mizu Theme resources
- Add Source Sans Pro and Source Code Pro fonts.
- Add syssetup entry for Mizu

Mizu Screenshot

### CODE REVIEW

**Comment by HBelusca** [comment]
For the `Add Source Sans font family.` commit, can you add in the commit log where these fonts have been taken from, and add in `https://git.reactos.org/?p=reactos.git;a=tree;f=media/fonts/doc;hb=HEAD` a license file (as done for the other fonts)?

**Comment by peterooch** [comment]
As an additional question about the fonts, do they support additional scripts other than Latin, such as Cyrillic, Hebrew and others? if not then the text will renders as squares if no font substitutions are in place.

**Comment by foxlet** [comment]
> For the `Add Source Sans font family.` commit, can you add in the commit log where these fonts have been taken from, and add in `https://git.reactos.org/?p=reactos.git;a=tree;f=media/fonts/doc;hb=HEAD` a license file (as done for the other fonts)?

License files have been added.

**Comment by foxlet** [comment]
> As an additional question about the fonts, do they support additional scripts other than Latin, such as Cyrillic, Hebrew and others? if not then the text will renders as squares if no font substitutions are in place.

They both should support the Extended Latin, Greek, Cyrillic, and other Western/Eastern European scripts.

**Comment by jeditobe** [comment]
Let's merge it before 0.4.12 branch! $)

**Pull request merged**
