### PR TITLE
[CMAKE] Remove obsolete 'CMAKE_CXX_COMPILER_VERSION' checks

### PR DESCRIPTION
**Pull request by SergeGautherie**
And upgrade forced 'CMAKE_C_COMPILER_VERSION' value for Clang-cl.

### CODE REVIEW

**Comment by learn-more** [comment]
What does this fix?

**Comment by SergeGautherie** [comment]
This is cleanup, not a fix: same as aae5cd8.

**Comment by learn-more** [comment]
Except there is a change to msvc compiler version, and a random comment in a gcc file

**Comment by SergeGautherie** [comment]
Let's split these `CMAKE_C*_COMPILER_VERSION` changes into separate PRs, then...

**Pull request closed without merging**
