### PR TITLE
Fix SVN to Git migration

### PR DESCRIPTION
**Pull request by HBelusca**
Empty .gitignore files have been added for no reason, and we lost some empty but useful directories (read: "that will be used later on") during the Git migration.

### CODE REVIEW

**Comment by HBelusca** [comment]
These changes should be OK for commit.

**Comment by HBelusca** [comment]
The "ghost" file deletions can be verified as I explain in the associated commit message.

**Comment by sanchaez** [comment]
@HBelusca Your commits are not bound to your account on GitHub.

**Comment by HBelusca** [comment]
Wth?? How do you see that, and how is this possible?

**Comment by sanchaez** [comment]
@HBelusca see image
image
If you associated this email with GitHub or added as secondary, you should click a confirmation link in the mail sent by GitHub.

**Comment by HBelusca** [comment]
Great, thank you very much @sanchaez, this should be fixed now!

**Comment by paulsapps** [comment]
Is it correct that so much stuff is deleted?

**Comment by sanchaez** [comment]
@paulsapps see 3b915b204e6a8414a44af8eb2b669c8d6b4b32ca

**Comment by HBelusca** [comment]
Thanks @ColinFinck ! Re. about the .gitignore files, they were not present in all the empty directories! (see for example boot/bootdata/livecd/ which didn't contain any .gitignore and thus was not present from the beginning)

**Pull request merged**
