### PR TITLE
WIP. [FREELDR] mm/mm.c: Use BYTES_TO_PAGES()

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Assumed not to change behavior, especially with regard to overflow...

## TODO

- [ ] Untested.

### CODE REVIEW

**Comment by learn-more** [comment]
'assumed not to change'
'untested'
those are the keywords that make us all feel good about mm commits.

**Comment by encodedpr** [comment]
/* ULONG
 * BYTES_TO_PAGES(
 *     _In_ ULONG Size)
 *
 * Note: This needs to be like this to avoid overflows!
 */
#define BYTES_TO_PAGES(Size) \
  (((Size) >> PAGE_SHIFT) + (((Size) & (PAGE_SIZE - 1)) != 0))

**Comment by Saibamen** [comment]
Please mark this Pull Request as Draft: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request

**Comment by GeoB99** [comment]
The PR is stall for like 3 years almost, and the author hasn't provided tests that exercise the code suggested. I'm closing this, same reason as for #1176.

**Pull request closed without merging**
