### PR TITLE
[NTOS:PNP] Investigate why the PnP-reset-device code was partially disabled.

### PR DESCRIPTION
**Pull request by HBelusca**

### CODE REVIEW

**Comment by HBelusca** [comment]
Crash on KVM: https://build.reactos.org/builders/Test%20KVM/builds/21474/steps/test/logs/stdio
Crash on VBox: https://build.reactos.org/builders/Test%20VBox/builds/9058/steps/test/logs/stdio
Comparison on KVM when original (disabled) code is kept: https://build.reactos.org/builders/Test%20KVM/builds/21473/steps/test/logs/stdio

**Comment by HBelusca** [comment]
@ThFabba , @vgalnt : any ideas on this problem?

**Comment by ThFabba** [comment]
I think we need to start with proper synchronization of PNP actions before looking at this further makes sense, i.e. finish https://jira.reactos.org/browse/CORE-10456

**Comment by Saibamen** [comment]
Please mark this Pull Request as Draft if is still WIP: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request

**Comment by Extravert-ir** [comment]
You're not polite with this, it is called "the reset hack of doom" :D
So, it was enabled at least three times by @cgutman 
3ad1745d96bad83f4b293a52ee837a51332fefbf
86ebeb35cc3558a1b52a288a28e74d82b9adcbe9
9261b45bedf895a0e5cd0da21a214f82463152e5

According to commit messages, it always caused issues in drivers' removal code. At current state I'm not sure (yet) is it a driver issue or a kernel one, needs more investigation. (added a comment about this in #1569 when moving the code to devaction.c)
Anyway, this should be a JIRA ticket and not a pull request

**Pull request closed without merging**
