### PR TITLE
[MEDIA][FONTS] Add Comic Sans MS fonts (comic.ttf, comicbd.ttf)

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Add Comic Sans MS font files.
JIRA issue: [CORE-16237](https://jira.reactos.org/browse/CORE-16237)
Add "Comic Relief" fonts by Jeff Davis under SIL Open Font License in the name of "Comic Sans MS".

### CODE REVIEW

**Comment by shytzedaka** [comment]
i Am assuming this might also help (not entirely) Solve CORE-16236
https://jira.reactos.org/browse/CORE-16236
As there is some Issues related to comicbd.ttf being missing.

**Comment by katahiromz** [comment]
File `ComicRelief.ttf` is renamed as `comic.ttf`.
File `ComicRelief-Bold.ttf` is renamed as `comicbd.ttf`.
Internal name "Comic Relief" is renamed as "Comic Sans MS".
Internal name "Comic Relief Bold" is renamed as "Comic Sans MS Bold".
I used FontForge to edit the font files.
Copyright text is modified.
FontForge has bug in generating TTF files, that the value of Underline Position goes mad. I did workaround by adding a constant value to Underline Position.

**Comment by katahiromz** [comment]
(c) 2013 Jeff Davis
(c) 2019 Katayama Hirofumi MZ

**Comment by katahiromz** [comment]
Codepage-problem
There is codepage problem. Latin 1 is not selected.
There is wordpad problem. The user cannot type text in WordPad.

**Comment by katahiromz** [comment]
```txt
(win32ss/gdi/ntgdi/freetype.c:432) ## DumpFontList(F8459AAC)
(win32ss/gdi/ntgdi/freetype.c:423) family_name 'Droid Sans Fallback', style_name 'Regular', FontGDI E119EE10, FontObj 00000000, iUnique 0, SharedFace 00000000, Face 00000000, CharSet 0, Filename '(null)'
(win32ss/gdi/ntgdi/freetype.c:423) family_name 'Droid Sans Fallback', style_name 'Regular', FontGDI E119EA68, FontObj 00000000, iUnique 0, SharedFace 00000000, Face 00000000, CharSet 0, Filename '(null)'
(win32ss/gdi/ntgdi/freetype.c:423) family_name 'Droid Sans Fallback', style_name 'Regular', FontGDI E119E938, FontObj 00000000, iUnique 0, SharedFace 00000000, Face 00000000, CharSet 0, Filename '(null)'
(win32ss/gdi/ntgdi/freetype.c:423) family_name 'Comic Sans MS', style_name 'Regular', FontGDI E119FC38, FontObj 00000000, iUnique 0, SharedFace 00000000, Face 00000000, CharSet 0, Filename '(null)'
(win32ss/gdi/ntgdi/freetype.c:423) family_name 'Comic Sans MS', style_name 'Regular', FontGDI E119FB28, FontObj 00000000, iUnique 0, SharedFace 00000000, Face 00000000, CharSet 0, Filename '(null)'
(win32ss/gdi/ntgdi/freetype.c:423) family_name 'Comic Sans MS', style_name 'Regular', FontGDI E119FA18, FontObj 00000000, iUnique 0, SharedFace 00000000, Face 00000000, CharSet 0, Filename '(null)'
```
@learn-more Help me! Not initialized `CharSet` and `SharedFace` of `FontGDI`.

**Comment by katahiromz** [comment]
FontPenalty
FontPalette13
This problem is not about font file. Font engine's fault.

**Comment by katahiromz** [comment]
Win98
Windows 98 can load these font files after I deleted the original. Not font file's fault.

**Pull request merged**
