### PR TITLE
[CMAKE] Use COMPILE_OPTIONS instead of superseded COMPILE_FLAGS

### PR DESCRIPTION
**Pull request by SergeGautherie**
for set_source_files_properties().

## Purpose

Be up-to-date:
https://cmake.org/cmake/help/v3.17/prop_sf/COMPILE_FLAGS.html
'superseded by the [COMPILE_OPTIONS](https://cmake.org/cmake/help/v3.17/prop_sf/COMPILE_OPTIONS.html) property'

## Proposed changes

- Use COMPILE_OPTIONS instead of superseded COMPILE_FLAGS

### CODE REVIEW

**Review by katahiromz — APPROVED** [review]

**Review by HBelusca — APPROVED** [review]

**Review by oleg-dubinskiy — COMMENTED** [review]
There are some more components which can be updated too (some Wine's and WIDL/WPP). See https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=COMPILE_FLAGS. Didn't you update them purposely? :thinking: 
изображение

**Comment by oleg-dubinskiy** [comment]
Also, suggestion for the commit message:
**[CMAKE]** Use COMPILE_OPTIONS instead of **deprecated** COMPILE_FLAGS
This wording sounds and looks much better I think. :slightly_smiling_face:

**Comment by SergeGautherie** [comment]
> Didn't you update them purposely?

https://cmake.org/cmake/help/latest/module/FindBISON.html
`BISON_TARGET(... COMPILE_FLAGS ...)`
is up-to-date as is.

**Comment by SergeGautherie** [comment]
> **[CMAKE]**

Right. Updated.

> **deprecated**

I prefer to copy the very word CMake uses.

**Comment by SergeGautherie** [comment]
Looking for a committer.

**Review by learn-more — APPROVED** [review]

**Review by HBelusca — APPROVED** [review]

**Review by tkreuzer — APPROVED** [review]

**Pull request merged**
