### PR TITLE
[COMDLG32] Fix comdlg32:printdlg crash

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

Fix crash.
JIRA issue: [ROSTESTS-388](https://jira.reactos.org/browse/ROSTESTS-388)

## Proposed changes

- Do `NULL` check on `dmA` variable.

## TODO

- [ ] Do big tests.

### CODE REVIEW

**Comment by katahiromz** [comment]
KVM BEFORE: 6b69202
KVM AFTER: 9920587

VBox BEFORE: 6b69202
VBox AFTER: 9920587

**Review by HBelusca — COMMENTED** [review]
Looking at the failre cases of convert_to_devmodeA function, I wonder which one here failed:
``
 330     if (!dmW) return NULL;
 331     size = dmW->dmSize - CCHDEVICENAME -
 332                         ((dmW->dmSize > FIELD_OFFSET(DEVMODEW, dmFormName)) ? CCHFORMNAME : 0);
 333 
 334     dmA = HeapAlloc(GetProcessHeap(), 0, size + dmW->dmDriverExtra);
 335     if (!dmA) return NULL;
 336 
```

**Comment by katahiromz** [comment]
There's a difficulty for me to fix correctly. I will try to fix for two day.

**Comment by Doug-Lyons** [comment]
@katahiromz, could you take a look at this patch that I had been working on and see if you can incorporate part or all of it here? Thanks.

[printdlg_c_test_crash_fix-01.patch](https://github.com/reactos/reactos/files/12567834/printdlg_c_test_crash_fix-01.patch)

**Comment by katahiromz** [comment]
This PR is beyond my capacity. Closed.

**Pull request closed without merging**
