### PR TITLE
Revert "[SHELL32] Show Product version on About dialog bmp (#3621)"

### PR DESCRIPTION
**Pull request by HBelusca**
## Purpose & Proposed changes

This reverts commit 2636cff09fdb70bfe63c52ea9d2d24dbfc1e337f by Catalin Gabriel Draghita (@jeffbox12), as well as any subsequent changes.

This was agreed upon by the original author on our official Mattermost chat (chat.reactos.org)

discussion_1
discussion_2
discussion_3

The reactos.bmp banners are again generated from the file:
  dll/win32/msgina/resources/svg/reactos.svg

### CODE REVIEW

**Review by binarymaster — APPROVED** [review]
Tested both livecd and bootcd. GINA ok, syssetup ok, shellabout ok. For the sake of consistency of commit titles, suggesting `[SHELL32] Revert "Show Product version on About dialog bmp (#3621)"`

**Comment by jeffbox12** [comment]
Revert looks correct.

**Review by DarkFire01 — APPROVED** [review]
Author consents to change,
discussion has been had

LGTM

**Review by tkreuzer — APPROVED** [review]

**Review by JoachimHenze — APPROVED** [review]
Approved. Yeah, definitely. Deduplication is always good. I do remember that @ColinFinck was also in favor of reverting that.

**Review by oleg-dubinskiy — APPROVED** [review]
LGTM, an old image looks better for me too. Can we merge this today, before 0.4.15 branching? Then we will have neither 0.4.15 nor any other release affected by that at all. Thanks.

**Comment by HBelusca** [comment]
I'll merge when I'm back at the computer (1 or 2 hours from now)

**Comment by oleg-dubinskiy** [comment]
Thanks for merging @HBelusca. :+1:

**Pull request merged**
