### PR TITLE
[WINLOGON] Start screen saver with current user

### PR DESCRIPTION
**Pull request by Doug-Lyons**
## Fix Wrong Text Displayed when 3D Text ScreenSaver Times Out

_Change User Context of creating the screensaver process in winlogon.exe ._

JIRA issue: [CORE-17875](https://jira.reactos.org/browse/CORE-17875)

## Change context that 3D Text ScreenSaver runs as to Current User

_This fixes the wrong text of "ReactOS Rocks!" being displayed when this screensaver times out._

### CODE REVIEW

**Comment by gonzoMD** [comment]
Just curious: Isn't the Screensaver text a "per user" setting? I mean, isn't that text saved in general with this reg key? Wouldn't some HKCU key a better place?

**Review by binarymaster — CHANGES_REQUESTED** [review]
This really looks like a hack. I don't see anywhere in the code of this screensaver where it reads settings from the system account registry.

https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=ScreenSavers%5C%5CText3D

**Comment by learn-more** [comment]
> This really looks like a hack. I don't see anywhere in the code of this screensaver where it reads settings from the system account registry.
> 
> https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=ScreenSavers%5C%5CText3D

Most likely the screensaver is not started as the same user that wrote the settings,
so a good fix would probably involve looking at that.

**Comment by Doug-Lyons** [comment]
I plan to make some major changes to the settings.c file, so I am setting this as a "draft" for now.

**Comment by Doug-Lyons** [comment]
The single failing test shows the error as follows:
LINK : fatal error LNK1201: error writing to program database 'D:\a\reactos\reactos\build\msvc_pdb\vfd.pdb'; check for insufficient disk space, invalid path, or insufficient privilege
This does not sound like any error that my program changes could have caused.

**Comment by Doug-Lyons** [comment]
> This really looks like a hack. I don't see anywhere in the code of this screensaver where it reads settings from the system account registry.
> 
> https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=ScreenSavers%5C%5CText3D

@binarymaster, With the recent changes, do you still consider this a "hack"?

**Comment by binarymaster** [comment]
> With the recent changes, do you still consider this a "hack"?

As long as you are attempting to save changes in other user's (SYSTEM) registry hive, I will consider this a hack.

**Comment by Doug-Lyons** [comment]
> > With the recent changes, do you still consider this a "hack"?
> 
> As long as you are attempting to save changes in other user's (SYSTEM) registry hive, I will consider this a hack.

Can you please provide suggestions on how to make this work without it being a "hack"? Thanks.

**Comment by learn-more** [comment]
> > > With the recent changes, do you still consider this a "hack"?
> > 
> > 
> > As long as you are attempting to save changes in other user's (SYSTEM) registry hive, I will consider this a hack.
> 
> Can you please provide suggestions on how to make this work without it being a "hack"? Thanks.

My comment from 2 days ago does this?

> > This really looks like a hack. I don't see anywhere in the code of this screensaver where it reads settings from the system account registry.
> > https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=ScreenSavers%5C%5CText3D
> 
> Most likely the screensaver is not started as the same user that wrote the settings, so a good fix would probably involve looking at that.
> 
> Probably `StartScreenSaver` (
> 
> https://github.com/reactos/reactos/blob/3fa57b8ff7fcee47b8e2ed869aecaf4515603f3f/base/system/winlogon/screensaver.c#L257
> 
> ) needs to start this process as a specific user, but I am not sure if this should always be done or only in specific cases.

**Comment by Doug-Lyons** [comment]
> > > > With the recent changes, do you still consider this a "hack"?
> > > 
> > > 
> > > As long as you are attempting to save changes in other user's (SYSTEM) registry hive, I will consider this a hack.
> > 
> > 
> > Can you please provide suggestions on how to make this work without it being a "hack"? Thanks.
> 
> My comment from 2 days ago does this?
> 
> > > This really looks like a hack. I don't see anywhere in the code of this screensaver where it reads settings from the system account registry.
> > > https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=ScreenSavers%5C%5CText3D
> > 
> > 
> > Most likely the screensaver is not started as the same user that wrote the settings, so a good fix would probably involve looking at that.
> > Probably `StartScreenSaver` (
> > https://github.com/reactos/reactos/blob/3fa57b8ff7fcee47b8e2ed869aecaf4515603f3f/base/system/winlogon/screensaver.c#L257
> > 
> > ) needs to start this process as a specific user, but I am not sure if this should always be done or only in specific cases.

@learn-more, Thank you for your earlier comments and your taking the time to point them out to me once more in your most recent message. Unfortunately, at my present level of understanding of Windows, most of your comments are incomprehensible to me. This is something that I will have to try and absorb over some period of time before I can even begin to try and do what you suggest. Thanks again for your suggestions. I just need to have lots of time to try and learn these topics to be able to deal with them. Doug Lyons

**Comment by learn-more** [comment]
> @learn-more, Thank you for your earlier comments and your taking the time to point them out to me once more in your most recent message. Unfortunately, at my present level of understanding of Windows, most of your comments are incomprehensible to me. This is something that I will have to try and absorb over some period of time before I can even begin to try and do what you suggest. Thanks again for your suggestions. I just need to have lots of time to try and learn these topics to be able to deal with them. Doug Lyons

In the function pointed out, the screensaver is simply started with `CreateProcessW`.
Because this is called from `Winlogon`, the screensaver is started on the same account as `Winlogon`, which is `Local System` in our case.

My suggestion is that the process should probably be started using `CreateProcessAsUser`, specifying the current logged-in user. (This user is already available, as hinted by `if (!ImpersonateLoggedOnUser(Session->UserToken))`).

However, I do not know if this should always be done, or that there is some switch that allows to control under which user the screensaver is started.

**Comment by Doug-Lyons** [comment]
@learn-more, Thanks lots. I did not know that `CreateProcessAsUser` even existed. This simple change seems to make everything work. Since currently ReactOS is only using the `administrator` user, this might require some fine tuning later on when we support multiple users.

**Review by binarymaster — APPROVED** [review]
Looks ok now, I guess. - Note that I didn't verified what exactly Windows does in different scenarios.

**Comment by gonzoMD** [comment]
Slightly off topic, but I'd suggest to set dwCreationFlags to IDLE_PRIORITY_CLASS.
See: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setpriorityclass

**Comment by trivalik** [comment]
@gonzoMD Where? I cannot find in commit call to SetPriorityClass. Just create a pull request is the easiest.

**Comment by Doug-Lyons** [comment]
> Just curious: Isn't the Screensaver text a "per user" setting? I mean, isn't that text saved in general with this reg key? Wouldn't some HKCU key a better place?

@gonzoMD, After the latest changes, we are now using only an HKCU registry key. Thanks.

**Comment by Doug-Lyons** [comment]
> Slightly off topic, but I'd suggest to set dwCreationFlags to IDLE_PRIORITY_CLASS. See: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setpriorityclass

@gonzoMD, I agree that the screen saver should be IDLE_PRIORITY_CLASS and I have changed this PR to reflect this. Can you add your approval to the PR? Thanks.

**Review by learn-more — APPROVED** [review]
lgtm

**Comment by Doug-Lyons** [comment]
@binarymaster, Thanks for your help in getting this merged. Now this screen saver 'mostly' works. I have more PR's for improving it upcoming.

**Pull request merged**
