### PR TITLE
[BROWSEUI][SHDOCVW] Move CExplorerBand to shdocvw

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

`CExplorerBand` should be implemented in `shdocvw.dll`.
https://github.com/reactos/reactos/blob/894ad4f17d119d312d4ae816cb41db12369389e8/modules/rostests/apitests/com/shdocvw.c#L37

JIRA issue: [CORE-19698](https://jira.reactos.org/browse/CORE-19698)

## Proposed changes

- Move `CExplorerBand` code from `browseui` to `shdocvw`.
- Delete `IDS_FOLDERSLABEL` resource string from `browseui`.
- Add `IDS_FOLDERSLABEL` resource string to `shdocvw`.
- Adapt code to these changes.
- Add `sdk/include/reactos/shdocvw_undoc.h`.
- Implement `IEILIsEqual` function.

## TODO

- [x] Do tests.

## Screenshots

still-working
Still working.

### CODE REVIEW

**Comment by yagoulas** [comment]
I do not agree with that. There is a reason noone tried to move it to shdocvw before. We do not need to follow exactly the silly way MS split the implementation of the browser into multiple dlls. Perhaps we should just move favorites bar to browseui

**Comment by katahiromz** [comment]
> Perhaps we should just move favorites bar to browseui

If so, we cannot commonize `CFavBand` and `CExplorerBand` like MS does.

**Comment by katahiromz** [comment]
Favorites related code is in shdocvw. Furthermore, favorites, history, and explorer common code is in shdocvw. It's best to build in shdocvw with this construction method. Otherwise, you'll end up with a "toilet is only in the villa" situation.

**Comment by katahiromz** [comment]
Never mind, never mind. He's just jealous. Don't take it seriously.

**Comment by katahiromz** [comment]
I'm ready for review.

**Review by yagoulas — CHANGES_REQUESTED** [review]
Does this solve anything?

**Comment by oleg-dubinskiy** [comment]
> Does this solve anything?

If it does not fix any bug(s), it does not mean this is useless. This is more like refactoring. It improves compatibility with Windows at least. As Katayama noted in the PR description, this should be implemented in shdocvw, same as it done in Windows XP/2003. So, as we can understand from this note, he investigated and found out this from his analysis and on the fact an our testcase for this is implemented in shdocvw apitest, and it expectedly works on Windows. :slightly_smiling_face:

**Comment by katahiromz** [comment]
> Does this solve anything?

At least, I saved the implementation of `IEILIsEqual` function.

**Comment by HBelusca** [comment]
You're now merging unreviewed and changes-request PRs?

**Comment by learn-more** [comment]
@katahiromz I fail to see the point of this change?
Why would we want to mimic this exactly?

On Windows this shdocvw is an IE control, and we do not gain anything by mimicking that design from ancient Windows?

**Comment by katahiromz** [comment]
@learn-more I am going to commonize some code of `CFavBand` and `CExplorerBand` as `CNSCBand` class like Windows does. I believe it is an optimization.

**Comment by learn-more** [comment]
> @learn-more I am going to commonize some code of `CFavBand` and `CExplorerBand` as `CNSCBand` class like Windows does. I believe it is an optimization.

Then it would probably make more sense to move stuff out of shdocvw, so we don't need it anymore.

**Comment by whindsaks** [comment]
In recent Windows versions, browseui contains nothing and does nothing so moving it back there makes no sense either.

**Comment by learn-more** [comment]
> In recent Windows versions, browseui contains nothing and does nothing so moving it back there makes no sense either.

Where is it stored now, the newer combase dll?

**Comment by whindsaks** [comment]
> Where is it stored now, the newer combase dll?

ExplorerFrame.dll? ieframe.dll?

(Stuck on Android for a couple of days so I can't check)

**Pull request merged**
