### PR TITLE
[WINLOGON] Implement system sounds.

### PR DESCRIPTION
**Pull request by TAN-Gaming**
[WINLOGON] Implement system sounds.

JIRA issue: [CORE-13951](https://jira.reactos.org/browse/CORE-13951)

Working sounds

- Logon sound (improved)
- Logoff sound
- MessageBox and MessageBeep sounds

### CODE REVIEW

**Comment by learn-more** [comment]
Previous PR: #4091

**Comment by TAN-Gaming** [comment]
@learn-more I have a problem with my fork (commited to the master branch) so I have to reopen the PR.

**Comment by nagayev** [comment]
@TAN-Gaming if you have problems you can revert your commits, see `git reset`

**Comment by TAN-Gaming** [comment]
@nagayev Thanks, but I've re-forked it.

**Pull request closed without merging**
