### PR TITLE
[USERENV] Update Romanian (ro-RO) translation

### PR DESCRIPTION
**Pull request by AndreiMiloiu**
Attendum to https://github.com/reactos/reactos/pull/6517.

Now it synchronizes with Shell32 (look at #6657).

### CODE REVIEW

**Comment by AndreiMiloiu** [comment]
Cc @reactos/lang-romanian

**Review by JoachimHenze — CHANGES_REQUESTED** [review]
When changing any of those paths, they have to be kept in sync with the paths in **shell32**/ro-RO.rc
Since you change one here without changing the other, I do request changes:
Either attach a screenshot which proves that all that you changed here is perfectly in sync to the paths in shell32/ro-RO.rc, or do perform the same changes in shell32/ro-RO.rc **in the same PR**!

**Comment by AndreiMiloiu** [comment]
> When changing any of those paths, they have to be kept in sync with the paths in **shell32**/ro-RO.rc Since you change one here without changing the other, I do request changes: Either attach a screenshot which proves that all that you changed here is perfectly in sync to the paths in shell32/ro-RO.rc, or do perform the same changes in shell32/ro-RO.rc **in the same PR**!

Now it does. I had to revert more changes for this. I attached you the proof for this.


2024-05-03 22_27_18-reactos_dll_win32_shell32_lang_ro-RO rc at f89c43e46aec4e3ffb4ff8c8aabcc07860177
2024-05-03 22_27_37-reactos_dll_win32_shell32_lang_ro-RO rc at f89c43e46aec4e3ffb4ff8c8aabcc07860177

**Comment by AndreiMiloiu** [comment]
However, I wasn't able to find information related to line 14 ("IDS_PROFILEPATH "%SystemDrive%\\Documente și preferințe") so I left it unchanged. It is translated in the same way as MSDN does.

**Review by JoachimHenze — APPROVED** [review]
Now that 99% of this PR was undone, and the PR consists only of a single line, I do approve it:
image

**Pull request merged**
