### PR TITLE
Proposed Implementation of the "Start Menu Properties" page

### PR DESCRIPTION
**Pull request by zecarlos1957**
## Purpose

This code shows the selected start menu image

JIRA issue: [CORE-16039](https://jira.reactos.org/browse/CORE-16039)

## Proposed changes

In order to see the effects of this code it is necessary to comment lines of code 199 to 219 in the class CStartMenuSettingsPage in "base / shell / explorer / trayprop.cpp"
in order to disable the REST_NOSTARTPANEL restriction.

## TODO

_Use a TODO when your pull request is Work in Progress._

- [ ] 
- [ ] 
 
https://github.com/reactos/reactos/commit/b5a223b6e6b924fcb4afb7024dd03e0f7c471fe9
https://github.com/reactos/reactos/commit/f667c71dcc0f83a2388139671445f1033de684e4

### CODE REVIEW

**Comment by HBelusca** [comment]
Why closed?

**Comment by zecarlos1957** [comment]
OPS! I'm confused about how github works and pull request.
I compiled the code with no problems, but in this pull request it has many problems, many red lines and says: "All checks have failed" and in my local repository it works. In addition, I only had two commits to present, but in this pull request are also older ones.
I reopened the pull requeste concerned but the commits are:
"f667c71" and "f667c71"

**Comment by zecarlos1957** [comment]
OPS! I'm confused about how github works and pull request.
I compiled the code with no problems, but in this pull request it has many problems, many red lines and says: "All checks have failed" and in my local repository it works. In addition, I only had two commits to present, but in this pull request are also older ones.
I reopened the pull requeste concerned but the commits are:
"f667c71" and "b5a223b"
and I do not know what the 6a594e0 is

**Comment by binarymaster** [comment]
Learn how to properly reset and force-push your branches. :wink:

**Comment by zecarlos1957** [comment]
OK. I need a little more time to work with GIT and pull requeste. I have already identified some of the problems. 
I found two good tutorials.
My apologies, because this is not the place to ask for help.

 thank you

**Comment by zecarlos1957** [comment]
Well! My pull request has passed all tests, but the commit f667c71 continues with a red cross. What can I do?
Can you review this pull request. Thank you.

**Comment by HBelusca** [comment]
OK I'm going to handle your PR from now on.

**Comment by HBelusca** [comment]
@zecarlos1957 : I have fixed your commits in your PR branch. On your side you need to fix your (local version of your) branch using the following commands:
```
git checkout master
git stash
git fetch --all
git reset --hard origin/master
git stash pop
```
Explanation: Because I have fixed in the remote version of your branch your commits, your local copy has now diverged. To bring it back in sync, first any uncommitted changes are stashed. All the git remote data is then fetched. Then your local branch is reset to match its remote version. **Beware that any other local commits you haven't yet pushed, will be lost!!!!** Finally the local uncommitted changes are unstashed.

In case of doubt (before performing the operation), please talk to us on IRC or Mattermost.

**Comment by HBelusca** [comment]
@zecarlos1957 : are the translations OK? I can commit them separately (they also don't belong to what this PR was supposed to implement).

**Comment by zecarlos1957** [comment]
Yes my friend, the translation is fine. I will be more careful not to mix matters in the next PR.

**Comment by binarymaster** [comment]
@zecarlos1957 congratulations, now this PR is messed up. :eyes:

**Comment by zecarlos1957** [comment]
?

**Comment by zecarlos1957** [comment]
I'll be back, after unlocking the secrets of GIT

**Comment by zecarlos1957** [comment]
it seems better now

**Comment by BenNottelling** [comment]
@zecarlos1957 would you like some help with git?

**Comment by zecarlos1957** [comment]
Yes BenNottlelling. This PR never ends?

**Comment by BenNottelling** [comment]
We can get it done :) 
Can you message me on mattermost?

**Pull request closed without merging**
