### PR TITLE
[WIN32SS][NTUSER] Fix PostTimeMessage message time

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
JIRA issue: [CORE-15632](https://jira.reactos.org/browse/CORE-15632)
`PostTimeMessage` function seems like posting wrong message time. This PR will fix it.

### CODE REVIEW

**Comment by katahiromz** [comment]
Test Program: https://jira.reactos.org/secure/attachment/50805/HaltWindowMsgTime.zip
Win10:
haltwindowmsgtime-win10
BEFORE:
haltwindowmsgtime-ros-before
AFTER:
haltwindowmsgtime-ros-after

**Comment by katahiromz** [comment]
Win10:
user32_apitest-messagetime-win10
BEFORE:
user32_apitest-messagetime-ros-before
AFTER:
user32_apitest-messagetime-ros-after

**Comment by HBelusca** [comment]
Out of curiosity, in which context have you found this bug? By testing some application? (if so, which one?)

**Comment by katahiromz** [comment]
I found this issue in trying to implement the ghosting feature. MsqIsHung wrongly had returned TRUE before waiting 5 seconds. So I doubted the message times.

**Comment by yagoulas** [comment]
Ok, this makes sense. Let me run it in buildbot to see the test results from this first.

**Comment by yagoulas** [comment]
I merged this manually to make it two commits, don't worry about the closed status.

**Pull request closed without merging**
