### PR TITLE
Add Red, White, Blue Classic Color Scheme for Classic Theme

### PR DESCRIPTION
**Pull request by milawynsrealm**
## Purpose

The purpose of this commit is to add the Red, White, and Blue Color Scheme that's currently missing from the list. Since this color scheme comes with Windows XP, it would make sense to add it since someone may expect it to be there. In addition, I also translated the strings for all the Color Schemes into themeui.

JIRA issue: [CORE-12943](https://jira.reactos.org/browse/CORE-12943)

## Proposed changes

- Adds the 'Red, White, and Blue' Color Scheme to the registry.
- Adds translations of Color Schemes for the Classic Theme into themeui.dll.

### CODE REVIEW

**Comment by milawynsrealm** [comment]
Don't know why it included all those other pull request merges I did to update my fork. Are they included in the pull request. Do I need to do anything about it, or what?

**Comment by milawynsrealm** [comment]
Forgot to branch

**Comment by milawynsrealm** [comment]
Created the commit to the proper branch. Not sure what to do next.

**Comment by binarymaster** [comment]
You have to recreate pull request from proper branch.

**Comment by Fraizeraust** [comment]
Bear in mind it's not recommended to create a pull request based on `master` branch. That branch is mainly reserved for commits which are merged to it. In order to push your work you've to create a separate (using `git checkout -b BRANCH_NAME`) and create a PR based on top of that as @binarymaster said.

**Pull request closed without merging**
