### PR TITLE
[MEDIA][FONTS] Fix French glyphs of Tahoma font

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Fix French glyphs (`U+00EC`, `U+00EE`, and `U+00EF`) of Tahoma font.
Version 0.018 khmz

JIRA issue: [CORE-16899](https://jira.reactos.org/browse/CORE-16899)

AFTER:
after

### CODE REVIEW

**Comment by katahiromz** [comment]
@KyleKatarn31 Can you test?

**Comment by KyleKatarn31** [comment]
> 
> 
> @KyleKatarn31 Can you test?
> 
>     1. Copy new Tahoma.ttf font file into media/fonts.
> 
>     2. Delete reactos.cab in output folder.
> 
>     3. Rebuild.

OK i will do it within 1 hour

**Comment by KyleKatarn31** [comment]
Test ongoing.

**Comment by KyleKatarn31** [comment]
I confirm it is fixed. Thanks !

**Comment by katahiromz** [comment]
I will wait for @JoachimHenze.

**Comment by JoachimHenze** [comment]
I can not review that binary file, but I have trust in your skills to modify the glyphs Katayama, as you successfully did that multiple times already. You just should remove that additional globber that gets into the ttfs by fontforge some day (just search for "thinkpad" within the binary file, but that got introduced earlier already). IIrc there was sometimes some metrics hack you had to apply upon saving into some fonts, but I don't remember why, under which conditions and so on. iirc whenever you saved with fontforge. And ofc I do not know, whether you might have already done this.

:)

No complaints from my side regarding this PR, as it has been confirmed to be working by your screenshot and Kyle. I did no practical tests myself.

**Comment by katahiromz** [comment]
@KyleKatarn31 The PR is updated. Retest please.

**Comment by KyleKatarn31** [comment]
> 
> 
> @KyleKatarn31 The PR is updated. Retest please. Read French texts carefully.

I confirm that the 3 "i" are now corrects.
However, when I compare Tahoma with charmap : XP vs ROS, there are some differences (some chars are on one side but not on the other). Is it intentionnal ?

image

**Comment by katahiromz** [comment]
There are some lacking glyphs. That will be fixed later. Thanks.

**Pull request merged**
