### PR TITLE
WIP. [USETUP] Enable bn-IN (so bn-BD too) language, on LiveCD. CORE-16766

### PR DESCRIPTION
**Pull request by SergeGautherie**
Follow-up to
JIRA issue: [CORE-16766](https://jira.reactos.org/browse/CORE-16766)

NB:
I duplicated en-US.
bn-BD is not translated at all yet.

### CODE REVIEW

**Comment by SergeGautherie** [comment]
@HBelusca, like this?

**Comment by HBelusca** [comment]
I think you should also take care of this file:
https://git.reactos.org/?p=reactos.git;a=blob;f=base/setup/usetup/muilanguages.h;hb=1edfddf07a7ef360eb3d5409a67217bd2d36bb0b#l486

**Comment by SergeGautherie** [comment]
> also take care

Indeed, I missed that update.
Eventually, doing the opposite, as trivial cleanup only.

**Comment by Saibamen** [comment]
Please mark this Pull Request as Draft: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request

**Pull request closed without merging**
