### PR TITLE
[CALC] Reset error status when getting out of error

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

Based on KRosUser's `calc_nan.patch`.
JIRA issue: [CORE-19191](https://jira.reactos.org/browse/CORE-19191)

## TODO

- [ ] Do tests.

### CODE REVIEW

**Comment by HBelusca** [comment]
@carlo-bramini Hi, could you check this PR and approve if it's correct?

**Comment by carlo-bramini** [comment]
> @carlo-bramini Hi, could you check this PR and approve if it's correct?

Nice catch fo the bug!
However, in my opinion the correction is not completely correct because the problem still exists also elsewhere, for example when you press backspace for deleting digits.
I think that it would be better to fix the code by doing the same behaviour of the original calculator for XP, by allowing only to press the clear key for deleting the NAN condition.
I did this fix and I'm going to share it.

**Comment by JoachimHenze** [comment]
most likely superseded by https://github.com/reactos/reactos/pull/5988

**Comment by katahiromz** [comment]
So, close.

**Pull request closed without merging**
