### PR TITLE
[FONTS][SETUP] Add Franklin Gothic Medium fonts

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

Add "Franklin Gothic Medium" fonts.
JIRA issue: [CORE-16272](https://jira.reactos.org/browse/CORE-16272)

- Add "Franklin Gothic Medium" and "Franklin Gothic Medium Italic" fonts by duplicating Alexei Vanyashin's "Libre Franklin" fonts and renaming them.
- Delete some "Franklin Gothic Medium" font substitutes.
- Add LICENSE file.

I made these font files by using FontForge. Their family name is "Franklin Gothic Medium". Their display names are "Franklin Gothic Medium" and "Franklin Gothic Medium Italic". Their font filenames are framd.ttf and framdit.ttf. The Underline Positions are hacked by adding an integer value for workaround of FontForge's bug.

Alexei Vanyashin's "Libre Franklin" fonts are available at https://github.com/alexeiva/Libre-Franklin .

### CODE REVIEW

**Comment by katahiromz** [comment]
Copyright (c) 2015, Impallari Type (www.impallari.com)
Copyright (c) 2019 Katayama Hirofumi MZ.

License: SIL Open Font License Version 1.1

**Comment by katahiromz** [comment]
wrong
Something is wrong... Retry.

**Comment by katahiromz** [comment]
right
OK.

**Comment by katahiromz** [comment]
Franklin Gothic Medium vs Libre Franklin Medium:
Franklin-Gothic-Medium-vs-Libre-Franklin-Medium
Shrinking is required.

**Comment by tkreuzer** [comment]
@katahiromz Isn't "Franklin Gothic" a protected name? I have doubts, that you can simply name something like that.

**Comment by katahiromz** [comment]
Cc @ColinFinck

**Pull request merged**
