### PR TITLE
[MEDIA][FONTS] Add Verdana fonts

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

JIRA issue: [CORE-16264](https://jira.reactos.org/browse/CORE-16264)

- Add "Verdana", "Verdana Bold", "Verdana Bold Italic" and "Verdana Italic" fonts by duplicating "Bitstream Vera Sans" fonts and renaming them.
- Delete some "Verdana" font substitutes.
- Add LICENSE file.

I made these font files by using FontForge. Their family name is "Verdana". Their display names are "Verdana", "Verdana Bold", "Verdana Bold Italic" and "Verdana Italic". Their font filenames are verdana.ttf, verdanab.ttf, verdanaz.ttf and verdanai.ttf. The Underline Positions are hacked by adding an integer value for workaround of FontForge's bug.

### CODE REVIEW

**Comment by katahiromz** [comment]
something-wrong
Something is wrong...

**Comment by katahiromz** [comment]
ok
OK, fixed.

**Comment by katahiromz** [comment]
Copyright (c) 2003 by Bitstream, Inc. All Rights Reserved.
Copyright (c) 2019 Katayama Hirofumi MZ.

Licensed under Bitstream Vera Fonts Copyright.

**Comment by katahiromz** [comment]
Stamina is not fixed and not related.
stamina

**Comment by katahiromz** [comment]
For comparison, in win10:
Win10

**Comment by ale5000-git** [comment]
@katahiromz

Just my idea: by reading "The Underline Positions are hacked by adding an integer value for workaround of FontForge's bug" over 20 times I wonder if you will take less efforts by fixing the FontForge's bug one time rather than workaround it infinite times :)

**Comment by SergeGautherie** [comment]
> Delete some "Verdana" font substitutes.

**Pull request merged**
