### PR TITLE
[COMDLG32] Enlarge list area in CHOOSE_FONT dialog

### PR DESCRIPTION
**Pull request by Mas4hmad**
## Purpose
_enlarge that area for user readibility._

## Proposed changes
- enlarge window and font, style, and font size list

### Preview
Before
Untitled
After
size_font

### CODE REVIEW

**Comment by HBelusca** [comment]
The dialogs are generated from some templated rc + the .po files in Wine... And I'm not sure how they deal with the different dialog and button sizes per lang there!

**Comment by Mas4hmad** [comment]
> 
> 
> Can you upload screenshots for **before** and **after** for comparison

Will do, please wait a moment

>
>
> it seems winesynced code.

>
>
>The dialogs are generated from some templated rc + the .po files in Wine

i don't know if it's wine-sync. And i don't have any other system after windows. so, i can't confirm that.

**Comment by Mas4hmad** [comment]
i just looking into wine's code at https://source.winehq.org/git/wine.git/blob/HEAD:/dlls/comdlg32/comdlg32.rc#l248

they don't update the size yet.

**Comment by Mas4hmad** [comment]
this issue has been linked to https://bugs.winehq.org/show_bug.cgi?id=49034. i have send the patch too.
i hope it can be reviewed.

**Comment by Mas4hmad** [comment]
winesync is merged in wine with link: https://source.winehq.org/git/wine.git/commitdiff/cf8a6eb2769d2c4ba5bb837d29db89f6b88706ae. let's merge it in ReactOS.

**Pull request merged**
