### PR TITLE
[TIMEDATE] Improve analog clock appearance

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

Improve analog clock appearance of Control Panel Applet `timedate`.

## Proposed changes

- Totally rewrite the clock-related code.
- Emulates line width by `WidenPath` trick.

BEFORE:
before
AFTER:
VirtualBox_ReactOS_15_02_2021_22_28_00

### CODE REVIEW

**Comment by katahiromz** [comment]
`timedate.cpl` on Win2k3:
2k3

**Comment by katahiromz** [comment]
We can change the colors as we like. For example, red, blue or darkgreen etc.

**Review by binarymaster — COMMENTED** [review]
Would be better do make it switchable, as some people might prefer previous style instead of the new one, or vice versa.

**Comment by katahiromz** [comment]
Closed.

**Pull request closed without merging**
