### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by Saibamen**
Created LICENSE from GitHub license templates (https://help.github.com/articles/adding-a-license-to-a-repository/)

Projects on GitHub can be searched by license type:
https://github.com/search?utf8=%E2%9C%93&q=GNU+GENERAL+PUBLIC+LICENSE++filename%3Alicense+&type=Code

### CODE REVIEW

**Comment by HBelusca** [comment]
Note that it's not as we had only one clear license. Instead we are running with "many": the most commonly used is GPL2, but we also have BSD and another one; see the different COPYING files we have at the root of the reactos repository.

**Comment by ColinFinck** [comment]
This is a duplicate of #8

**Comment by wjk** [comment]
May I suggest that the `LICENSE` file in this repository instead contain links to the other applicable license files, plus [the note at the bottom of the `COPYING` file stating the linking exception](https://github.com/reactos/reactos/blob/31aab36e886a65c51dacdd7264615b4c65dd6789/COPYING#L342-L348)? This is how I would solve the issue of having a single LICENSE file for a project that is released under the terms of multiple different licenses.

**Comment by ColinFinck** [comment]
The idea should be that all file headers are eventually changed to refer to the official license texts at spdx.org.
This way, also eliminating the linking exception, because a normal GPL restricts us in no way.

**Comment by wjk** [comment]
@ColinFinck Wouldn't eliminating the linking exception cause problems for distributing ReactOS with proprietary applications/drivers? Could you please clarify this? Thanks!

**Comment by ColinFinck** [comment]
@wjk: Regarding that, please check my Hackfest presentation (https://youtu.be/OTVVz9VLisU) and the slides (https://svn.reactos.org/press-media/trunk/Events/2017%20-%20Hackfest/Licensing.pdf)

**Comment by sanchaez** [comment]
See #8 .

**Comment by sanchaez** [comment]
Adding LICENSE has little sense except for a badge and search queries. 
Also, we have [COPYING](https://github.com/reactos/reactos/blob/31aab36e886a65c51dacdd7264615b4c65dd6789/COPYING)
that is also [widely used](https://github.com/search?utf8=%E2%9C%93&q=GNU+GENERAL+PUBLIC+LICENSE++filename%3Acopying+&type=Code) on GitHub. 
I think adding LICENSE is a part of much bigger changes in headers that @ColinFinck mentioned. There are files that link to `COPYING`.
Until that this PR is irrelevant as it's duplicate #8 and shoul be closed.

**Pull request closed without merging**
