### PR TITLE
Disable gcc threadsafe static init code.

### PR DESCRIPTION
**Pull request by learn-more**
## Purpose

This disables gcc code that will guard the creation of statics with locks.
Our MSVC build does not do this either.

Binaries to check:

 - [x] base\applications\fltmc\fltmc.exe
 - [ ] base\applications\msconfig_new\msconfig_new.exe
 - [ ] base\applications\mspaint\mspaint.exe
 - [ ] base\applications\network\telnet\telnet.exe
 - [ ] base\applications\rapps\rapps.exe
 - [ ] base\shell\explorer\explorer.exe
 - [ ] base\shell\filebrowser\browseui.dll
 - [ ] bootcd\reactos\reactos\acppage.dll
 - [ ] bootcd\reactos\reactos\atl_apitest.exe
 - [ ] bootcd\reactos\reactos\browseui.dll
 - [ ] bootcd\reactos\reactos\devmgr.dll
 - [ ] bootcd\reactos\reactos\explorer.exe
 - [ ] bootcd\reactos\reactos\explorer_old.exe
 - [ ] bootcd\reactos\reactos\fltmc.exe
 - [ ] bootcd\reactos\reactos\fontsub.exe
 - [ ] bootcd\reactos\reactos\frag.exe
 - [ ] bootcd\reactos\reactos\msconfig_new.exe
 - [ ] bootcd\reactos\reactos\mspaint.exe
 - [ ] bootcd\reactos\reactos\netreg.exe
 - [ ] bootcd\reactos\reactos\rapps.exe
 - [ ] bootcd\reactos\reactos\rosautotest.exe
 - [ ] bootcd\reactos\reactos\roshttpd.exe
 - [ ] bootcd\reactos\reactos\shellbtrfs.dll
 - [ ] bootcd\reactos\reactos\stobject.dll
 - [ ] bootcd\reactos\reactos\telnet.exe
 - [ ] bootcd\reactos\reactos\unfrag.exe
 - [ ] dll\shellext\acppage\acppage.dll
 - [ ] dll\shellext\shellbtrfs\shellbtrfs.dll
 - [ ] dll\shellext\stobject\stobject.dll
 - [ ] dll\win32\browseui\browseui.dll
 - [ ] dll\win32\devmgr\devmgr.dll
 - [ ] dll\win32\shell32\shell32.dll
 - [ ] host-tools\utf16le.exe
 - [ ] host-tools\xml2sdb.exe
 - [ ] host-tools\sdk\tools\hhpcomp\hhpcomp.exe
 - [ ] modules\rosapps\applications\explorer-old\explorer_old.exe
 - [ ] modules\rosapps\applications\fraginator\frag.exe
 - [ ] modules\rosapps\applications\fraginator\unfrag.exe
 - [ ] modules\rosapps\applications\net\netreg\netreg.exe
 - [ ] modules\rosapps\applications\net\roshttpd\roshttpd.exe
 - [ ] modules\rosapps\applications\sysutils\fontsub\fontsub.exe
 - [ ] modules\rostests\apitests\atl\atl_apitest.exe
 - [ ] modules\rostests\apitests\browseui\browseui_apitest.exe
 - [ ] modules\rostests\rosautotest\rosautotest.exe

### CODE REVIEW

**Comment by HBelusca** [comment]
So... what's the real purpose of disabling such a thing? Does it fix compilation of some modules, or "fix" corruptions?

**Comment by learn-more** [comment]
Transforms this code into this code

The trigger for writing this was a compiler error, but in general I think it's good to aim for (somewhat) equal code generation.

**Comment by HBelusca** [comment]
Ah yeah I see that gxx_personality_stuff.

**Comment by paulsapps** [comment]
Disabling thread safe static init in C++ means that if 2 threads in an app create an ATL string for instance, then this will introduce a race condition. The "fix" for that is to then add some manual synchronization, it is probably quite dangerous to do this.

**Comment by tkreuzer** [comment]
If VS doesn't generate this kind of code, then we need to fix it in a proper/compatible way. From a quick look at the guarded statics I would judge that the code is sloppy/broken. I suggest using the info from the GCC build to identify all instances and fix them first. Either get rid of the static locals and convert them into globals, so they get initialized at startup time, or allocate the instances from the heap and save their pointers using InterlockedCompareExchange().

**Comment by learn-more** [comment]
@paulsapps I am well aware of this.
@tkreuzer MSVC has never generated code for this as far as I know, why would we all of a sudden need a global fix for a gcc specific addition?

**Comment by tkreuzer** [comment]
@learn-more We also have code in our CRT that initializes global variables, which crashes when compiled with MSVC with optimizations enabled. You could ask, why "all of a sudden" we would need a fix for that. Probably because nobody tested that before. In this case you risk breaking GCC builds based on the assumption that it should probably somehow work, since nobody noticed anything bad with VS builds so far.

**Comment by learn-more** [comment]
All binaries with the text `_cxa_guard_acquire` in them:
```
fltmc.exe
msconfig_new.exe
mspaint.exe
telnet.exe
rapps.exe
browseui.dll
acppage.dll
shellbtrfs.dll
stobject.dll
browseui.dll
devmgr.dll
shell32.dll
utf16le.exe
xml2sdb.exe
hhpcomp.exe
explorer_old.exe
frag.exe
unfrag.exe
netreg.exe
roshttpd.exe
fontsub.exe
atl_apitest.exe
rosautotest.exe
```

**Comment by paulsapps** [comment]
Yeah "magic statics" only got added in MSVC2015 :|

**Comment by learn-more** [comment]
@tkreuzer how's this?
```
    static IAtlStringMgr* GetInstance(void)
    {
#if !defined(ROS_ATL_NO_THREADSAFE_STRINGMGR_INIT)
        static volatile LONG g_HeapInitialized = 0;
        static CWin32Heap* Win32Heap = NULL;
        static CAtlStringMgr* StringMgr = NULL;

        switch (InterlockedCompareExchange(&g_HeapInitialized, 1, 0))
        {
        case 0:
            /* We are the first, initialize it */
            Win32Heap = new CWin32Heap(::GetProcessHeap());
            StringMgr = new CAtlStringMgr(Win32Heap);
            InterlockedIncrement(&g_HeapInitialized);
            break;
        case 1:
            /* Someone beat us to it, let's wait for them */
            while (InterlockedCompareExchange(&g_HeapInitialized, 2, 2) != 2)
                Sleep(0);
            break;
        case 2:
            /* Nothing to do */
            break;
        }

        return StringMgr;
#else
        static CWin32Heap Win32Heap(::GetProcessHeap());
        static CAtlStringMgr StringMgr(&Win32Heap);
        return &StringMgr;
#endif
    }
```

**Comment by paulsapps** [comment]
What about implementing the `InitOnceExecuteOnce` API instead? https://msdn.microsoft.com/en-us/library/windows/desktop/ms683493(v=vs.85).aspx

**Comment by HBelusca** [comment]
@paulsapps: It is already there: https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=InitOnceExecuteOnce
But since it's a Vista+ API I'm not sure how we would use it in our core "win32" modules (unless of course if we statically link this lib where needed).

**Comment by learn-more** [comment]
@tkreuzer It seems that we already disable this for msvc:
https://git.reactos.org/?p=reactos.git;a=blob;f=sdk/cmake/msvc.cmake;hb=68af472a2133fb8e6859a7a9d5363385b995f891#l55

**Comment by tkreuzer** [comment]
@learn-more Your code mixes CWin32Heap* and CWin32Heap. It also seems a bit overcomplicated. Here's what I have in mind:

```
static IAtlStringMgr* GetInstance(void)
{
    static CWin32Heap* s_Win32Heap = NULL;
    static IAtlStringMgr* s_StringMgr;

    CWin32Heap* Win32Heap = new CWin32Heap(::GetProcessHeap());
    if (InterlockedCompareExchangePointer((PVOID*)&s_Win32Heap, Win32Heap, NULL) != NULL)
    {
        delete TempWin32Heap;
    }

    IAtlStringMgr* StringMgr = new CAtlStringMgr(Win32Heap);
    if (InterlockedCompareExchangePointer((PVOID*)&s_StringMgr, StringMgr, NULL) != NULL)
    {
        delete StringMgr;
    }

    return s_StringMgr;
}
```

**Comment by learn-more** [comment]
@tkreuzer But in your code, you are creating new objects every call to this function, that is a bit of a waste?

**Comment by tkreuzer** [comment]
@learn-more Yeah, you're right. I updated it.

**Comment by learn-more** [comment]
@tkreuzer Thanks, I added it to this PR under your name.

**Comment by learn-more** [comment]
Will revisit this at a later time.

**Pull request closed without merging**
