### PR TITLE
[KERNEL32] LCMapString: Convert Chinese characters

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

Realize conversion between Simplified Chinese and Traditional Chinese in `kernel32!LCMapStringA/W/Ex` functions.

JIRA issue: [CORE-18987](https://jira.reactos.org/browse/CORE-18987), [CORE-18950](https://jira.reactos.org/browse/CORE-18950)

## Proposed changes

- Add `sim2tra.h` and `tra2sim.h` files.
- Implement `LCMAP_SIMPLIFIED_CHINESE` and `LCMAP_TRADITIONAL_CHINESE` flags in `LCMapStringA/W/Ex`.

## TODO

- [x] Do small tests.

### CODE REVIEW

**Comment by katahiromz** [comment]
Checking `kernel32_winetest locale`...
BEFORE:
before-1
AFTER:
after-1
No change.

**Comment by katahiromz** [comment]
Using test programs...

BEFORE:
before
AFTER:
after
LGTM.

**Comment by katahiromz** [comment]
Cc @reactos/lang-chinese

**Review by eason329 — APPROVED** [review]
used test program in zh-TW environment (somehow), LGTM rn

**Pull request merged**
