### PR TITLE
CORE-14513 [CMAKE] Remove modules that are shipped with cmake

### PR DESCRIPTION
**Pull request by ariscop**
JIRA issue: [CORE-14513](https://jira.reactos.org/browse/CORE-14513)

Remove some of the cmake modules that shadow upstream modules
These were included apparently 'so things work for everyone', maybe there were multiple versions of cmake in use at the time? with rosbe this is no longer the case
The MSVC related files have some changes related to clang-cl that i'm not currently able to test

- `CMakeDetermineCompilerId` is not used at all, cmake uses its own copy
- `CMakeParseArguments` is simply an old version of the upstream module
- `Compiler/GNU.cmake` was edited to change some default flags, now overridden in gcc.cmake
- `Platform/Windows.cmake` was an old version with two nmake related lines commented out, possibly breaking the nmake generator

### CODE REVIEW

**Comment by ariscop** [comment]
Original svn branch isn't part of the git repo, i've not been able to track the files history past the trunk merge in 2011, but when merged it seems they were identical to the files shipping with cmake 2.8
They were also fixed for cmake 3.6 support ([CORE-12373](https://jira.reactos.org/browse/CORE-12373)) but not overriding avoids the problem

**Comment by HBelusca** [comment]
Cc @AmineKhaldi , @tkreuzer or @ThFabba as they may know why these files were originally added and their precise state as of now.

**Comment by ariscop** [comment]
I'm confident that `Platform/Windows-MSVC.cmake` is the only file with meaningful changes
`VISUAL-ASM.cmake` is unique to reactos and unaffected by the cmake policy

**Comment by ariscop** [comment]
Found that the intended way to override _INIT flags is using `CMAKE_USER_MAKE_RULES_OVERRIDE`, which can be set in the toolchain files, the commit removing GNU.cmake sets that

[gist containing all commits to Windows-MSVC.cmake](https://gist.github.com/ariscop/d96a5cfffd5214cf70798a9c993f31a1), the most recent one is odd as `CMAKE_COMPILER_SUPPORTS_PDBTYPE` should only be true for msvc 6, the flag seems to have been removed in all later versions of msvc

**Comment by SergeGautherie** [comment]
> Original svn branch isn't part of the git repo

If you haven't already, try and have a look at the [svn repo](https://svn.reactos.org/svn/reactos/trunk/reactos/sdk/cmake/).

**Comment by ariscop** [comment]
@SergeGautherie I'm unfamiliar with svn, but a quick check didn't reveal any changes of note from before the merge

There's something weird going on with implib handling, which will have to be a separate pr, this one is complete

**Comment by tkreuzer** [comment]
Just FYI: I tested building with unmodified CMake 3.2.1 and it still works. It will probably kill some extra features like support for clang / VsSolution when the vanilla CMake is used, but that is not worth keeping these files IMO. We should preferably also get rid of Windows.MSVC.cmake, but that will require fixing.

**Comment by SergeGautherie** [comment]
> The MSVC related files have some changes related to clang-cl that i'm not currently able to test

In case you lack an environment, you may try and use the `AppVeyor` service (See `appveyor.yml`).

**Comment by ariscop** [comment]
As it turns out the clang-cl changes are trivial, msvc fails if you remove that file because it emits an empty /implib: argument. The root cause for that is the use of spec2def to generate lib files to support delay load libs on gcc, and later repurposed to speed up rebuilds 7c9159f25fac61d3f8bf9ba5e12fbc5e7d3c8277

Quick fix is to override build/link commands for msvc, the gcc build does this for rsym and SEPARATE_DBG and incidentally removes --out-implib

Proper fix involves reworking spec2def so its only used for delay load libs on gcc, which is a larger change for a different PR. The 3 files removed in this one are done so trivially with no measurable side effect, confirmed by diffing cmake variables and build files

**Comment by ariscop** [comment]
To clarify spec2def is of course needed for generating arch-specific def files. upstream cmake and visual studio both expect the compiler to generate the import lib

**Comment by ariscop** [comment]
pushed the hack, i hate it but it seems to work and is the last file affected by cmp0017

**Comment by ariscop** [comment]
Due to circular dependencies (notably user32 and gdi32) the 'proper' fix i suggest is impossible without patching cmake

**Comment by HBelusca** [comment]
You mean that user32 depends on gdi2 and vice-versa?

**Comment by ariscop** [comment]
@HBelusca Yes, and the same is true on windows

**Comment by tkreuzer** [comment]
I am working on a fix that allows to remove Windows.MSVC.cmake

**Comment by ariscop** [comment]
@tkreuzer There's one in this PR now 7c927640847bda7e3fe4c4182a136a0271ad3969

**Comment by tkreuzer** [comment]
After testing this PR locally with vanilla cmake and some different settings, it looks like my "fixes" were not needed. Iow lgtm.

**Pull request merged**
