### PR TITLE
[USB] Delete old USB drivers and update names of new

### PR DESCRIPTION
**Pull request by oleg-dubinskiy**
## Purpose

Delete the old usb drivers that have its *_new equivalents, except usbstor(_new), since it is not yet enabled/merged. Rename all new drivers from *_new to *.
Also delete sdk/lib/drivers/libusb and update CMakeLists accordingly.
In my opinion, these names are more logically correct for now, because nearly all the new USB drivers are now default.

JIRA issue: None

## Proposed changes

Rename the following USB drivers:
- usbehci_new -> usbehci;
- usbhub_new -> usbhub;
- usbohci_new -> usbohci;
- usbuhci_new -> usbuhci.

Delete the following:
- usbehci (old);
- usbhub (old);
- usbohci (old);
- usbuhci (old);
- sdk/lib/drivers/libusb (used only by old USB drivers).

### CODE REVIEW

**Comment by ThFabba** [comment]
The old drivers should be deleted instead of renamed.

**Comment by oleg-dubinskiy** [comment]
Done @ThFabba.

**Comment by Extravert-ir** [comment]
I think the right way would be:
(1st commit) remove old drivers
(2nd commit) rename current drivers

This will keep the history consistent

**Comment by oleg-dubinskiy** [comment]
Done @Extravert-ir. Thanks.

**Comment by Mouvedia** [comment]
Does CORE-16107 cover what's left for usbstor?

**Comment by oleg-dubinskiy** [comment]
Yes. There are CORE-16109 and CORE-16110 already linked to that ticket.

**Comment by ThFabba** [comment]
Please also delete `sdk/lib/drivers/libusb`, and remove the corresponding line from CODEOWNERS.

**Comment by oleg-dubinskiy** [comment]
Hmm, but usbstor_new is still not merged/enabled. Isn't `sdl/lib/drivers/libusb` used by old usbstor? :thinking:

**Comment by oleg-dubinskiy** [comment]
Oh, compilation of old usbstor still succeeds for me after deleting libusb, so look like it does not.
Done, thanks.

**Pull request merged**
