### PR TITLE
WIP. [KERNEL32] GetSystemPowerStatus(): Fix and improve

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Contribution to current work by @EricKohl.

Documentation: [(MS) SYSTEM_POWER_STATUS structure](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/ns-winbase-_system_power_status)

## Proposed changes

- Fix BatteryLifePercent calculation.
This mostly reverts formula used since [r52841](https://git.reactos.org/?p=reactos.git;a=commit;h=078cdde168c7bb34135ebd99fc2d5173cbbecbaf), which looks rather wrong.
- Calculate BatteryFullLifeTime too.

## TODO

- [ ] Is the "restored" formula better/correct?
- [ ] Could we "early return" when in `if (!BattState.BatteryPresent)` case?
Calculating/Setting most of other values seems rather odd in this case...
- [ ] Someone else needs to test it, as I have no computer with battery.

### CODE REVIEW

**Comment by EricKohl** [comment]
Please do not make any 'code flow optimizations'. Keep the code well readable instead. Optimization is the compilers job, not yours!

**Comment by JaredSmudde** [comment]
Silly question, but does the battery percentage actually work in ReactOS and real hw? Every time I've tried it on a laptop, it doesn't show anything.

**Comment by Mouvedia** [comment]
ref CORE-14780

**Comment by SergeGautherie** [comment]
> does the battery percentage actually work

That seems to be [CORE-14780](https://jira.reactos.org/browse/CORE-14780) indeed.
Anyway, this PR is not expected to help in that regard.

**Comment by SergeGautherie** [comment]
> Please do not make any 'code flow optimizations'. Keep the code well readable instead. Optimization is the compilers job, not yours!

Reverted.
I assume our mileages of 'well readable' do vary :-|
I didn't know compilers do this kind of rewrite. Anyway, if the compiler does it eventually, why not match intended/actual (execution) logic in source code?

**Pull request closed without merging**
