### PR TITLE
Hungarian fix + some translation

### PR DESCRIPTION
**Pull request by Tudi20**
## Purpose

_Consistency between dialogue boxes. Also Select Folder and Font size not number translation._
## Proposed changes

- Fixing consistency between dialogue buttons and what the instruction text says.
- Translation of IDS_SELECT_FOLDER and IDS_FONT_SIZE_INPUT in comdlg32.

### CODE REVIEW

**Comment by learn-more** [comment]
You have committed with a nickname (`Tudi20`), please correct this to your full name.

**Comment by Tudi20** [comment]
Corrected.

**Comment by HBelusca** [comment]
You need to amend both of your commits to change the author name there too, because they still contain your nickname.

**Comment by HBelusca** [comment]
I've amended myself your commits with the name you gave to your github account.

**Pull request merged**
