### PR TITLE
[SHELL32] CDefaultContextMenu: Provide a fallback property sheet

### PR DESCRIPTION
**Pull request by learn-more**
JIRA issue: [CORE-17691](https://jira.reactos.org/browse/CORE-17691)

### CODE REVIEW

**Comment by yagoulas** [comment]
What is shown in the properties dialog with this?

**Comment by learn-more** [comment]
> What is shown in the properties dialog with this?

image

**Comment by yagoulas** [comment]
Huh nice. The way all pieces come together is absurdly complicated but it makes sense.

**Comment by learn-more** [comment]
> Huh nice. The way all pieces come together is absurdly complicated but it makes sense.

I think there should be default handling for more cases, but let's not block this improvement on that and wait until we actually have a use case for it.

**Pull request merged**
