### PR TITLE
[WINSPOOL] GetPrinterDriverA(): Refactor failure handling. CORE-16622

### PR DESCRIPTION
**Pull request by SergeGautherie**
Addendum to d90beaeed26863985486874aaa2a1c3422fd6d9f.

JIRA issue: [CORE-16622](https://jira.reactos.org/browse/CORE-16622)

### CODE REVIEW

**Comment by JoachimHenze** [comment]
Can we avoid linking this to CORE-16622? The issue has a fixVer in the past, and I don't see how the proposed changes would improve that usecase.

**Comment by SergeGautherie** [comment]
> Can we avoid linking this to CORE-16622?

Already answered on #2830.
NB:
I may understand your tester point of view, yet I have a code writer point of view.
Obviously, it would have been much better to fix all these PRs before committing them...

> Will it improve https://jira.reactos.org/browse/CORE-16715 instead maybe?

Already answered on #2304.

**Comment by SergeGautherie** [comment]
> should result in the same

Agreed. Done, then.

> let `UnicodeToAnsiInPlace` return a `DWORD`

I concur: I had thought about it, but I do not want to make all these changes.
This is a minimal fix only.

> especially hard to understand

Well, I simply tried to respect that new way of doing things...

**Comment by ColinFinck** [comment]
> > let `UnicodeToAnsiInPlace` return a `DWORD`
> 
> I concur: I had thought about it, but I do not want to make all these changes.
> This is a minimal fix only.

It's as simple as changing `return TRUE` to `return ERROR_SUCCESS` and `return FALSE` to `return ERROR_NOT_ENOUGH_MEMORY` in `UnicodeToAnsiInPlace` :)

This PR is already making a few things better - thank you for that. Let's also do the last step and make it perfect!
This saves us a discussion in a subsequent PR :)

**Comment by SergeGautherie** [comment]
> > This is a minimal fix only.
> 
> as simple

Alright, added UnicodeToAnsiInPlace commit.

**Comment by ColinFinck** [comment]
Thanks a lot! Looks exactly as I envisioned it :)

**Pull request merged**
