### PR TITLE
[SHELL32] Add desktop.ini more to some folders

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

JIRA issue: [CORE-10045](https://jira.reactos.org/browse/CORE-10045)

BEFORE:
before
AFTER:
after

### CODE REVIEW

**Comment by katahiromz** [comment]
In Japanese:
japanese
There is double translation problem...

**Comment by gonzoMD** [comment]
@katahiromz iirc I had a similar problem with a German installation too, some years ago. Does this also happen without your patch?

**Comment by katahiromz** [comment]
In Japanese:
japanese
OK.

**Comment by katahiromz** [comment]
Files "Hidden" and "SuperHidden" for `desktop.ini` are not working.

**Comment by katahiromz** [comment]
@gonzoMD I changed the value from `SHGFP_TYPE_DEFAULT` to `SHGFP_TYPE_CURRENT` then the bug seems fixed.

**Pull request merged**
