### PR TITLE
[SYSSETUP][SHELL32] Choose Shell Folders Layout

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Add an option to choose either XP layout or Vista+ layout of Shell Folders.
JIRA issue: [CORE-13795](https://jira.reactos.org/browse/CORE-13795)

Add a page to ReactOS setup wizard.
shell-folder-wizard

You can choose XP layout:
my-documents

### CODE REVIEW

**Comment by JoachimHenze** [comment]
You introduced an additional dlg during syssetup. Is it ready for unattended installation mode yet?

**Comment by gonzoMD** [comment]
I really like the ability to let the user customize its os as much as possible. But a few concerns:

I would not write Windows XYZ style and I would also not recommend anything because it is some kind of personal taste. Just my 2 cents.

**Comment by katahiromz** [comment]
@gonzoMD Can you name these two styles?

**Comment by ale5000-git** [comment]
@katahiromz
The "2003 style" (not correctly named) is the one used by Windows Vista+ (including Windows 7, 8, 10), so since XP is died it is used by all currently supported OSes and it is what apps expect.
So why "Not Recommended"?

**Comment by ale5000-git** [comment]
@katahiromz
Does the settings also affects new users created after the initial setup?

**Comment by katahiromz** [comment]
I agree with Modern and Legacy.
I agree with deletion of recommendations.

This setting is under `HKEY_LOCAL_MACHINE`, so it affects machine-wide.

**Comment by ale5000-git** [comment]
I'm not sure of what can be the best way but if the setting is changed does the existing users update correctly or is it problematic?

**Comment by katahiromz** [comment]
`SHGetFolderLocation` call with specific flags creates the special folder unless any. If the setting changed, then it creates at another place.

**Comment by ale5000-git** [comment]
But changing to the Modern layout does remove them if they are already created?

If not then I think it could be better to have the HKEY_LOCAL_MACHINE setting be only the default for new users and not changing existing users.
But it would be nice to have also other opinions.

**Comment by katahiromz** [comment]
OK, the setup will set `HKEY_LOCAL_MACHINE` and `HKEY_CURRENT_USER`. And `wine/shellpath.c` recognizes them. `HKEY_CURRENT_USER` setting takes priority from `HKEY_LOCAL_MACHINE` setting.

**Comment by Mouvedia** [comment]
You should read https://books.google.fr/books?id=qXcpGQ9ic8EC&pg=PA379

**Comment by katahiromz** [comment]
I have no idea how it has to be implemented. CLOSED.

**Pull request closed without merging**
