### PR TITLE
[MMSYS] IMGINFO: Add a FIXME about missing iPlanes and iBits

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Goal: be consistent or explain why not.
See
https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=struct+_IMGINFO

### CODE REVIEW

**Comment by SergeGautherie** [comment]
Cc @EricKohl, who worked a lot on this code "recently".

**Comment by learn-more** [comment]
Why quote 'recently' ?

**Comment by SergeGautherie** [comment]
> Why quote 'recently' ?

Pff. Why add a space before the question mark? :-<

**Comment by learn-more** [comment]
> 
> 
> > Why quote 'recently' ?
> 
> Pff. Why add a space before the question mark? :-<

In case you did not know: punctuation does carry meaning in sentences. When you use it to decorate random words, it makes it harder to understand the actual meaning of a sentence. (And usually I just stop reading those comments and disregard them completely)

**Comment by HBelusca** [comment]
Check the rest of the code: Do you see when the code would need to use these missing iPLanes / iBits? Yes -> instead of "FIXME", please implement the missing feature. No -> Why doing the PR?

**Comment by SergeGautherie** [comment]
> No -> Why doing the PR?

No, I didn't try to figure out the whole code.
I reported, to add a remainder: I assume that is what a `FIXME` is used for.
With regard to this `IMGINFO` structure, my questions are:
- 'Why 3 copies?' which I don't mind for the time being.
- 'Why each with different fields?' which I am trying to sync' with #2059 and this one.
If these 2 fields are intended not to be there, then why not at least add a comment or even rename the struct? To reduce confusion.

**Pull request closed without merging**
