### PR TITLE
Implement big pool table expansion

### PR DESCRIPTION
**Pull request by ThFabba**
## Purpose

This implements expansion of the big pool tracker table.

JIRA issue: [CORE-15051](https://jira.reactos.org/browse/CORE-15051)

### CODE REVIEW

**Comment by Extravert-ir** [comment]
No tests though?

**Comment by ThFabba** [comment]
No, I haven't worked on this further. If you have tests I'd love to add them (feel free to push to my branch).

**Comment by Extravert-ir** [comment]
I found that it's not that easy to this thing. Right now if the table is full, the pool is just being allocated with "BIG" tag and finishes successfully. So you can't just do many allocations (more than table size) to trigger error

**Comment by Zero3K** [comment]
Running the installer linked at https://jira.reactos.org/browse/CORE-15061 on a BTRFS formatted drive with ReactOS as its OS causes the table to be filled.

**Comment by Zero3K** [comment]
Any news regarding this PR?

**Pull request merged**
