### PR TITLE
[UTILMAN] Add Ukrainian translation

### PR DESCRIPTION
**Pull request by oleg-dubinskiy**
## Purpose

Add Ukrainian translation for ReactOS Accessibility Utility Manager.

JIRA issue: None

## Proposed changes

- Add the translation;
- Include it into the RC file:
- Translate the shortcut in the Start Menu.

## Result
utilman_ukrainian

### CODE REVIEW

**Comment by Extravert-ir** [comment]
Do we translate the developers' names?

**Comment by learn-more** [comment]
I don't think we should?

**Comment by oleg-dubinskiy** [comment]
> Do we translate the developers' names?

Why not, if this is a part of the localization resource?

**Comment by HBelusca** [comment]
Any consensus has been reached?

**Comment by binarymaster** [comment]
> Do we translate the developers' names?

They were already being translated for russian and ukrainian localizations before, in sysdm.cpl for example.

**Pull request merged**
