### PR TITLE
[LEGCYDRV][INF] Update Romanian (ro-RO) translation

### PR DESCRIPTION
**Pull request by AndreiMiloiu**
Attendum to PR https://github.com/reactos/reactos/pull/5908

### CODE REVIEW

**Comment by AndreiMiloiu** [comment]
Cc @reactos/lang-romanian

**Comment by binarymaster** [comment]
Please use a single PR for changes in the INF files: #5969.

**Comment by binarymaster** [comment]
Yes, just push the changes into other PR and close this one.

**Comment by AndreiMiloiu** [comment]
I understand, thank you! I pushed the file in the previous one. I'll close this PR.

**Pull request closed without merging**
