### PR TITLE
[SHELLEXT] Turkish translations update

### PR DESCRIPTION
**Pull request by ercanersoy**
## Purpose

Update Turkish translations.

JIRA issue: None

## Proposed changes

- Add Turkish translations on FONTEXT.
- Update Turkish translations on DESKMON.
- Update Turkish translations on ACPPAGE.
- Update Turkish translations on DESKADP.
- Update Turkish translations on NETSHELL.
- Update Turkish translations on NTOBJSHEX.
- Update Turkish translations on STOBJECT.

## TODO

None

### CODE REVIEW

**Comment by HBelusca** [comment]
Cc @learn-more  for the acppage translation (clashes with your PO work).

**Comment by ercanersoy** [comment]
What do I? I don't know the clashes with my PO work.

**Comment by HBelusca** [comment]
@ercanersoy : I was referring to @learn-more's PR 84

**Comment by learn-more** [comment]
@HBelusca I've found a but that will need fixing first, so i'll commit your commit this week as well as to no longer hold it back.

**Pull request merged**
