### PR TITLE
[APITESTS] Add UTF-8 BOM to biditext.c

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Add a UTF-8 BOM to biditext.c. This will fix CORE-14971.
JIRA issue: [CORE-14971](https://jira.reactos.org/browse/CORE-14971)

### CODE REVIEW

**Comment by ThFabba** [comment]
I would prefer if we replaced the string literals with their `\xABCD` equivalent

**Comment by katahiromz** [comment]
I cannot handle Hebrew characters. Closed.

**Comment by katahiromz** [comment]
Both of GCC and MSVC can handle UTF-8 text if we add UTF-8 BOM to the top of the file.

**Comment by peterooch** [comment]
I checked (used utf8 bom option in notepad++) to see if it doesn't ruin anything and it works. 

Other idea is to put the strings into the resource file and load them, then pragma codepage can be used.

**Comment by learn-more** [comment]
@peterooch Does this look ok?
example

**Comment by learn-more** [comment]
using:
`LPWSTR szString = L"\x05D0\x05D1\x05D2\x05D3\x05D4" L"ABCD\x05D5\x05D6\x05D7\x05D8\x05D9";`
and:
`TextOutW(hdc, 200, 30, L"\x05D4\x05D3\x05D2\x05D1\x05D0" L"ABCD\x05D9\x05D8\x05D7\x05D6\x05D5", 14);`

**Comment by HBelusca** [comment]
Normally the source files should be in UTF-8 **without** BOM!

**Comment by peterooch** [comment]
The Lpk Getcharacterplacement calls show the Hebrew glyphs as empty spaces or vertical lines, it should display as exttextout calls

**Comment by katahiromz** [comment]
It shouldn't be my work. Closed.

**Comment by HBelusca** [comment]
@peterooch , can you replace the example strings with strings using the hex codes instead? (as e.g. @learn-more showed above).

**Comment by learn-more** [comment]
See my new PR please.
I attached binaries.

**Pull request closed without merging**
