### PR TITLE
[AUDIOSRV] logmsg(): Skip it on non-debug builds. CORE-16912

### PR DESCRIPTION
**Pull request by SergeGautherie**
Near mininal workaround for
JIRA issue: [CORE-16912](https://jira.reactos.org/browse/CORE-16912)

Co-authored-by: Hermès BÉLUSCA - MAÏTO <hermes.belusca-maito@reactos.org>

### CODE REVIEW

**Comment by HBelusca** [comment]
@SergeGautherie : could you please test the "suggestions (aka. if they compile OK in non-dbg mode)?
Basically what they do is to go further and just completely "remove" the logmsg() functions calls by defining an empty macro with the same syntax in non-dbg builds (and then just disabling the whole contents of the debug.c file).

**Comment by SergeGautherie** [comment]
> go further

Sure, I too went a bit further ;-)

**Comment by KyleKatarn31** [comment]
Any update of this PR ? Anything I can do to help ?

**Comment by Extravert-ir** [comment]
The fix is very hacky. The debug messages should just be done like in other ReactOS modules

**Comment by SergeGautherie** [comment]
Superseded by #5067.

**Pull request closed without merging**
