### PR TITLE
[TRANSLATION] Update Chinese translation.

### PR DESCRIPTION
**Pull request by njlyf2011**

### CODE REVIEW

**Comment by njlyf2011** [comment]
The problem seems to happen at base/applications/network/net , but I have not changed these files.
So I really want to know what the reason is and how to solve it.

**Comment by katahiromz** [comment]
Look the history of base/applications/network/net.

**Comment by njlyf2011** [comment]
The reason was found, but I don't know how to solve it.
He didn't have fix build when I forked the source code.

**Comment by katahiromz** [comment]
Not your repository, but reactos/reactos.
Eric has fixed build. You can fix it by git rebase.

**Comment by njlyf2011** [comment]
How about directly merge PR?
Because my PR changes the translation file instead of net, I think it may not be affected.

**Comment by katahiromz** [comment]
```bash
git remote add upstream https://github.com/reactos/reactos.git
git fetch upstream
git merge upstream/master
```

**Comment by njlyf2011** [comment]
My local git settings seem to be having problems with my yesterday's operation.
I will git clone again and re-create PR.

I will try with your method.

**Pull request closed without merging**
