### PR TITLE
[NTOS:KE] *init.c: Add CODE_SEG("INIT")

### PR DESCRIPTION
**Pull request by SergeGautherie**
Addendum to 5c7ce44.

NB:
Ignoring powerpc...

### CODE REVIEW

**Comment by ThFabba** [comment]
> Addendum to [5c7ce44](https://github.com/reactos/reactos/commit/5c7ce4475e246560d1622b8cc60dc603e3955f66).

Can you please use a more descriptive message? How did you determine that these functions should be in the INIT section? How did you test your change?

**Comment by SergeGautherie** [comment]
> Can you please use a more descriptive message?

Can you suggest one?

> How did you determine that these functions should be in the INIT section? How did you test your change?

They are parts of 'KiSystemStartup() > ... > KiIdleLoop()' initial flow. Why should these functions not be in INIT section, while the others are?
Very basic test only: GCC ISOs still work.

**Comment by learn-more** [comment]
> > Can you please use a more descriptive message?
> 
> Can you suggest one?

If you have trouble describing what you changed, you might ask yourself if you should change it.

**Comment by SergeGautherie** [comment]
> If you have trouble describing what you changed, you might ask yourself if you should change it.

??
What I changed is rather obvious: I added `CODE_SEG("INIT")` to the functions that do not have it yet, and removed one from a declaration.
What I may have trouble with is figuring out what else you want to know...

**Comment by ThFabba** [comment]
> > Can you please use a more descriptive message?
> 
> Can you suggest one?

I'm saying the commit message should answer the two questions I asked, so that people making future changes don't have to guess about your reasoning.

**Comment by SergeGautherie** [comment]
> commit message & PR description

Ah. Updated.
I assumed the INIT section was kind of self-explanatory.
I haven't much to say about testing this, unless you would want some specific test I could do.

**Comment by SergeGautherie** [comment]
> closed

Please, reopen.

**Pull request closed without merging**
