### PR TITLE
[TRANSLATION][SERVICES] Add Bulgarian translation.

### PR DESCRIPTION
**Pull request by WindowxDeveloper**
## Purpose

Add Bulgarian translation for the Services Control Manager.

### CODE REVIEW

**Comment by katahiromz** [comment]
https://reactos.org/wiki/Translation_Introduction

**Comment by gigaherz** [comment]
@katahiromz Please don't close people's PRs without need. This PR can still be updated, his branch can be fixed and force-pushed.

**Comment by WindowxDeveloper** [comment]
> @katahiromz Please don't close people's PRs without need. This PR can still be updated, his branch can be fixed and force-pushed.
> 
> Now if the translator CHOOSES not to continue with this branch, that's their choice.

Maybe I will continue with this branch.

**Comment by MailYouLater** [comment]
@WindowxDeveloper: Are you still interested in getting this PR merged?
I noticed earlier today that this PR was mentioned in the ReactOS chat, and it was brought up because the commit history is such a mess that someone thought it should probably just be closed, but it also looks like it would be really easy for you to clean it up.

The issue is that there are 24 commits in this PR's branch, but most of them aren't part of what the PR is about. To fix this, make sure you have the right branch checked out, then run `git rebase -i HEAD~24`, delete all of the lines for the commits that shouldn't be in the PR, save the file and exit the text editor, then force-push the branch to GitHub.

**Pull request merged**
