### PR TITLE
[SYSSETUP] Make Workstation default product option

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

JIRA issue: [CORE-13795](https://jira.reactos.org/browse/CORE-13795)

after
Unattended Setup is supported.

### CODE REVIEW

**Comment by katahiromz** [comment]
@ColinFinck Is this PR really OK?

**Comment by JoachimHenze** [comment]
Personally I like Server being default. But I won't argue. Just saying this in case anyone else would feel the same.

**Comment by milawynsrealm** [comment]
Is the unattended installation set up for this yet?

**Comment by blackcrack** [comment]
Not any is a technician, and the most Peoples are "Users"  i've meant therewith, they want have a Ordering System for using and connecting to Servers and want not at first have a Server installing.
Because this should maybe be the First Option be a Workstation. If is need to installing a Server, then is the 2nd option to chose a Server maybe better to have.
Therefore Workstation as Default.

**Comment by ColinFinck** [comment]
> @ColinFinck Is this PR really OK?

Yes, Workstation should be the default in my opinion.

Ultimately, this wizard page should be removed again and we should only set this setting through our Application Compatibility Framework, just as I described in https://github.com/reactos/reactos/pull/2329#issuecomment-584805470

**Comment by ale5000-git** [comment]
> Ultimately, this wizard page should be removed again and we should only set this setting through our Application Compatibility Framework, just as I described in #2329 (comment)

This option also control whether Pictures/Music/Videos folders are inside documents or user, so please keep it in the setup or add a separate setting and page for this (preferred).

**Comment by EricKohl** [comment]
> Ultimately, this wizard page should be removed again and we should only set this setting through our Application Compatibility Framework, just as I described in [#2329 (comment)](https://github.com/reactos/reactos/pull/2329#issuecomment-584805470)

This is not a good idea because we need a way to install ReactOS as either Workstation or Server in order to test security or networking features. For example, on a Workstation users can shut the machine down because they have the shutdown privilege but on a Server only administrators can shut the machine down because users lack the shutdown privilege. This is just a single example but in the future we will have more and more code that needs different code paths for Workstation and Server, like NetJoinDomain() and NetUnjoinDomain().

**Comment by ColinFinck** [comment]
> This is not a good idea because we need a way to install ReactOS as either Workstation or Server in order to test security or networking features. For example, on a Workstation users can shut the machine down because they have the shutdown privilege but on a Server only administrators can shut the machine down because users lack the shutdown privilege.

Is there any feature that is not artificially limited by Microsoft to a Workstation or Server edition?

To follow up on your examples: I know that shutdown is limited to administrators by default on Windows Server systems, but this can easily be extended to all users using a group policy setting. So it would be sufficient if the one and only ReactOS version just had that group policy setting.
Same thing for NT domains: A Workstation can only join a domain, but not serve as a domain controller while a Server can do both.

We already don't distinguish between "ReactOS Home Edition" and "ReactOS Professional" for good.
Not just because we don't need artificial limitations, but also because we cannot maintain endless different versions of ReactOS. I have the same feeling for a ReactOS Workstation and Server edition.

Correct me if I'm wrong, but so far I have only encountered applications which checked the NT Product Type (like server applications which expect a Server OS), which is why I wanted to solve this entirely with Application Compatibility settings.

**Pull request merged**
