### PR TITLE
[DOC] 3rd Party Files.txt: Add 'TreeList' entry

### PR DESCRIPTION
**Pull request by SergeGautherie**
See 2fdfb411b69932e765ed8b64646cae76f3e3193f.

### CODE REVIEW

**Review by learn-more — APPROVED** [review]

**Comment by HBelusca** [comment]
That's great etc. but I was planning to rewrite that treelist code to something more maintainable (I imported that 3rd party treelist code for having a quick treelist implementation for getting the setup GUI code out asap., before writing a more proper version later on.)

**Comment by SergeGautherie** [comment]
> That's great etc. but

Yeah, that is what is written in your commit comment.
What is your point?

**Comment by HBelusca** [comment]
> > That's great etc. but
> 
> Yeah, that is what is written in your commit comment.
> What is your point?

The point is that it was not necessary to create a PR for a thing that will disappear soon.

**Comment by learn-more** [comment]
'soon' is a bit relative, this thing is here since 6 Nov 2018 ?

**Comment by SergeGautherie** [comment]
> not necessary

Well, code was included nearly 2 years ago and I can't guess how much time it will still be...

**Comment by Extravert-ir** [comment]
Superseded by dcfb80c47adc8d3b876486b956403fed3077b8e6

**Pull request closed without merging**
