### PR TITLE
[DRWTSN32] PrintStackBacktrace(): Do not default to i386

### PR DESCRIPTION
**Pull request by SergeGautherie**
(Split off from #3685 )

Sync with other cases.

JIRA issue: [CORE-17605](https://jira.reactos.org/browse/CORE-17605)

### CODE REVIEW

**Comment by learn-more** [comment]
And once again: Dont just change the code for the lulz.
Fix a bug or leave it alone.

**Comment by SergeGautherie** [comment]
> And once again: Dont just change the code for the lulz.
> Fix a bug or leave it alone.

?? This PR seems very much part of the actual fix to me.
Unless you would explain why this case has to be different than the other ones: as in what is so great about implicitly defaulting to i386 here?

**Comment by learn-more** [comment]
> > And once again: Dont just change the code for the lulz.
> > Fix a bug or leave it alone.
> 
> ?? This PR seems very much part of the actual fix to me.
> Unless you would explain why this case has to be different than the other ones: as in what is so great about implicitly defaulting to i386 here?

How does this fix anything?
It just exchanges one error for another.

**Comment by SergeGautherie** [comment]
> How does this fix anything?
> It just exchanges one error for another.

It stops trying to compile i386 code on other architectures, like arm/arm64.
It gives 1 explicit error instead of multiple misleading ones, and compilation stops at once instead of getting the actual error on the next case.
If you find the current misbehavior so fine, then why not make the others cases like it?

**Comment by Extravert-ir** [comment]
We don't support arm/arm64 right now. And adding nitpicks which don't really fix the issue don't make the situation any better.
Mark has already said that - fix the real bug, or don't play on our nerves. We prefer real fixes to that chicanery

**Comment by SergeGautherie** [comment]
Eventually included in 1f44552d36f41397991d4594edada88cd062a107.

**Pull request closed without merging**
