### PR TITLE
Fix Chinese font name in apps

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
Our applications should use Windows-compatible font names in Chinese resources.
JIRA issue: [CORE-9566](https://jira.reactos.org/browse/CORE-9566)

## Proposed changes
Use FONT 9, "宋体" for Simplified Chinese resources in base/applications/**.
Use FONT 9, "新細明體" for Traditional Chinese resources in base/applications/**.

### CODE REVIEW

**Comment by yagoulas** [comment]
I wonder, do these applications work properly in windows without these changes?

**Comment by katahiromz** [comment]
Windows has "font link" mechanism that enables to display the absent glyphs by using another font.

**Comment by yagoulas** [comment]
But do these apps work in windows properly?

**Comment by katahiromz** [comment]
I don't know. Just try.

**Comment by HBelusca** [comment]
To check whether it "works on Windows", this means that an app that wants "PMingLiU" but uses "PMingLiU" written in English would display with a different font, while one that uses the localized name would display with the expected font.

**Comment by HBelusca** [comment]
Here is a comparison, on Windows, of our ROS Paint using "MS Shell Dlg" (that links to some other font) on the left, ROS Paint using "PMingLiU" (the font "新細明體") on the right, and on the bottom MS Paint using the font it specifies in its resouces: we see it also uses PMingLiU.

comparison_font_ros_ms_paint

**Comment by yagoulas** [comment]
Ok, Hermes cleared the situation. This patch looks good.

**Comment by HBelusca** [comment]
LGTM too :)

**Comment by HBelusca** [comment]
Committed in d09998dfc7, thanks!

**Pull request closed without merging**
