### PR TITLE
Make configure.sh behave like configure.cmd

### PR DESCRIPTION
**Pull request by Extravert-ir**
Right now configure.sh creates a folder in build directory but configure.cmd does not.
This PR makes configure.sh consistent with configure.cmd

### CODE REVIEW

**Comment by Extravert-ir** [comment]
Is there a reason why this folder is being created or this is just a mistake?
I've got used to configure.cmd when I worked on Windows and this extra folder is a bit annoying on Linux :)

**Comment by HeisSpiter** [comment]
Ah yes, you're right. It's a leftover from previous build style (where host-tools and reactos were separated). So, it looks OK.

**Comment by Extravert-ir** [comment]
There is a jira ticket for it :)
https://jira.reactos.org/browse/CORE-12716

**Comment by MailYouLater** [comment]
> Looks like `.travis.yml` needs to be updated too.

Just need to remove `&& cd reactos` from this line:
https://github.com/reactos/reactos/blob/3df31a821741e7abf5fa9a2f3ab8a1355d1f7338/.travis.yml#L9
@Extravert-ir: Any chance you could update this PR with this fix?

**Comment by Extravert-ir** [comment]
At first glance, buildbot config doesn't require changes

**Pull request merged**
