### PR TITLE
[SHELL32] Revise "Desktop" icon

### PR DESCRIPTION
**Pull request by Splitwirez**
## Purpose

Change our "Desktop" icon to depict what it refers to (computer desktop) instead of its namesake (physical desktop).

| fig. # | Image | Context |
| ---- | ---- | ---- |
| fig.1 | fig. 1 | **On ReactOS**: Existing (Tango) Desktop icon |
| fig.2 | fig. 2 | **On Windows 7**: Desktop icon introduced in Windows Vista <br/> (used up to and including Windows 8.1) |
| fig.3 | fig. 3 | **On ReactOS**: Proposed new Desktop icon |
| fig.4 | fig. 4 | Screenshot of a Discord message, in which someone expresses confusion about the current icon, and requests clarification. |

## JIRA issue
None...? (*Again*? I'm starting to see a pattern here...)

## Proposed changes

At present, we use the standard Tango "Desktop" icon, which depicts a traditional, physical desktop of sorts, rather than a computer desktop, for our "Desktop" icon. (see fig. 1)

On paper, this makes sense...but in practice, it has lead to some confusion. This confusion is not new, but (unsurprisingly) has been exacerbated by my Show Desktop button appearance PR. (see fig. 4)

<hr/>

Now, consider the icon used in Windows 7. (see fig. 2)
Notice how the icon depicts the Windows desktop - and, in turn, depicts exactly what it does.

<hr/>

I am proposing we change this icon accordingly, to depict the ReactOS desktop. (see fig. 3)

I initially raised this concern during my [Show Desktop button appearance PR](https://github.com/reactos/reactos/pull/5744) - At the time, this change was deemed out-of-scope...which was fair, as the icon is used in other places besides the Show Desktop button. (more on that later)
I had intended to circle back to this change after that PR was merged, but after how long it took to wrap up, this ultimately slipped my mind at the time. However, in light of the news that ReactOS 0.4.15 will apparently be locked in in a matter of days, I've thankfully remembered to get back to it.

<hr/>

I don't mean to overstep in saying this, but as far as I'm concerned, it is imperative that this be addressed *before* the release of 0.4.15, else we'll face a bombardment of (understandably) confused comments, like the one above. (see fig. 4)

As I see it, the confusion is understandable - though the digital desktop metaphor does take cues from a physical desktop (hence the name), the inspiration for the metaphor is entirely irrelevant in most (if not all) contexts where the icon is used. Notably, the Windows XP iteration of the icon and prior also depicted a physical desktop, but this was changed in Windows Vista. I think that change was made for good reason.

<hr/>

Note: this icon is used in other places as well. If merged, this change will be reflected across all of those locations.

As such, I've ensured to the best of my ability that the new icon has all of the same sizes as its predecessor:

| Size | Preview |
| ---- | ---- |
| 16x | 16x |
| 32x | 32x |
| 48x | 48x |

Whether you love or hate Tango, I suspect we can all agree that having just *one* icon that sticks out like a sore thumb would be bad. As such, I've tried to emulate the Tango style...though I'm not certain I've entirely succeeded. I'm open to feedback regarding the appearance/styling/etc. of the icon, so please don't hesitate to speak up. (we don't have much time left though, so my ability to act upon said feedback may be limited by that)

For what it's worth, the SVGs are also included. They can be found at [`dll/win32/shell32/res/icons/svg/`](https://github.com/Splitwirez/reactos/tree/desktop-icon/dll/win32/shell32/res/icons/svg).

## TODO

- [X] Create new icon
- [ ] Finalize icon appearance
- [ ] Figure out licensing for icon, if needed
- [ ] Other stuff TBD

### CODE REVIEW

**Comment by binarymaster** [comment]
I just noticed that the spacing between the button and clock is 1px bigger in ReactOS, compared to Windows.

Regarding the icon, I still would prefer current one. The new one doesn't feel Tango enough for me.

**Review by cbialorucki — APPROVED** [review]
I agree that the old desktop icon was confusing. Great job Split!

**Comment by HBelusca** [comment]
Looks like only "young" people don't know what the current desktop icon looks like.

**Comment by Splitwirez** [comment]
> I just noticed that the spacing between the button and clock is 1px bigger in ReactOS, compared to Windows.

Yeah our clock has...*problems*, but that's a separate can of worms for a separate PR.

> Regarding the icon, I still would prefer current one.

@binarymaster Is  that solely *because* the new icon "doesn't feel Tango enough"? I'll admit, it could probably be made to fit better...not quite sure how I'd go about making that happen though. If you see any ways I could make it more Tango-ish, please do tell.

**Review by maj113 — APPROVED** [review]
I like this one, should we consider minifying the SVGs?

**Comment by Splitwirez** [comment]
> Looks like only "young" people don't know what the current desktop icon looks like.

@HBelusca I don't follow...is that intended to be an argument against this PR, or...?

**Comment by Splitwirez** [comment]
> I like this one, should we consider minifying the SVGs?

Fine by me...not sure how to do that though...

**Review by DarkFire01 — APPROVED** [review]

**Comment by yoshiask** [comment]
I agree with this proposal, the current icon is certainly confusing

**Comment by maj113** [comment]
> > I like this one, should we consider minifying the SVGs?
> 
> Fine by me...not sure how to do that though...

image

**Comment by freedom7341** [comment]
This makes ReactOS look that much more modern and not only that but it'll make it easier for new users to pick up. I think the icon fits the set well, too. Great addition.

**Comment by DarkFire01** [comment]
Love the new icon fantastic addition

**Comment by Splitwirez** [comment]
> I like this one, should we consider minifying the SVGs?

@maj113 Actually, would minification strip out the InkScape-y bits? Part of me questions how valuable...erm, *editable-ness* is here. Given the time constraint at play, maybe they should be left as-is for now, and minified later if needed? idk

**Comment by oleg-dubinskiy** [comment]
The icon itself looks OK, but I'm agreed with Stas'M that it's better to keep the current one, which belongs to Tango icon theme, to have a consistent icons for all items.
I remember I implemented the changing the icons by user in shell32 in #6421, but I did not implement that for Desktop icon yet. Maybe I'll implement changing Desktop icon too, to make it customizable by user and to make everyone happy? In that case, we will be not limited by modifying system resources. I can send a PR with that. :slightly_smiling_face:

**Comment by maj113** [comment]
> > I like this one, should we consider minifying the SVGs?
> 
> @maj113 Actually, would minification strip out the InkScape-y bits? Part of me questions how valuable...erm, _editable-ness_ is here. Given the time constraint at play, maybe they should be left as-is for now, and minified later if needed? idk

if you are asking if it's still editable in inkscape after minifying it does seem to be however it's my first time using inkscape so idk if this is what you expect:

image

here's the minified 16x16 file so you can try for yourself:

desktop_16x16

**Comment by Splitwirez** [comment]
> The icon itself looks OK, but I'd agree with Stas'M that it's better to keep the current one, which belongs to Tango icon theme, to have a consistent icons for all items and to not break the consistency. I remember I implemented the changing the icons by user in shell32 in #6421, but I did not implement that for Desktop icon yet. Maybe it makes sense implement changing Desktop icon too, to make it customizable by user and to make everyone happy? In that case, we will be not limited by modifying system resources and will able to apply any icon we want. I can send a PR with that. 🙂

@oleg-dubinskiy Icon customization is great, I'm all for it.

But customization isn't an alternative to sane defaults.

It's not relevant to the topic of this PR.

**Comment by oleg-dubinskiy** [comment]
> > The icon itself looks OK, but I'd agree with Stas'M that it's better to keep the current one, which belongs to Tango icon theme, to have a consistent icons for all items and to not break the consistency. I remember I implemented the changing the icons by user in shell32 in #6421, but I did not implement that for Desktop icon yet. Maybe it makes sense implement changing Desktop icon too, to make it customizable by user and to make everyone happy? In that case, we will be not limited by modifying system resources and will able to apply any icon we want. I can send a PR with that. 🙂
> 
> @oleg-dubinskiy Icon customization is great, I'm all for it.
> 
> But customization isn't an alternative to sane defaults.
> 
> It's not relevant to the topic of this PR.

OK. Sorry then.

**Comment by jeffbox12** [comment]
I feel like this PR came in very spontaneously over just one question that didn't even clarify himself. Was it the icon? Was it the button? Imho it doesn't have a design problem. It even has a tooltip that describes the action of the button. It is in a common place that even a couple desktop environments adopted. In my eyes, it was just a little silly question that nobody else asked. Unless a moderate count of people have had problems with this or something else in particular, only then I would consider finding a solution.

Unless he exclusively used modern Gnome or macOS his entire life, or maybe Windows from 8 to now (which the show desktop button is somewhat invisible, unlike 7's), only then I would see how such question would be asked. But I don't know. Nobody asked him what motivated him to do such question.

**Review by learn-more — APPROVED** [review]
Thanks for working on this!
I like the current proposal, and would be totally fine with merging it.

**Comment by Splitwirez** [comment]
> I feel like this PR came in very spontaneously over just one question that didn't even clarify himself. Was it the icon? Was it the button? Imho it doesn't have a design problem.

The apparent spontaneity was because I'd completely forgotten to circle back to this right up until I found out I had *four days* before 0.4.15 launches.

> It even has a tooltip that describes the action of the button.

Actually, ours doesn't. That's something I'd also wanted to address at some point, but that seems too involved to take care of on such short notice (at least given the limits of my present skillset)

> It is in a common place that even a couple desktop environments adopted.

True...though an unconventional icon can lead people to presume their expectations may be incorrect. Wouldn't be the first time I've seen such a thing occur.


> To be clear: I am happy with either and I prefer this icon over the other. I'm just making you aware that such things require a bit more thought before proposing a change.

I don't disagree...but in this case, we know an icon which depicts a computer desktop can work in this context, and we - again - only have four days.

> The only concern I and other devs had is the collision with the overall Tango icon set the system uses, even though you made an effort to make it look Tango-like which I approve.

I...won't deny, it's not a *perfect* match for the Tango style as-is...but again, I'm open to tweaking it to make it more Tango-ish, I'm just...not sure what I could change to achieve that. If anyone has any ideas, I'm all ears.

**Comment by DarkFire01** [comment]
I wouldn’t change it to be “more like tango” 
It’s close enough to tango and looks far better for this usage. 

If people want to change the style let THEM make a PR and work on a custom icon.

you put the effort in.

**Comment by Splitwirez** [comment]
> I wouldn’t change it to be “more like tango” It’s close enough to tango and looks far better for this usage.
> 
> If people want to change the style let THEM make a PR and work on a custom icon.
> 
> you put the effort in.

Fair...though as I said, I'm not 100% happy with the Tango-ness of the current revision of the icon. It's...*passable* as-is, but there *is* room to improve...so, if anyone can nail down how to do so, I'd like to act on that.

...unless that would stop the PR from being merged in time for 0.4.15, that is.

**Review by yoshiask — APPROVED** [review]

**Comment by cbialorucki** [comment]
> The icon itself looks OK, but I'd agree with Stas'M that it's better to keep the current one, which belongs to Tango icon theme, to have a consistent icons for all items and to not break the consistency.
> I remember I implemented the changing the icons by user in shell32 in #6421, but I did not implement that for Desktop icon yet. Maybe it makes sense implement changing Desktop icon too, to make it customizable by user and to make everyone happy? In that case, we will be not limited by modifying system resources and will able to apply any icon we want. I can send a PR with that. :slightly_smiling_face: 

I think that's a very, very bad idea; the show desktop icon should be pulled from shell32 because that is the system wide desktop icon. Setting a different one would make the experience inconsistent when abn app grabs the desktop icon from shell32.

**Review by freedom7341 — APPROVED** [review]

**Comment by OliviaIsTyping** [comment]
This looks nice

**Review by buddyjojo — APPROVED** [review]

**Review by cernodile — APPROVED** [review]
LGTM. I believe it communicates intent/function much better than the previous icon.

**Review by HBelusca — COMMENTED** [review]
While the icon per se looks quite nice, it would make more sense to have it _**as part of a new icon set**_ (like the one used in the private NT6+ builds by @DarkFire01 and co.), instead of one "new" icon amongst all the other vintage-looking Tango ones.

Therefore I'm not going to approve the PR as it currently is.

**Comment by HBelusca** [comment]
@Splitwirez 
> Figure out licensing for icon, if needed

Usually our in-house art stuff is `Distributed under CC-BY-SA 4.0 International License Terms.`, see for example:
https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=CC%5C-BY&sr=1

**Comment by HBelusca** [comment]
> > Looks like only "young" people don't know what the current desktop icon looks like.
> 
> @HBelusca I don't follow...is that intended to be an argument against this PR, or...?

@Splitwirez I was unamusingly answering back this part:
> On paper, this makes sense...but in practice, _**it has lead to some confusion. This confusion is not new, but (unsurprisingly) has been exacerbated by my Show Desktop button appearance PR. (see fig. 4)**_

**Comment by whindsaks** [comment]
> Notably, the Windows XP iteration of the icon and prior also depicted a physical desktop, but this was changed in Windows Vista. I think that change was made for good reason.

But in Vista (and the later versions), the icon of the actual root IShellFolder changed as well, the same icon is used in the folder tree and this feature.

> I'm open to feedback regarding the appearance/styling/etc. of the icon, so please don't hesitate to speak up.

I don't like that the 16x16 version has a black taskbar while the larger ones are blue. Vista has black taskbar in the larger sizes as well but I actually prefer the blue you used here.

**Comment by Splitwirez** [comment]
> But in Vista (and the later versions), the icon of the actual root IShellFolder changed as well, the same icon is used in the folder tree and this feature.

@whindsaks As I said, the icon is used elsewhere, and this change will be reflected across the board.

> I don't like that the 16x16 version has a black taskbar while the larger ones are blue. Vista has black taskbar in the larger sizes as well but I actually prefer the blue you used here.

@whindsaks They're all black. Check the SVGs.

Possibly some kind of optical illusion at play?

**Comment by whindsaks** [comment]
> Possibly some kind of optical illusion at play?

Still looks blue to me, only a single black line there on the others. Unless those pictures are outdated.

screenshot

**Comment by Splitwirez** [comment]
> Usually our in-house art stuff is `Distributed under CC-BY-SA 4.0 International License Terms.`,

@HBelusca Right, okay...

> https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=CC%5C-BY&sr=1

...I have no idea what I'm looking at thonk emoji

**Comment by Splitwirez** [comment]
> Still looks blue to me, only a single black line there on the others. Unless those pictures are outdated.
> 
> screenshot

@whindsaks Uhhhh...ok something weird is going on with the SVG rendering. Here's how they're meant to look, as PNG previews for now:

| Size | Preview |
| ---- | ---- |
| 16x | 16x |
| 32x | 32x |
| 48x | 48x |

**Comment by Splitwirez** [comment]
@whindsaks Just updated the SVGs to *hopefully* not have that problem anymore. Mind doing me a favor, to help confirm?
1. Do a hard refresh in your web browser
2. Send a *new* screenshot of how the previews look in the inital PR post up-top

**Comment by maj113** [comment]
> @whindsaks Just updated the SVGs to _hopefully_ not have that problem anymore. Mind doing me a favor, to help confirm?
> 
> 1. Do a hard refresh in your web browser
> 2. Send a _new_ screenshot of how the previews look in the inital PR post up-top

They look good now 

Screenshot_2024-09-07-21-40-46-508_com android chrome-edit

Screenshot_2024-09-07-21-40-18-776_com android chrome-edit

**Comment by HBelusca** [comment]
> > Usually our in-house art stuff is `Distributed under CC-BY-SA 4.0 International License Terms.`,
> 
> @HBelusca Right, okay...
> 
> > https://git.reactos.org/?p=reactos.git&a=search&h=HEAD&st=grep&s=CC%5C-BY&sr=1
> 
> ...I have no idea what I'm looking at 

Cases examples where our artwork is released under creative commons license.

**Comment by binarymaster** [comment]
> Is that solely because the new icon "doesn't feel Tango enough"? I'll admit, it could probably be made to fit better...not quite sure how I'd go about making that happen though. If you see any ways I could make it more Tango-ish, please do tell.

@Splitwirez I've just found this nice page: https://logos.fandom.com/wiki/Desktop_(Windows)

Take a look at it and tell me, which generation our current Tango icon resembles, and the same for your new icon. It should give you some idea.

**Review by binarymaster — COMMENTED** [review]
Not sure about giving approval here, please look at my comment: https://github.com/reactos/reactos/pull/7312#issuecomment-2336429776

**Comment by maj113** [comment]
> Not sure about giving approval here, please look at my comment: [#7312 (comment)](https://github.com/reactos/reactos/pull/7312#issuecomment-2336429776)



Should we not aim for something that looks newer while also clarifying its purpose/intent/whatever much better?

Current tango icon seems to at best represent the 1998 icon and visually looks even worse than the windows one because it has no other elements than the corners + the rectangle (I could never guess that's supposed to signify a desktop) while split's looks like the 2014 unreleased one and actually looks like... desktop

**Comment by Splitwirez** [comment]
> it has no other elements than the corners + the rectangle (I could never guess that's supposed to signify a desktop)

An aside: I didn't see it either...I still can't really tbh

**Review by JoachimHenze — APPROVED** [review]

**Review by JoachimHenze — APPROVED** [review]
Approved. I do appreciate its look, and I do appreciate even more that it is 9.89 KB smaller than the old one.

**Comment by whindsaks** [comment]
> An aside: I didn't see it either...I still can't really tbh

Perhaps you just had to live it? The Windows icon had a similar design from 1998 to 2006. The first time I saw the Tango version I knew what it was. But I agree that the Tango version is missing the little extras that the Windows version had.

**Review by GeoB99 — APPROVED** [review]
I'm a simple man and I love sexy icons. Here have a green onion.

**Comment by DarkFire01** [comment]
This was a bit of a fight. 
That's 6 core dev approvals
Versus
2 core devs denies. Ill merge it tomorrow.

**Comment by binarymaster** [comment]
> I'll merge it tomorrow.

We forgot to discuss one important change that was not mentioned in PR description:

| Before | After |
|---|---|
| image | image |

**Comment by DarkFire01** [comment]
uh oh

**Comment by DarkFire01** [comment]
from @freedom7341 

windows for reference

**Comment by Splitwirez** [comment]
> i do like that better but i dont think that was remotely intended

@DarkFire01 It was a known outcome, yes...though I realize now that my acknowledgement of it was...not nearly specific enough.

**Comment by Splitwirez** [comment]
Following discussion on Discord, I've prepared a few alternate variants:

| v2A | v2B |
| ---- | ---- |
| v2A at 48x | v2B at 48x |

Only 48x currently - I'll do the other sizes if these are chosen over the original variant.

Again, I'm open to making/trying further changes...but I can't do that without knowing what said changes are.

**Comment by whindsaks** [comment]
I prefer your original. v2A is too shiny and v2B looks like a portable drive (and I don't think you need to pretend that the new icon is a new take on the old Tango icon).

**Comment by binarymaster** [comment]
v2A looks interesting, but could you tweak the color to be closer to the color of folders?

**Comment by JoachimHenze** [comment]
I think we should be ok to merge already what is inside this PR **currently** before the 0.4.15-rls-branching. It is definitely an improvement already, both: in icon size and visual quality. You could start the next iteration/generation of that icon then during 0.4.16-dev'ing within a new PR. (to me v2A does not reflect the standard desktop background color close enough, and is too shiny for my taste). The current one in this PR is easier to recognize as "the desktop" for the human eye imho.

My personal **opinion** for a desireable endgoal would be to bring "fig.3" from the PRs description (current state) even closer to "fig.2 Win7" icon.

I am merging the current state now, to preserve what has already been achieved so far. We do have 8 approvals already.

**Pull request merged**
