### PR TITLE
CORE-12580. Shell32: it is _WIN32_WINNT, not WIN32_WINNT

### PR DESCRIPTION
**Pull request by SergeGautherie**
## Purpose

Fix a typo.

JIRA issue: [CORE-12580](https://jira.reactos.org/browse/CORE-12580)

## Proposed changes

See [CORE-12580 comment](https://jira.reactos.org/browse/CORE-12580?focusedCommentId=87704&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-87704).

### CODE REVIEW

**Comment by SergeGautherie** [comment]
@gigaherz as initial code author.

**Comment by sanchaez** [comment]
You don't need to put your name in the branch. It looks like this: 
>image

**Comment by SergeGautherie** [comment]
> `__REACTOS__`

Done, with an added comment, for future (Vista target) reference.

**Comment by SergeGautherie** [comment]
> You don't need to put your name in the branch.

The second "name" is a namespace to locally filter my branches in, in addition to `master`.
How can I do that without a namespace?

**Comment by gigaherz** [comment]
"don't need to" doesn't mean "you shouldn't". If you like to put your name in it, it's perfectly fine... just redundant.

**Comment by SergeGautherie** [comment]
> like ... redundant.

I know it looks redundant and I don't like it either.
Then again, how else can I filter out, as in not `pull`, all other branches?
Or, if the point is that my namespace is identical to my GitHub account name, which namespace would you suggest to use instead?

**Comment by gigaherz** [comment]
You don't need to do any of that, when you pull or push, you can specify which branch you want.  But this isn't the place to chat, you can come over to IRC if you want to ask about things like that.

**Pull request merged**
