### PR TITLE
[KERNEL32_APITEST] Adjust ConsoleCP testcase for Win10 JPN

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose

JIRA issue: [CORE-12451](https://jira.reactos.org/browse/CORE-12451)

BEFORE (WinXP Japanese):
ConsoleCP-WinXPja-before
AFTER (WinXP Japanese):
ConsoleCP-WinXPja-after
No change.

BEFORE (Win10 Japanese):
ConsoleCP-Win10ja-before
AFTER (Win10 Japanese):
ConsoleCP-Win10ja-after
Reduced 4 failures.

### CODE REVIEW

**Comment by SergeGautherie** [comment]
Not a good way (if any) of doing it: that would accept an unexpected value on XP/S03...

**Comment by katahiromz** [comment]
I have added version check by `GetVersionEx` API. I have no Vista PC, so I don't know the details of implementation of all Windows versions.

**Comment by ale5000-git** [comment]
@katahiromz: I don't know if it is useful but if you provide the compiled executable I can test it on Windows 7 x64

**Comment by SergeGautherie** [comment]
> I have added version check by GetVersionEx API.

That way looks good :-)

--

While there, do you know why the behavior is different? char vs wchar? UTF8 vs UTF16? ...

**Comment by katahiromz** [comment]
@ale5000-git Here it is:
https://jira.reactos.org/secure/attachment/55421/kernel32_apitest.exe
You have to make Windows Japanese before testing.

**Comment by ale5000-git** [comment]
@katahiromz
Italian Windows 7 64-bit.
I have set language for not unicode programs and also keyboard to Japanese.

The result is:
```
ConsoleCP.c:498: Tests skipped: Russian testcase is skipped because of CJK
ConsoleCP.c:291: csbi.dwSize.X:250, csbi.dwSize.Y:300
ConsoleCP.c:293: count: 375
ConsoleCP.c:415: Test failed: len was: 75000
ConsoleCP.c:459: Test failed: len was: 4
ConsoleCP.c:460: Test failed: str[0] was: 0x0020
ConsoleCP.c:462: Test failed: str[2] was: 0x0020

ConsoleCP: 1550 tests executed (0 marked as todo, 4 failures), 1 skipped.
```

**Comment by ale5000-git** [comment]
Giving my result I sugget switching from `if (s_bIsVistaPlus)` to `if (s_bIs8Plus)`.

**Comment by katahiromz** [comment]
@ale5000-git https://jira.reactos.org/secure/attachment/55461/kernel32_apitest.exe

**Comment by ale5000-git** [comment]
Windows 7 64-bit in Italian language.
I have set language for not unicode programs and also keyboard to Japanese.
The language change cause `chcp` to be `932`.

The result is:
```
ConsoleCP.c:500: Tests skipped: Russian testcase is skipped because of CJK
ConsoleCP.c:291: csbi.dwSize.X:250, csbi.dwSize.Y:300
ConsoleCP.c:293: count: 375

ConsoleCP: 1550 tests executed (0 marked as todo, 0 failures), 1 skipped.
```

**Pull request merged**
