### PR TITLE
[APITESTS] Fix OpenAs_RunDLL tests

### PR DESCRIPTION
**Pull request by katahiromz**
## Purpose
The shel32_apitests OpenAs_RunDLL tests couldn't run properly. It falls in infinity loop. This PR will fix it.
JIRA issue: [CORE-14762](https://jira.reactos.org/browse/CORE-14762)

I made the test in another thread. The main thread will wait for the "Open With" dialog box.

### CODE REVIEW

**Comment by katahiromz** [comment]
AFTER (2K3):
2k3-success
AFTER (ROS):
ros-ok

**Comment by katahiromz** [comment]
Before, it worked successfully.

**Comment by ThFabba** [comment]
If the test worked correctly on Windows, then why does it need fixing?

**Comment by katahiromz** [comment]
It doesn't work in ReactOS.

**Comment by ThFabba** [comment]
Then ReactOS's code needs changing, not the test :)

**Comment by HBelusca** [comment]
Maybe on Windows, the OpenAs_RunDLL opens the dialog in a separate thread?

**Comment by yagoulas** [comment]
_RunDLL functions are meant to be used only by rundll32.exe and they all use the same patameters. That means that code doesnt call it manually and it doesnt usually create threads to do ita job.

**Comment by katahiromz** [comment]
Bad string pointers make crash.

**Comment by katahiromz** [comment]
Closed.

**Comment by katahiromz** [comment]
Commit me as a workaround.

**Comment by katahiromz** [comment]
To be honest, I don't understand the message queues yet. It's difficult for me.

**Pull request closed without merging**
